# Adding metadata to A3 sequences

Goal: Make sure collection date in dataset matches the metadata sheet, and more specific location (including the site at the end) matches the sheet

In [1]:
# Housekeeping

import os
import shutil
import pandas as pd
import numpy as np
import dateutil
from datetime import datetime
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# File paths

home = "C:/Users/maksiaevai.NCBI_NT/OneDrive - National Institutes of Health/Documents/Virus_Evolution/Avian_Flu_Files/"
datasets_west = home + "Combinations/NCBI_Virus_Andersen_GISAID/11-01-2021--05-15-2026_Antarctica_North_America_South_America/"
datasets_east = home + "GISAID/complete/2021-11-01--2026-05-15_Africa_Asia_Europe/"
metadata = home + "Other/A3/"

In [2]:
os.chdir(metadata)

elephant_seal_metadata = pd.read_excel("Elephant-seal-metadata-2026_050626_GJ.xlsx")
elephant_seal_metadata

,File,metadata-(white-poultry-or-mammal---yellow-wb,Specimen ID (UCD),Collection date,Death date IF KNOWN,Unique Animal ID,Multiple specimens per animal?,Classification,Common_name,Scientific_name,...,Genotype,Comments,Substitutions of concern,"Metadata segment detail: average % coverage, % under 10X coverage, % no coverage bases by segment",Minor Variant Percents,Old SRA decision column,Unnamed: 23,NVSL_accession,status,SRA_runs
0,26G03029-001,26G03029-001_Northern-Elephant-Seal_2026-02-20...,NaN,NaT,NaT,ES S,No,Mammal,Northern elephant seal,Mirounga angustirostris,...,A3,NaN,E627K,PB2:722.1X_-0.0%_-0.0% -- PB1:304.0X_0.0%_0.0%...,A_PB2 0.1% A_PB1 0.0% A_PA 0.0% A_HA_H5 0.1% A...,NaN,NaN,26G03029-001,FOUND,SRR37511459
1,26G03029-002,26G03029-002_Northern-Elephant-Seal_2026-02-20...,NaN,NaT,NaT,ES U,Yes,Mammal,Northern elephant seal,Mirounga angustirostris,...,A3,NaN,E627K,PB2:2340.6X_-0.0%_-0.0% -- PB1:1637.9X_0.0%_0....,A_PB2 0.1% A_PB1 0.0% A_PA 0.1% A_HA_H5 0.1% A...,NaN,NaN,26G03029-002,FOUND,SRR37511458
2,26G03029-004,26G03029-004_Northern-Elephant-Seal_2026-02-20...,NaN,NaT,NaT,ES 64803,No,Mammal,Northern elephant seal,Mirounga angustirostris,...,A3,"FASTA not included due to assembly error, FAST...",E627K,PB2:1383.0X_-0.0%_-0.0% -- PB1:1096.6X_-2.3%_-...,A_PB2 0.0% A_PB1 0.3% A_PA 0.1% A_HA_H5 0.1% A...,NaN,NaN,26G03029-004,FOUND,SRR37511457
3,26G03029-009,26G03029-009_Northern-Elephant-Seal_2026-02-20...,NaN,NaT,NaT,ES T,No,Mammal,Northern elephant seal,Mirounga angustirostris,...,A3,NaN,E627K,PB2:1324.4X_-0.0%_-0.0% -- PB1:656.3X_0.0%_0.0...,A_PB2 0.0% A_PB1 0.1% A_PA 0.1% A_HA_H5 0.1% A...,NaN,NaN,26G03029-009,FOUND,SRR37511456
4,26G03370-007,26G03370-007_Northern-Elephant-Seal_2026-02-21...,NaN,NaT,NaT,ES W,Yes,Mammal,Northern elephant seal,Mirounga angustirostris,...,A3,NaN,E627K,PB2:317.0X_-0.0%_-0.0% -- PB1:126.4X_0.0%_0.0%...,A_PB2 0.1% A_PB1 0.1% A_PA 0.1% A_HA_H5 0.1% A...,NaN,NaN,26G03370-007,FOUND,SRR37710364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,26G06613-004,NaN,AN807,2026-04-13,NaT,20260413-ES-6,No,Mammal,Northern elephant seal,Mirounga angustirostris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26G06613-004,NOT_FOUND_IN_SRA,NaN
137,26G06613-005,NaN,AN801,2026-04-13,NaT,20260413-B-8,No,Bird,American herring gull,Larus smithsonianus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26G06613-005,NOT_FOUND_IN_SRA,NaN
138,26G06613-006,NaN,AN805,2026-04-13,NaT,20260413-CSL-3,No,Mammal,California sea lion,Zalophus californianus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26G06613-006,NOT_FOUND_IN_SRA,NaN
139,26G06613-007,NaN,AN812,2026-04-13,NaT,20260413-CSL-5,No,Mammal,California sea lion,Zalophus californianus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26G06613-007,NOT_FOUND_IN_SRA,NaN
140,26G06612-001,NaN,SO 11520-25-BR1,2025-11-17,2025-11-14,SO 11520-25,No,Mammal,Southern sea otter,Enhydra lutris nereis,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26G06612-001,NOT_FOUND_IN_SRA,NaN

In [3]:
os.chdir(datasets_west)

# PB2 only for now for speed -- add to other segments later
a3_west_pb2 = metadata_from_fasta("A3_PB2_11-01-2021--05-15-2026.fasta").sort_values("Collection_Date")
a3_west_pb2

,full_header,sequence,Accession,Host,Isolate,Subtype,Geo_Location,Collection_Date,Host_Type,Genotype
815,>SRR31885889|A/Red-tailed_hawk/MT/22-040683-00...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR31885889,Red-tailed_hawk,22-040683-006-original,H5N1,USA-MT,2022,wild_avian,A3\n
833,>SRR29281472|A/glaucous_gull/USA/22-031916-001...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR29281472,glaucous_gull,22-031916-001,H5N1,USA,2022,wild_avian,A3\n
831,>SRR29281472|A/glaucous_gull/USA/22-023553-003...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR29281472,glaucous_gull,22-023553-003,H5N1,USA,2022,wild_avian,A3\n
825,>SRR29281472|A/bald_eagle/USA/22-035250-002/20...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR29281472,bald_eagle,22-035250-002,H5N1,USA,2022,wild_avian,A3\n
824,>SRR29281472|A/bald_eagle/USA/22-035250-001/20...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR29281472,bald_eagle,22-035250-001,H5N1,USA,2022,wild_avian,A3\n
...,...,...,...,...,...,...,...,...,...,...
461,>SRR38140009|A/Brant_Goose/AK/26G04803-001-ori...,NNNNNNNNNATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR38140009,Brant_Goose,26G04803-001-original,,USA-AK,2026-03-13,wild_avian,A3\n
484,>SRR38140113|A/Northern_Elephant_Seal/CA/26G05...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR38140113,Northern_Elephant_Seal,26G05227-008-original,,USA-CA,2026-03-14,other_mammal,A3\n
482,>SRR38140097|A/Turkey_Vulture/CA/26G05230-001-...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR38140097,Turkey_Vulture,26G05230-001-original,,USA-CA,2026-03-14,wild_avian,A3\n
492,>SRR38140122|A/Northern_Elephant_Seal/CA/26G04...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR38140122,Northern_Elephant_Seal,26G04796-001-original,,USA-CA,2026-03-17,other_mammal,A3\n
465,>SRR38140041|A/Dunlin/WA/26G04804-001-original...,ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAGTCTCGCA...,SRR38140041,Dunlin,26G04804-001-original,,USA-WA,2026-03-17,wild_avian,A3\n

In [4]:
# Add in sequences from SRA that were genotyped incorrectly

sras_missed = ["SRR38140129", "SRR38139957", "SRR38140084", "SRR38140112", "SRR37376628"]

refs = "C:/Users/maksiaevai.NCBI_NT/OneDrive - National Institutes of Health/Documents/Virus_Evolution/Avian_Flu/"

references = refs + "references/"
os.chdir(references)
state_ref = pd.read_csv("states_ref.csv")
animals_ref = pd.read_csv("animals_ref.csv")

andersen = home + "Andersen/"
metadata_folder = andersen + "avian-influenza/metadata/"

os.chdir(metadata_folder)
metadata_andersen = pd.read_csv("SraRunTable_automated_normalized.tsv", delimiter="\t")
print(metadata_andersen.columns)
genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genoflu_results = pd.read_csv("genoflu_results.tsv", delimiter="\t")

fasta_folder = andersen + "avian-influenza/fasta/"
os.chdir(fasta_folder)

sra_dict = {}
for sra in sras_missed:
    sra_metadata = metadata_andersen[metadata_andersen["Run"] == sra]
    print(sra_metadata)
    # Merge with genbank_mapping
    genbank_mapping = genbank_mapping.rename(columns={"sra_run":"Run"})
    sra_metadata = sra_metadata.merge(genbank_mapping, how="left")
    # Get the name of the state, unless it's not in genbank_mapping -- then get it from normalized metadata
    sra_metadata["name_state_genbank"] = sra_metadata["genbank_name"].apply(lambda x: x.split("/")[2] if x == x 
                                                                    else x)
    sra_metadata["name_state_genbank"] = sra_metadata["name_state_genbank"].fillna(sra_metadata["geo_loc_name"])

    # forbidden_chars = [", ", ": "] # List of characters to replace
    # Format: USA-[state abbreviation], e.g. USA-MD
    sra_metadata["Geo_Location"] = sra_metadata["name_state_genbank"].apply( # lambda x: state_ref.loc[state_ref["Abbreviation"] == x.split("/")[2], 'Country'].iloc[0] + "-" + x.split("/")[2] if x.split("/")[2] in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x.split("/")[2].replace("_", " "), 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x.split("/")[2].replace("_", " "), 'Abbreviation'].iloc[0] if x.split("/")[2].replace("_", " ") in state_ref["State"].values else x.split("/")[2].replace(": ", "-"))
        
                                                            lambda x: 
                                                            # If "x" has the state abbreviation (e.g. "MD")
                                                            state_ref.loc[state_ref["Abbreviation"].str.contains('|'.join(x.replace(": ", ",").replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                            + "-" + 
                                                            x.split(" ")[-1]
                                                            if state_ref["Abbreviation"].str.contains("|".join((x.replace(": ", ",").replace(" ", "_").split(','))), regex=True).any()
                                                            # If "x" has the full state name (e.g. "Maryland")
                                                            else state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(": ", ",").replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                            + "-" + 
                                                            state_ref.loc[state_ref['State'].str.contains('|'.join(x.replace(": ", ",").replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                            if state_ref["State"].str.contains("|".join((x.replace(": ", ",").replace(" ", "_").split(','))), regex=True).any()
                                                            # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                            else 
                                                            x
                                                            )

    # If USA-, delete -
    sra_metadata["Geo_Location"] = sra_metadata["Geo_Location"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)
    genoflu_results = genoflu_results.rename(columns={"sample" : "Run"}) # Rename so we can merge
    sra_metadata = sra_metadata.merge(genoflu_results, on="Run", how="inner") # Add genoflu results to dataframe, excluding runs without results
    fix_animals_andersen(sra_metadata, animals_ref) # Get host type

    sra_segs = {}
    for seg in ["PB2", "PB1", "PA", "HA", "NP", "NA", "MP", "NS"]:
        sra_fasta = sra + "_" + seg + "_cns.fa"
        sequence = ""
        with open(sra_fasta) as f:
            lines = f.readlines()
            sequence = lines[1] 
        f.close()
        sra_segs[seg] = sequence
    sra_header = ">" + sra_metadata["Run"] + "|" + sra_metadata["isolate"] + "|H5N1|" + sra_metadata["Geo_Location"] + "|" + sra_metadata["Collection_Date"].apply(lambda x: str(x) if "-" not in str(x) else str(dateutil.parser.parse(str(x), default=datetime(2000, 1, 1)).strftime("%Y")) if dateutil.parser.parse(str(x), default=datetime(2000, 1, 1)).month == datetime(2000, 1, 1).month and dateutil.parser.parse(str(x), default=datetime(2000, 1, 1)).day == datetime(2000, 1, 1).day else dateutil.parser.parse(str(x), default=datetime(2000, 1, 1)).strftime("%Y-%m-%d")) + "|" + sra_metadata["Host_Type"] + "|" + sra_metadata["Genotype"]
    print(sra_header)
    sra_dict[sra_header.values[0]] = sra_segs

print(sra_dict)

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_28252\3878597145.py:16: DtypeWarning: Columns (16,32,36) have mixed types. Specify dtype option on import or set low_memory=False.
  metadata_andersen = pd.read_csv("SraRunTable_automated_normalized.tsv", delimiter="\t")

Index(['Run', 'Assay Type', 'AvgSpotLen', 'Bases', 'BioProject', 'BioSample',
       'BioSampleModel', 'Bytes', 'Center Name', 'Collection_Date', 'Consent',
       'DATASTORE filetype', 'DATASTORE provider', 'DATASTORE region',
       'Experiment', 'geo_loc_name_country', 'geo_loc_name_country_continent',
       'geo_loc_name', 'Host', 'Instrument', 'isolate', 'Library Name',
       'LibraryLayout', 'LibrarySelection', 'LibrarySource', 'Organism',
       'Platform', 'ReleaseDate', 'create_date', 'version', 'Sample Name',
       'SRA Study', 'serotype', 'isolation_source', 'BioSample Accession',
       'is_retracted', 'retraction_detection_date_utc'],
      dtype='object')
               Run Assay Type  AvgSpotLen     Bases    BioProject  \
21471  SRR38140129        WGS      147.88  79274185  PRJNA1207547

          BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
21471  SAMN57311567          Viral  26269481   USDA-NVSL      2026-02-24  ...

               ReleaseDate          create_date version   Sample Name  \
21471  2026-04-17 00:01:53  2026-04-16 14:35:21     1.0  26G04061-001

       SRA Study serotype isolation_source BioSample Accession is_retracted  \
21471  SRP557452      NaN       swab nasal         SRS28822010        False

      retraction_detection_date_utc
21471                           NaN

[1 rows x 37 columns]
0    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
1    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
2    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
3    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
4    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
5    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
6    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
7    >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
dtype: object
               Run Assay Type  AvgSpotLen      Bases    BioProject  \
21299  SRR38139957        WGS      144.99  104116416  PRJNA1207547

          BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
21299  SAMN57311527          Viral  33788731   USDA-NVSL      2026-02-24  ...

               ReleaseDate          create_date version   Sample Name  \
21299  2026-04-17 00:01:52  2026-04-16 14:35:23     1.0  26G04061-012

       SRA Study serotype isolation_source BioSample Accession is_retracted  \
21299  SRP557452      NaN       swab nasal         SRS28822182        False

      retraction_detection_date_utc
21299                           NaN

[1 rows x 37 columns]
0    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
1    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
2    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
3    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
4    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
5    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
6    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
7    >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
dtype: object
               Run Assay Type  AvgSpotLen      Bases    BioProject  \
21426  SRR38140084        WGS      146.74  158335078  PRJNA1207547

          BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
21426  SAMN57311637          Viral  49493534   USDA-NVSL            2026  ...

               ReleaseDate          create_date version   Sample Name  \
21426  2026-04-17 00:01:52  2026-04-16 14:36:05     1.0  26G04898-008

       SRA Study serotype    isolation_source BioSample Accession  \
21426  SRP557452      NaN  swab oropharyngeal         SRS28822055

      is_retracted retraction_detection_date_utc
21426        False                           NaN

[1 rows x 37 columns]
0    >SRR38140084|26G04898-008|H5N1|United States//...
dtype: object
               Run Assay Type  AvgSpotLen     Bases    BioProject  \
21454  SRR38140112        WGS      130.87  83830146  PRJNA1207547

          BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
21454  SAMN57311583          Viral  27451888   USDA-NVSL      2026-03-19  ...

               ReleaseDate          create_date version   Sample Name  \
21454  2026-04-17 00:01:55  2026-04-16 14:35:26     1.0  26G05228-001

       SRA Study serotype isolation_source BioSample Accession is_retracted  \
21454  SRP557452      NaN       swab nasal         SRS28822027        False

      retraction_detection_date_utc
21454                           NaN

[1 rows x 37 columns]
0    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
1    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
2    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
3    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
4    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
5    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
6    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
7    >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
dtype: object
               Run Assay Type  AvgSpotLen      Bases    BioProject  \
20588  SRR37376628        WGS      145.79  118246783  PRJNA1207547

          BioSample BioSampleModel     Bytes Center Name Collection_Date  ...  \
20588  SAMN55973235          Viral  38995364   USDA-NVSL      2025-12-19  ...

               ReleaseDate          create_date version   Sample Name  \
20588  2026-02-27 00:09:04  2026-02-26 13:04:44     1.0  26G02304-009

       SRA Study serotype isolation_source BioSample Accession is_retracted  \
20588  SRP557452      NaN     swab choanal         SRS28209983        False

      retraction_detection_date_utc
20588                           NaN

[1 rows x 37 columns]
0    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
1    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
2    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
3    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
4    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
5    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
6    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
7    >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...
dtype: object

In [14]:
# Function to find matches for all segments
def find_A3_matches(elephant_seal_metadata, segment_file):

    a3_west_pb2 = metadata_from_fasta(segment_file)

    # If SRR exists, match based on SRA_runs. Else, match based on File. 

    # sra_metadata = elephant_seal_metadata[elephant_seal_metadata["status"] == "FOUND"]
    elephant_seal_metadata["Accession"] = elephant_seal_metadata["SRA_runs"]
    a3_west_pb2["NVSL_accession"] = a3_west_pb2["Isolate"].apply(lambda x: x.split("-original")[0])

    # print(elephant_seal_metadata)
    # print(a3_west_pb2)

    common_columns = list(a3_west_pb2.columns.intersection(elephant_seal_metadata.columns)) #.difference(["Accession", "NVSL_accession"]))

    print(common_columns)

    a3_west_pb2_sra = a3_west_pb2.merge(elephant_seal_metadata, on="Accession", how="left")
    # print(a3_west_pb2_sra)

    a3_west_pb2_nvsl = a3_west_pb2.merge(elephant_seal_metadata, on="NVSL_accession", how="left")
    # print(a3_west_pb2_nvsl)

    # a3_west_pb2_sra["File"] = a3_west_pb2_sra["Isolate"].apply(lambda x: x.split("-original")[0])
    # a3_west_pb2_sra_gisaid = a3_west_pb2_sra.merge(elephant_seal_metadata, on="File", how="inner")

    a3_west_pb2_common = pd.merge(a3_west_pb2_sra, a3_west_pb2_nvsl, how="outer") #.drop_duplicates() # (keep="first")
    a3_west_pb2_right = a3_west_pb2_common.merge(elephant_seal_metadata, how="left")
    # a3_west_pb2_common = pd.merge(a3_west_pb2_sra, a3_west_pb2_nvsl, how="inner") #.drop_duplicates() # (keep="first")

    return a3_west_pb2_right

In [16]:
os.chdir(datasets_west)
for dirpath, dirs, files in os.walk(datasets_west):
    if len(files) > 0: # If we have any files that need to be moved
        for file in files:
            if ".fasta" in file:
                file_name = file.split(".fasta")[0] + "_updated.fasta"
                og_fasta = df_from_fasta(file)
                # Add missed SRAs with Andersen
                dict_to_make_df = {}
                for seg in ["PB2", "PB1", "PA", "HA", "NP", "NA", "MP", "NS"]:
                    if seg in file_name:
                        for sra_header in sra_dict.keys():
                            sequence = sra_dict[sra_header][seg]
                            dict_to_make_df[sra_header] = sequence
                print(dict_to_make_df)
                small_df = pd.DataFrame()
                small_df["full_header"] = dict_to_make_df.keys()
                small_df["sequence"] = dict_to_make_df.values()
                small_df["Accession"] = small_df["full_header"].apply(lambda x: x.split("|")[0][1:])
                print(small_df)
                updated_fasta = find_A3_matches(elephant_seal_metadata, file)
                print(updated_fasta)
                # updated_concat_fasta = pd.concat([updated_fasta, small_df])
               # df1 is original, df2 contains the new values to inject
                updated_fasta.set_index('Accession', inplace=True)
                small_df.set_index('Accession', inplace=True)

                updated_fasta.update(small_df)

                updated_fasta.reset_index(inplace=True)

                new_fasta = updated_fasta
                
                # updated_concat_fasta = updated_fasta.merge(small_df, how="outer", on=["Accession", "full_header", "sequence"])
                # print(updated_concat_fasta)
                # new_fasta = og_fasta.merge(updated_concat_fasta, how="right")
                # Add serotype
                # Add county
                new_fasta["full_header"] = new_fasta["full_header"].apply(lambda x: x.strip() + "|" + new_fasta[new_fasta["full_header"] == x]["County"].values[0] if x == x and len(new_fasta[new_fasta["full_header"] == x]["County"].dropna()) > 0 else x.strip() if x == x else x)
                # Replace date with collaborator's date, if that exists
                new_fasta["full_header"] = new_fasta["full_header"].apply(lambda x: "".join(x.strip().replace(x.split("|")[4], str(new_fasta[new_fasta["full_header"] == x]["Collection date"].values[0]).split("T")[0])) if x == x and len(new_fasta[new_fasta["full_header"] == x]["Collection date"].dropna()) > 0 else x.strip() if x == x else x)
                # new_fasta = new_fasta.dropna(subset="full_header")
                
                df_to_fasta(new_fasta, file_name, metadata)

{'>SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-24|other_mammal|Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file': 'ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAAGTGATCAGATTTGCATTGGTTACCATGCAAACAATTCGACAGAGCAGGTTGACACGATAATGGAAAAGAACGTCACCGTTACACATGCCCAAGACATACTAGAAAAAACACACAACGGGAAGCTCTGTGATCTAAATGGGGTGAAGCCTCTGATTTTAAAGGATTGTAGTGTAGCTGGATGGCTCCTCGGAAACCCAATGTGCGACGAATTCATCAGAGTGCCGGAATGGTCCTACATAGTGGAGCGGGCTAATCCAGCTAATGACCTCTGTTACCCAGGGAGCCTCAATGACTACGAAGAACTGAAACACCTGTTGAGCAGAATAAATCACTTTGAGAAGATTCTGATCATCCCCAAGAGTTCCTGGCCAAATCATGAAACATCACTAGGGGTGAGTGCAGCTTGTCCATACCAGGGAGCACCCTCCTTTTTCAGAAATGTGGTGTGGCTTATCAAAAAGAACGATGCATACCCAACAATAAAGATAAGCTACAATAATACCAATCGGGAAGATCTCTTGATACTGTGGGGGATTCATCATTCCAACAATGCAGAAGAACAGACAAATCTCTATAAAAACCCAACCACCTACATTTCAGTTGGAACATCAACTTTAAACCAGAGGTTGGTGCCAAAAATAACTACTAGATCCCAAGTAAACGGGCAACGTGGAAGAATGGACTTCTTCTGGACAATTTTAAAACCAGATGATGCCATCCATTTCGAGAGTAATGGAAATTTCATTGCTCCAGAATATGCATACAAAATTGTCAAGAAAGGGGACTCAACAATTATGAAAAGTGGAGTGGAATATGGCCACTGCAACACCAAATGTCAAACCCCAGTAGGAGCGATAAATTCTAGTATGCCATTCCACAATATACACCCTCTCACCATTGGGGAATGCCCCAAATACGTGAAATCAAACAAGTTGGTCCTTGCGACTGGGCTCAGAAATAGTCCTCTAAGAGAAAGGAGAAGAAAAAGAGGCCTGTTTGGGGCGATAGCAGGGTTTATAGAGGGAGGATGGCAGGGAATGGTTGATGGTTGGTATGGGTACCACCATAGCAATGAGCAGGGGAGTGGGTACGCTGCAGACAAAGAATCCACCCAAAAGGCAATAGATGGAGTTACCAATAAGGTCAACTCAATCATTGACAAAATGAACACTCAATTTGAGGCAGTTGGAAGGGAGTTTAATAACTTAGAAAGGAGGATAGAGAATTTGAACAAGAAAATGGAAGACGGATTCCTAGATGTCTGGACCTATAATGCTGAACTTCTAGTTCTCATGGAAAACGAGAGGACTCTAGATTTCCATGATTCAAATGTCAAGAACCTTTACGACAAAGTCAGACTACAGCTTAGGGATAATGCAAAGGAGCTGGGTAATGGCTGTTTCGAATTCTATCACAAATGCGATAATGAATGTATGGAAAGTGTGAAAAATGGGACATATGACTACCCTCAGTATTCAGAAGAAGCAAGATTAAAAAGAGAAGAAATAAGCGGAGTGAAATTAGAATCAATAGGAACTTACCAGATACTGTCAATTTATTCAACAGCGGCGAGTTCCCTAGCACTGGCAATCATGATGGCTGGTCTATCTTTATGGATGTGCTCCAATGGGTCGTTACAGTGCAGAATTTGCATTTAG\n', '>SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-24|wild_avian|Not assigned: Only 7 segments >98.0% match found of total 8 segments in input file': 'ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAAGTGATCAGATTTGCATTGGTTACCATGCAAACAATTCGACAGAGCAGGTTGACACGATAATGGAAAAGAACGTCACCGTTACACATGCCCAAGACATACTAGAAAAAACACACAACGGGAAGCTCTGTGATCTAAATGGGGTGAAGCCTCTGATTTTAAAGGATTGTAGTGTAGCTGGATGGCTCCTCGGAAACCCAATGTGCGACGAATTCATCAGAGTGCCGGAATGGTCCTACATAGTGGAGCGGGCTAATCCAGCTAATGACCTCTGTTACCCAGGGAGCCTCAATGACTACGAAGAACTGAAACACCTGTTGAGCAGAATAAATCACTTTGAGAAGATTCTGATCATCCCCAAGAGTTCCTGGCCAAATCATGAAACATCACTAGGGGTGAGTGCAGCTTGTCCATACCAGGGAGCACCCTCCTTTTTCAGAAATGTGGTGTGGCTTATCAAAAAGAACGATGCATACCCAACAATAAAGATAAGCTACAATAATACCAATCGGGAAGATCTCTTGATACTGTGGGGGATTCATCATTCCAACAATGCAGAAGAACAGACAAATCTCTATAAAAACCCAACCACCTACATTTCAGTTGGAACATCAACTTTAAACCAGAGGTTGGTGCCAAAAATAACTACTAGATCCCAAGTAAACGGGCAACGTGGAAGAATGGACTTCTTCTGGACAATTTTAAAACCAGATGATGCCATCCATTTCGAGAGTAATGGAAATTTCATTGCTCCAGAATATGCATACAAAATTGTCAAGAAAGGGGACTCAACAATTATGAAAAGTGGAGTGGAATATGGCCACTGCAACACCAAATGTCAAACCCCAGTAGGAGCGATAAATTCTAGTATGCCATTCCACAATATACACCCTCTCACCATTGGGGAATGCCCCAAATACGTGAAATCAAACAAGTTGGTCCTTGCGACTGGGCTCAGAAATAGTCCTCTAAGAGAAAGGAGAAGAAAAAGAGGCCTGTTTGGGGCGATAGCAGGGTTTATAGAGGGAGGATGGCAGGGAATGGTTGATGGTTGGTATGGGTACCACCATAGCAATGAGCAGGGGAGTGGGTACGCTGCAGACAAAGAATCCACCCAAAAGGCAATAGATGGAGTTACCAATAAGGTCAACTCAATCATTGACAAAATGAACACTCAATTTGAGGCAGTTGGAAGGGAGTTTAATAACTTAGAAAGGAGGATAGAGAATTTGAACAAGAAAATGGAAGACGGATTCCTAGATGTCTGGACCTATAATGCTGAACTTCTAGTTCTCATGGAAAACGAGAGGACTCTAGATTTCCATGATTCAAATGTCAAGAACCTTTACGACAAAGTCAGACTACAGCTTAGGGATAATGCAAAGGAGCTGGGTAATGGCTGTTTCGAATTCTATCACAAATGCGATAATGAATGTATGGAAAGTGTGAAAAATGGGACATATGACTACCCTCAGTATTCAGAAGAAGCAAGATTAAAAAGAGAAGAAATAAGCGGAGTGAAATTAGAATCAATAGGAACTTACCAGATACTGTCAATTTATTCAACAGCGGCGAGTTCCCTAGCACTGGCAATCATGATGGCTGGTCTATCTTTATGGATGTGCTCCAATGGGTCGTTACAGTGCAGAATTTGCATTTAG\n', '>SRR38140084|26G04898-008|H5N1|United States///|2026|wild_avian|Not assigned: No Matching Genotypes': 'ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAAGTGATCAGATTTGCATTGGTTACCATGCAAACAATTCGACAGAGCAGGTTGACACGATAATGGAAAAGAACGTCACCGTTACACATGCCCAAGACATACTGGAAAAAGCACACAACGGGAAGCTCTGTGATCTAAATGGGGTGAAGCCTCTGATTTTAAAGGATTGTAGTGTAGCTGGATGGCTTCTCGGAAACCCAATGTGCGACGAATTCATCAGAGTGCCGGAATGGTCCTACATAGTGGAGCGGGACAATCCAGCCAATGACCTCTGTTACCCAGGGAGCCTCAATGACTACGAAGAATTGAAACACCTGTTGAGCAGAATAAATCACTTTGAGAAGATTCTGATCATCCCCAAGAGTTCCTGGCCAAATCATGAAACATCACTAGGGGTGAGCGCAGCTTGTCCATACCAGGGAGCGCCCTCCTTTTTCAGAAATGTGGTGTGGCTTATCAAAAAGAACGATGCATACCCAACAATAAAGATAAGCTACAATAATACCAATCGGGAAGATCTCTTGATACTGTGGGGGATTCATCATTCCAACAATGCAGAAGAGCAGACAAATCTCTATAAAAATCCAACCACCTACATTTCAGTTGGAACATCAACTTTAAACCAGAGGTTGGTACCAAAAATAGCTACTAGATCCCAAGTAAACGGGCAACGTGGAAGAATGGACTTCTTCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNGCTCCAGAATATGCATACAAAATTGTCAAGAAAGGGGACTCAACAATCATGAAAAGTGGAGTGGAATATGGCCACTGCAACACCAAATGTCAAACCCCAGTAGGAGCGATAAATTCTAGTATGCCATTCCACAACATACACCCTCTCACCATTGGGGAATGCCCCAAATACGTGAAATCAAACAAGTTGGTCCTTGCGACTGGGCTCAGAAATAGTCCTCTAAGAGAAAGGAGAAGAAAAAGAGGCCTGTTTGGGGCGATAGCAGGGTTTATAGAGGGAGGATGGCAGGGAATGGTTGATGGTTGGTATGGGTACCATCATAGCAATGAGCAGGGGAGTGGGTACGCTGCAGACAAAGAATCCACCCAAAAGGCAATAGATGGAGTTACCAATAAGGTCAACTCAATCATTGACAAAATGAACACTCAATTTGAGGCAGTTGGAAGGGAGTTTAATAACTTAGAAAGGAGGATAGAGAATTTGAACAAGAAAATGGAAGACGGATTCCTAGATGTCTGGACCTATAATGCTGAACTTCTAGTTCTCATGGAAAACGAGAGGACTCTAGATTTCCATGATTCAAATGTAAAGAACCTTTACGACAAAGTCAGACTACAGCTTAGGGATAATGCAAAGGAGCTGGGTAATGGCTGTTTCGAATTCTATCACAAATGCGATGATGAATGTATGGAAAGTGTGAGAAATGGGACGTATGACTACCCTCAGTATTCAGAAGAAGCAAGATTAAAAAGAGAAGAAATAAGCGGAGTGAAATTAGAATCAATAGGAACTTACCAGATACTGTCAATTTATTCAACAGCGGCGAGTTCCCTAGCACTGGCAATCATGATGGCTGGTCTATCTTTATGGATGTGCTCCAATGGGTCGTTACAGTGCAGAATTTGCATTTAG\n', '>SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-19|other_mammal|A3': 'ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAAGTGATCAGATTTGCATTGGTTACCATGCAAACAATTCGACAGAGCAGGTTGACACGATAATGGAAAAGAACGTCACCGTTACACATGCCCAAGACATACTAGAAAAAACACACAACGGGAAGCTCTGTGATCTAAATGGGGTGAAGCCTCTGATTTTAAAGGATTGTAGTGTAGCTGGATGGCTCCTCGGAAACCCAATGTGCGACGAATTCATCAGAGTGCCGGAATGGTCCTACATAGTGGAGCGGGCTAATCCAGCTAATGACCTCTGTTACCCAGGGAGCCTCAATGACTACGAAGAACTGAAACACCTGTTGAGCAGAATAAATCACTTTGAGAAGATTCTGATCATCCCCAAGAGTTCCTGGCCAAATCATGAAACATCACTAGGGGTGAGTGCAGCTTGTCCATACCAGGGAGCACCCTCCTTTTTCAGAAATGTGGTGTGGCTTATCAAAAAGAACGATGCATACCCAACAATAAAGATAAGCTACAATAATACCAATCGGGAAGATCTCTTGATACTGTGGGGGATTCATCATTCCAACAATGCAGAAGAACAGACAAATCTCTATAAAAACCCAACCACCTACATTTCAGTTGGAACATCAACTTTAAACCAGAGGTTGGTGCCAAAAATAACTACTAGATCCCAAGTAAACGGGCAACGTGGAAGAATGGACTTCTTCTGGACAATTTTAAAACCAGACGATGCCATCCATTTCGAGAGTAATGGAAATTTCATTGCTCCAGAATATGCATACAAAATTGTCAAGAAAGGGGACTCAACAATTATGAAAAGTGGAGTGGAATATGGCCACTGCAACACCAAATGTCAAACCCCAGTAGGAGCGATAAATTCTAGTATGCCATTCCACAATATACACCCTCTCACCATTGGGGAATGCCCCAAATACGTGAAATCAAACAAGTTGGTCCTTGCGACTGGGCTCAGAAATAGTCCTCTAAGAGAAAGGAGAAGAAAAAGAGGCCTGTTTGGGGCGATAGCAGGGTTTATAGAGGGAGGATGGCAGGGAATGGTTGATGGTTGGTATGGGTACCACCATAGCAATGAGCAGGGGAGTGGGTACGCTGCAGACAAAGAATCCACCCAAAAGGCAATAGATGGAGTTACCAATAAGGTCAACTCAATCATTGACAAAATGAACACTCAATTTGAGGCAGTTGGAAGGGAGTTTAATAACTTAGAAAGGAGGATAGAGAATTTGAACAAGAAAATGGAAGACGGATTCCTAGATGTCTGGACCTATAATGCTGAACTTCTAGTTCTCATGGAAAACGAGAGGACTCTAGATTTCCATGATTCAAATGTCAAGAACCTTTACGACAAAGTCAGACTACAGCTTAGGGATAATGCAAAGGAGCTGGGTAATGGCTGTTTCGAATTCTATCACAAATGCGATAATGAATGTATGGAAAGTGTGAAAAATGGGACATATGACTACCCTCAGTATTCAGAAGAAGCAAGATTAAAAAGAGAAGAAATAAGCGGAGTGAAATTAGAATCAATAGGAACTTACCAGATACTGTCAATTTATTCAACAGCGGCGAGTTCCCTAGCACTGGCAATCATGATGGCTGGTCTATCTTTATGGATGTGCTCCAATGGGTCGTTACAGTGCAGAATTTGCATTTAG\n', '>SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-19|wild_avian|D1.1': 'ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAAGTGATCAGATTTGCATTGGTTACCATGCAAACAATTCGACAGAGCAGGTTGACACGATAATGGAAAAGAACGTCACCGTTACACATGCCCAAGACATACTGGAAAAAGCACACAACGGGAAGCTCTGTGATCTAAATGGGGTGAAGCCTCTGATTTTAAAGGATTGTAGTGTAGCTGGATGGCTTCTCGGAAACCCAATGTGCGACGAATTCATCAGAGTGCCGGAATGGTCCTACATAGTGGAGCGGGACAATCCAGCCAATGACCTCTGTTACCCAGGGAGCCTCAATGACTACGAAGAACTGAAACACCTGTTGAGCAGAATAAATCACTTCGAGAAGATTCTGATCATCCCCAAGAGTTCCTGGCCAAATCATGAAACATCACTAGGGGTGAGCGCAGCTTGTCCATACCAGGGAGCGCCCTCCTTTTTCAGAAATGTGGTGTGGCTTATCAAAAAGAACGATGCATACCCAACAATAAAAATAAGCTACAATAATACCAATCGGGAAGATCTCTTGATACTGTGGGGGATTCATCATTCCAACAGTGCAGAAGAGCAGACAAATCTCTATAAAAATCCAACCACCTACATTTCAGTTGGAACATCAACTTTAAACCAGAGGTTGGTACCAAAAATAGCTACTAGATCCCAAGTAAACGGGCAACGTGGAAGAATGGACTTCTTCTGGACAATTTTAAAACCAGATGATGCCATCCATTTCGAGAGTAATGGAAATTTCATTGCTCCAGAATATGCATACAAAATTGTCAAGAAGGGGGACTCAACAATTATGAAAAGTGTAGTGGAATATGGCCACTGCAACACCAAATGTCAAACCCCAGTAGGAGCGATAAATTCTAGTATGCCATTCCACAACATACACCCTCTCACCATTGGGGAATGCCCCAAATACGTGAAATCAAACAAGTTGGTCCTTGCGACTGGGCTCAGAAATAGTCCTCTAAGAGAAAGGAGAAGAAAAAGAGGCCTGTTTGGGGCGATAGCAGGGTTTATAGAGGGAGGATGGCAGGGAATGGTTGATGGTTGGTATGGGTATCATCATAGCAATGAGCAGGGGAGTGGGTACGCTGCAGACAAAGAATCCACCCAAAAGGCAATAGATGGAGTTACCAATAAGGTCAACTCAATCATTGACAAAATGAACACTCAATTTGAGGCAGTTGGAAGGGAGTTTAATAACTTAGAAAGGAGGATAGAGAATTTGAACAAGAAAATGGAAGACGGGTTCCTAGATGTCTGGACCTATAATGCTGAACTTCTAGTTCTCATGGAAAACGAGAGGACTCTAGATTTCCATGATTCAAATGTAAAGAACCTTTACGACAAAGTCAGACTACAGCTTAGGGATAATGCAAAGGAGCTGGGTAATGGCTGTTTCGAATTCTATCACAAATGCGATGATGAATGTATGGAAAGTGTGAGAAATGGGACGTATGACTACCCTCAGTATTCAGAAGAAGCAAGATTAAAAAGAGAAGAAATAAGCGGAGTGAAATTAGAATCAATAGGAACTTACCAGATACTGTCAATTTATTCAACAGCGGCGAGTTCCCTAGCACTGGCAATCATGATGGCTGGTCTATCTTTATGGATGTGCTCCAATGGGTCGTTACAGTGCAGAATCTGCATTTAG\n'}
                                         full_header  \
0  >SRR38140129|26G04061-001|H5N1|USA-CA|2026-02-...
1  >SRR38139957|26G04061-012|H5N1|USA-CA|2026-02-...
2  >SRR38140084|26G04898-008|H5N1|United States//...
3  >SRR38140112|26G05228-001|H5N1|USA-CA|2026-03-...
4  >SRR37376628|26G02304-009|H5N1|USA-CA|2025-12-...

                                            sequence    Accession
0  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  SRR38140129
1  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  SRR38139957
2  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  SRR38140084
3  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  SRR38140112
4  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...  SRR37376628
['Accession', 'Subtype', 'Genotype', 'NVSL_accession']
                                           full_header  \
0    >EPI_ISL_15843373|A/Bald_Eagle/BC/OTH-33-36/20...
1    >EPI_ISL_16297073|A/chicken/California/22-0351...
2    >EPI_ISL_16297074|A/domestic_goose/California/...
3    >EPI_ISL_17051482|A/canada_goose/BC/AIVPHL-371...
4    >EPI_ISL_17051483|A/trumpeter_swan/BC/AIVPHL-3...
..                                                 ...
838  >SRR38427727|A/mink/United_States/26G06157-001...
839  >SRR38563564|A/northern_elephant_seal/United_S...
840  >SRR38563564|A/northern_elephant_seal/United_S...
841  >SRR38563565|A/herring_gull/United_States/26G0...
842  >SRR38563565|A/herring_gull/United_States/26G0...

                                              sequence         Accession  \
0    agcaaaagcaggggttcactctgtcaaaatggagaacatagtactt...  EPI_ISL_15843373
1    atggagaacatagtacttcttcttgcaataattagccttgttaaaa...  EPI_ISL_16297073
2    atggagaacatagtacttcttcttgcaataattagccttgttaaaa...  EPI_ISL_16297074
3    nnnnnnnnnnnnggttcactctgtcaaaatggaaaacatagtactt...  EPI_ISL_17051482
4    nnnnnnnnnnnnggttcactctgtcaaaatggagaacatagtactt...  EPI_ISL_17051483
..                                                 ...               ...
838  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...       SRR38427727
839  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...               NaN
840  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...       SRR38563564
841  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...               NaN
842  ATGGAGAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...       SRR38563565

                       Host        Isolate Subtype_x Geo_Location  \
0                Bald_Eagle      OTH-33-36      H5N1    Canada-BC
1                   chicken  22-035144-001      H5N1       USA-CA
2            domestic_goose  22-035144-003      H5N1       USA-CA
3              canada_goose     AIVPHL-371      H5N1    Canada-BC
4            trumpeter_swan     AIVPHL-364      H5N1    Canada-BC
..                      ...            ...       ...          ...
838                    mink   26G06157-001                    USA
839  northern_elephant_seal   26G05924-005                    USA
840  northern_elephant_seal   26G05924-005                    USA
841            herring_gull   26G06613-005                    USA
842            herring_gull   26G06613-005                    USA

    Collection_Date       Host_Type Genotype_x  ... Old SRA decision column  \
0        2022-02-03      wild_avian       A3\n  ...                     NaN
1        2022-10-31  domestic_avian       A3\n  ...                     NaN
2        2022-10-31  domestic_avian       A3\n  ...                     NaN
3        2023-01-16      wild_avian       A3\n  ...                     NaN
4        2023-01-16      wild_avian       A3\n  ...                     NaN
..              ...             ...        ...  ...                     ...
838            2026    other_mammal       A3\n  ...                     NaN
839            2026    other_mammal       A3\n  ...                     NaN
840            2026    other_mammal       A3\n  ...                     NaN
841            2026      wild_avian       A3\n  ...                     NaN
842            2026      wild_avian       A3\n  ...                     NaN

    Unnamed: 23 NVSL_accession_y            status SRA_runs       Accession_x  \
0           NaN              NaN               NaN      NaN  EPI_ISL_15843373
1           NaN              NaN               NaN      NaN  EPI_ISL_16297073
2           NaN              NaN               NaN      NaN  EPI_ISL_16297074
3           NaN              NaN               NaN      NaN  EPI_ISL_17051482
4           NaN              NaN               NaN      NaN  EPI_ISL_17051483
..          ...              ...               ...      ...               ...
838         NaN              NaN               NaN      NaN       SRR38427727
839         NaN              NaN  NOT_FOUND_IN_SRA      NaN       SRR38563564
840         NaN              NaN               NaN      NaN               NaN
841         NaN              NaN  NOT_FOUND_IN_SRA      NaN       SRR38563565
842         NaN              NaN               NaN      NaN               NaN

    NVSL_accession Accession_y Subtype Genotype
0        OTH-33-36         NaN     NaN      NaN
1    22-035144-001         NaN     NaN      NaN
2    22-035144-003         NaN     NaN      NaN
3       AIVPHL-371         NaN     NaN      NaN
4       AIVPHL-364         NaN     NaN      NaN
..             ...         ...     ...      ...
838   26G06157-001         NaN     NaN      NaN
839   26G05924-005         NaN     NaN      NaN
840            NaN         NaN     NaN      NaN
841   26G06613-005         NaN     NaN      NaN
842            NaN         NaN     NaN      NaN

[843 rows x 43 columns]

In [7]:
# print(a3_west_pb2_sra["NVSL_accession"].dropna())

In [8]:
# os.chdir(datasets_east)
# a3_east_pb2 = metadata_from_fasta("A3_PB2_2021-11-01--2026-05-15.fasta").sort_values("Collection_Date")

# # Making sure there's nothing in Eurasia/Africa

# a3_east_pb2["File"] = a3_east_pb2["Isolate"].apply(lambda x: x.split("-original")[0])
# a3_east_pb2_gisaid = a3_east_pb2.merge(elephant_seal_metadata)
# a3_east_pb2_gisaid

In [10]:
os.chdir(metadata)
new_fasta.sort_values("Host_Type").to_csv("A3_PB2_right_on_collab_update.csv", index=False)