# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI, by de-duplicating from Andersen/GISAID, and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import re
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [5]:
# Paths

# Dates
start_date = "06-28-2025"
end_date = "07-04-2025"
date_range = start_date + "--" + end_date
# update_date = "06-17-2025"
# genotypes = ["D1.1", "B3.2", "B3.6", "B3.13", "A3", "A2", "C2.1"]

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = home + "NCBI_Virus/downloads/" + date_range + "_Antarctica_North_America_South_America/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_Antarctica_North_America_South_America/" # + "_B3_13/"
# gisaid_andersen = home + "Cats/Datasets/GISAID_Andersen/GISAID_Andersen_cats_only_6_5_2025/"
# combined_files = home + "Cats/Datasets/GISAID_Andersen_NCBI_Virus/cat_genotypes_" + update_date + "/" # 04-14-2025--06-05-2025"
# gisaid_ant = home + "GISAID/complete/" + date_range + "_all_genotypes_ant/"
# gisaid_southa = home + "GISAID/complete/" + date_range + "_all_genotypes_southa/"
# gisaid_ant_southa = home + "GISAID/complete/" + date_range + "_all_genotypes_Antarctica_South_America"

gisaid_andersen = home + "Combinations/GISAID_Andersen/B3_13/" + date_range + "_B3_13_Antarctica_North_America_South_America/" # B3_13/"
combined_files = home + "Combinations/GISAID_Andersen_NCBI_Virus/" + date_range + "_Antarctica_North_America_South_America/" # + update_date + "_B3_13/"
references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"
# references = "C:/Users/maksi/Documents/Statistics/projects/Avian_Flu/references/"

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")
# genotypes_df = pd.read_excel("genotype_key.xlsx")

# genotypes = list(genotypes_df["Genotype"])

genotypes = ["B3.13", "D1.1"]

os.chdir(downloads)

## De-Duplication

In [6]:
metadata = pd.read_csv("sequences.csv")

print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.SRA_Accession, as_index=False).size()

print(metadata_counts)

metadata_counted = metadata.merge(metadata_counts, on="SRA_Accession")

# Only keep those with size=8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates

metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="first") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]

metadata_segments

174
Empty DataFrame
Columns: [SRA_Accession, size]
Index: []

Empty DataFrame
Columns: [Accession, GenBank_RefSeq, Assembly, SRA_Accession, BioSample, BioProject, Organism_Name, Species, Genotype, Isolate, Segment, GenBank_Title, Length, Nuc_Completeness, Geo_Location, Host, Tissue_Specimen_Source, Submitters, Collection_Date, Release_Date, Molecule_type, size]
Index: []

[0 rows x 22 columns]

In [14]:
# De-duplicate from Andersen/GISAID using isolate

# Function to prepare dataframes
def fasta_df_complete(file_name, state_ref):

    fasta = pd.DataFrame()
    headers = []
    isolate_ids = []
    isolate_names = []
    subtypes = []
    # segments = []
    collection_dates = []
    sequences = []
    host_types = []
    species = []
    identifiers = []
    genotypes = []
    with open(file_name) as f:
        lines = f.readlines()
        for num, line in enumerate(lines):
            # print(line)
            if line[0] == ">": # If it's a header
                if line[1:].strip() not in headers: # And the previous line is not a header we've seen before
                    header = line[1:].strip() # Remove the ">"
                    # print(header)
                    try:
                        split_header = header.split("|")
                        if len(header.split("|")) > 6:
                            identifier = header.split("|")[0]
                            identifiers.append(identifier)
                            split_first_header = split_header[1].split("/")
                        else:
                            identifiers.append("unknown")
                            split_first_header = split_header[0].split("/")
                        # print(split_first_header)
                        # print(split_header)
                        headers.append(header) 
                        isolate_ids.append(split_first_header[3])
                        isolate_names.append(split_header[-6]) # We'll need to extract data from this too
                        # print(split_header[2].split("_")[-1])
                        subtypes.append(split_header[-5].split("_")[-1])  # Get only H5N1
                        genotypes.append(split_header[-1])
                        # segments.append(split_header[-2]) # .split("|")[-1])
                        host_types.append(split_header[-2])
                        species.append(split_first_header[1])
                        # if split_header[4] == "2024-01-01":
                        #     collection_dates.append("2024") # No samples were collected 1/1/2024, these are all unknown 
                        # elif split_header[4] == "2025-01-01":
                        #     collection_dates.append("2025")
                        # else: 
                        collection_dates.append(split_header[-3])
                        # collection_dates.append(split_header[-1].split("_")[-1])
                        if num < len(lines): # If we're not at the last line
                            # for i, l in enumerate(lines[num + 1:]):
                            i = num
                            sequence = ""
                            # print(lines[i])
                            # print(lines[i + 1])
                            while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                                sequence = sequence + lines[i + 1].strip()
                                i += 1
                            sequences.append(sequence) # Add next line to sequences
                    except:
                        headers.remove(header)
                        identifiers.remove(identifier)
                        print(header)
                        continue
        f.close()

    # Create columns for data frame 
    fasta["Header"] = headers
    fasta["Isolate_Id"] = isolate_ids
    fasta["Isolate_Name"] = isolate_names
    fasta["Subtype"] = subtypes
    # fasta["Segment"] = segments
    # Geo_Location is more complicated
    fasta["Geo_Location"] = fasta["Header"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"] == x.split("/")[2], 'Country'].iloc[0] + "-" + x.split("/")[2] if x.split("/")[2] in state_ref["Abbreviation"].values else state_ref.loc[state_ref["State"] == x.split("/")[2].replace("_", " "), 'Country'].iloc[0] + "-" + state_ref.loc[state_ref["State"] == x.split("/")[2].replace("_", " "), 'Abbreviation'].iloc[0] if x.split("/")[2].replace("_", " ") in state_ref["State"].values else x.split("/")[2].replace(": ", "-"))
    fasta["Date Collected"] = collection_dates
    fasta["Species"] = species
    fasta["Host_Type"] = host_types
    fasta["Genotype"] = genotypes
    fasta["Sequence"] = sequences
    # if len(identifiers) == len(fasta):
    fasta["Identifier"] = identifiers
    
    return fasta

# If even one isolate in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
gisaid_isolates = []
andersen_isolates = []
# Grab files
# for genotype in genotypes:
    # print(gisaid_andersen + genotype.replace(".", "_") + "/")
    # for dirpath, dirs, files in os.walk(gisaid_andersen + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "/"):
for dirpath, dirs, files in os.walk(gisaid_andersen):
    for file in files:
        file_name = os.path.join(dirpath, file)
        # print(file_name)
        if ".fasta" in file_name:
            fasta_file = fasta_df_complete(file_name, states_ref) # Convert fasta file to dataframe
            print(fasta_file)
            # isolates = fasta_file["Isolate_Name"].apply(lambda x: x.split("/")[3])
            isolates = fasta_file["Isolate_Id"]
            for index, value in isolates.items():
                gisaid_isolates.append(value)

            isolate_ids = fasta_file["Identifier"]
            for index, value in isolates.items():
                if "SRR" in value:
                    andersen_isolates.append(value)
            
        # break 

    # for dirpath, dirs, files in os.walk(gisaid_southa):
    #     for file in files:
    #         file_name = os.path.join(dirpath, file)
    #         # print(file_name)
    #         if ".fasta" in file_name:
    #             fasta_file = fasta_df(file_name, states_ref) # Convert fasta file to dataframe
    #             print(fasta_file)
    #             # isolates = fasta_file["Isolate_Name"].apply(lambda x: x.split("/")[3])
    #             isolates = fasta_file["Isolate_Id"]
    #             for index, value in isolates.items():
    #                 gisaid_isolates.append(value)

    #             isolate_ids = fasta_file["Identifier"]
    #             for index, value in isolates.items():
    #                 if "SRR" in value:
    #                     andersen_isolates.append(value)
            
    #     break 

gisaid_isolates = list(set(gisaid_isolates))

print(len(gisaid_isolates))
print(gisaid_isolates)

                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  atggagaacatagtacttcttcttgcaataattagccttgttaaaa...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  atgaatccaaatcaaaggataataaccactggatcaatctgtatgg...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  atggcgtctcaaggcaccaaacgatcctatgaacagatggagactg...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  atggattccaacactgtgtcaagctttcaggtagactgctttcttt...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn...

         Identifier
0  EPI_ISL_20055135
                                              Header  Isolate_Id  \
0  EPI_ISL_20055135|A/red_fox/USA/028269-001/2024...  028269-001

                    Isolate_Name Subtype Geo_Location Date Collected  Species  \
0  A/red_fox/USA/028269-001/2024    H5N1          USA     2024-01-01  red_fox

      Host_Type Genotype                                           Sequence  \
0  other_mammal       A3  nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnngtctcgca...

         Identifier
0  EPI_ISL_20055135
                                                Header     Isolate_Id  \
0    SRR33993024|A/cattle/USA/25-016866-004/2025||U...  25-016866-004
1    SRR33993025|A/cattle/USA/25-016866-002/2025||U...  25-016866-002
2    SRR33993026|A/cattle/USA/25-016847-007/2025||U...  25-016847-007
3    SRR34270243|A/opossum/USA/24-011942-046/2025||...  24-011942-046
4    SRR34270150|A/cattle/USA/25-017893-002/2025||U...  25-017893-002
..                                                 ...            ...
103  EPI_ISL_20049091|A/dairy_cow/USA/017364-001/20...     017364-001
104  EPI_ISL_20049093|A/dairy_cow/USA/016878-003/20...     016878-003
105  EPI_ISL_20049092|A/dairy_cow/USA/017049-001/20...     017049-001
106  EPI_ISL_20049095|A/dairy_cow/USA/016741-001/20...     016741-001
107  EPI_ISL_20049094|A/dairy_cow/USA/016745-001/20...     016745-001

                         Isolate_Name Subtype Geo_Location Date Collected  \
0     A/cattle/USA/25-016866-004/2025                  USA           2025
1     A/cattle/USA/25-016866-002/2025                  USA           2025
2     A/cattle/USA/25-016847-007/2025                  USA           2025
3    A/opossum/USA/24-011942-046/2025                  USA           2025
4     A/cattle/USA/25-017893-002/2025                  USA           2025
..                                ...     ...          ...            ...
103   A/dairy_cow/USA/017364-001/2025    H5N1          USA     2025-01-01
104   A/dairy_cow/USA/016878-003/2025    H5N1          USA     2025-01-01
105   A/dairy_cow/USA/017049-001/2025    H5N1          USA     2025-01-01
106   A/dairy_cow/USA/016741-001/2025    H5N1          USA     2025-01-01
107   A/dairy_cow/USA/016745-001/2025    H5N1          USA     2025-01-01

       Species     Host_Type Genotype  \
0       cattle        cattle    B3.13
1       cattle        cattle    B3.13
2       cattle        cattle    B3.13
3      opossum  other_mammal    B3.13
4       cattle        cattle    B3.13
..         ...           ...      ...
103  dairy_cow        cattle    B3.13
104  dairy_cow        cattle    B3.13
105  dairy_cow        cattle    B3.13
106  dairy_cow        cattle    B3.13
107  dairy_cow        cattle    B3.13

                                              Sequence        Identifier
0    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...       SRR33993024
1    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...       SRR33993025
2    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...       SRR33993026
3    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...       SRR34270243
4    ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...       SRR34270150
..                                                 ...               ...
103  atgaagaacatagcactacttcttgcaatagttagccttgttaaaa...  EPI_ISL_20049091
104  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...  EPI_ISL_20049093
105  atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...  EPI_ISL_20049092
106  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...  EPI_ISL_20049095
107  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...  EPI_ISL_20049094

[108 rows x 11 columns]
                                                Header     Isolate_Id  \
0    SRR33993024|A/cattle/USA/25-016866-004/2025||U...  25-016866-004
1    SRR33993025|A/cattle/USA/25-016866-002/2025||U...  25-016866-002
2    SRR33993026|A/cattle/USA/25-016847-007/2025||U...  25-016847-007
3    SRR34270243|A/opossum/USA/24-011942-046/2025||...  24-011942-046
4    SRR34270150|A/cattle/USA/25-017893-002/2025||U...  25-017893-002
..                                                 ...            ...
103  EPI_ISL_20049091|A/dairy_cow/USA/017364-001/20...     017364-001
104  EPI_ISL_20049093|A/dairy_cow/USA/016878-003/20...     016878-003
105  EPI_ISL_20049092|A/dairy_cow/USA/017049-001/20...     017049-001
106  EPI_ISL_20049095|A/dairy_cow/USA/016741-001/20...     016741-001
107  EPI_ISL_20049094|A/dairy_cow/USA/016745-001/20...     016745-001

                         Isolate_Name Subtype Geo_Location Date Collected  \
0     A/cattle/USA/25-016866-004/2025                  USA           2025
1     A/cattle/USA/25-016866-002/2025                  USA           2025
2     A/cattle/USA/25-016847-007/2025                  USA           2025
3    A/opossum/USA/24-011942-046/2025                  USA           2025
4     A/cattle/USA/25-017893-002/2025                  USA           2025
..                                ...     ...          ...            ...
103   A/dairy_cow/USA/017364-001/2025    H5N1          USA     2025-01-01
104   A/dairy_cow/USA/016878-003/2025    H5N1          USA     2025-01-01
105   A/dairy_cow/USA/017049-001/2025    H5N1          USA     2025-01-01
106   A/dairy_cow/USA/016741-001/2025    H5N1          USA     2025-01-01
107   A/dairy_cow/USA/016745-001/2025    H5N1          USA     2025-01-01

       Species     Host_Type Genotype  \
0       cattle        cattle    B3.13
1       cattle        cattle    B3.13
2       cattle        cattle    B3.13
3      opossum  other_mammal    B3.13
4       cattle        cattle    B3.13
..         ...           ...      ...
103  dairy_cow        cattle    B3.13
104  dairy_cow        cattle    B3.13
105  dairy_cow        cattle    B3.13
106  dairy_cow        cattle    B3.13
107  dairy_cow        cattle    B3.13

                                              Sequence        Identifier
0    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...       SRR33993024
1    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...       SRR33993025
2    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...       SRR33993026
3    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...       SRR34270243
4    ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...       SRR34270150
..                                                 ...               ...
103  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...  EPI_ISL_20049091
104  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...  EPI_ISL_20049093
105  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...  EPI_ISL_20049092
106  atgagtcttctaaccgaggtcgaaacgtacgttctctctatygtcc...  EPI_ISL_20049095
107  atgagtcttctaaccgaggtcgaaacgtacgttctctctatcgtcc...  EPI_ISL_20049094

[108 rows x 11 columns]
                                                Header     Isolate_Id  \
0    SRR33993024|A/cattle/USA/25-016866-004/2025||U...  25-016866-004
1    SRR33993025|A/cattle/USA/25-016866-002/2025||U...  25-016866-002
2    SRR33993026|A/cattle/USA/25-016847-007/2025||U...  25-016847-007
3    SRR34270243|A/opossum/USA/24-011942-046/2025||...  24-011942-046
4    SRR34270150|A/cattle/USA/25-017893-002/2025||U...  25-017893-002
..                                                 ...            ...
103  EPI_ISL_20049091|A/dairy_cow/USA/017364-001/20...     017364-001
104  EPI_ISL_20049093|A/dairy_cow/USA/016878-003/20...     016878-003
105  EPI_ISL_20049092|A/dairy_cow/USA/017049-001/20...     017049-001
106  EPI_ISL_20049095|A/dairy_cow/USA/016741-001/20...     016741-001
107  EPI_ISL_20049094|A/dairy_cow/USA/016745-001/20...     016745-001

                         Isolate_Name Subtype Geo_Location Date Collected  \
0     A/cattle/USA/25-016866-004/2025                  USA           2025
1     A/cattle/USA/25-016866-002/2025                  USA           2025
2     A/cattle/USA/25-016847-007/2025                  USA           2025
3    A/opossum/USA/24-011942-046/2025                  USA           2025
4     A/cattle/USA/25-017893-002/2025                  USA           2025
..                                ...     ...          ...            ...
103   A/dairy_cow/USA/017364-001/2025    H5N1          USA     2025-01-01
104   A/dairy_cow/USA/016878-003/2025    H5N1          USA     2025-01-01
105   A/dairy_cow/USA/017049-001/2025    H5N1          USA     2025-01-01
106   A/dairy_cow/USA/016741-001/2025    H5N1          USA     2025-01-01
107   A/dairy_cow/USA/016745-001/2025    H5N1          USA     2025-01-01

       Species     Host_Type Genotype  \
0       cattle        cattle    B3.13
1       cattle        cattle    B3.13
2       cattle        cattle    B3.13
3      opossum  other_mammal    B3.13
4       cattle        cattle    B3.13
..         ...           ...      ...
103  dairy_cow        cattle    B3.13
104  dairy_cow        cattle    B3.13
105  dairy_cow        cattle    B3.13
106  dairy_cow        cattle    B3.13
107  dairy_cow        cattle    B3.13

                                              Sequence        Identifier
0    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...       SRR33993024
1    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...       SRR33993025
2    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...       SRR33993026
3    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN...       SRR34270243
4    ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...       SRR34270150
..                                                 ...               ...
103  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...  EPI_ISL_20049091
104  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...  EPI_ISL_20049093
105  atgaatccaaatcaaaagataacaaccattggatcaatctgtatga...  EPI_ISL_20049092
106  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...  EPI_ISL_20049095
107  atgaatccaaatcaaaagataacaaccattggatcaatctgtatgg...  EPI_ISL_20049094

[108 rows x 11 columns]
                                                Header     Isolate_Id  \
0    SRR33993024|A/cattle/USA/25-016866-004/2025||U...  25-016866-004
1    SRR33993025|A/cattle/USA/25-016866-002/2025||U...  25-016866-002
2    SRR33993026|A/cattle/USA/25-016847-007/2025||U...  25-016847-007
3    SRR34270243|A/opossum/USA/24-011942-046/2025||...  24-011942-046
4    SRR34270150|A/cattle/USA/25-017893-002/2025||U...  25-017893-002
..                                                 ...            ...
103  EPI_ISL_20049091|A/dairy_cow/USA/017364-001/20...     017364-001
104  EPI_ISL_20049093|A/dairy_cow/USA/016878-003/20...     016878-003
105  EPI_ISL_20049092|A/dairy_cow/USA/017049-001/20...     017049-001
106  EPI_ISL_20049095|A/dairy_cow/USA/016741-001/20...     016741-001
107  EPI_ISL_20049094|A/dairy_cow/USA/016745-001/20...     016745-001

                         Isolate_Name Subtype Geo_Location Date Collected  \
0     A/cattle/USA/25-016866-004/2025                  USA           2025
1     A/cattle/USA/25-016866-002/2025                  USA           2025
2     A/cattle/USA/25-016847-007/2025                  USA           2025
3    A/opossum/USA/24-011942-046/2025                  USA           2025
4     A/cattle/USA/25-017893-002/2025                  USA           2025
..                                ...     ...          ...            ...
103   A/dairy_cow/USA/017364-001/2025    H5N1          USA     2025-01-01
104   A/dairy_cow/USA/016878-003/2025    H5N1          USA     2025-01-01
105   A/dairy_cow/USA/017049-001/2025    H5N1          USA     2025-01-01
106   A/dairy_cow/USA/016741-001/2025    H5N1          USA     2025-01-01
107   A/dairy_cow/USA/016745-001/2025    H5N1          USA     2025-01-01

       Species     Host_Type Genotype  \
0       cattle        cattle    B3.13
1       cattle        cattle    B3.13
2       cattle        cattle    B3.13
3      opossum  other_mammal    B3.13
4       cattle        cattle    B3.13
..         ...           ...      ...
103  dairy_cow        cattle    B3.13
104  dairy_cow        cattle    B3.13
105  dairy_cow        cattle    B3.13
106  dairy_cow        cattle    B3.13
107  dairy_cow        cattle    B3.13

                                              Sequence        Identifier
0    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...       SRR33993024
1    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...       SRR33993025
2    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...       SRR33993026
3    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...       SRR34270243
4    ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...       SRR34270150
..                                                 ...               ...
103  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...  EPI_ISL_20049091
104  atggcgtcccaaggcaccaaacgatcctatgaacaaatggaaactg...  EPI_ISL_20049093
105  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...  EPI_ISL_20049092
106  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...  EPI_ISL_20049095
107  atggcgtctcaaggcaccaaacgatcctatgaacaaatggaaactg...  EPI_ISL_20049094

[108 rows x 11 columns]
                                                Header     Isolate_Id  \
0    SRR33993024|A/cattle/USA/25-016866-004/2025||U...  25-016866-004
1    SRR33993025|A/cattle/USA/25-016866-002/2025||U...  25-016866-002
2    SRR33993026|A/cattle/USA/25-016847-007/2025||U...  25-016847-007
3    SRR34270243|A/opossum/USA/24-011942-046/2025||...  24-011942-046
4    SRR34270150|A/cattle/USA/25-017893-002/2025||U...  25-017893-002
..                                                 ...            ...
103  EPI_ISL_20049091|A/dairy_cow/USA/017364-001/20...     017364-001
104  EPI_ISL_20049093|A/dairy_cow/USA/016878-003/20...     016878-003
105  EPI_ISL_20049092|A/dairy_cow/USA/017049-001/20...     017049-001
106  EPI_ISL_20049095|A/dairy_cow/USA/016741-001/20...     016741-001
107  EPI_ISL_20049094|A/dairy_cow/USA/016745-001/20...     016745-001

                         Isolate_Name Subtype Geo_Location Date Collected  \
0     A/cattle/USA/25-016866-004/2025                  USA           2025
1     A/cattle/USA/25-016866-002/2025                  USA           2025
2     A/cattle/USA/25-016847-007/2025                  USA           2025
3    A/opossum/USA/24-011942-046/2025                  USA           2025
4     A/cattle/USA/25-017893-002/2025                  USA           2025
..                                ...     ...          ...            ...
103   A/dairy_cow/USA/017364-001/2025    H5N1          USA     2025-01-01
104   A/dairy_cow/USA/016878-003/2025    H5N1          USA     2025-01-01
105   A/dairy_cow/USA/017049-001/2025    H5N1          USA     2025-01-01
106   A/dairy_cow/USA/016741-001/2025    H5N1          USA     2025-01-01
107   A/dairy_cow/USA/016745-001/2025    H5N1          USA     2025-01-01

       Species     Host_Type Genotype  \
0       cattle        cattle    B3.13
1       cattle        cattle    B3.13
2       cattle        cattle    B3.13
3      opossum  other_mammal    B3.13
4       cattle        cattle    B3.13
..         ...           ...      ...
103  dairy_cow        cattle    B3.13
104  dairy_cow        cattle    B3.13
105  dairy_cow        cattle    B3.13
106  dairy_cow        cattle    B3.13
107  dairy_cow        cattle    B3.13

                                              Sequence        Identifier
0    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...       SRR33993024
1    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...       SRR33993025
2    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...       SRR33993026
3    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...       SRR34270243
4    ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...       SRR34270150
..                                                 ...               ...
103  atggattccaacactgtgttaagctttcaggtagactgctttcttt...  EPI_ISL_20049091
104  atggattccaacactgtgttaagctttcaggtagactgctttcttt...  EPI_ISL_20049093
105  atggattccaacactgtgttaagctttcaggtagactgctttcttt...  EPI_ISL_20049092
106  atggattccaacactgtgttaagctttcaggtagactgctttcttt...  EPI_ISL_20049095
107  atggattccaatactgtgttaagctttcaggtagactgctttcttt...  EPI_ISL_20049094

[108 rows x 11 columns]
                                                Header     Isolate_Id  \
0    SRR33993024|A/cattle/USA/25-016866-004/2025||U...  25-016866-004
1    SRR33993025|A/cattle/USA/25-016866-002/2025||U...  25-016866-002
2    SRR33993026|A/cattle/USA/25-016847-007/2025||U...  25-016847-007
3    SRR34270243|A/opossum/USA/24-011942-046/2025||...  24-011942-046
4    SRR34270150|A/cattle/USA/25-017893-002/2025||U...  25-017893-002
..                                                 ...            ...
103  EPI_ISL_20049091|A/dairy_cow/USA/017364-001/20...     017364-001

In [15]:
# Remove duplicates from GISAID/Andersen

print(len(metadata_segments))

count = 0
isolate_partial = {}
for value in metadata_segments["Isolate"].values:
    # partial = value.split("_")[-1] # If 25_, get the last bit
    # print(partial)
    if value != value: # If NaN
        value = ""
    digits = value.split("-")
    isolate = ""
    # other = ""
    for d in digits:
        # print(d)
        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
            isolate = d + "-"
        elif len(d) == 3 and d.isnumeric():
            isolate = isolate + d
        # elif d.isnumeric() == False: # If it's a weird isolate
        #     other = d + "-"
        # else: # If it's a weird isolate
        #     other = other + d
    # Now add to list to check in Andersen files without doing wild for loops
    if len(isolate) == 10: # If this is a correctly formatted isolate
        # isolates.append(isolate)
        # All headers are followed by sequences
        isolate_partial[value] = isolate
    else: # If this is some other isolate
        isolate_partial[value] = value
    # print(isolate)
# for index, value in metadata_segments["Isolate"].items():




to_remove = andersen_isolates
for value in isolate_partial.keys():
    isolate = isolate_partial[value]
    # print(isolate)
    r = re.compile(".*" + isolate + ".*")
    # print(r)
    if len(list(filter(r.search, gisaid_isolates))) > 0:
        for i in list(filter(r.search, gisaid_isolates)):
            to_remove.append(value) 
    # print(to_remove)
    # if isolate_partial[value] in gisaid_andersen_isolates:
    # if value in gisaid_andersen_isolates:
    #     count += 1
    #     to_remove.append(value)
            # metadata_segments = metadata_segments.drop(index)

print(to_remove)
print(len(to_remove))

for value in to_remove:
    if "SRR" in value:
        metadata_segments = metadata_segments[metadata_segments["SRA_Accession"] != value]
    # print(value)
    # print(isolate_partial[value])
    else:
        metadata_segments = metadata_segments[metadata_segments["Isolate"] != value]

print(len(metadata_segments))
print(len(isolate_partial))
metadata_segments
# print(count)

2376
['24-034840-002-original-repeat2', '25-004922-001-original', '25-004922-002-original', '25-004922-003-original', '25-004922-005-original', '25-004922-006-original', '25-014338-001-original', '25-014293-001-original-repeat', '25-012798-007-original-repeat', '24-024710-002-original-repeat2', '24-024710-004-original-repeat2', '24-036182-001-original-repeat2', '24-036182-002-original-repeat2', '25-000462-001-original', '25-000462-002-original', '25-000462-003-original', '25-000462-004-original', '25-007985-001-original-repeat2', '25-011565-001-original-repeat2']
19
2224
297

,Accession,GenBank_RefSeq,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genotype,Isolate,Segment,...,Length,Nuc_Completeness,Geo_Location,Host,Tissue_Specimen_Source,Submitters,Collection_Date,Release_Date,Molecule_type,size
0,PV845802.1,GenBank,SRR33681813,SAMN48710861,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,24-028985-001-tile,1,...,2273,partial,USA: CA,Bos taurus,mammalian milk,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2024-10-01,2025-06-27,ssRNA(-),8
1,PV845803.1,GenBank,SRR33681813,SAMN48710861,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,24-028985-001-tile,2,...,2253,partial,USA: CA,Bos taurus,mammalian milk,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2024-10-01,2025-06-27,ssRNA(-),8
2,PV845804.1,GenBank,SRR33681813,SAMN48710861,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,24-028985-001-tile,3,...,2151,partial,USA: CA,Bos taurus,mammalian milk,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2024-10-01,2025-06-27,ssRNA(-),8
3,PV845805.1,GenBank,SRR33681813,SAMN48710861,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,24-028985-001-tile,4,...,1704,partial,USA: CA,Bos taurus,mammalian milk,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2024-10-01,2025-06-27,ssRNA(-),8
4,PV845806.1,GenBank,SRR33681813,SAMN48710861,PRJNA1102327,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,24-028985-001-tile,5,...,1497,partial,USA: CA,Bos taurus,mammalian milk,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2024-10-01,2025-06-27,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2371,PV792621.1,GenBank,SRR33476664,SAMN48398150,PRJNA980729,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,25-013275-010-original,4,...,1704,partial,USA: NY,Gallus gallus,oronasopharynx,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2025-04-22,2025-06-16,ssRNA(-),8
2372,PV792622.1,GenBank,SRR33476664,SAMN48398150,PRJNA980729,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,25-013275-010-original,5,...,1497,partial,USA: NY,Gallus gallus,oronasopharynx,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2025-04-22,2025-06-16,ssRNA(-),8
2373,PV792623.1,GenBank,SRR33476664,SAMN48398150,PRJNA980729,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,25-013275-010-original,6,...,1410,partial,USA: NY,Gallus gallus,oronasopharynx,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2025-04-22,2025-06-16,ssRNA(-),8
2374,PV792624.1,GenBank,SRR33476664,SAMN48398150,PRJNA980729,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,25-013275-010-original,7,...,982,partial,USA: NY,Gallus gallus,oronasopharynx,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2025-04-22,2025-06-16,ssRNA(-),8
2375,PV792625.1,GenBank,SRR33476664,SAMN48398150,PRJNA980729,Influenza A virus,Alphainfluenzavirus influenzae,H5N1,25-013275-010-original,8,...,838,partial,USA: NY,Gallus gallus,oronasopharynx,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",2025-04-22,2025-06-16,ssRNA(-),8

In [16]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title


# print(metadata_segments["GenBank_Title"].iloc[0])

# Get sequences and headers together
headers = []
isolates = []
sras = []
headers_seqs = {}
with open("sequences.fasta") as f:
    lines = f.readlines()
    for num, line in enumerate(lines):
        if line[0] == ">": # If this is a header
            if line.strip() not in headers: # And is not a header we've seen before
                header = line.strip() 
                # print(header)
                split_header = header.split("|")
                # print(split_header)
                headers.append(header) 
                if num < len(lines): # If we're not at the last line
                    # for i, l in enumerate(lines[num + 1:]):
                    i = num
                    sequence = ""
                    # print(lines[i])
                    # print(lines[i + 1])
                    while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                        sequence = sequence + lines[i + 1].strip()
                        i += 1
                    headers_seqs[header] = sequence # Add next lines to sequences
                # name = split_header[-1] # Last part gives GenBank name, with segment and isolate
                isolate = split_header[2]
                isolates.append(isolate)
                sra = split_header[7]
                sras.append(sra)
    f.close()



# print(mask_all.all(axis=1))

In [17]:
# Double-check de-duplication
mask = metadata_segments["Isolate"].isin(isolates) # Check if isolate is in fasta
# mask_sra = metadata_segments["SRA_Accession"].isin(sras) # Check if sra is in fasta

metadata_masked = metadata_segments[mask] # Some do not have isolates, so check sra too
# metadata_masked_sra = metadata_segments[mask_sra]

# merged_metadata = metadata_masked.merge(metadata_masked_sra, how="outer")
merged_metadata = metadata_masked.drop_duplicates(keep="first")

print(len(headers_seqs))
print(len(merged_metadata))

2448
2224

In [18]:
# Add sequences to a dataframe 
headers_seqs_df = pd.DataFrame.from_dict(headers_seqs, orient="index")
headers_seqs_df = headers_seqs_df.reset_index()
headers_seqs_df["GenBank_Title"] = headers_seqs_df["index"].apply(lambda x: x[1:].split("|")[-1])
headers_seqs_df = headers_seqs_df.rename(columns={0: "Sequence", "index": "Header"})

# Add sequences to the dataframe
metadata_seqs = merged_metadata.merge(headers_seqs_df, on="GenBank_Title", how="left")

print(metadata_seqs)

       Accession GenBank_RefSeq SRA_Accession     BioSample    BioProject  \
0     PV845802.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
1     PV845803.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
2     PV845804.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
3     PV845805.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
4     PV845806.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
...          ...            ...           ...           ...           ...
2219  PV792621.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2220  PV792622.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2221  PV792623.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2222  PV792624.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2223  PV792625.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729

          Organism_Name                         Species Genotype  \
0     Influenza A virus  Alphainfluenzavirus influenzae     H5N1
1     Influenza A virus  Alphainfluenzavirus influenzae     H5N1
2     Influenza A virus  Alphainfluenzavirus influenzae     H5N1
3     Influenza A virus  Alphainfluenzavirus influenzae     H5N1
4     Influenza A virus  Alphainfluenzavirus influenzae     H5N1
...                 ...                             ...      ...
2219  Influenza A virus  Alphainfluenzavirus influenzae     H5N1
2220  Influenza A virus  Alphainfluenzavirus influenzae     H5N1
2221  Influenza A virus  Alphainfluenzavirus influenzae     H5N1
2222  Influenza A virus  Alphainfluenzavirus influenzae     H5N1
2223  Influenza A virus  Alphainfluenzavirus influenzae     H5N1

                     Isolate  Segment  ... Geo_Location           Host  \
0         24-028985-001-tile        1  ...      USA: CA     Bos taurus
1         24-028985-001-tile        2  ...      USA: CA     Bos taurus
2         24-028985-001-tile        3  ...      USA: CA     Bos taurus
3         24-028985-001-tile        4  ...      USA: CA     Bos taurus
4         24-028985-001-tile        5  ...      USA: CA     Bos taurus
...                      ...      ...  ...          ...            ...
2219  25-013275-010-original        4  ...      USA: NY  Gallus gallus
2220  25-013275-010-original        5  ...      USA: NY  Gallus gallus
2221  25-013275-010-original        6  ...      USA: NY  Gallus gallus
2222  25-013275-010-original        7  ...      USA: NY  Gallus gallus
2223  25-013275-010-original        8  ...      USA: NY  Gallus gallus

     Tissue_Specimen_Source  \
0            mammalian milk
1            mammalian milk
2            mammalian milk
3            mammalian milk
4            mammalian milk
...                     ...
2219         oronasopharynx
2220         oronasopharynx
2221         oronasopharynx
2222         oronasopharynx
2223         oronasopharynx

                                             Submitters Collection_Date  \
0     Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2024-10-01
1     Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2024-10-01
2     Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2024-10-01
3     Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2024-10-01
4     Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2024-10-01
...                                                 ...             ...
2219  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2025-04-22
2220  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2025-04-22
2221  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2025-04-22
2222  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2025-04-22
2223  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...      2025-04-22

     Release_Date Molecule_type size  \
0      2025-06-27      ssRNA(-)    8
1      2025-06-27      ssRNA(-)    8
2      2025-06-27      ssRNA(-)    8
3      2025-06-27      ssRNA(-)    8
4      2025-06-27      ssRNA(-)    8
...           ...           ...  ...
2219   2025-06-16      ssRNA(-)    8
2220   2025-06-16      ssRNA(-)    8
2221   2025-06-16      ssRNA(-)    8
2222   2025-06-16      ssRNA(-)    8
2223   2025-06-16      ssRNA(-)    8

                                                 Header  \
0     >Influenza A virus |USA: CA|24-028985-001-tile...
1     >Influenza A virus |USA: CA|24-028985-001-tile...
2     >Influenza A virus |USA: CA|24-028985-001-tile...
3     >Influenza A virus |USA: CA|24-028985-001-tile...
4     >Influenza A virus |USA: CA|24-028985-001-tile...
...                                                 ...
2219  >Influenza A virus |USA: NY|25-013275-010-orig...
2220  >Influenza A virus |USA: NY|25-013275-010-orig...
2221  >Influenza A virus |USA: NY|25-013275-010-orig...
2222  >Influenza A virus |USA: NY|25-013275-010-orig...
2223  >Influenza A virus |USA: NY|25-013275-010-orig...

                                               Sequence
0     GAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCACTCGCGA...
1     CTCTTCTTGAAAGTTCCAGCGCAAAATGCCATAAGCACCACATTCC...
2     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3     ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
4     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
...                                                 ...
2219  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
2220  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
2221  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
2222  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
2223  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...

[2224 rows x 23 columns]

In [19]:
# Create FASTA files per Header

metadata_seqs["Partial_Header"] = metadata_seqs["Header"].apply(lambda x: "|".join(x.split("|")[:-1]))

unique_partial_headers = []

# Each header should repeat 8 times
for partial_header in metadata_seqs["Partial_Header"].values:
    if partial_header not in unique_partial_headers: # Only use the first occurence
        unique_partial_headers.append(partial_header)

print(len(unique_partial_headers)) # Sanity check

278

In [20]:
df_list = []
for partial_header in unique_partial_headers:
    # Get smaller dataframe
    df = metadata_seqs[metadata_seqs["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    df = df[["Header", "Sequence"]]
    df = df.rename(columns={"Header": "full_header", "Sequence": "sequence"}) # For utils function
    df["full_header"] = df["full_header"].apply(lambda x: ">" + x.split("|")[-1].replace(" ", "_"))
    # Make sure there are 8 segments
    if len(df) == 8:
        df_list.append(df)

In [21]:
print(df_list[0])
print(len(df_list))

                                         full_header  \
0  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
1  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
2  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
3  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
4  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
5  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
6  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...
7  >Influenza_A_virus_(A/cattle/CA/24-028985-001-...

                                            sequence
0  GAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCACTCGCGA...
1  CTCTTCTTGAAAGTTCCAGCGCAAAATGCCATAAGCACCACATTCC...
2  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
3  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
4  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
5  ATGAATCCAAATCAGAAGATAACAACCATTGGATCAATCTGTATGG...
6  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7  AGTCCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTTGGC...
278

In [22]:
# Make fasta files. Finally

os.chdir(temp_files)

for df in df_list:
    # print(df)
    file_name = df["full_header"].apply(lambda x: x.split("|")[-1]).values[0] + "_temp.fasta"
    # Forbidden characters
    for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
        file_name = file_name.replace(c, "")
    # print(file_name)
    output_file = open(temp_files + file_name, "w")

    for index, row in df.iterrows():
        name = df.loc[index, "full_header"]
        # print(name)
        sequence = df.loc[index, "sequence"]
        # print(sequence)
        # break 
    # First is header, second is sequence
        output_file.write(name + "\n")
        output_file.write(sequence + "\n")
    output_file.close()

## Re-Labeling Using GenoFlu

In [23]:
# Merging

os.chdir(downloads)

output_genoflu = pd.read_csv("output.tsv", delimiter="\t")

# print(output_genoflu)

# print(metadata_seqs["Header"])

file_name = metadata_seqs["Header"].apply(lambda x: x.split("|")[-1].replace(" ", "_") + "_temp.fasta")
for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
    file_name = file_name.apply(lambda x: x.replace(c, ""))

metadata_seqs["File Name"] = file_name

metadata_genoflu = metadata_seqs.merge(output_genoflu, how="left", on="File Name")

metadata_genoflu = metadata_genoflu.ffill()



print(metadata_genoflu)

       Accession GenBank_RefSeq SRA_Accession     BioSample    BioProject  \
0     PV845802.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
1     PV845803.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
2     PV845804.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
3     PV845805.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
4     PV845806.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
...          ...            ...           ...           ...           ...
2219  PV792621.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2220  PV792622.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2221  PV792623.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2222  PV792624.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729
2223  PV792625.1        GenBank   SRR33476664  SAMN48398150   PRJNA980729

          Organism_Name                         Species Genotype_x  \
0     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
3     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
4     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
...                 ...                             ...        ...
2219  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2220  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2221  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2222  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2223  Influenza A virus  Alphainfluenzavirus influenzae       H5N1

                     Isolate  Segment  ...  \
0         24-028985-001-tile        1  ...
1         24-028985-001-tile        2  ...
2         24-028985-001-tile        3  ...
3         24-028985-001-tile        4  ...
4         24-028985-001-tile        5  ...
...                      ...      ...  ...
2219  25-013275-010-original        4  ...
2220  25-013275-010-original        5  ...
2221  25-013275-010-original        6  ...
2222  25-013275-010-original        7  ...
2223  25-013275-010-original        8  ...

                                         Partial_Header  \
0     >Influenza A virus |USA: CA|24-028985-001-tile...
1     >Influenza A virus |USA: CA|24-028985-001-tile...
2     >Influenza A virus |USA: CA|24-028985-001-tile...
3     >Influenza A virus |USA: CA|24-028985-001-tile...
4     >Influenza A virus |USA: CA|24-028985-001-tile...
...                                                 ...
2219  >Influenza A virus |USA: NY|25-013275-010-orig...
2220  >Influenza A virus |USA: NY|25-013275-010-orig...
2221  >Influenza A virus |USA: NY|25-013275-010-orig...
2222  >Influenza A virus |USA: NY|25-013275-010-orig...
2223  >Influenza A virus |USA: NY|25-013275-010-orig...

                                              File Name     sample  \
0     Influenza_A_virus_AcattleCA24028985001tile2024...  Influenza
1     Influenza_A_virus_AcattleCA24028985001tile2024...  Influenza
2     Influenza_A_virus_AcattleCA24028985001tile2024...  Influenza
3     Influenza_A_virus_AcattleCA24028985001tile2024...  Influenza
4     Influenza_A_virus_AcattleCA24028985001tile2024...  Influenza
...                                                 ...        ...
2219  Influenza_A_virus_AchickenNY25013275010origina...  Influenza
2220  Influenza_A_virus_AchickenNY25013275010origina...  Influenza
2221  Influenza_A_virus_AchickenNY25013275010origina...  Influenza
2222  Influenza_A_virus_AchickenNY25013275010origina...  Influenza
2223  Influenza_A_virus_AchickenNY25013275010origina...  Influenza

                     date Genotype_y  \
0     2025-06-30_15-45-21      B3.13
1     2025-06-30_15-45-21      B3.13
2     2025-06-30_15-45-21      B3.13
3     2025-06-30_15-45-21      B3.13
4     2025-06-30_15-45-21      B3.13
...                   ...        ...
2219  2025-06-30_15-55-33       D1.1
2220  2025-06-30_15-55-33       D1.1
2221  2025-06-30_15-55-33       D1.1
2222  2025-06-30_15-55-33       D1.1
2223  2025-06-30_15-55-33       D1.1

                            Genotype List Used, >=98.0%  \
0     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
1     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
4     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                 ...
2219  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2220  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2221  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2222  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2223  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
1     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
4     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                 ...
2219  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2220  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2221  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2222  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2223  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     98.64%, 99.42%, 99.07%, 98.59%, 99.00%, 98.79%...
1     98.64%, 99.42%, 99.07%, 98.59%, 99.00%, 98.79%...
2     98.64%, 99.42%, 99.07%, 98.59%, 99.00%, 98.79%...
3     98.64%, 99.42%, 99.07%, 98.59%, 99.00%, 98.79%...
4     98.64%, 99.42%, 99.07%, 98.59%, 99.00%, 98.79%...
...                                                 ...
2219  99.65%, 99.30%, 99.49%, 99.53%, 99.67%, 99.29%...
2220  99.65%, 99.30%, 99.49%, 99.53%, 99.67%, 99.29%...
2221  99.65%, 99.30%, 99.49%, 99.53%, 99.67%, 99.29%...
2222  99.65%, 99.30%, 99.49%, 99.53%, 99.67%, 99.29%...
2223  99.65%, 99.30%, 99.49%, 99.53%, 99.67%, 99.29%...

             Genotype Mismatch List Genotype Average Depth of Coverage List
0     31, 13, 20, 24, 15, 17, 12, 8       Ran on FASTA - No Coverage Report
1     31, 13, 20, 24, 15, 17, 12, 8       Ran on FASTA - No Coverage Report
2     31, 13, 20, 24, 15, 17, 12, 8       Ran on FASTA - No Coverage Report
3     31, 13, 20, 24, 15, 17, 12, 8       Ran on FASTA - No Coverage Report
4     31, 13, 20, 24, 15, 17, 12, 8       Ran on FASTA - No Coverage Report
...                             ...                                     ...
2219      8, 16, 11, 8, 5, 10, 3, 9       Ran on FASTA - No Coverage Report
2220      8, 16, 11, 8, 5, 10, 3, 9       Ran on FASTA - No Coverage Report
2221      8, 16, 11, 8, 5, 10, 3, 9       Ran on FASTA - No Coverage Report
2222      8, 16, 11, 8, 5, 10, 3, 9       Ran on FASTA - No Coverage Report
2223      8, 16, 11, 8, 5, 10, 3, 9       Ran on FASTA - No Coverage Report

[2224 rows x 33 columns]

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [32]:
# Re-Labeling

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

fix_animals_andersen(metadata_genoflu, animals_ref)

metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# print(metadata_genoflu["Host_Type"])

names = ">" + metadata_genoflu["SRA_Accession"] + "|A/" + metadata_genoflu["Host"] + "/" + metadata_genoflu["Geo_Location"].apply(lambda x: x.split(": ")[-1]) + "/" + metadata_genoflu["Isolate"] + "/" + metadata_genoflu["Years"].apply(lambda x: str(x)) + "|" + metadata_genoflu["Genotype_x"] + "|" + metadata_genoflu["Geo_Location"].apply(lambda x: x.replace(": ", "-")) + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype_y"]

metadata_genoflu["Name"] = names

print(metadata_genoflu["Name"])

0       >SRR33681813|A/bos taurus/CA/24-028985-001-til...
1       >SRR33681813|A/bos taurus/CA/24-028985-001-til...
2       >SRR33681813|A/bos taurus/CA/24-028985-001-til...
3       >SRR33681813|A/bos taurus/CA/24-028985-001-til...
4       >SRR33681813|A/bos taurus/CA/24-028985-001-til...
                              ...
2219    >SRR33476664|A/gallus gallus/NY/25-013275-010-...
2220    >SRR33476664|A/gallus gallus/NY/25-013275-010-...
2221    >SRR33476664|A/gallus gallus/NY/25-013275-010-...
2222    >SRR33476664|A/gallus gallus/NY/25-013275-010-...
2223    >SRR33476664|A/gallus gallus/NY/25-013275-010-...
Name: Name, Length: 2224, dtype: object

## Merge all datasets and de-duplicate again

In [33]:
# # Set up segments

# segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}

# metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].map(segments)

# # print(metadata_genoflu["Segment_Name"])

# # Separate into several dataframes based on genotype + segment
# segment_genotype_dfs = []
# for segment in segments.values():
#     print(segment)
#     m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
#     print(m_g)
#     for genotype in list(set(m_g["Genotype_y"].values)):
#         if "Not assigned:" not in genotype:
#             df = m_g[(m_g["Genotype_y"] == genotype)] # & (metadata_genoflu["Segment"] == segment)]
#             segment_genotype_dfs.append(df)
#             # pair = genotype + "_" + segment
#             # print(pair)

# print(segment_genotype_dfs[3])

# # print(metadata_genoflu["Header"].apply(lambda x: x.split("|")[-1].split("/")[-1].split(")")[2:]))

In [34]:
# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}



metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].map(segments)

# print(metadata_genoflu["Segment_Name"])

# Separate into several dataframes based on genotype + segment
# b313_count = 0
segment_genotype_dfs = []
for segment in segments.values():
    # print(segment)
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    # print(m_g)
    for genotype in list(set(m_g["Genotype_y"].values)):
        # if "B3.13" in genotype:
        if genotype in genotypes:
            # b313_count += 1
            df = m_g[(m_g["Genotype_y"] == genotype)] # & (metadata_genoflu["Segment"] == segment)]
            # b313_count += len(df)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

# print(b313_count)
# print(segment_genotype_dfs[8])

B3.6_PB2
B3.13_PB2
D1.1_PB2
B3.6_PB1
B3.13_PB1
D1.1_PB1
B3.6_PA
B3.13_PA
D1.1_PA
B3.6_HA
B3.13_HA
D1.1_HA
B3.6_NP
B3.13_NP
D1.1_NP
B3.6_NA
B3.13_NA
D1.1_NA
B3.6_MP
B3.13_MP
D1.1_MP
B3.6_NS
B3.13_NS
D1.1_NS

In [35]:
# Create FASTA files

os.chdir(complete_files)

names = []

for df in segment_genotype_dfs:
    if len(df["Genotype_y"].values[0]) > 0:
        file_name = df["Genotype_y"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            names.append(name)
            # print(name)
            sequence = df.loc[index, "Sequence"]
            # print(sequence)
            # break 
        # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        output_file.close()

print(len(names))

2216

In [36]:
print(segment_genotype_dfs)

[       Accession GenBank_RefSeq SRA_Accession     BioSample   BioProject  \
1656  PV847514.1        GenBank   SRR33682399  SAMN48711133  PRJNA980729

          Organism_Name                         Species Genotype_x  \
1656  Influenza A virus  Alphainfluenzavirus influenzae       H5N1

                     Isolate  Segment  ... Genotype_y  \
1656  25-014787-002-original        1  ...       B3.6

                            Genotype List Used, >=98.0%  \
1656  PB2:am5, PB1:am4, PA:ea1, HA:ea1, NP:am1.4.1, ...

                             Genotype Sample Title List  \
1656  am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...

                            Genotype Percent Match List  \
1656  99.08%, 98.86%, 98.42%, 98.30%, 98.93%, 98.37%...

              Genotype Mismatch List Genotype Average Depth of Coverage List  \
1656  21, 26, 34, 29, 16, 23, 15, 11       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
1656     avian  2025  >SRR33682399|A/gallus gallus/FL/25-014787-002-...

     Segment_Name
1656          PB2

[1 rows x 37 columns],        Accession GenBank_RefSeq SRA_Accession     BioSample    BioProject  \
0     PV845802.1        GenBank   SRR33681813  SAMN48710861  PRJNA1102327
8     PV845810.1        GenBank   SRR33681815  SAMN48710859  PRJNA1102327
16    PV845818.1        GenBank   SRR33681809  SAMN48710865  PRJNA1102327
24    PV845826.1        GenBank   SRR33681775  SAMN48710851  PRJNA1102327
32    PV845834.1        GenBank   SRR33764569  SAMN48808557  PRJNA1102327
...          ...            ...           ...           ...           ...
2128  PV792514.1        GenBank   SRR33476727  SAMN48398187  PRJNA1102327
2136  PV792522.1        GenBank   SRR33476726  SAMN48398188  PRJNA1102327
2144  PV792530.1        GenBank   SRR33369785  SAMN48199940  PRJNA1102327
2152  PV792538.1        GenBank   SRR33369784  SAMN48199941  PRJNA1102327
2160  PV792546.1        GenBank   SRR33369783  SAMN48199942  PRJNA1102327

          Organism_Name                         Species Genotype_x  \
0     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
8     Influenza A virus  Alphainfluenzavirus influenzae       H5N1
16    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
24    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
32    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
...                 ...                             ...        ...
2128  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2136  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2144  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2152  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2160  Influenza A virus  Alphainfluenzavirus influenzae       H5N1

                     Isolate  Segment  ... Genotype_y  \
0         24-028985-001-tile        1  ...      B3.13
8         24-028980-001-tile        1  ...      B3.13
16        24-030164-001-tile        1  ...      B3.13
24        24-027469-003-tile        1  ...      B3.13
32    25-015136-001-original        1  ...      B3.13
...                      ...      ...  ...        ...
2128  25-012909-003-original        1  ...      B3.13
2136  25-012909-004-original        1  ...      B3.13
2144  25-012952-001-original        1  ...      B3.13
2152  25-012952-003-original        1  ...      B3.13
2160  25-012952-005-original        1  ...      B3.13

                            Genotype List Used, >=98.0%  \
0     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
8     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
16    PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
24    PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
32    PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                 ...
2128  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2136  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2144  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2152  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2160  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...

                             Genotype Sample Title List  \
0     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
8     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
16    am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
24    am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
32    am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                 ...
2128  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2136  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2144  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2152  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2160  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...

                            Genotype Percent Match List  \
0     98.64%, 99.42%, 99.07%, 98.59%, 99.00%, 98.79%...
8     98.68%, 99.51%, 99.02%, 98.47%, 99.06%, 98.86%...
16    98.68%, 99.47%, 99.12%, 98.47%, 99.06%, 98.79%...
24    98.68%, 99.51%, 99.07%, 98.53%, 99.06%, 98.86%...
32    98.51%, 99.38%, 98.84%, 98.30%, 98.86%, 98.65%...
...                                                 ...
2128  98.51%, 99.56%, 98.88%, 98.24%, 98.93%, 98.72%...
2136  98.51%, 99.56%, 98.88%, 98.24%, 98.93%, 98.72%...
2144  98.47%, 99.52%, 98.88%, 98.30%, 98.93%, 98.58%...
2152  98.47%, 99.52%, 98.88%, 98.30%, 98.93%, 98.58%...
2160  98.47%, 99.56%, 98.88%, 98.24%, 98.93%, 98.72%...

              Genotype Mismatch List Genotype Average Depth of Coverage List  \
0      31, 13, 20, 24, 15, 17, 12, 8       Ran on FASTA - No Coverage Report
8      30, 11, 21, 26, 14, 16, 10, 7       Ran on FASTA - No Coverage Report
16     30, 12, 19, 26, 14, 17, 10, 8       Ran on FASTA - No Coverage Report
24     30, 11, 20, 25, 14, 16, 10, 7       Ran on FASTA - No Coverage Report
32    34, 14, 25, 29, 17, 19, 10, 10       Ran on FASTA - No Coverage Report
...                              ...                                     ...
2128   34, 10, 24, 30, 16, 18, 10, 9       Ran on FASTA - No Coverage Report
2136   34, 10, 24, 30, 16, 18, 10, 9       Ran on FASTA - No Coverage Report
2144   35, 11, 24, 29, 16, 20, 9, 11       Ran on FASTA - No Coverage Report
2152   35, 11, 24, 29, 16, 20, 9, 11       Ran on FASTA - No Coverage Report
2160   35, 10, 24, 30, 16, 18, 10, 9       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
0       cattle  2024  >SRR33681813|A/bos taurus/CA/24-028985-001-til...
8       cattle  2024  >SRR33681815|A/bos taurus/CA/24-028980-001-til...
16      cattle  2024  >SRR33681809|A/bos taurus/CA/24-030164-001-til...
24      cattle  2024  >SRR33681775|A/bos taurus/CA/24-027469-003-til...
32      cattle  2025  >SRR33764569|A/bos taurus/ID/25-015136-001-ori...
...        ...   ...                                                ...
2128    cattle  2025  >SRR33476727|A/bos taurus/ID/25-012909-003-ori...
2136    cattle  2025  >SRR33476726|A/bos taurus/ID/25-012909-004-ori...
2144    cattle  2025  >SRR33369785|A/bos taurus/ID/25-012952-001-ori...
2152    cattle  2025  >SRR33369784|A/bos taurus/ID/25-012952-003-ori...
2160    cattle  2025  >SRR33369783|A/bos taurus/ID/25-012952-005-ori...

     Segment_Name
0             PB2
8             PB2
16            PB2
24            PB2
32            PB2
...           ...
2128          PB2
2136          PB2
2144          PB2
2152          PB2
2160          PB2

[238 rows x 37 columns],        Accession GenBank_RefSeq SRA_Accession     BioSample   BioProject  \
56    PV845858.1        GenBank   SRR33682398  SAMN48711134  PRJNA980729
64    PV845866.1        GenBank   SRR33682397  SAMN48711135  PRJNA980729
72    PV845874.1        GenBank   SRR33564628  SAMN48491408  PRJNA980729
80    PV845882.1        GenBank   SRR33564627  SAMN48491409  PRJNA980729
88    PV845890.1        GenBank   SRR33764496  SAMN48808519  PRJNA980729
96    PV845898.1        GenBank   SRR33764494  SAMN48808520  PRJNA980729
1520  PV847378.1        GenBank   SRR33764506  SAMN48808501  PRJNA980729
1528  PV847386.1        GenBank   SRR33764495  SAMN48808502  PRJNA980729
1536  PV847394.1        GenBank   SRR33764493  SAMN48808503  PRJNA980729
1544  PV847402.1        GenBank   SRR33764492  SAMN48808504  PRJNA980729
1552  PV847410.1        GenBank   SRR33764491  SAMN48808505  PRJNA980729
1560  PV847418.1        GenBank   SRR33764490  SAMN48808506  PRJNA980729
1568  PV847426.1        GenBank   SRR33764489  SAMN48808507  PRJNA980729
1576  PV847434.1        GenBank   SRR33764488  SAMN48808508  PRJNA980729
1584  PV847442.1        GenBank   SRR33764487  SAMN48808509  PRJNA980729
1592  PV847450.1        GenBank   SRR33764505  SAMN48808510  PRJNA980729
1600  PV847458.1        GenBank   SRR33764504  SAMN48808511  PRJNA980729
1608  PV847466.1        GenBank   SRR33764503  SAMN48808512  PRJNA980729
1616  PV847474.1        GenBank   SRR33764502  SAMN48808513  PRJNA980729
1624  PV847482.1        GenBank   SRR33764501  SAMN48808514  PRJNA980729
1632  PV847490.1        GenBank   SRR33764500  SAMN48808515  PRJNA980729
1640  PV847498.1        GenBank   SRR33764499  SAMN48808516  PRJNA980729
1648  PV847506.1        GenBank   SRR33764498  SAMN48808517  PRJNA980729
1664  PV847522.1        GenBank   SRR33564631  SAMN48491405  PRJNA980729
1672  PV847530.1        GenBank   SRR33564630  SAMN48491406  PRJNA980729
1680  PV847538.1        GenBank   SRR33564629  SAMN48491407  PRJNA980729
1688  PV847546.1        GenBank   SRR33764507  SAMN48808500  PRJNA980729
1696  PV847554.1        GenBank   SRR33564634  SAMN48491402  PRJNA980729
1704  PV847562.1        GenBank   SRR33564633  SAMN48491403  PRJNA980729
1720  PV792042.1        GenBank   SRR33476661  SAMN48398153  PRJNA980729
1728  PV792050.1        GenBank   SRR33476660  SAMN48398154  PRJNA980729
1736  PV792058.1        GenBank   SRR33476659  SAMN48398155  PRJNA980729
2176  PV792578.1        GenBank   SRR33476668  SAMN48398146  PRJNA980729
2184  PV792586.1        GenBank   SRR33476667  SAMN48398147  PRJNA980729
2192  PV792594.1        GenBank   SRR33476663  SAMN48398151  PRJNA980729
2200  PV792602.1        GenBank   SRR33476666  SAMN48398148  PRJNA980729
2208  PV792610.1        GenBank   SRR33476665  SAMN48398149  PRJNA980729
2216  PV792618.1        GenBank   SRR33476664  SAMN48398150  PRJNA980729

          Organism_Name                         Species Genotype_x  \
56    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
64    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
72    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
80    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
88    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
96    Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1520  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1528  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1536  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1544  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1552  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1560  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1568  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1576  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1584  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1592  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1600  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1608  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1616  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1624  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1632  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1640  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1648  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1664  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1672  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1680  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1688  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1696  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1704  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1720  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1728  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
1736  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2176  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2184  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2192  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2200  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2208  Influenza A virus  Alphainfluenzavirus influenzae       H5N1
2216  Influenza A virus  Alphainfluenzavirus influenzae       H5N1

                     Isolate  Segment  ... Genotype_y  \
56    25-015044-004-original        1  ...       D1.1
64    25-015044-006-original        1  ...       D1.1
72    25-014146-001-original        1  ...       D1.1
80    25-014146-002-original        1  ...       D1.1
88    25-015216-001-original        1  ...       D1.1
96    25-015216-002-original        1  ...       D1.1
1520  25-015760-001-original        1  ...       D1.1
1528  25-015760-002-original        1  ...       D1.1
1536  25-015760-003-original        1  ...       D1.1
1544  25-015760-004-original        1  ...       D1.1
1552  25-015760-005-original        1  ...       D1.1
1560  25-015760-006-original        1  ...       D1.1
1568  25-015760-008-original        1  ...       D1.1
1576  25-015760-009-original        1  ...       D1.1
1584  25-015760-010-original        1  ...       D1.1
1592  25-015760-012-original        1  ...       D1.1
1600  25-015760-014-original        1  ...       D1.1
1608  25-015760-015-original        1  ...       D1.1
1616  25-015760-016-original        1  ...       D1.1
1624  25-015760-017-original        1  ...       D1.1
1632  25-015760-018-original        1  ...       D1.1
1640  25-015760-019-original        1  ...       D1.1
1648  25-015760-020-original        1  ...       D1.1
1664  25-014151-001-original        1  ...       D1.1
1672  25-014151-002-original        1  ...       D1.1
1680  25-014151-003-original        1  ...       D1.1
1688  25-014921-001-original        1  ...       D1.1
1696  25-013882-001-original        1  ...       D1.1
1704  25-013882-002-original        1  ...       D1.1
1720  25-013275-004-original        1  ...       D1.1
1728  25-013275-005-original        1  ...       D1.1
1736  25-013275-009-original        1  ...       D1.1
2176  25-013149-001-original        1  ...       D1.1
2184  25-013149-002-original        1  ...       D1.1
2192  25-013300-001-original        1  ...       D1.1
2200  25-013275-002-original        1  ...       D1.1
2208  25-013275-007-original        1  ...       D1.1
2216  25-013275-010-original        1  ...       D1.1

                            Genotype List Used, >=98.0%  \
56    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
64    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
72    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
80    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
88    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
96    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1520  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1528  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1536  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1544  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1552  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1560  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1568  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1576  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1584  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1592  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1600  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1608  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1616  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1624  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1632  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1640  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1648  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1664  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1672  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1680  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1688  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1696  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1704  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1720  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1728  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1736  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2176  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2184  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2192  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2200  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2208  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2216  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
56    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
64    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
72    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
80    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
88    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
96    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1520  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1528  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1536  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1544  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1552  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1560  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1568  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1576  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1584  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1592  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1600  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1608  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1616  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1624  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1632  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1640  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1648  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1664  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1672  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1680  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1688  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1696  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1704  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1720  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1728  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1736  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2176  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2184  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2192  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2200  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2208  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2216  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
56    99.52%, 99.25%, 99.44%, 99.35%, 99.60%, 99.29%...
64    99.52%, 99.25%, 99.49%, 99.35%, 99.60%, 99.29%...
72    99.52%, 99.03%, 99.53%, 99.41%, 99.40%, 99.43%...
80    99.52%, 99.03%, 99.49%, 99.41%, 99.40%, 99.43%...
88    99.65%, 99.34%, 99.35%, 99.47%, 99.73%, 99.36%...
96    99.65%, 99.34%, 99.35%, 99.47%, 99.73%, 99.36%...
1520  99.52%, 99.25%, 99.49%, 99.47%, 99.60%, 99.50%...
1528  99.56%, 99.25%, 99.49%, 99.47%, 99.60%, 99.50%...

In [37]:
# Concatenate

os.chdir(combined_files)

filenames_gisaid_andersen = []
for genotype in genotypes:
    # print(gisaid_andersen + genotype.replace(".", "_") + "/")
    # for dirpath, dirs, files in os.walk(gisaid_andersen + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "/"):
    for dirpath, dirs, files in os.walk(gisaid_andersen): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            filenames_gisaid_andersen.append(file_name)
        break 

print(filenames_gisaid_andersen)

filenames_ncbi = []
for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        filenames_ncbi.append(file_name)
    break 

print(filenames_ncbi)

do_not_do_these_partials = []
for ga_file in filenames_gisaid_andersen:
    partial_filename_ga = ga_file.split("_")[-4].split("/")[-1] + "_" + ga_file.split("_")[-3]
    for nv_file in filenames_ncbi:
        partial_filename_nv = nv_file.split("_")[-3].split("/")[-1] + "_" + nv_file.split("_")[-2]
        if partial_filename_ga == partial_filename_nv:
            do_not_do_these_partials.append(partial_filename_ga)
            print(partial_filename_nv)
            filenames = [ga_file, nv_file]
            with open(combined_files + partial_filename_ga + "_combined_" + date_range + ".fasta", 'w') as outfile:
                for fname in filenames:
                    with open(fname) as infile:
                        for line in infile:
                            outfile.write(line)

for ga_file in filenames_gisaid_andersen:
    partial_filename_ga = ga_file.split("_")[-4].split("/")[-1] + "_" + ga_file.split("_")[-3]
    if partial_filename_ga not in do_not_do_these_partials:
        with open(combined_files + partial_filename_ga + "_combined_" + date_range + ".fasta", 'w') as outfile2:
            # for fname in filenames_gisaid_andersen:
            with open(ga_file) as infile1:
                for line in infile1:
                    outfile2.write(line)
    

# lines = 0

# fns_seen = set()
# for filename in filenames_ncbi:
#     print("NCBI_Virus", filename)
#     # lines = 0
#     # filename.split("_")[-5] + "." +   
#     partial_filename = filename.split("_")[-3].split("/")[-1] + "_" + filename.split("_")[-2] 
#     print(partial_filename)
    
#     for fn in filenames_gisaid_andersen:
#         # print(fns_seen)
#         if partial_filename in fn: # and partial_filename not in fns_seen: # If partial filenames match
#             fns_seen.add(fn)
#         #     fns_seen.add(partial_filename)
#             # print("hi", partial_filename)
#             filenames = [filename, fn]
#             with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile:
#                 for fname in filenames:
#                     with open(fname) as infile1:
#                         for line in infile1:
#                             outfile.write(line)

# for fn in filenames_gisaid_andersen: # Extra files
#     if fn not in fns_seen:
#         partial_filename = fn.split("_")[-4].split("/")[-1] + "_" + fn.split("_")[-3] 
#         with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile:
#             for fname in filenames:
#                 with open(fname) as infile1:
#                     for line in infile1:
#                         outfile.write(line)
    
#                             # if line[0] == ">":
#                             #     lines += 1
#             #         infile.close()
#             # outfile.close()
#         # elif partial_filename not in fns_seen: # Save the ones that aren't shared -- if partial filename was not seen before
#         #     # print("hello", partial_filename)
#         #     fns_seen.add(partial_filename)
#         #     with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile2:
#         #         # Copy
#         #         with open(fn) as infile2:
#         #             for line in infile2:
#         #                 outfile2.write(line)
#         # else: # If partial filename doesn't match AND if partial filename has been seen before
#         #     continue 
#         #                 # if line[0] == ">":
#         #                 #     lines += 1
#         #             # infile.close()
#         #         with open(fn) as infile3:
#         #             for line in infile3:
#         #                 outfile2.write(line)
#         #                 # if line[0] == ">":
#                         #     lines += 1
#             #     infile.close()
#         outfile.close()


#     # break 

#     # print(lines)

# # lines = 0
# # Counting
#     with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'r') as outfile:
#         for line in outfile.readlines():
#             if line[0] == ">":
#                 lines += 1

# print(lines)

['C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_HA_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_MP_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_NA_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_NP_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_NS_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_PA_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_PB1_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_PB2_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/D1.1_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/Minor92_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/A3_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.13_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.2_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_NS_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_PA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_PB1_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/B3.7_PB2_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_HA_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_MP_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_NA_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_NP_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_NS_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_PA_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_PB1_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C2.1_PB2_06-14-2025--06-27-2025_andersen_updated.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_HA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_MP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_NA_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/all_genotypes/06-14-2025--06-27-2025_all_genotypes/C3.1_NP_combined_06-14-2025--06-27-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAI

In [38]:
# # Mega fasta file
# all_files = []
# for dirpath, dirs, files in os.walk(combined_files):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         all_files.append(file_name)

# with open(combined_files + "all_files_combined_" + update_date + ".fasta", 'w') as outfile3:
#     for fname in all_files:
#         with open(fname) as infile4:
#             for line in infile4:
#                 outfile3.write(line)
# #         infile.close()
# # outfile.close()

In [40]:
# Animals 

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['gallus gallus', 'anatidae', 'bos taurus', 'perdicinae', 'meleagris gallopavo']
[]
                      avian               cattle        feline   other_mammal  \
0          great_horned_owl            dairy_cow           cat     deer mouse
1              common_raven               cattle  domestic_cat    house_mouse
2             cooper's_hawk  cattle milk product     feral_cat          skunk
3              coopers_hawk          bovine_milk        feline  striped_skunk
4                   peafowl              bovine   domestic-cat     norway rat
..                      ...                  ...           ...            ...
798  von_schrenck's_bittern                  NaN           NaN            NaN
799           harris's_hawk                  NaN           NaN            NaN
800           eurasian_coot                  NaN           NaN            NaN
801                   layer                  NaN           NaN            NaN
802              perdicinae                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             '  NaN
..          ...           ...  ...
798         NaN           NaN  NaN
799         NaN           NaN  NaN
800         NaN           NaN  NaN
801         NaN           NaN  NaN
802         NaN           NaN  NaN

[803 rows x 7 columns]

In [ ]:
# # Concat

# os.chdir(combined_files)

# for dirpath, dirs, files in os.walk(complete_files):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         print(file_name)
#         for dirpath1, dirs1, files1 in os.walk(gisaid_andersen):
#             for file1 in files1:
#                 file_name1 = os.path.join(dirpath1, file1)
#                 if file_name.split("/")[-1].split("_")[0] + file_name.split("/")[-1].split("_")[1] == file_name1.split("/")[-1].split("_")[0] + file_name1.split("/")[-1].split("_")[1]:
                    
#                     output_path = combined_files + file_name1.split("/")[-1] # Genotype and Segment should all be the same
#                     output_file = open(output_path, "w")
#                     with open(file_name) as f:
#                         for line in f.readlines():
#                             output_file.write(line)
#                             # output_file.write("\n")
#                         f.close()
#                     with open(file_name1) as f1:
#                        for line in f1.readlines():
#                             output_file.write(line)
#                             # output_file.write("\n")
#                     f1.close()  

#                     output_file.close()