# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [1]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai/Documents/Avian_Flu"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen_Downloads/"
temp_files = downloads + "Andersen_Temp_Files/"
complete_files = downloads + "Andersen_Complete_Files/"

os.chdir(downloads)

In [2]:
# Read metadata

metadata_folder = downloads + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

# Split date format to only check year
for date in metadata["Collection_Date"]:
    if "/" in date or date == "missing":
        metadata = metadata[metadata["Collection_Date"] != date]
metadata["Collection_Date"] = metadata["Collection_Date"].apply(lambda x: x.split("-")[0])
metadata["Collection_Date"] = metadata["Collection_Date"].apply(lambda x: int(x))

# Find only >= 2024 using run ID from metadata
metadata_new = metadata[metadata["Collection_Date"] >= 2024]
metadata_new["Collection_Date"] = metadata_new["Collection_Date"].astype(int) # Years are not floats

print(len(metadata_new)) # 6053 rows

7397
6053

C:\Users\maksiaevai\AppData\Local\Temp\2\ipykernel_24120\268948126.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_new["Collection_Date"] = metadata_new["Collection_Date"].astype(int) # Years are not floats

In [3]:
# Modify isolates to xxxxxx-xxx

# new_isolates = []
# for isolate in metadata_new["isolate"]:
#     new_isolate = ""
#     # if isolate:
#     #     print(isolate)
#     try:
#         split_isolate = isolate.split("-")
#     except:
#         new_isolate = ""
#     # else:
#     #     split_isolate = ""
#     for split in split_isolate:
#         if len(split) == 6:
#             new_isolate = new_isolate + split
#         if len(split) == 3:
#             new_isolate = new_isolate + "-" + split
#     new_isolates.append(new_isolate)

# metadata_new["isolate"] = new_isolates

# display(metadata_new["isolate"])

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype: B3.13 or D1.1]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use output.tsv

In [4]:
# Get genotype from genoflu
os.chdir(temp_files)
output_tsv = pd.read_csv("output.tsv", delimiter="\t")

b313_and_d11_only = output_tsv[(output_tsv["Genotype"] == "B3.13") | (output_tsv["Genotype"] == "D1.1")]
b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")
# print(b313_and_d11_only)
print(len(b313_and_d11_only)) # 5160 rows

metadata_new = metadata_new.merge(b313_and_d11_only, on="Run", how="inner")

print(len(metadata_new)) # 5160

5160
5160

In [5]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata_new, animals_ref) # Get host type
metadata_new["years"] = metadata_new["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

In [6]:
print(len(metadata_new))

5160

In [7]:
# Get geolocation from genbank_mapping.tsv

os.chdir(metadata_folder)
genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run")
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2])
# genbank_mapping["isolate"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[3])

# Change isolate names in genbank mapping

# new_isolates = []
# for isolate in genbank_mapping["isolate"]:
#     new_isolate = ""
#     # if isolate:
#     #     print(isolate)
#     try:
#         split_isolate = isolate.split("-")
#     except:
#         continue
#     # else:
#     #     split_isolate = ""
#     for split in split_isolate:
#         if len(split) == 6:
#             new_isolate = new_isolate + split
#         if len(split) == 3:
#             new_isolate = new_isolate + "-" + split
#     new_isolates.append(new_isolate)

# genbank_mapping["isolate"] = new_isolates


# map to metadata


metadata_genbank = metadata_new.merge(genbank_mapping, on="Run", how="inner")

print(len(metadata_genbank))
display(metadata_genbank)

3357

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,Host_Type,years,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state
0,SRR28752446,WGS,146.11,93605195,PRJNA1102327,SAMN41019184,Viral,30074178,USDA-NVSL,2024,...,avian,2024,SRR28752446_HA_cns.fa,Consensus_SRR28752446_HA_cns_threshold_0.5_qua...,SRR28752446,HA,PP740722.1,4,A/blackbird/Texas/24-008354-001/2024,Texas
1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,cattle,2024,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,SRR28752447,HA,PP752829.1,4,A/cattle/Texas/24-009108-005/2024,Texas
2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,cattle,2024,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,SRR28752448,HA,PP752821.1,4,A/cattle/Texas/24-009108-004/2024,Texas
3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,cattle,2024,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,SRR28752449,HA,PP752813.1,4,A/cattle/Texas/24-009108-003/2024,Texas
4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,cattle,2024,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,SRR28752450,HA,PP752805.1,4,A/cattle/Texas/24-009108-002/2024,Texas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,SRR32653896,WGS,147.21,170346135,PRJNA1102327,SAMN47305024,Viral,58690418,USDA-NVSL,2025,...,cattle,2025,SRR32653896_HA_cns.fa,Consensus_SRR32653896_HA_cns_threshold_0.5_qua...,SRR32653896,HA,PV338836.1,4,A/cattle/CA/25-003262-003-original/2024,CA
3353,SRR32653897,WGS,148.06,69910137,PRJNA1102327,SAMN47305023,Viral,23973854,USDA-NVSL,2025,...,cattle,2025,SRR32653897_HA_cns.fa,Consensus_SRR32653897_HA_cns_threshold_0.5_qua...,SRR32653897,HA,PV338828.1,4,A/cattle/CA/25-003262-002-original/2024,CA
3354,SRR32653898,WGS,148.21,61895474,PRJNA1102327,SAMN47305022,Viral,21444614,USDA-NVSL,2025,...,cattle,2025,SRR32653898_HA_cns.fa,Consensus_SRR32653898_HA_cns_threshold_0.5_qua...,SRR32653898,HA,PV338820.1,4,A/cattle/CA/25-003262-001-original/2024,CA
3355,SRR32653899,WGS,148.15,67537431,PRJNA1102327,SAMN47305021,Viral,25457165,USDA-NVSL,2025,...,avian,2025,SRR32653899_HA_cns.fa,Consensus_SRR32653899_HA_cns_threshold_0.5_qua...,SRR32653899,HA,PV336676.1,4,A/Duck/CA/25-003063-003-original/2025,CA
3356,SRR32653903,WGS,147.27,96292618,PRJNA1102327,SAMN47305027,Viral,33482181,USDA-NVSL,2025,...,feline,2025,SRR32653903_HA_cns.fa,Consensus_SRR32653903_HA_cns_threshold_0.5_qua...,SRR32653903,HA,PV338476.1,4,A/cat/CO/25-003476-003-original/2025,CO

In [ ]:
# Get collection date from GenBank eutils 

def search_collection_date(biosample):

    print(biosample)
    
    # Avoid spamming the server
    time.sleep(2)

    try:
    
        base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
        search_url = base_url + "esearch.fcgi?db=biosample&term=" + biosample +"&usehistory=y&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

        # Get Biosample ID from search_url
        output = requests.get(search_url)
        xml = output.content
        root = ET.fromstring(xml)
        sample_id = root.find("./IdList/Id").text

        biosample_url = base_url + "elink.fcgi?dbfrom=biosample&db=nuccore&id=" + sample_id + "&cmd=neighbor_history&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"
        
        # Get Nucleotide ID from biosample_url
        output = requests.get(biosample_url)
        xml = output.content
        root = ET.fromstring(xml)
        query_key = root.find(".//QueryKey").text
        web_env = root.find(".//WebEnv").text

        nucleotide_url = base_url + "esummary.fcgi?db=nuccore&query_key=" + query_key + "&WebEnv=" + web_env + "&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

        output = requests.get(nucleotide_url) 
        xml = output.content
        root = ET.fromstring(xml)

        # Grab collection date at the end of the sub name
        collection_date = root.find(".//SubName").text.split("|")[-1]

        return collection_date
    
    except:
        print("Unable to find collection date.")

        collection_date = metadata_genbank[metadata_genbank["BioSample"] == biosample]["years"]

        return collection_date
    
metadata_genbank["Collection_Date_Specific"] = metadata_genbank["BioSample"].apply(search_collection_date)

SAMN41019184
SAMN41019237
SAMN41019236
SAMN41019235
Unable to find collection date.
SAMN41019234
SAMN41019233
SAMN41019232
SAMN41019231
SAMN41019230
SAMN41019229
SAMN41019228
SAMN41019183
SAMN41019227
SAMN41019226
SAMN41019225
SAMN41019224
SAMN41019223
SAMN41019222
SAMN41019221
SAMN41019220
SAMN41019219
SAMN41019218
SAMN41019182
SAMN41019217
SAMN41019215
SAMN41019213
SAMN41019212
SAMN41019209
SAMN41019366
SAMN41019365
SAMN41019364
SAMN41019363
SAMN41019362
SAMN41019361
SAMN41019360
SAMN41019359
SAMN41019358
SAMN41019196
SAMN41019357
SAMN41019356
SAMN41019355
SAMN41019354
SAMN41019353
SAMN41019352
SAMN41019351
SAMN41019350
SAMN41019349
SAMN41019348
SAMN41019195
SAMN41019347
SAMN41019346
SAMN41019345
SAMN41019344
SAMN41019343
SAMN41019342
SAMN41019341
SAMN41019340
SAMN41019339
SAMN41019338
SAMN41019194
SAMN41019277
SAMN41019276
SAMN41019275
SAMN41019274
SAMN41019273
SAMN41019272
SAMN41019271
SAMN41019270
SAMN41019269
SAMN41019268
SAMN41019187
SAMN41019208
SAMN41019181
Unable to find collection date.
SAMN41019207
SAMN41019206
SAMN41019205
SAMN41019204
SAMN41019202
SAMN41019416
SAMN41019415
SAMN41019414
SAMN41019413
SAMN41019412
SAMN41019411
SAMN41019410
SAMN41019409
SAMN41019408
SAMN41019201
SAMN41019407
SAMN41019406
SAMN41019405
SAMN41019404
SAMN41019403
SAMN41019402
SAMN41019401
SAMN41019400
SAMN41019399
SAMN41019398
SAMN41019397
SAMN41019396
SAMN41019395
SAMN41019337
SAMN41019335
SAMN41019334
SAMN41019333
SAMN41019332
SAMN41019331
SAMN41019330
SAMN41019329
SAMN41019328
SAMN41019193
SAMN41019327
SAMN41019326
SAMN41019325
SAMN41019324
SAMN41019323
SAMN41019322
SAMN41019321
SAMN41019320
SAMN41019319
SAMN41019318
SAMN41019192
SAMN41019317
SAMN41019316
SAMN41019315
SAMN41019314
SAMN41019313
SAMN41019312
SAMN41019311
SAMN41019310
SAMN41019309
SAMN41019308
SAMN41019267
SAMN41019266
SAMN41019265
SAMN41019264
SAMN41019263
SAMN41019262
SAMN41019261
SAMN41019260
SAMN41019259
SAMN41019258
SAMN41019186
SAMN41019257
SAMN41019256
SAMN41019255
SAMN41019254
SAMN41019253
SAMN41019252
SAMN41019251
SAMN41019250
SAMN41019249
SAMN41019248
SAMN41019185
SAMN41019247
SAMN41019246
SAMN41019245
SAMN41019244
SAMN41019243
SAMN41019242
SAMN41019241
SAMN41019240
SAMN41019239
SAMN41019238
SAMN41019394
SAMN41019393
SAMN41019392
SAMN41019391
SAMN41019390
SAMN41019389
SAMN41019388
SAMN41019199
SAMN41019387
SAMN41019386
SAMN41019385
SAMN41019384
SAMN41019383
SAMN41019382
SAMN41019381
Unable to find collection date.
SAMN41019380
Unable to find collection date.
SAMN41019379
Unable to find collection date.
SAMN41019378
Unable to find collection date.
SAMN41019198
Unable to find collection date.
SAMN41019180
Unable to find collection date.
SAMN41019377
Unable to find collection date.
SAMN41019376
Unable to find collection date.
SAMN41019375
Unable to find collection date.
SAMN41019374
Unable to find collection date.
SAMN41019373
Unable to find collection date.
SAMN41019372
Unable to find collection date.
SAMN41019371
Unable to find collection date.
SAMN41019370
Unable to find collection date.
SAMN41019369
Unable to find collection date.
SAMN41019368
Unable to find collection date.
SAMN41019367
Unable to find collection date.
SAMN41019191
Unable to find collection date.
SAMN41019307
Unable to find collection date.
SAMN41019306
Unable to find collection date.
SAMN41019305
Unable to find collection date.
SAMN41019304
Unable to find collection date.
SAMN41019303
Unable to find collection date.
SAMN41019302
Unable to find collection date.
SAMN41019301
SAMN41019300
Unable to find collection date.
SAMN41019299
Unable to find collection date.
SAMN41019298
Unable to find collection date.
SAMN41019190
Unable to find collection date.
SAMN41019297
Unable to find collection date.
SAMN41019296
Unable to find collection date.
SAMN41019295
Unable to find collection date.
SAMN41019294
Unable to find collection date.
SAMN41019293
Unable to find collection date.
SAMN41019292
SAMN41019291
Unable to find collection date.
SAMN41019290
SAMN41019289
Unable to find collection date.
SAMN41019288
Unable to find collection date.
SAMN41019189
Unable to find collection date.
SAMN41019287
Unable to find collection date.
SAMN41019286
Unable to find collection date.
SAMN41019285
Unable to find collection date.
SAMN41019284
Unable to find collection date.
SAMN41019283
SAMN41019282
SAMN41019281
SAMN41019280
SAMN41019279
Unable to find collection date.
SAMN41019278
Unable to find collection date.
SAMN41019188
Unable to find collection date.
SAMN41019179
Unable to find collection date.
SAMN41100353
Unable to find collection date.
SAMN41100350
SAMN41106832
Unable to find collection date.
SAMN41106831
Unable to find collection date.
SAMN41106830
Unable to find collection date.
SAMN41106826
Unable to find collection date.
SAMN41106825
Unable to find collection date.
SAMN41390792
Unable to find collection date.
SAMN41390791
Unable to find collection date.
SAMN41390790
Unable to find collection date.
SAMN41390788
Unable to find collection date.
SAMN41390787
Unable to find collection date.
SAMN41390786
Unable to find collection date.
SAMN41390812
Unable to find collection date.
SAMN41390811
Unable to find collection date.
SAMN41390810
Unable to find collection date.
SAMN41390809
Unable to find collection date.
SAMN41390808
Unable to find collection date.
SAMN41390807
Unable to find collection date.
SAMN41390806
Unable to find collection date.
SAMN41390805
SAMN41390804
Unable to find collection date.
SAMN41390803
SAMN41390785
SAMN41390802
Unable to find collection date.
SAMN41390801
Unable to find collection date.
SAMN41390800
Unable to find collection date.
SAMN41390799
Unable to find collection date.
SAMN41390798
SAMN41390797
Unable to find collection date.
SAMN41390796
Unable to find collection date.
SAMN41390795
Unable to find collection date.
SAMN41390794
Unable to find collection date.
SAMN41390793
Unable to find collection date.
SAMN41390784
Unable to find collection date.
SAMN41390783
SAMN41267476
SAMN41267486
Unable to find collection date.
SAMN41267485
SAMN41267484
SAMN41267496
Unable to find collection date.
SAMN41267495
Unable to find collection date.
SAMN41267475
Unable to find collection date.
SAMN41267474
Unable to find collection date.
SAMN41267473
Unable to find collection date.
SAMN41267472
Unable to find collection date.
SAMN41267483
Unable to find collection date.
SAMN41267471
Unable to find collection date.
SAMN41267470
Unable to find collection date.
SAMN41267469
Unable to find collection date.
SAMN41267468
Unable to find collection date.
SAMN41267467
Unable to find collection date.
SAMN41267466
Unable to find collection date.
SAMN41267465
Unable to find collection date.
SAMN41267464
Unable to find collection date.
SAMN41267463
Unable to find collection date.
SAMN41267462
Unable to find collection date.
SAMN41267482
Unable to find collection date.
SAMN41267461
Unable to find collection date.
SAMN41267460
Unable to find collection date.
SAMN41267459
Unable to find collection date.
SAMN41267458
Unable to find collection date.
SAMN41267457
SAMN41267456
Unable to find collection date.
SAMN41267455
SAMN41267454
SAMN41267453
SAMN41267452
SAMN41267487
SAMN41267451
SAMN41267450
SAMN41267449
SAMN41267448
SAMN41267447
SAMN41267446
SAMN41267445
Unable to find collection date.
SAMN41267444
Unable to find collection date.
SAMN41267443
Unable to find collection date.
SAMN41267442
Unable to find collection date.
SAMN41267481
Unable to find collection date.
SAMN41267441
Unable to find collection date.
SAMN41267494
Unable to find collection date.
SAMN41267493
Unable to find collection date.
SAMN41267491
Unable to find collection date.
SAMN41267490
Unable to find collection date.
SAMN41267489
SAMN41267478
SAMN41267477
SAMN41267479
Unable to find collection date.
SAMN41267480
SAMN41267488
Unable to find collection date.
SAMN41189790
Unable to find collection date.
SAMN41189789
Unable to find collection date.
SAMN41189796
Unable to find collection date.
SAMN41189779
Unable to find collection date.
SAMN41189778
Unable to find collection date.
SAMN41189777
Unable to find collection date.
SAMN41189776
Unable to find collection date.
SAMN41189742
Unable to find collection date.
SAMN41189775
Unable to find collection date.
SAMN41189774
Unable to find collection date.
SAMN41189773
Unable to find collection date.
SAMN41189772
Unable to find collection date.
SAMN41189771
Unable to find collection date.
SAMN41189770
Unable to find collection date.
SAMN41189768
Unable to find collection date.
SAMN41189767
Unable to find collection date.
SAMN41189766
Unable to find collection date.
SAMN41189765
Unable to find collection date.
SAMN41189741
Unable to find collection date.
SAMN41189764
Unable to find collection date.
SAMN41189763
Unable to find collection date.
SAMN41189762
Unable to find collection date.
SAMN41189738
Unable to find collection date.
SAMN41189737
Unable to find collection date.
SAMN41189736
Unable to find collection date.
SAMN41189735
Unable to find collection date.
SAMN41189788
Unable to find collection date.
SAMN41189787
SAMN41189786
Unable to find collection date.
SAMN41189740
Unable to find collection date.
SAMN41189785
Unable to find collection date.
SAMN41189784
Unable to find collection date.
SAMN41189745
Unable to find collection date.
SAMN41189807
Unable to find collection date.
SAMN41189806
Unable to find collection date.
SAMN41189744
Unable to find collection date.
SAMN41189805
SAMN41189804
SAMN41189803
SAMN41189802
SAMN41189801
Unable to find collection date.
SAMN41189800
Unable to find collection date.
SAMN41189798
Unable to find collection date.
SAMN41189797
Unable to find collection date.
SAMN41189793
Unable to find collection date.
SAMN41189743
Unable to find collection date.
SAMN41189794
Unable to find collection date.
SAMN41189792
Unable to find collection date.
SAMN41189791
Unable to find collection date.
SAMN41189783
Unable to find collection date.
SAMN41189782
Unable to find collection date.
SAMN41189781
Unable to find collection date.
SAMN41189734
SAMN41189733
Unable to find collection date.
SAMN41189732
Unable to find collection date.
SAMN41189731
Unable to find collection date.
SAMN41189730
Unable to find collection date.
SAMN41189739
Unable to find collection date.
SAMN41189729
Unable to find collection date.
SAMN41189728
Unable to find collection date.
SAMN41189727
Unable to find collection date.
SAMN41189726
Unable to find collection date.
SAMN41189780
Unable to find collection date.
SAMN41189769
Unable to find collection date.
SAMN41189759
Unable to find collection date.
SAMN41189758
Unable to find collection date.
SAMN41189757
Unable to find collection date.
SAMN41189756
Unable to find collection date.
SAMN41189760
Unable to find collection date.
SAMN41189755
Unable to find collection date.
SAMN41189754
Unable to find collection date.
SAMN41189753
Unable to find collection date.
SAMN41189752
Unable to find collection date.
SAMN41189751
Unable to find collection date.
SAMN41189750
SAMN41189749
Unable to find collection date.
SAMN41189748
Unable to find collection date.
SAMN41189747
Unable to find collection date.
SAMN41189746
Unable to find collection date.
SAMN41189761
Unable to find collection date.
SAMN41189795
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
nan
Unable to find collection date.
SAMN41489086
Unable to find collection date.
SAMN41489085
Unable to find collection date.
SAMN41489084
Unable to find collection date.
SAMN41489083
Unable to find collection date.
SAMN41489082
Unable to find collection date.
SAMN41489081
Unable to find collection date.
SAMN41489080
Unable to find collection date.
SAMN41489079
Unable to find collection date.
SAMN41489095
Unable to find collection date.
SAMN41489094
Unable to find collection date.
SAMN41489093
Unable to find collection date.
SAMN41489092
Unable to find collection date.
SAMN41489091
Unable to find collection date.
SAMN41489090
Unable to find collection date.
SAMN41489089
Unable to find collection date.
SAMN41489088
Unable to find collection date.
SAMN41489087
Unable to find collection date.
SAMN41489078
Unable to find collection date.
SAMN41489077
Unable to find collection date.
SAMN41656648
Unable to find collection date.
SAMN41656647
SAMN41656646
SAMN41656645
Unable to find collection date.
SAMN41656644
SAMN41656684
SAMN41656683
SAMN41656682
SAMN41656681
Unable to find collection date.
SAMN41656680
Unable to find collection date.
SAMN41656679
Unable to find collection date.
SAMN41656678
SAMN41656677
Unable to find collection date.
SAMN41656676
SAMN41656675
Unable to find collection date.
SAMN41656674
SAMN41656673
Unable to find collection date.
SAMN41656672
SAMN41656671
Unable to find collection date.
SAMN41656670
SAMN41656669
Unable to find collection date.
SAMN41656668
SAMN41656667
SAMN41656666
SAMN41656665
Unable to find collection date.
SAMN41656664
Unable to find collection date.
SAMN41656663
Unable to find collection date.
SAMN41656662
Unable to find collection date.
SAMN41656661
Unable to find collection date.
SAMN41656660
Unable to find collection date.
SAMN41656659
Unable to find collection date.
SAMN41656658
Unable to find collection date.
SAMN41656657
Unable to find collection date.
SAMN41656656
Unable to find collection date.
SAMN41656655
Unable to find collection date.
SAMN41656654
Unable to find collection date.
SAMN41656653
Unable to find collection date.
SAMN41656652
Unable to find collection date.
SAMN41656651
Unable to find collection date.
SAMN41656650
Unable to find collection date.
SAMN41656649
Unable to find collection date.
SAMN41656639
Unable to find collection date.
SAMN41805887
Unable to find collection date.
SAMN41805886
Unable to find collection date.
SAMN41805885
Unable to find collection date.
SAMN41805884
Unable to find collection date.
SAMN41805883
Unable to find collection date.
SAMN41805882
Unable to find collection date.
SAMN41805881
Unable to find collection date.
SAMN41805880
Unable to find collection date.
SAMN41805798
SAMN41805879
Unable to find collection date.
SAMN41805878
Unable to find collection date.
SAMN41805877
Unable to find collection date.
SAMN41805876
Unable to find collection date.
SAMN41805875
Unable to find collection date.
SAMN41805874
SAMN41805873
SAMN41805872
Unable to find collection date.
SAMN41805871
Unable to find collection date.
SAMN41805870
Unable to find collection date.
SAMN41805797
Unable to find collection date.
SAMN41805869
Unable to find collection date.
SAMN41805868
Unable to find collection date.
SAMN41805867
Unable to find collection date.
SAMN41805866
Unable to find collection date.
SAMN41805865
Unable to find collection date.
SAMN41805864
Unable to find collection date.
SAMN41805863
Unable to find collection date.
SAMN41805862
SAMN41805861
SAMN41805860
SAMN41805796
SAMN41805859
Unable to find collection date.
SAMN41805858
Unable to find collection date.
SAMN41805857
Unable to find collection date.
SAMN41805856
Unable to find collection date.
SAMN41805855
Unable to find collection date.
SAMN41805854
Unable to find collection date.
SAMN41805853
Unable to find collection date.
SAMN41805852

In [ ]:
# Make names

# names = ">A/" + metadata_new["Host"] + "/" + metadata_new["geo_loc_name"] + "/" + metadata_new["isolate"] + "/" + years + "|H5N1|" + metadata_new["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata_new["Host_Type"] + "|" + metadata_new["Genotype"]
names = ">A/" + metadata_genbank["Host"] + "/" + metadata_genbank["name_state"] + "/" + metadata_genbank["isolate"] + "/" + metadata_genbank["years"] + "|H5N1|" + metadata_genbank["Collection_Date_Specific"] + "|" + metadata_genbank["Host_Type"] + "|" + metadata_genbank["Genotype"]

metadata_genbank["Name"] = names

display(metadata_genbank)

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,Genotype,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state,Name
0,SRR28752470,WGS,147.45,81957492,PRJNA1102327,SAMN41019216,Viral,26941955,USDA-NVSL,2024,...,B3.13,SRR28752471_HA_cns.fa,Consensus_SRR28752471_HA_cns_threshold_0.5_qua...,SRR28752471,HA,PQ011563.1,4,A/Cattle/Michigan/24-009027-002-v/2024,Michigan,>A/Cattle/Michigan/24-009027-002-v/2024|H5N1|2...
1,SRR28752470,WGS,147.45,81957492,PRJNA1102327,SAMN41019216,Viral,26941955,USDA-NVSL,2024,...,B3.13,SRR28752471_MP_cns.fa,Consensus_SRR28752471_MP_cns_threshold_0.5_qua...,SRR28752471,MP,PQ011566.1,7,A/Cattle/Michigan/24-009027-002-v/2024,Michigan,>A/Cattle/Michigan/24-009027-002-v/2024|H5N1|2...
2,SRR28752470,WGS,147.45,81957492,PRJNA1102327,SAMN41019216,Viral,26941955,USDA-NVSL,2024,...,B3.13,SRR28752471_NA_cns.fa,Consensus_SRR28752471_NA_cns_threshold_0.5_qua...,SRR28752471,NaN,PQ011565.1,6,A/Cattle/Michigan/24-009027-002-v/2024,Michigan,>A/Cattle/Michigan/24-009027-002-v/2024|H5N1|2...
3,SRR28752470,WGS,147.45,81957492,PRJNA1102327,SAMN41019216,Viral,26941955,USDA-NVSL,2024,...,B3.13,SRR28752471_NP_cns.fa,Consensus_SRR28752471_NP_cns_threshold_0.5_qua...,SRR28752471,NP,PQ011564.1,5,A/Cattle/Michigan/24-009027-002-v/2024,Michigan,>A/Cattle/Michigan/24-009027-002-v/2024|H5N1|2...
4,SRR28752470,WGS,147.45,81957492,PRJNA1102327,SAMN41019216,Viral,26941955,USDA-NVSL,2024,...,B3.13,SRR28752471_NS_cns.fa,Consensus_SRR28752471_NS_cns_threshold_0.5_qua...,SRR28752471,NS,PQ011567.1,8,A/Cattle/Michigan/24-009027-002-v/2024,Michigan,>A/Cattle/Michigan/24-009027-002-v/2024|H5N1|2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4451,SRR31167894,WGS,147.42,65957232,PRJNA980729,SAMN44493025,Viral,20955917,USDA-NVSL,2024,...,D1.1,SRR31167894_NP_cns.fa,Consensus_SRR31167894_NP_cns_threshold_0.5_qua...,SRR31167894,NP,PQ664442.1,5,A/chicken/WA/24-030039-001/2024,WA,>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024|avi...
4452,SRR31167894,WGS,147.42,65957232,PRJNA980729,SAMN44493025,Viral,20955917,USDA-NVSL,2024,...,D1.1,SRR31167894_NS_cns.fa,Consensus_SRR31167894_NS_cns_threshold_0.5_qua...,SRR31167894,NS,PQ664445.1,8,A/chicken/WA/24-030039-001/2024,WA,>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024|avi...
4453,SRR31167894,WGS,147.42,65957232,PRJNA980729,SAMN44493025,Viral,20955917,USDA-NVSL,2024,...,D1.1,SRR31167894_PA_cns.fa,Consensus_SRR31167894_PA_cns_threshold_0.5_qua...,SRR31167894,PA,PQ664440.1,3,A/chicken/WA/24-030039-001/2024,WA,>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024|avi...
4454,SRR31167894,WGS,147.42,65957232,PRJNA980729,SAMN44493025,Viral,20955917,USDA-NVSL,2024,...,D1.1,SRR31167894_PB1_cns.fa,Consensus_SRR31167894_PB1_cns_threshold_0.5_qu...,SRR31167894,PB1,PQ664439.1,2,A/chicken/WA/24-030039-001/2024,WA,>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024|avi...
4455,SRR31167894,WGS,147.42,65957232,PRJNA980729,SAMN44493025,Viral,20955917,USDA-NVSL,2024,...,D1.1,SRR31167894_PB2_cns.fa,Consensus_SRR31167894_PB2_cns_threshold_0.5_qu...,SRR31167894,PB2,PQ664438.1,1,A/chicken/WA/24-030039-001/2024,WA,>A/CHICKEN/WA/24-030039-001/2024|H5N1|2024|avi...

In [ ]:
# Make fasta files

fasta_folder = downloads + "avian-influenza/fasta/"

os.chdir(fasta_folder)

pairs = []
fasta_files = {}

for genotype in ["B3.13", "D1.1"]:
    for segment in ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = []

for run in metadata_genbank["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            fasta_files[pair].append(header)
                            fasta_files[pair].append(sequence)
                f.close()

In [ ]:
# print(fasta_files[list(fasta_files.keys())[0]])

print(len(fasta_files["B3.13_PB1"]))

8880

In [ ]:
# Create fasta files 
os.chdir(complete_files)
for pair in fasta_files.keys():
    output_path = complete_files + pair + ".fasta" 

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        item = fasta_files[pair]
        name = str(item[0])
        # print(item[1])
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

In [ ]:
# def search_collection_date(biosample):
    
#     base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
#     search_url = base_url + "esearch.fcgi?db=biosample&term=" + biosample +"&usehistory=y&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

#     # Get Biosample ID from search_url
#     output = requests.get(search_url)
#     xml = output.content
#     root = ET.fromstring(xml)
#     sample_id = root.find("./IdList/Id").text

#     biosample_url = base_url + "elink.fcgi?dbfrom=biosample&db=nuccore&id=" + sample_id + "&cmd=neighbor_history&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"
    
#     # Get Nucleotide ID from biosample_url
#     output = requests.get(biosample_url)
#     xml = output.content
#     root = ET.fromstring(xml)
#     query_key = root.find(".//QueryKey").text
#     web_env = root.find(".//WebEnv").text

#     nucleotide_url = base_url + "esummary.fcgi?db=nuccore&query_key=" + query_key + "&WebEnv=" + web_env + "&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

#     output = requests.get(nucleotide_url) 
#     xml = output.content
#     root = ET.fromstring(xml)

#     # Grab collection date at the end of the sub name
#     collection_date = root.find(".//SubName").text.split("|")[-1]

#     # Avoid spamming the server
#     time.sleep(3)
    
#     return collection_date

In [ ]:
# example = search_collection_date("SAMN41019216")
# print(example)

24-Mar-2024

In [ ]:

# unique_animals_all = sort_animals_anderson(metadata_new)

# # Flatten unique_animals
# every_unique_animal = []
# for animal in unique_animals_all:
#     every_unique_animal.append(animal)

# print(every_unique_animal)

# unique_animals_set = list(set(every_unique_animal))
# # animals_df = pd.DataFrame(columns=["avian", "cattle", "feline", "other_mammal", "human", "other"])
# # animals_df["other"] = unique_animals_set # to sort

# os.chdir(downloads)

# animals_ref = pd.read_csv("animals_ref.csv")


# # If animal not in ref1, put in ref2

# common_animals = []
# # Check if animals in unique_animals_set are in ref1
# for animal in unique_animals_set:
#     for col in animals_ref.columns:
#         if animal in animals_ref[col].values and type(animal) == str:
#             common_animals.append(animal)

# print(common_animals)
# print(len(common_animals))

# different_animals = []
# for animal in unique_animals_set:
#     if animal not in common_animals:
#         different_animals.append(animal)

# print(different_animals)

# # Add to dataframe
# animals_df = animals_ref
# # Make different_animals same length as dataframe, if shorter
# if len(different_animals) < len(animals_df):
#     number_of_times_to_add_nan = len(animals_df) - len(different_animals)
#     for i in range(number_of_times_to_add_nan):
#         different_animals.append(float('nan'))
# # If longer, deal with that later

# animals_df["new"] = (different_animals)

# print(animals_df)

# animals_df.to_csv("animals_ref_to_sort.csv")