# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI, by de-duplicating from Andersen/GISAID, and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [2]:
# Paths

home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = home + "NCBI_Virus_Downloads/11-01-2021--04-14-2025/"
complete_files = home + "NCBI_Virus_Complete_Files/"
gisaid_andersen = home + "Complete_Combined_Files/11-01-2021--04-14-2025_all_genotypes/11-01-2021--04-14-2025_all_genotypes/"

# Day we're updating data
update_date = "04-14-2025"

os.chdir(downloads)

## De-Duplication

In [3]:
metadata = pd.read_csv("sequences.csv")

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.SRA_Accession, as_index=False).size()

print(metadata_counts)

metadata_counted = metadata.merge(metadata_counts, on="SRA_Accession")

# Only keep those with size=8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates

metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="first") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]

metadata_segments

     SRA_Accession  size
0      SRR23852495     8
1      SRR28752446     8
2      SRR28752447     8
3      SRR28752448     8
4      SRR28752449     8
...            ...   ...
4141   SRR33124773     8
4142   SRR33124774     8
4143   SRR33124775     8
4144   SRR33124776     8
4145   SRR33124777     8

[4146 rows x 2 columns]

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV571926,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,1,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
1,PV571927,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,2,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
2,PV571928,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,3,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
3,PV571929,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,4,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
4,PV571930,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,5,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37035,OQ565628,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,4,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37036,OQ565629,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,5,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37037,OQ565630,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,6,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37038,OQ565631,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,7,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37039,OQ565632,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,8,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8

In [4]:
# De-duplicate from Andersen/GISAID using isolate

# If even one isolate in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
gisaid_andersen_isolates = []
# Grab files
for dirpath, dirs, files in os.walk(gisaid_andersen):
    for file in files:
        file_name = os.path.join(dirpath, file)
        # print(file_name)
        if ".fasta" in file_name:
            fasta_file = fasta_df(file_name) # Convert fasta file to dataframe
            isolates = fasta_file["Isolate_Id"].apply(lambda x: x.split("/")[3])
            for index, value in isolates.items():
                gisaid_andersen_isolates.append(value)
         
    break 

gisaid_andersen_isolates = list(set(gisaid_andersen_isolates))

print(gisaid_andersen_isolates)

['24_032631-001', '22-024217-004', '031310-001', '22-013084-001', '004339-007', 'FAV-1223-3', '22-031183-001-R', '037984-001', '004415-016', '22-013395-011', 'W23-119', '22-028824-005-R', '24_033988-004', '22-011789-002', 'USDA-008176-005', 'FAV-1149-8', 'USGS-0760', '22-024181-003', '22-011775-001', '24_032027-004', '031326-001', '24_033003-002', '25_004920-001', '24_009027-001', '007185-004-R', '22-035394-002', '003936-004', '037188-001', 'FAV-0891-2', '033249-001', '029618-002', '007118-030', '006660-002', '006661-004', '24_016252-005', 'FAV-0505-47', 'FAV-0329-1', 'FAV-0118-3', 'CEIRR-4050', 'FAV-0083-126', '22-009412-002', '006144-041', '24_017652-010', '22-040230-002', '003803-005', 'FAV-0133-2', '24-004334-016-original', '004290-003', 'USDA-010806-001', '24-008552-015', '24_031627-002', '24-020282-002', '23-037463-001', '22-013276-001', 'FAV-1194-1', '23-004228-001', '24_033687-001', '003778-001', '24_015973-021', '23-032795-043', '038353-001', '000308-001', '23-022512-007-original', '22-029332-006', 'FAV-0053-35', 'USDA-010085-003', '005754-001', 'FAV-0053-36', '22-035144-001', '22-027922-003', '22-008242-001', '22-014526-001', '23-001474-001', '035979-009', '23-038546-001-original', '036123-004', 'USDA-002768-003', '23-004612-008', 'FAV-0236-16', '23-003815-001', '22-035569-001', '067041-24-5', '007549-024', '24_014336-002', '23-007186-001-original', '22-033403-003-R', 'FAV-0003-02', '24_017152-021', 'FAV-0835-13', '22-011671-001', 'FAV-0348-OS', '23-031491-001', 'USDA-003417-039', '25_005209-001', '23-038112-112-original', '22-037656-001', 'USDA-007919-004', '008872-002', 'USDA-009481-019', '035991-001', '038439-001', '036369-002', '021768-002', '003855-001', 'FAV-0976-4', '038617-001', '008493-001', 'USDA-005110-001', '036640-003', '001892-001', '014126-010', '006328-001', 'USDA-009207-012', '24_033001-002', 'FAV-0473-5', 'FAV-1619-1', '037232-001', 'W24-248A', '028504-001', 'USDA-009361-006', '033506-002', '23-038979-025-original', 'AIVPHL-2638', 'FAV-0802-10', 'FAV-0061-1', 'FAV-0985-1', '24_034643-001-R', 'UGAI22-3190', '23-013078-022', 'FAV-1676-2', '003036-002', '23-032411-001', '004236-004', '23-012114-001', 'FAV-1277-1', '22-035144-003', 'W241290019-18-P', 'FAV-0134-2', '24_011573-008', '22-015408-001', '034204-001', '24-027086-003', '036391-001', '23-002690-001', '22-033350-004', 'AIVPHL-1400', '026566-001', '22-014031-001', 'AIVPHL-14', '22-031912-001', 'AIVPHL-176', 'FAV-0802-41', '037177-002', 'FAV-0448-2', 'USDA-007946-001', '005784-001', 'FAV-0149-2', '24_031280-003', '22-022010-003-original', 'FAV-1347-3', '001426-001', '22-018402-001', '002697-001', '22-017865-004-original', 'USDA-012056-001', 'AIVPHL-139', 'FAV-0390-1', 'FAV-1166-5', 'FAV-0438-3', '007609-004', 'FAV-0257-1', 'USDA-010036-002', '23-033982-003', 'FAV-0402-9', '24_009110-010', '002740-001', '037202-002', '23-033638-002', '006274-001', '038444-009', '007549-121', '007709-003', '23-034854-001', '24-020796-008', 'USDA-003935-024', '022861-001', 'FAV-0064-1', '22-026942-001', 'FAV-0918-34', '22-038970-002', 'FAV-0146-4', 'MME-117-ns', '002050-001', 'USDA-010136-002', 'FAV-0739-1', '23-035700-001-original', 'AIVPHL-2866', '24_017584-014', '24-034635-001', 'USDA-013181-001', '026219-005', '002423-001', '033840-002', '22-023551-001', '22-025499-001', 'FAV-0567-1', '24-004128-001-original', '22-014175-003', '22-041262-001', '014126-025', '002290-001', 'FAV-0438-02', '24_018271-001', 'FAV-1294-4', 'FAV-0124-1', '24_020797-008', '038656-007', 'W22-749B', 'W24-190F', '24_027475-001-R2', '22-016599-004', '038338-002', 'FAV-0573-1', 'FAV-1543-1', 'FAV-1642-1', 'FAV-1092-1', 'W24-1066', '003807-020', '22-025683-001', 'USDA-010979-009', 'USDA-012026-001', '24_009367-018', '009387-001', '003471-001', '23-038797-002-original', '22-029929-002', 'FAV-0525-3', '036311-001', '008003-001', 'BI-ME-023', 'FAV-1611-2', 'FAV-0381-2', '24_012346-005', '22-015271-002', '22-018176-005', '032191-002', '24_034005-001', '22-033680-002', 'FAV-0524-2', 'IZ22_0270', '036567-004', '22-038205-001', '22-014327-002', '24_016687-002', '22-011140-001', '007549-029', 'FAV-0505-32', '22-024929-005', '23-002693-003', '002402-001', '23-033638-010', '24_014882-003', '038658-002', '007119-012', 'FAV-1652-5', '036162-003', '036542-005', '24_020797-005', '23-025001-003', 'FAV-0210', '22-014701-001', '24-027086-002', 'IZ22_0894', 'FAV-1628-19', 'USDA-012022-002', 'FAV-0855-9', 'FAV-0386-1', 'AIVPHL-342', '033249-003', '22-016602-002', 'FAV-0728-2', 'W24-248D', '006282-001', '036536-002', '002736-001', '23-029035-007', '007549-006', 'USDA-009477-001', '004707-001', '007640-001', '038625-001', '24-031862-002', '24_017152-010', '031862-010', '22-025071-001', '24_010661-014', '59_RML', '004430-002', '22-024499-001', 'FAV-0201-1', '014126-053', '22-042131-001', '007470-003', 'FAV-0544-P1', '24_009110-004', '23-001466-001', '002047-006', 'USDA-011517-008', '22-031242-005-R', 'CEIRR-297', '23-038496-001', '22-017953-001', '037569-001', 'AIVPHL-30', '24-004649-001-original', '22-013392-001', '003824-003', 'USDA-010771-005', 'FAV-1679-7', '22-017872-002-original', '22-033430-002', '24_034694-003', '23-032795-007', '007549-071', 'FAV-0575-16', 'W24-007E', '003299-004', '014126-043', '24-016313-001', '24-012236-001-original', '24-037490-002', 'USDA-008376-001', 'USDA-001330-029', '031145-001', 'FAV-0437-2', '22-013395-008', '22-036551-002', '017048-005', '23-034421-008-original', 'FAV-0395-1', '036562-001', '22-014183-004', '22-013424-001', '24_034009-004', '22-033925-001', '23-030280-002-original', '031284-006', '23-036683-012-original', '003747-001', '22-033477-001', '036566-001', '001879-001', 'FAV-0829-2', '012377-002', '24-005369-002-original', '24_032021-005', '22-009983-007', '007119-016', '002456-001', '005800-002', '006508-010-R', '004499-001', '22-029379-002', '22-015563-001', '22-011338-001', '22-018538-001', '23-003641-008', '22-029901-002-R', 'FAV-0032-2', '22-009287-002', '002402-008', '24_033001-003', '007489-001', '036766-003', '22-041830-001', '23-007190-001', '24-010948-001', 'FAV-1628-28', '063200-24-5', '22-038652-002', '24-035675-003', '22-038970-004', '22-011334-002', '038977-002', '23-032269-017-original', '009496-001', '24_034007-004', 'FAV-1682-1', '009235-001', '015307-003', '25_000593-001', '22-015068-005', '22-013941-002', '23-000764-001', '23-035084-0032', 'FAV-0146-1', '24_015195-001', 'USDA-009805-004', '005993-001', '008067-005', '24_021716-005', '158', '24_018030-002', '22-010923-004', '22-008373-002', '24-005371-001-original', '22-027791-006', 'FAV-0896-1', '24_017484-005', '24_011573-017', '22-029889-003-R', 'AIVPHL-85', '035992-001', '24_025746-001', '23-038132-001', '22-017360-002', '22-019716-001', '23-039991-002-original', '25_004920-005', '23-005533-030', 'AIVPHL-270', '004292-002', '24_018030-001', '038266-002', '23-009211-001', '033495-001', '24_009310-007', '037225-044', '006251-004', 'USDA-011586-004', 'USDA-007696-009', '24_034691-001', '22-027995-006', '23-034360-007-original', '22-013222-004', 'FAV-1166-9', '24_033016-001', '22-038592-004', '22-029100-001', 'USDA-001673-001', '24-000133-004-original', '22-018174-001', '24_034148-001', '23-004611-001', '23-034940-001-original', '24-019884-002', 'USDA-010036-004', 'FAV-0575-45', '24-002738-002-original', 'FAV-1131-1', '23-023002-001-original', '038987-003', 'FAV-1530', '23-035040-001', '24_025992-002', '22-031728-004-R', '004219-004', '24_011573-021', '005793-001', 'USDA-010995-006', '24_034019-002', '003245-001', '008597-002', 'W22-719A', '22-010994-001', '22-019255-001', '24_025992-003', '035999-001', 'FAV-0950-8', 'FAV-0802-78', '22-018423-004', '23-014010-001', '22-036105-005', 'USDA-012541-001', '23-034346-006', '23-005535-001', '22-012932-002', '23-034050-002', 'USDA-012936-009', '004840-002', '22-037698-001', '001170-002', 'FAV-0597-1', '037050-001', '021589-001', '24-020796-003', 'FAV-0575-27', '037043-006', '23-013242-001', '006142-009', '22-030784-001', '22-017264-002', '22-015312-001-R', '23-025003-001', 'FAV-1444-2', '005918-001', '24_009497-006', '22-041037-003', '22-021013-004', '22-012392-001', '22-010015-001', '006145-001', '007549-009', '007118-009', 'USDA-013105-001', '23-003283-001', '006709-001', '23-001516-001', 'FAV-1470-11', '007119-009', '22-014533-002', '22-013224-001', '22-038501-001', '24-017676-002', '22-030423-014-R', '028518-001', '013021-002', '23-036896-002', '22-027083-005', '22-016645-003-original', '22-024356-001', 'NYCVH-22-8477', '004631-004-R', '22-039758-001-3', '22-024975-002', 'USDA-009742-001', 'FAV-0268-8', '24_009110-009', '24_016523-001', '23-034174-002', '23-013078-031', '23-038112-097-original', 'USDA-010923-006', '24-008354-001', '22-017769-001', '22-016973-001', 'FAV-1166-16', '038428-003', '003975-001', '24-035690-002', '24_017154-006', 'FAV-0446-2', '005938-002', '22-010845-003', '22-010445-001', '007154-007', '009028-001', '23-011582-001', 'FAV-0497-2', '22-010713-003', '004497-001', 'FAV-0802-2', '24-037436-002', 'FAV-0385-4', '24_034221-004', 'FAV-0802-32', '007151-003', '003579-004', '23-034643-006-original', '22-016599-001', '23-022051-010-original', 'FAV-0802-75', '24_032035-001', 'FAV-0918-8', '22-021192-001', '002315-001', '23-000324-002', 'USDA-010663-004', '004539-001', '23-004672-001', '22-033697-001', 'FAV-0893-1', '22-029049-001', '031666-015', '026563-002', '24-000770-001-original', '24_016337-001', 'W22-773', '22-014431-005', '22-009976-003', '006539-001', 'FAV-0434-2', '004839-001', 'FAV-0068-6', '007608-008', '24_033004-003', '22-008951-005', '007608-009', '23-035544-002', 'FAV-0576-1', '22-010464-001', 'AIVPHL-2558', 'USDA-009053-001', '004397-004', 'FAV-0076-5', '009376-002', '24_024710-009', 'FAV-0464-1', '22-029194-001', 'USDA-006742-003', '24_018772-009', 'USDA-003150-010', '22-013438-001', '24_016437-022', '24_031305-003', 'FAV-0505-08', '007626-002', '007450-001', '006143-017', '23-000185-001', '24_009109-005', 'FAV-0802-73', '23-033668-001', '23-013078-032', '005928-006', '035979-008', '004840-003', 'FAV-0660-3', 'AIVPHL-25', 'FAV-0433-1', '013021-004', '22-035763-001', '24-037489-002', '24-037156-002', 'FAV-0364-1', '23-040000-002-original', 'FAV-0948-5', '007609-006', '037237-001', '006537-001-R2', '23-034483-001-original', '24_019886-004', '22-014361-001', 'FAV-1679-2', '23-033317-001-original2', '22-030915-003', '23-034424-002-original', 'FAV-0425-2', '002205-001', '24_033011-003', '010285-002', '22-020388-001', '22-034097-002', '22-018406-002', '24_017898-002', '009181-001', '24_009109-003', '22-013421-001', '006814-001', '23-037849-010', 'FAV-0987-2', '22-017243-013', '22-033479-020', '22MM00822', '22-035070-002', '23-005398-004', '22-014524-001', '24_009775-001', '23-001343-007', '009986-003', '038335-003', '22-012784-001', '003270-001', 'FAV-1204-1', '004865-002', '032424-006', 'FAV-1053-1', '037219-029', '22-041882-001', '009291-001', '24_033990-004', '22-034128-001-R', '24_009496-002', '23-010018-001', 'USDA-010924-001', 'USDA-012327-003', 'AIVPHL-127', '22-029924-007-R', '24-035157-001', '24_016288-007', '22-026962-083', '22-038564-002', '22-024871-012', '22-035838-002', '23-013080-008', '037225-040', '24_009110-015', '038979-001', '010058-001', '22-014481-002', 'FAV-0506-2', 'FAV-0743-1', '23-039759-001-original', '001388-002', '004415-014', '007118-046', '24_010354-004-300', '036567-003', 'USDA-011035-005', '24_020712-008', '23-000776-001', '006508-008-R', '036371-003', '007305-001', '24_014883-003', '22-030637-001', 'USDA-009057-001', '24_009110-022', 'FAV-1537-2', 'FAV-0860-6', '23-002623-001', 'FAV-0833-56', '22-015654-001', '23-038249-002', 'FAV-0661-3', 'USDA-007679-010', '22-014360-001', '24-004330-005-original', '032635-001', '004415-013', '22-009980-002', 'FAV-1258-2', '030170-001', 'FAV-0833-51', '007549-019', '22-038821-028', '23-005638-001', 'AIVPHL-2585', 'FAV-1366-5', '24-010303-002', 'USDA-010663-009', '033434-019', '035990-001', '007637-002', '004295-004', 'USDA-007764-001', '24_020284-010', '007549-087', '007607-009', '005928-004', 'USDA-007630-001', '22-009849-001', '005481-002', '002143-001', '23-035010-002-original', '004323-001', 'FAV-0005-1', '032641-001', '22-013267-001', '003579-001', '23-030959-002', '22-024871-013', '24_031165-008', '007476-001', '22-012855-003', 'IZ22_0821', '037410-010', '22-041853-002', '034223-003', '22-014522-001', '032620-001', 'FAV-0505-48', '029374-003', '008364-001', '22-014874-006', '23-002693-024', '23-027066-002', '24-012046-004', 'FAV-0938-1', '003240-004', 'FAV-0642-1', '22-036753-074', 'FAV-0899-3', '22-008114-001', 'USDA-009668-001', '22-013643-001', 'USDA-013145-001', '23-035656-001', '037225-009', '099488', '23-034211-002', '033876-004', '22-011826-002', '007609-008', '22-019846-002', '000084-002', '25-000082-001', '22-006261-001', 'USDA-011188-001', 'FAV-0575-52', 'FAV-0425-1', '22-024871-014', '003389-001', 'FAV-1655-1', 'FAV-0299-3', '028305-002', '22-017361-002', '033989-002', '24-037518-002', '24_014510-003', '24-019523-001', '23-032991-003', 'IZ22_0763', 'FAV-0736-1', '22-008704-001', '002426-001', 'FAV-0281-8', 'FAV-0168-4', '23-007337-002-original', '22-028905-002', '23-008358-001-original', '24_022855-001', '22-024351-001', '005885-001', 'USDA-012338-005', '037168-007', 'USDA-013006-001', '23-032683-002', '24-012234-002', '004003-002', '007921-009', 'FAV-0079-4', '22-027997-001', '22-038820-006-R', '22-016938-001', 'FAV-0303-7', '22-027793-001', '007939-008', '24_016134-071', '24_016134-080', '22-031242-001', '22-017940-008', '22-014967-001', '003574-003', '23-005533-006', 'FAV-0575-36', '038623-002', '23-038532-002', 'FAV-0670-3', '006656-015', '24_031165-011', 'FAV-0104-3', 'USDA-009376-003', '001662-001', '22-008176-003', 'FAV-0834-1', '035870-003', 'AIVPHL-2656', '23-037497-003-original', '004426-001', '23-001041-002', '22-034331-001-R', '004652-002', '23-001007-001', '22-039984-003', '22-014034-002', '24_033015-003', '25_003262-001', '23-005879-001', 'USDA-011578-005', 'FAV-1513-9', 'USDA-010679-001', '23-002238-004', 'FAV-0429-2', 'USDA-012633-002', 'FAV-1628-29', 'FAV-0232-1', '24-003120-014-original', '22-039970-001', 'USDA-008506-007', '24_026564-001', '22-013663-006', 'FAV-0978-2', '002788-004', 'W22-199F', 'USDA-012665-001', '035007-002', '004290-007', '23-000335-001', 'AIVPHL-2662', '24_010193-007', '22-013433-001', 'FAV-1689-2', '036536-001', '22-032451-005-R', 'FAV-1278-1', 'AIVPHL-776', 'CEIRR-291', '005864-001', '24-036599-002', '22-026137-045', '22-012977-001', '006506-003-R', '033976-003', '003829-003', '22-035580-001', '24-035521-001', '23-040664-002-original', '22-009286-001', '24-004235-001', 'FAV-0378-2', '24-037983-002', '24_014545-006', '062222-24-1-3', '004632-001', 'UGAI22-3620', '24_009110-026', '062222-24-1-4', '003584-001', 'AIVPHL-1550', '22-020416-010', 'FAV-1166-12', '22-041037-002', 'FAV-0363-4', 'FAV-1053-2', '22-033000-001', '007471-001', '22-032043-001', 'USDA-001743-004', 'CEIRR-282', '22-022528-008', '036593-002', '003227-001', '24_014336-012', 'FAV-1541-2', 'USDA-007376-003', 'AIVPHL-2870', '038995-002', '22-033036-002', '037573-003', 'FAV-0089-1', 'FAV-1027-1', '22-032799-001', '23-034934-001', '23-037959-002', '23-011964-001', 'USDA-012025-001', 'OH22-21172-1', '23-003062-010', 'W22-1226', '25_004923-001', '24-027086-004', '007813-009', '027805-002', '24-020796-007', '002898-006', '003044-002', '23-002626-001', '028770-001', 'USDA-009404-001', 'USDA-011563-002', '037822-002', '24_018873-002', '037225-003', '24-004330-035-original', 'USDA-006578-014', '22-016942-001', '23-036804-011-original', '037045-002', '22-015937-001', '003860-001', '22-022940-003', 'FAV-0388-1', '24-035703-001', '23-006644-003', '22-006792-002', '007609-009', 'FAV-0994-8', '003582-001', 'FAV-0334-1', 'FAV-1633-1', '002921-003', 'FAV-0838-5', '006143-012', '006202-007', '23-002762-002', '037225-054', 'FAV-1126-1', '22-025285-002', 'FAV-0378-3', '22-034260-001', '009173-001', '003670-005', '22-016119-003', 'FAV-0802-80', '23-002236-003', '006223-001', 'AIVPHL-131', '22-014874-001', '22-030338-001', '22-025066-001', '033428-001', '005174-002', '007549-124', '24-013710-004', '009472-002', 'AIVPHL-2528', '23-032221-011-original2', '002440-004', '006648-001', 'CENAPA-18079', '23-036674-001', 'FAV-0379-22', 'USDA-010927-001', '22-009986-002', '22-027792-006', '22-010008-002', 'FAV-0687-3', '001719-005-R2', 'FAV-0340-12022', '028759-003', 'FAV-0582-1', '22-028671-001', 'USGS-0685', 'FAV-1470-17', 'FAV-1616-1', '006012-005', '22-015885-002', '22-023553-001', '23-008517-001', '24_018872-001', 'FAV-0469-12', '23-005876-026', '007549-034', 'FAV-0856-14', '003062-017', '014127-001', '003850-003', '22-018767-003', '24-031666-002', '003807-018', '22-028886-001', 'USDA-009041-001', 'FAV-0575-18', '23-030994-014', 'FAV-0256-1', '008065-005', '034949-001', '24_022168-002', '23-002762-024', 'FAV-0228-OS', 'FAV-0862-4', '031285-006', 'USDA-003935-013', '23-001056-001', '005148-001', '22-032511-077', '24_032597-002', '22-032511-165', 'FAV-0448-1', '22-035743-002', '22-040681-001', '008086-001', '22-016611-009', 'FAV-0953-3', '037410-003', '035649-001', '001170-001', '025748-002', 'FAV-0833-13', '22-022940-002', 'FAV-0386-2', '035630-003', '22-016457-007', 'FAV-1580-5', '033976-001', '24_009110-027', '22-014701-002', 'FAV-0833-73', '24-034441-003', '24-035690-001', '005872-003', '22-038267-001', '24_012341-015', '24_018782-001', '007069-001', 'USDA-008935-003', 'USDA-001329-001', '003352-001', '037832-001', '007118-056', '23-032059-002-original', '24-034932-003', '23-037463-002', '006183-001', '22-014696-001', '031667-007', 'FAV-0060-2', '002423-004', '22-012046-001', 'FAV-0301-2', 'FAV-1006-3', '22-026980-007', 'FAV-0247-1', '22-031409-001-R', '22-005440-001', '22-041373-003', '23-039245-001-original', 'FAV-0833-50', '23-039033-001-original', '23-034416-003-original', '24_011574-001', 'FAV-1369-1', '23-032793-004-original', '23-038677-002-original', '033866-002', '24_017584-003', '22-040701-002', '24_035846-001-R2', '24_020027-007', 'FAV-0053-1', '22-008485-001', '036570-001', 'FAV-0544', '22-033035-001', '007464-001', '245467', '22-020785-003-original', 'W24-219E', 'FAV-1469-4', '033852-001', '24-004334-024-original', '22-010378-001', '23-035546-002', '037217-014', '22-013663-007', 'USDA-011035-001', 'AIVPHL-82', '22-014744-004', '036411-002', '22-013369-007', '002923-001', '22-017013-003-original', '038123-003', '22-030257-001', '035916-002', '000733-002', 'AV22-675', 'B2410989-URINE-54', '23-033623-001', 'FAV-0877-3', 'CEIRR-287', '007729-023', 'FAV-0841-1', '23-011169-003', '22-040817-009', 'USDA-008935-006', '22-017052-001', 'FAV-0413-4', '22-012099-002', '23-037612-002', '24-035675-001', '24-032297-001', 'USDA-011033-005', '22-015577-001', 'AIVPHL-764', '22-015545-001', 'FAV-0035-3', '22-020455-001', 'FAV-0080-1', 'FAV-0918-31', '000286-001', '22-012855-002', 'AIVPHL-2929', '24_033008-001', 'FAV-0432-2', 'FAV-0379-23', 'W22-480B', '24_016370-012', 'USDA-008506-001', '003847-001', '23-000751-001', 'FAV-1595-2', 'FAV-0233-125', '22-010654-002', '22-032452-001', '24_021716-003', '23-006268-006', '003857-003', '24_017660-003', 'FAV-0987-1', '24-033963-001', '036568-004', '005551-001', '23-033317-020-original2', '031959-001', '036371-002', 'USGS-0326', '51_LUL', '23-001343-002', '036535-001', 'FAV-1627-5', '22-030422-001', 'FAV-1480-8', '001531-001', '23-016105-001', 'AIVPHL-91', '24_017652-001', '24-018880-002', '033226-001', '009321-002', '24-000764-003', '22-019521-005', '031286-006', 'USDA-012633-001', '004843-001', '24_033003-003', '005928-001', '010286-001', '22-025065-001', '24-000378-001', '23-004612-010', '22-024602-001', 'USDA-006203-003', '006660-003', '22-015303-001', 'USDA-001330-019', '23-034924-005', 'FAV-0505-31', '22-016611-011', '22-013278-001', '24_014287-001', '23-034293-006-original', '028247-001', '012313-002', '24_024710-001', '22-034533-007-R2', 'W24-248B', '23-036678-011-original', '23-005127-001', '23-001041-008', 'FAV-0639-1', '24_016688-006', 'AIVPHL-247', '24-037561-001', '22-037636-003', 'AIVPHL-2678', '038656-0

In [5]:
# Remove duplicates from GISAID/Andersen

print(len(metadata_segments))

for index, value in metadata_segments["Isolate"].items():
    if value in gisaid_andersen_isolates:
        metadata_segments = metadata_segments.drop(index)

print(len(metadata_segments))

metadata_segments

29400
29248

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV571926,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,1,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
1,PV571927,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,2,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
2,PV571928,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,3,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
3,PV571929,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,4,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
4,PV571930,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,5,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37035,OQ565628,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,4,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37036,OQ565629,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,5,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37037,OQ565630,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,6,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37038,OQ565631,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,7,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37039,OQ565632,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,8,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8

In [6]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds

# print(metadata_segments["GenBank_Title"].iloc[0])

# Get sequences and headers together
headers = []
isolates = []
sras = []
headers_seqs = {}
with open("sequences.fasta") as f:
    lines = f.readlines()
    for num, line in enumerate(lines):
        if line[0] == ">": # If this is a header
            if line[1:].strip() not in headers: # And the previous line is not a header we've seen before
                header = line[1:].strip() # Remove the ">"
                # print(header)
                split_header = header.split("|")
                # print(split_header)
                headers.append(header) 
                if num < len(lines): # If we're not at the last line
                    # for i, l in enumerate(lines[num + 1:]):
                    i = num
                    sequence = ""
                    # print(lines[i])
                    # print(lines[i + 1])
                    while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                        sequence = sequence + lines[i + 1].strip()
                        i += 1
                    headers_seqs[header] = sequence # Add next lines to sequences
                # name = split_header[-1] # Last part gives GenBank name, with segment and isolate
                isolate = split_header[2]
                isolates.append(isolate)
                sra = split_header[7]
                sras.append(sra)
    f.close()



# print(mask_all.all(axis=1))

In [7]:
# Goal: one fasta file per SRA, with all 8 segments within it


# Double-check
mask = metadata_segments["Isolate"].isin(isolates) # Check if isolate is in fasta
mask_sra = metadata_segments["SRA_Accession"].isin(sras) # Check if sra is in fasta

metadata_masked = metadata_segments[mask] # Some do not have isolates, so check sra too
metadata_masked_sra = metadata_segments[mask_sra]

merged_metadata = metadata_masked.merge(metadata_masked_sra, how="outer")

print(len(headers_seqs))
print(len(merged_metadata))

# Get only the sequences that survived the metadata purge
valid_headers_seqs = {}
for key in headers_seqs.keys():
    isolate = key.split("|")[2]
    sra = key.split("|")[7]
    if isolate in merged_metadata["Isolate"].values or sra in merged_metadata["SRA_Accession"]:
        valid_headers_seqs[key] = headers_seqs[key]

print(len(valid_headers_seqs))

# print(pd.concat([metadata_segments,merged_metadata]).drop_duplicates(keep=False))

75007
29248
27512

In [8]:
for key in valid_headers_seqs.keys():
    print(key)
    break

Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds