# Cleaning Downloaded Data from avian-flu

Author: Alexander Maksiaev

Purpose: Clean downloaded data from avian-flu, rename sequences according to convention, de-duplicate from GISAID

In [2]:
# Housekeeping

import os
import glob 
import pandas as pd
import xml.etree.ElementTree as ET
import requests
import time
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import * 

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu"
# downloads = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
originals = downloads + "Andersen_Downloads/"
temp_files = downloads + "Andersen_Temp_Files/"
complete_files = downloads + "Andersen_Complete_Files/"

os.chdir(downloads)

In [3]:
# Read metadata

metadata_folder = originals + "avian-influenza/metadata/"
os.chdir(metadata_folder)

metadata = pd.read_csv("SraRunTable_automated.csv")

print(len(metadata)) # 7397 rows

# Split date format to only check year
for date in metadata["Collection_Date"]:
    if "/" in date or date == "missing":
        metadata = metadata[metadata["Collection_Date"] != date]
metadata["Collection_Date"] = metadata["Collection_Date"].apply(lambda x: x.split("-")[0])
metadata["Collection_Date"] = metadata["Collection_Date"].apply(lambda x: int(x))

# Find only >= 2024 using run ID from metadata
metadata_new = metadata[metadata["Collection_Date"] >= 2024]
metadata_new["Collection_Date"] = metadata_new["Collection_Date"].astype(int) # Years are not floats

print(len(metadata_new)) # 6053 rows

7397
6053

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\4\ipykernel_17196\2731231253.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_new["Collection_Date"] = metadata_new["Collection_Date"].astype(int) # Years are not floats

In [4]:
# Modify isolates to xxxxxx-xxx

# new_isolates = []
# for isolate in metadata_new["isolate"]:
#     new_isolate = ""
#     # if isolate:
#     #     print(isolate)
#     try:
#         split_isolate = isolate.split("-")
#     except:
#         new_isolate = ""
#     # else:
#     #     split_isolate = ""
#     for split in split_isolate:
#         if len(split) == 6:
#             new_isolate = new_isolate + split
#         if len(split) == 3:
#             new_isolate = new_isolate + "-" + split
#     new_isolates.append(new_isolate)

# metadata_new["isolate"] = new_isolates

# display(metadata_new["isolate"])

### Naming convention ###
>A/[host]/[geo_loc_name]/[isolate]/[year]|[serotype: H5N1]|[collection_date]|[host_type]|[genotype: B3.13 or D1.1]

host_type is from manual animal reference

In metadata, we have: host, geo_loc_name, isolate, year

We need: geo_loc_name, collection_date, host_type, genotype

host = Host

geo_loc_name (primary) = geo_loc_name

geo_loc_name (secondary) = genbank_mapping.tsv > genbank_name

isolate = isolate

collection date (primary) = Collection_Date

collection date (secondary) = https://www.ncbi.nlm.nih.gov/genbank/ > BioSample (input: BioSample) > Nucleotide > [first result] > collection_date

serotype = serotype

host type = [from ref] 

genotype = [from genoflu] -- use output.tsv

In [5]:
# Get genotype from genoflu
os.chdir(temp_files)
output_tsv = pd.read_csv("output.tsv", delimiter="\t")

b313_and_d11_only = output_tsv[(output_tsv["Genotype"] == "B3.13") | (output_tsv["Genotype"] == "D1.1")]
b313_and_d11_only = b313_and_d11_only.rename(columns={"sample": "Run"})
b313_and_d11_only = b313_and_d11_only.drop_duplicates(subset="Run", keep="last")
# print(b313_and_d11_only)
print(len(b313_and_d11_only)) # 5160 rows

metadata_new = metadata_new.merge(b313_and_d11_only, on="Run", how="inner")

print(len(metadata_new)) # 5160

5160
5160

In [6]:
# Get animals from animal reference
os.chdir(downloads)
animals_ref = pd.read_csv("animals_ref.csv")
fix_animals_andersen(metadata_new, animals_ref) # Get host type
metadata_new["years"] = metadata_new["Collection_Date"].apply(lambda x: str(x).split("-")[0]) # Get year only from collection date

In [7]:
print(len(metadata_new))

5160

In [8]:
# Get geolocation from genbank_mapping.tsv

os.chdir(metadata_folder)
genbank_mapping = pd.read_csv("genbank_mapping.tsv", delimiter="\t")
genbank_mapping["Run"] = genbank_mapping["sra_run"]
genbank_mapping = genbank_mapping.drop_duplicates(subset="Run")
genbank_mapping["name_state"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[2])
# genbank_mapping["isolate"] = genbank_mapping["genbank_name"].apply(lambda x: x.split("/")[3])

# Change isolate names in genbank mapping

# new_isolates = []
# for isolate in genbank_mapping["isolate"]:
#     new_isolate = ""
#     # if isolate:
#     #     print(isolate)
#     try:
#         split_isolate = isolate.split("-")
#     except:
#         continue
#     # else:
#     #     split_isolate = ""
#     for split in split_isolate:
#         if len(split) == 6:
#             new_isolate = new_isolate + split
#         if len(split) == 3:
#             new_isolate = new_isolate + "-" + split
#     new_isolates.append(new_isolate)

# genbank_mapping["isolate"] = new_isolates


# map to metadata


metadata_genbank = metadata_new.merge(genbank_mapping, on="Run", how="inner")

print(len(metadata_genbank))
display(metadata_genbank)

3357

,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,Collection_Date,...,Host_Type,years,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state
0,SRR28752446,WGS,146.11,93605195,PRJNA1102327,SAMN41019184,Viral,30074178,USDA-NVSL,2024,...,other,2024,SRR28752446_HA_cns.fa,Consensus_SRR28752446_HA_cns_threshold_0.5_qua...,SRR28752446,HA,PP740722.1,4,A/blackbird/Texas/24-008354-001/2024,Texas
1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,2024,...,cattle,2024,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,SRR28752447,HA,PP752829.1,4,A/cattle/Texas/24-009108-005/2024,Texas
2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,2024,...,cattle,2024,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,SRR28752448,HA,PP752821.1,4,A/cattle/Texas/24-009108-004/2024,Texas
3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,2024,...,cattle,2024,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,SRR28752449,HA,PP752813.1,4,A/cattle/Texas/24-009108-003/2024,Texas
4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,2024,...,cattle,2024,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,SRR28752450,HA,PP752805.1,4,A/cattle/Texas/24-009108-002/2024,Texas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,SRR32653896,WGS,147.21,170346135,PRJNA1102327,SAMN47305024,Viral,58690418,USDA-NVSL,2025,...,cattle,2025,SRR32653896_HA_cns.fa,Consensus_SRR32653896_HA_cns_threshold_0.5_qua...,SRR32653896,HA,PV338836.1,4,A/cattle/CA/25-003262-003-original/2024,CA
3353,SRR32653897,WGS,148.06,69910137,PRJNA1102327,SAMN47305023,Viral,23973854,USDA-NVSL,2025,...,cattle,2025,SRR32653897_HA_cns.fa,Consensus_SRR32653897_HA_cns_threshold_0.5_qua...,SRR32653897,HA,PV338828.1,4,A/cattle/CA/25-003262-002-original/2024,CA
3354,SRR32653898,WGS,148.21,61895474,PRJNA1102327,SAMN47305022,Viral,21444614,USDA-NVSL,2025,...,cattle,2025,SRR32653898_HA_cns.fa,Consensus_SRR32653898_HA_cns_threshold_0.5_qua...,SRR32653898,HA,PV338820.1,4,A/cattle/CA/25-003262-001-original/2024,CA
3355,SRR32653899,WGS,148.15,67537431,PRJNA1102327,SAMN47305021,Viral,25457165,USDA-NVSL,2025,...,avian,2025,SRR32653899_HA_cns.fa,Consensus_SRR32653899_HA_cns_threshold_0.5_qua...,SRR32653899,HA,PV336676.1,4,A/Duck/CA/25-003063-003-original/2025,CA
3356,SRR32653903,WGS,147.27,96292618,PRJNA1102327,SAMN47305027,Viral,33482181,USDA-NVSL,2025,...,feline,2025,SRR32653903_HA_cns.fa,Consensus_SRR32653903_HA_cns_threshold_0.5_qua...,SRR32653903,HA,PV338476.1,4,A/cat/CO/25-003476-003-original/2025,CO

In [9]:
# # Get collection date from GenBank eutils 

# def search_collection_date(biosample):

#     print(biosample)

#     try:

#         # Avoid spamming the server
#         time.sleep(2)
    
#         base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
#         search_url = base_url + "esearch.fcgi?db=biosample&term=" + biosample +"&usehistory=y&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

#         # Get Biosample ID from search_url
#         output = requests.get(search_url)
#         xml = output.content
#         root = ET.fromstring(xml)
#         sample_id = root.find("./IdList/Id").text

#         biosample_url = base_url + "elink.fcgi?dbfrom=biosample&db=nuccore&id=" + sample_id + "&cmd=neighbor_history&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"
        
#         # Get Nucleotide ID from biosample_url
#         output = requests.get(biosample_url)
#         xml = output.content
#         root = ET.fromstring(xml)
#         query_key = root.find(".//QueryKey").text
#         web_env = root.find(".//WebEnv").text

#         nucleotide_url = base_url + "esummary.fcgi?db=nuccore&query_key=" + query_key + "&WebEnv=" + web_env + "&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

#         output = requests.get(nucleotide_url) 
#         xml = output.content
#         root = ET.fromstring(xml)

#         # Grab collection date at the end of the sub name
#         collection_date = root.find(".//SubName").text.split("|")[-1]

#         return collection_date
    
#     except:
#         print("Unable to find collection date.")

#         if len(metadata_genbank[metadata_genbank["BioSample"] == biosample]["years"]) > 0: # If a year exists
#             collection_date = metadata_genbank[metadata_genbank["BioSample"] == biosample]["years"].values[0]
#         else:
#             collection_date = float('nan') 

#         return collection_date
    
# metadata_genbank["Collection_Date_Specific"] = metadata_genbank["BioSample"].apply(search_collection_date)

In [10]:
# # Save this so we don't have to do it again

# os.chdir(temp_files)
# metadata_genbank.to_csv("metadata_genbank.csv")

In [11]:
# Upload saved data
os.chdir(temp_files)
metadata_genbank = pd.read_csv("metadata_genbank.csv")
display(metadata_genbank)

,Unnamed: 0,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,...,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state,Collection_Date_Specific,Name
0,0,SRR28752446,WGS,146.11,93605195,PRJNA1102327,SAMN41019184,Viral,30074178,USDA-NVSL,...,SRR28752446_HA_cns.fa,Consensus_SRR28752446_HA_cns_threshold_0.5_qua...,SRR28752446,HA,PP740722.1,4,A/blackbird/Texas/24-008354-001/2024,Texas,16-Mar-2024,>A/Blackbird/Texas/24-008354-001-original/2024...
1,1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,...,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,SRR28752447,HA,PP752829.1,4,A/cattle/Texas/24-009108-005/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-005-original/2024|H5...
2,2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,...,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,SRR28752448,HA,PP752821.1,4,A/cattle/Texas/24-009108-004/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-004-original/2024|H5...
3,3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,...,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,SRR28752449,HA,PP752813.1,4,A/cattle/Texas/24-009108-003/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-003-original/2024|H5...
4,4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,...,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,SRR28752450,HA,PP752805.1,4,A/cattle/Texas/24-009108-002/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-002-original/2024|H5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,3352,SRR32653896,WGS,147.21,170346135,PRJNA1102327,SAMN47305024,Viral,58690418,USDA-NVSL,...,SRR32653896_HA_cns.fa,Consensus_SRR32653896_HA_cns_threshold_0.5_qua...,SRR32653896,HA,PV338836.1,4,A/cattle/CA/25-003262-003-original/2024,CA,05-Nov-2024,>A/CATTLE/CA/25-003262-003/2025|H5N1|05-Nov-20...
3353,3353,SRR32653897,WGS,148.06,69910137,PRJNA1102327,SAMN47305023,Viral,23973854,USDA-NVSL,...,SRR32653897_HA_cns.fa,Consensus_SRR32653897_HA_cns_threshold_0.5_qua...,SRR32653897,HA,PV338828.1,4,A/cattle/CA/25-003262-002-original/2024,CA,05-Nov-2024,>A/CATTLE/CA/25-003262-002/2025|H5N1|05-Nov-20...
3354,3354,SRR32653898,WGS,148.21,61895474,PRJNA1102327,SAMN47305022,Viral,21444614,USDA-NVSL,...,SRR32653898_HA_cns.fa,Consensus_SRR32653898_HA_cns_threshold_0.5_qua...,SRR32653898,HA,PV338820.1,4,A/cattle/CA/25-003262-001-original/2024,CA,05-Nov-2024,>A/CATTLE/CA/25-003262-001/2025|H5N1|05-Nov-20...
3355,3355,SRR32653899,WGS,148.15,67537431,PRJNA1102327,SAMN47305021,Viral,25457165,USDA-NVSL,...,SRR32653899_HA_cns.fa,Consensus_SRR32653899_HA_cns_threshold_0.5_qua...,SRR32653899,HA,PV336676.1,4,A/Duck/CA/25-003063-003-original/2025,CA,22-Jan-2025,>A/DUCK/CA/25-003063-003/2025|H5N1|22-Jan-2025...
3356,3356,SRR32653903,WGS,147.27,96292618,PRJNA1102327,SAMN47305027,Viral,33482181,USDA-NVSL,...,SRR32653903_HA_cns.fa,Consensus_SRR32653903_HA_cns_threshold_0.5_qua...,SRR32653903,HA,PV338476.1,4,A/cat/CO/25-003476-003-original/2025,CO,26-Jan-2025,>A/CAT/CO/25-003476-003/2025|H5N1|26-Jan-2025|...

In [12]:
# Make names

# names = ">A/" + metadata_new["Host"] + "/" + metadata_new["geo_loc_name"] + "/" + metadata_new["isolate"] + "/" + years + "|H5N1|" + metadata_new["Collection_Date"].apply(lambda x: str(x)) + "|" + metadata_new["Host_Type"] + "|" + metadata_new["Genotype"]
names = ">A/" + metadata_genbank["Host"] + "/" + metadata_genbank["name_state"] + "/" + metadata_genbank["isolate"] + "/" + metadata_genbank["years"].apply(lambda x: str(x)) + "|H5N1|" + metadata_genbank["Collection_Date_Specific"] + "|" + metadata_genbank["Host_Type"] + "|" + metadata_genbank["Genotype"]

metadata_genbank["Name"] = names

display(metadata_genbank)

,Unnamed: 0,Run,Assay Type,AvgSpotLen,Bases,BioProject,BioSample,BioSampleModel,Bytes,Center Name,...,seg_file,seg_seq_name,sra_run,seg,genbank_acc,genbank_seg,genbank_name,name_state,Collection_Date_Specific,Name
0,0,SRR28752446,WGS,146.11,93605195,PRJNA1102327,SAMN41019184,Viral,30074178,USDA-NVSL,...,SRR28752446_HA_cns.fa,Consensus_SRR28752446_HA_cns_threshold_0.5_qua...,SRR28752446,HA,PP740722.1,4,A/blackbird/Texas/24-008354-001/2024,Texas,16-Mar-2024,>A/Blackbird/Texas/24-008354-001-original/2024...
1,1,SRR28752447,WGS,241.29,86080323,PRJNA1102327,SAMN41019237,Viral,28164109,USDA-NVSL,...,SRR28752447_HA_cns.fa,Consensus_SRR28752447_HA_cns_threshold_0.5_qua...,SRR28752447,HA,PP752829.1,4,A/cattle/Texas/24-009108-005/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-005-original/2024|H5...
2,2,SRR28752448,WGS,250.30,75035343,PRJNA1102327,SAMN41019236,Viral,24547283,USDA-NVSL,...,SRR28752448_HA_cns.fa,Consensus_SRR28752448_HA_cns_threshold_0.5_qua...,SRR28752448,HA,PP752821.1,4,A/cattle/Texas/24-009108-004/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-004-original/2024|H5...
3,3,SRR28752449,WGS,146.61,59363690,PRJNA1102327,SAMN41019235,Viral,19686302,USDA-NVSL,...,SRR28752449_HA_cns.fa,Consensus_SRR28752449_HA_cns_threshold_0.5_qua...,SRR28752449,HA,PP752813.1,4,A/cattle/Texas/24-009108-003/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-003-original/2024|H5...
4,4,SRR28752450,WGS,251.31,119232569,PRJNA1102327,SAMN41019234,Viral,38846827,USDA-NVSL,...,SRR28752450_HA_cns.fa,Consensus_SRR28752450_HA_cns_threshold_0.5_qua...,SRR28752450,HA,PP752805.1,4,A/cattle/Texas/24-009108-002/2024,Texas,20-Mar-2024,>A/Cattle/Texas/24-009108-002-original/2024|H5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3352,3352,SRR32653896,WGS,147.21,170346135,PRJNA1102327,SAMN47305024,Viral,58690418,USDA-NVSL,...,SRR32653896_HA_cns.fa,Consensus_SRR32653896_HA_cns_threshold_0.5_qua...,SRR32653896,HA,PV338836.1,4,A/cattle/CA/25-003262-003-original/2024,CA,05-Nov-2024,>A/CATTLE/CA/25-003262-003/2025|H5N1|05-Nov-20...
3353,3353,SRR32653897,WGS,148.06,69910137,PRJNA1102327,SAMN47305023,Viral,23973854,USDA-NVSL,...,SRR32653897_HA_cns.fa,Consensus_SRR32653897_HA_cns_threshold_0.5_qua...,SRR32653897,HA,PV338828.1,4,A/cattle/CA/25-003262-002-original/2024,CA,05-Nov-2024,>A/CATTLE/CA/25-003262-002/2025|H5N1|05-Nov-20...
3354,3354,SRR32653898,WGS,148.21,61895474,PRJNA1102327,SAMN47305022,Viral,21444614,USDA-NVSL,...,SRR32653898_HA_cns.fa,Consensus_SRR32653898_HA_cns_threshold_0.5_qua...,SRR32653898,HA,PV338820.1,4,A/cattle/CA/25-003262-001-original/2024,CA,05-Nov-2024,>A/CATTLE/CA/25-003262-001/2025|H5N1|05-Nov-20...
3355,3355,SRR32653899,WGS,148.15,67537431,PRJNA1102327,SAMN47305021,Viral,25457165,USDA-NVSL,...,SRR32653899_HA_cns.fa,Consensus_SRR32653899_HA_cns_threshold_0.5_qua...,SRR32653899,HA,PV336676.1,4,A/Duck/CA/25-003063-003-original/2025,CA,22-Jan-2025,>A/DUCK/CA/25-003063-003/2025|H5N1|22-Jan-2025...
3356,3356,SRR32653903,WGS,147.27,96292618,PRJNA1102327,SAMN47305027,Viral,33482181,USDA-NVSL,...,SRR32653903_HA_cns.fa,Consensus_SRR32653903_HA_cns_threshold_0.5_qua...,SRR32653903,HA,PV338476.1,4,A/cat/CO/25-003476-003-original/2025,CO,26-Jan-2025,>A/CAT/CO/25-003476-003/2025|H5N1|26-Jan-2025|...

In [13]:
# Make fasta files

fasta_folder = originals + "avian-influenza/fasta/"

os.chdir(fasta_folder)

pairs = []
fasta_files = {}

for genotype in ["B3.13", "D1.1"]:
    for segment in ["PB2", "PB1", "PA", "NS", "NP", "NA", "MP", "HA"]:
        pair = genotype + "_" + segment
        pairs.append(pair)

for pair in pairs:
    fasta_files[pair] = [] # List to hold fasta files

for run in metadata_genbank["Run"].values: # For each run 
    for dirpath, dirs, files in os.walk(fasta_folder): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            # print(file_name)
            if run in file_name: # Note that there will be ~8 files total with that run name
                # Make a fasta file and put it in the list
                with open(file_name) as f:
                    lines = f.readlines()
                    sequence = lines[1] 
                    # Each run/segment pair has one sequence -- it's placed into a file with other run/segment pairs with the same segment and genotype
                    header = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Name"].values[0]
                    genotype = metadata_genbank[metadata_genbank["Run"] == run].loc[:, "Genotype"].values[0]
                    # print(header)
                    # print(genotype)
                    # break 
                    segment = file_name.split("_")[-2]
                    # Find the pair that corresponds to 
                    pair_name = genotype + "_" + segment
                    this_specific_fasta = []
                    for pair in pairs:
                        # print(pair)
                        # print(pair_name)
                        if pair_name == pair:
                            this_specific_fasta.append(header)
                            this_specific_fasta.append(sequence)
                            fasta_files[pair].append(this_specific_fasta)
                f.close()

In [24]:
# print(fasta_files[list(fasta_files.keys())[0]])

print(len(fasta_files["D1.1_PB2"]))

# print(fasta_files["B3.13_PB1"])

602

In [15]:
# Create fasta files 
os.chdir(complete_files)
for pair in fasta_files.keys():
    output_path = complete_files + pair + ".fasta" 

    output_file = open(output_path, "w")
    for item in fasta_files[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[0].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[0])
        print(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name + "\n")
        output_file.write(item[1])
    output_file.close()

>A/Blackbird/Texas/24-008354-001-original/2024|H5N1|16-Mar-2024|other|B3.13
>A/Cattle/Texas/24-009108-005-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009108-004-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009108-003-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009108-002-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009108-001-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009088-002-original/2024|H5N1|13-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009088-001-original/2024|H5N1|13-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009087-001-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009029-001-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-019-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-007264-003-original/2024|H5N1|07-Mar-2024|avian|B3.13
>A/Cattle/Texas/24-009028-009-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-008-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-007-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-005-original-repeat/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-003-original-MTM/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-002-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009028-001-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Michigan/24-009027-010-original-repeat/2024|H5N1|24-Mar-2024|cattle|B3.13
>A/Cattle/Michigan/24-009027-005-original-MTM/2024|H5N1|24-Mar-2024|cattle|B3.13
>A/Cattle/Michigan/24-009027-004-original-repeat/2024|H5N1|24-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-007264-001-original/2024|H5N1|07-Mar-2024|avian|B3.13
>A/Cattle/Michigan/24-009027-003-original-repeat/2024|H5N1|24-Mar-2024|cattle|B3.13
>A/Cattle/Michigan/24-009027-002-original/2024|H5N1|24-Mar-2024|cattle|B3.13
>A/Cat/Texas/24-008850-002-original/2024|H5N1|20-Mar-2024|feline|B3.13
>A/Cat/Texas/24-008850-001-original/2024|H5N1|20-Mar-2024|feline|B3.13
>A/Cattle/Kansas/24-008766-001-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010193-003-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010192-006-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-010-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-009-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-008-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-007-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-006-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-005-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-003-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-008749-001-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-002-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010071-001-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-009776-015-original/2024|H5N1|10-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009776-004-original/2024|H5N1|10-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009776-002-original/2024|H5N1|10-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009776-001-original/2024|H5N1|10-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009775-001-original/2024|H5N1|10-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-009654-004-original/2024|H5N1|01-Apr-2024|avian|B3.13
>A/Chicken/Texas/24-009654-001-original/2024|H5N1|01-Apr-2024|avian|B3.13
>A/Cattle/Ohio/24-009586-010-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-008660-002-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-009-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-008-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-007-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-006-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-005-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-003-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-002-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/Ohio/24-009586-001-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Chicken/Michigan/24-009582-003-original/2024|H5N1|01-Apr-2024|avian|B3.13
>A/Chicken/Michigan/24-009582-002-original/2024|H5N1|01-Apr-2024|avian|B3.13
>A/Cattle/Texas/24-008660-001-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009290-001-original/2024|H5N1|13-Mar-2024|cattle|B3.13
>A/Cat/New Mexico/24-009116-005-original/2024|H5N1|20-Mar-2024|feline|B3.13
>A/Cat/New Mexico/24-009116-004-original/2024|H5N1|20-Mar-2024|feline|B3.13
>A/Cat/New Mexico/24-009116-002-original/2024|H5N1|20-Mar-2024|feline|B3.13
>A/Cattle/Texas/24-009110-027-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-026-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-025-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-024-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-023-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-022-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-008355-003-original/2024|H5N1|16-Mar-2024|avian|B3.13
>A/Grackle/Texas/24-008765-002-original/2024|H5N1|20-Mar-2024|other|B3.13
>A/Skunk/New Mexico/24-006483-001-original/2024|H5N1|2024|other_mammal|B3.13
>A/Cat/Texas/24-008764-002-original/2024|H5N1|22-Mar-2024|feline|B3.13
>A/Cat/Texas/24-008764-001-original/2024|H5N1|22-Mar-2024|feline|B3.13
>A/Cattle/Texas/24-008749-008-original-repeat/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-008749-007-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-008749-006-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-010514-002-original/2024|H5N1|03-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-010513-007-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-010513-006-original/2024|H5N1|28-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-010513-004-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-010513-003-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-010513-002-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010512-001-original/2024|H5N1|02-Apr-2024|cattle|B3.13
>A/Chicken/Kansas/24-010482-001-original/2024|H5N1|08-Apr-2024|avian|B3.13
>A/Cattle/South Dakota/24-010354-020-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-008749-005-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-019-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-018-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-017-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-016-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-015-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-014-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-013-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-012-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-011-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-010-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-009-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-008-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-006-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Chicken/Michigan/24-009582-001-original/2024|H5N1|01-Apr-2024|avian|B3.13
>A/Cattle/Texas/24-009499-001-original/2024|H5N1|17-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-014-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-012-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-011-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-010-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-009-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-008-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-007-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Blackbird/Texas/24-008357-001-original/2024|H5N1|16-Mar-2024|other|B3.13
>A/Cattle/Kansas/24-009497-006-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-005-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-004-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Kansas/24-009497-003-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Raccoon/New Mexico/24-009496-002-original/2024|H5N1|23-Mar-2024|other|B3.13
>A/Cattle/Texas/24-009495-012-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009495-011-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009495-010-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009495-009-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009495-008-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Grackle/Texas/24-008356-003-original/2024|H5N1|18-Mar-2024|other|B3.13
>A/Cattle/Texas/24-009495-003-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009495-002-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009495-001-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Idaho/24-009491-007-original/2024|H5N1|27-Mar-2024|cattle|B3.13
>A/Cattle/Idaho/24-009491-006-original/2024|H5N1|27-Mar-2024|cattle|B3.13
>A/Cattle/Idaho/24-009491-005-original/2024|H5N1|27-Mar-2024|cattle|B3.13
>A/Cattle/Idaho/24-009491-003-original/2024|H5N1|27-Mar-2024|cattle|B3.13
>A/Cattle/Idaho/24-009491-002-original/2024|H5N1|27-Mar-2024|cattle|B3.13
>A/Cattle/Idaho/24-009491-001-original/2024|H5N1|27-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-023-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-021-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-020-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-019-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-018-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-017-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-016-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-015-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-014-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-012-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-011-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-008355-002-original/2024|H5N1|16-Mar-2024|avian|B3.13
>A/Cattle/Texas/24-009110-010-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-009-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-008-original-repeat/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-007-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-006-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-005-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-004-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-003-original-repeat/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-002-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009110-001-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-008355-001-original/2024|H5N1|16-Mar-2024|avian|B3.13
>A/Cattle/Texas/24-009109-008-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-007-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-006-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-005-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-004-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-003-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-002-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009109-001-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009108-007-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009108-006-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-005-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-004-original-300/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-003-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-002-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/South Dakota/24-010354-001-original/2024|H5N1|05-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-010331-001-original/2024|H5N1|14-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-013-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-008749-004-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-012-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-011-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-009-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-008-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-007-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-006-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-005-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-004-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-003-original/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010330-002-original-300/2024|H5N1|01-Apr-2024|cattle|B3.13
>A/Cattle/Texas/24-008749-003-original/2024|H5N1|20-Mar-2024|cattle|B3.13
>A/PEFA/California/24-005915-001-original/2024|H5N1|14-Feb-2024|other|B3.13
>A/Cattle/North Carolina/24-010327-003-original/2024|H5N1|04-Apr-2024|cattle|B3.13
>A/Chicken/Michigan/24-010308-012-original/2024|H5N1|06-Apr-2024|avian|B3.13
>A/Chicken/Michigan/24-010308-007-original/2024|H5N1|06-Apr-2024|avian|B3.13
>A/Chicken/Michigan/24-010308-006-original-300/2024|H5N1|06-Apr-2024|avian|B3.13
>A/Chicken/Michigan/24-010308-001-original-300/2024|H5N1|06-Apr-2024|avian|B3.13
>A/Cattle/Michigan/24-010303-002-original/2024|H5N1|03-Apr-2024|cattle|B3.13
>A/Cattle/Michigan/24-010303-001-original-300/2024|H5N1|03-Apr-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010195-001-original/2024|H5N1|15-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010194-001-original/2024|H5N1|15-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010193-007-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-010193-006-original/2024|H5N1|29-Mar-2024|cattle|B3.13
>A/Grackle/Texas/24-008356-001-original/2024|H5N1|18-Mar-2024|other|B3.13
>A/Cattle/Texas/24-009367-018-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-016-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-014-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-013-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-012-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-011-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-010-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-009-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-007-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-005-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-008355-006-original/2024|H5N1|16-Mar-2024|avian|B3.13
>A/Cattle/Texas/24-009367-004-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-003-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-002-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009367-001-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cat/United States/24-009311-006-original/2024|H5N1|16-Mar-2024|feline|B3.13
>A/Cat/Texas/24-009311-004-original/2024|H5N1|16-Mar-2024|feline|B3.13
>A/Cattle/Texas/24-009310-010-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009310-007-original-repeat/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009310-006-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009310-005-original/2024|H5N1|21-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-008355-005-original/2024|H5N1|16-Mar-2024|avian|B3.13
>A/Cattle/New Mexico/24-009309-004-original/2024|H5N1|16-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-009309-002-original/2024|H5N1|16-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-009309-001-original/2024|H5N1|16-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009308-008-original/2024|H5N1|19-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009308-006-original/2024|H5N1|19-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009308-004-original/2024|H5N1|19-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-009306-004-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/New Mexico/24-009306-003-original/2024|H5N1|25-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009290-006-original/2024|H5N1|13-Mar-2024|cattle|B3.13
>A/Cattle/Texas/24-009290-005-original/2024|H5N1|13-Mar-2024|cattle|B3.13
>A/Chicken/Texas/24-008355-004-original/2024|H5N1|16-Mar-2024|avian|B3.13
>A/CAGO/WY/24-003692-001-original/2024|H5N1|25-Jan-2024|other|B3.13
>A/CATTLE/New Mexico/24-010195-004/2024|H5N1|15-Mar-2024|cattle|B3.13
>A/PIGEON/Texas/24-008765-001/2024|H5N1|20-Mar-2024|avian|B3.13
>A/cattle/Texas/24-009495-005-original/2024|H5N1|2024|cattle|B3.13
>A/cattle/Texas/24-009495-004-original/2024|H5N1|2024|cattle|B3.13
>A/cattle/Texas/24-009310-009-original/2024|H5N1|2024|cattle|B3.13
>A/Domestic Cat/Oklahoma/24-009118-002-original/2024|H5N1|2024|other|B3.13
>A/Domestic Cat/New Mexico/24-009116-001-original/2024|H5N1|2024|other|B3.13
>A/CATTLE/MI/24-013021-003/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-002/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-001/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/DOMESTIC-CAT/SD/24-012039-001/2024|H5N1|19-Apr-2024|other|B3.13
>A/DOMESTIC-CAT/NM/24-012046-004/2024|H5N1|17-Apr-2024|other|B3.13
>A/DOMESTIC-CAT/NM/24-012046-003/2024|H5N1|17-Apr-2024|other|B3.13
>A/RED FOX/MI/24-013016-005/2024|H5N1|24-Apr-2024|other|B3.13
>A/RED FOX/MI/24-013016-004/2024|H5N1|24-Apr-2024|other|B3.13
>A/RED FOX/MI/24-013016-003/2024|H5N1|24-Apr-2024|other|B3.13
>A/RED FOX/MI/24-013016-002/2024|H5N1|24-Apr-2024|other|B3.13
>A/RED FOX/MI/24-013016-001/2024|H5N1|24-Apr-2024|other|B3.13
>A/COMON-GRACKLE/New Mexico/24-012607-002/2024|H5N1|23-Apr-2024|other|B3.13
>A/HAWK/New Mexico/24-012607-001/2024|H5N1|23-Apr-2024|avian|B3.13
>A/TURKEY/MI/24-012707-001/2024|H5N1|29-Apr-2024|avian|B3.13
>A/CATTLE/Idaho/24-013170-012/2024|H5N1|01-May-2024|cattle|B3.13
>A/CATTLE/Idaho/24-013170-011/2024|H5N1|01-May-2024|cattle|B3.13
>A/DOMESTIC-CAT/NM/24-012046-002/2024|H5N1|17-Apr-2024|other|B3.13
>A/CATTLE/Idaho/24-013170-006/2024|H5N1|01-May-2024|cattle|B3.13
>A/CATTLE/MI/24-013172-002/2024|H5N1|30-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-011/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-010/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-009/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-008/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-007/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-006/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-005/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/CATTLE/MI/24-013021-004/2024|H5N1|29-Apr-2024|cattle|B3.13
>A/DOMESTIC-CAT/NM/24-012046-001/2024|H5N1|17-Apr-2024|other|B3.13
>A/CATTLE/Idaho/24-012341-002/2024|H5N1|23-Apr-2024|cattle|B3.13
>A/DOMESTIC CAT/MI/24-011797-002-original/2024|H5N1|19-Apr-2024|other|B3.13
>A/CATTLE/Idaho/24-011573-017-original-repeat/2024|H5N1|15-Apr-2024|cattle|B3.13

In [174]:
# De-duplication attempt 2

from collections import defaultdict

# Gisaid 

gisaid = downloads + "GISAID_Complete_Fasta_Files/"

os.chdir(gisaid)

dfs_gisaid = defaultdict(list)
for dirpath, dirs, files in os.walk(gisaid): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        gisaid_df = pd.DataFrame()
        with open(file_name) as f:
            lines = f.readlines()
            isolate_partial = []
            full_header = []
            sequence = []
            # Some lines start with 25_, others 25-. This shouldn't matter, but split on "_" first
            for num, line in enumerate(lines):
                if line[0] == ">": # If it's a header
                    full_header.append(line)
                    full = line.split("/")[3] # Get the isolate
                    partial = full.split("_")[-1] # If 25_, get the last bit
                    digits = partial.split("-")
                    isolate = ""
                    other = ""
                    for d in digits:
                        # print(d)
                        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
                            isolate = d + "-"
                        elif len(d) == 3 and d.isnumeric():
                            isolate = isolate + d
                        elif d.isnumeric() == False: # If it's a weird isolate
                            other = d + "-"
                        else: 
                            other = other + d
                    # Now add to list to check in Andersen files without doing wild for loops
                    if len(isolate) == 10: # If this is a correctly formatted isolate
                        # isolates.append(isolate)
                        # All headers are followed by sequences
                        isolate_partial.append(isolate)
                    else: # If this is some other isolate
                        isolate_partial.append(other)
                else: # It's a sequence
                    sequence.append(line)
            gisaid_df["isolate_partial"] = isolate_partial
            gisaid_df["full_header"] = full_header
            gisaid_df["sequence"] = sequence
            dfs_gisaid[file_name.split("/")[-1][:-6]].append(gisaid_df)

In [175]:
print(dfs_gisaid["B3.13_HA"][0])

       isolate_partial                                        full_header  \
0           038428-002  >A/chicken/USA/038428-002/2024|H5N1|2024|avian...
1           035208-001  >A/dairy_cow/USA/035208-001/2024|H5N1|2024|cat...
2           003574-003  >A/turkey/California/003574-003/2025|H5N1|2025...
3           038428-001  >A/chicken/USA/038428-001/2024|H5N1|2024|avian...
4           003903-001  >A/turkey/California/003903-001/2025|H5N1|2025...
..                 ...                                                ...
778         005913-003  >A/cat/USA/005913-003/2025|H5N1|2025|feline|B3...
779         004757-001  >A/environment/USA/004757-001/2025|H5N1|2025|o...
780         004757-002  >A/environment/USA/004757-002/2025|H5N1|2025|o...
781         034828-002  >A/dairy_cow/California/24_034828-002-R2/2024|...
782  10|human|B3.13\n-  >A/California/216/2024|H5N1|2024-12-10|human|B...

                                              sequence
0    atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
1    atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
2    atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
3    atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
4    atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
..                                                 ...
778  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
779  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
780  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
781  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
782  atggagaacatagtgcttcttcttgcaatagttagccttgttaaaa...

[783 rows x 3 columns]

In [176]:
# Do the same with Andersen 

dfs_andersen = defaultdict(list)
for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        andersen_df = pd.DataFrame()
        with open(file_name) as f:
            lines = f.readlines()
            isolate_partial = []
            full_header = []
            sequence = []
            # Some lines start with 25_, others 25-. This shouldn't matter, but split on "_" first
            for num, line in enumerate(lines):
                if line[0] == ">": # If it's a header
                    full_header.append(line)
                    full = line.split("/")[3] # Get the isolate
                    partial = full.split("_")[-1] # If 25_, get the last bit
                    digits = partial.split("-")
                    isolate = ""
                    other = ""
                    for d in digits:
                        # print(d)
                        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
                            isolate = d + "-"
                        elif len(d) == 3 and d.isnumeric() and len(isolate) < 10: # If we haven't already gotten the isolate
                            isolate = isolate + d
                        elif d.isnumeric() == False: # If it's a weird isolate
                            other = d + "-"
                        else: 
                            other = other + d
                    # Now add to list to check in Andersen files without doing wild for loops
                    if len(isolate) == 10: # If this is a correctly formatted isolate
                        # print(isolate)
                        # isolates.append(isolate)
                        # All headers are followed by sequences
                        isolate_partial.append(isolate)
                    else: # If this is some other isolate
                        # print(full)
                        # print(other)
                        isolate_partial.append(other)
                else: # It's a sequence
                    sequence.append(line)
            andersen_df["isolate_partial"] = isolate_partial
            andersen_df["full_header"] = full_header
            andersen_df["sequence"] = sequence
            dfs_andersen[file_name.split("/")[-1][:-6]].append(andersen_df)

In [180]:
print(dfs_andersen["B3.13_HA"][0])

     isolate_partial                                        full_header  \
0         000003-001  >A/CHICKEN/CA/25-000003-001/2025|H5N1|28-Dec-2...
1         000003-001  >A/chicken/California/25-000003-001/2024|H5N1|...
2         000003-001  >A/chicken/USA/000003-001/2025|H5N1|2025|avian...
3         000026-001  >A/dairy_cow/USA/000026-001/2025|H5N1|2025|cat...
4         000026-002  >A/dairy_cow/USA/000026-002/2025|H5N1|2025|cat...
...              ...                                                ...
3472   A241900097-37  >A/dairy_cow/Texas/A241900097-37/2024|H5N1|202...
3473           F001-  >A/cat/New_Mexico/F001/2024|H5N1|2024|feline|B...
3474            SM-3  >A/dairy_cow/Kansas/SM-3/2024|H5N1|2024-04-12|...
3475            SM-6  >A/dairy_cow/Kansas/SM-6/2024|H5N1|2024-04-12|...
3476       T2402448-  >A/dairy_cow/California/T2402448/2024|H5N1|202...

                                               sequence
0     ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
1     atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
2     atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
3     atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
4     atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
...                                                 ...
3472  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
3473  agcaaaagcaggggttcactctgtcaaaatggagaacatagtacta...
3474  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
3475  atggagaacatagtactacttcttgcaatagttrgccttgttaaaa...
3476  gcaggggttcactctgtcaaaatggagaacatagtactacttcttg...

[3477 rows x 3 columns]

In [183]:
full_dfs = defaultdict(list)
for key in dfs_andersen.keys():
    dataframes = dfs_andersen[key]
    for i, df in enumerate(dataframes):
        full_df = df.merge(dfs_gisaid[key][i], how="outer")
        # print(full_df)
        full_df = full_df.drop_duplicates(subset=["isolate_partial"])
        full_dfs[key].append(full_df)

In [184]:
print(full_dfs["B3.13_HA"][0])

     isolate_partial                                        full_header  \
0         000003-001  >A/CHICKEN/CA/25-000003-001/2025|H5N1|28-Dec-2...
3         000026-001  >A/dairy_cow/USA/000026-001/2025|H5N1|2025|cat...
4         000026-002  >A/dairy_cow/USA/000026-002/2025|H5N1|2025|cat...
5         000045-001  >A/CHICKEN/CA/25-000045-001/2025|H5N1|29-Dec-2...
7         000046-001  >A/chicken/USA/000046-001/2025|H5N1|2025|avian...
...              ...                                                ...
3472   A241900097-37  >A/dairy_cow/Texas/A241900097-37/2024|H5N1|202...
3473           F001-  >A/cat/New_Mexico/F001/2024|H5N1|2024|feline|B...
3474            SM-3  >A/dairy_cow/Kansas/SM-3/2024|H5N1|2024-04-12|...
3475            SM-6  >A/dairy_cow/Kansas/SM-6/2024|H5N1|2024-04-12|...
3476       T2402448-  >A/dairy_cow/California/T2402448/2024|H5N1|202...

                                               sequence
0     ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
3     atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
4     atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
5     ATGAAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
7     atgaagaacatagtactacttcttgcaatagttagccttgttaaaa...
...                                                 ...
3472  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
3473  agcaaaagcaggggttcactctgtcaaaatggagaacatagtacta...
3474  atggagaacatagtactacttcttgcaatagttagccttgttaaaa...
3475  atggagaacatagtactacttcttgcaatagttrgccttgttaaaa...
3476  gcaggggttcactctgtcaaaatggagaacatagtactacttcttg...

[2981 rows x 3 columns]

In [185]:
# Create fasta files 
os.chdir(complete_files)
for pair in full_dfs.keys():
    output_path = complete_files + pair + ".fasta" 

    output_file = open(output_path, "w")
    for item in full_dfs[pair]:
        # for item in item:
        # item = fasta_files[pair]
        for index, row in item.iterrows():
            name = item.loc[index, "full_header"]
            sequence = item.loc[index, "sequence"]
        # print(name)
        # First is header, second is sequence
        # print(value)
            output_file.write(name)
            output_file.write(sequence)
    output_file.close()

In [ ]:
# De-duplication with GISAID

gisaid = downloads + "GISAID_Complete_Fasta_Files/"

os.chdir(gisaid)

isolates = {}
for dirpath, dirs, files in os.walk(gisaid): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        to_append = []
        with open(file_name) as f:
            lines = f.readlines()
            # Some lines start with 25_, others 25-. This shouldn't matter, but split on "_" first
            for num, line in enumerate(lines):
                if line[0] == ">": # If it's a header
                    full = line.split("/")[3] # Get the isolate
                    partial = full.split("_")[-1] # If 25_, get the last bit
                    digits = partial.split("-")
                    isolate = ""
                    other = ""
                    for d in digits:
                        # print(d)
                        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
                            isolate = d + "-"
                        elif len(d) == 3 and d.isnumeric():
                            isolate = isolate + d
                        elif d.isnumeric() == False: # If it's a weird isolate
                            other = d + "-"
                        else: 
                            other = other + d
                    # Now add to list to check in Andersen files without doing wild for loops
                    if len(isolate) == 10: # If this is a correctly formatted isolate
                        # isolates.append(isolate)
                        # All headers are followed by sequences
                        to_append.append([isolate, line, lines[num + 1]])
                    else: # If this is some other isolate
                        to_append.append([other, line, lines[num + 1]])
        isolates[file_name.split("/")[-1][:-6]] = to_append

print(len(isolates["D1.1_PB2"]))

1615

In [125]:
# If this isolate is not already in the Andersen fasta files, add it to those files

os.chdir(complete_files)


print(len(metadata_genbank))
# Some names don't exist
metadata_genbank = metadata_genbank.dropna(subset="Name")
print(len(metadata_genbank))
# Exclude duplicates
metadata_genbank = metadata_genbank.drop_duplicates(subset="Name")
print(len(metadata_genbank))

andersen_isolates = {}
for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        to_append = []
        with open(file_name) as f:
            lines = f.readlines()
            # Some lines start with 25_, others 25-. This shouldn't matter, but split on "_" first
            for num, line in enumerate(lines):
                if line[0] == ">": # If it's a header
                    print(num)

                    full = line.split("/")[3] # Get the isolate
                    partial = full.split("_")[-1] # If 25_, get the last bit
                    digits = partial.split("-")
                    isolate = ""
                    other = ""
                    for d in digits:
                        # print(d)
                        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
                            isolate = d + "-"
                        elif len(d) == 3 and d.isnumeric():
                            isolate = isolate + d
                        elif d.isnumeric() == False: # If it's a weird isolate
                            other = d + "-"
                        else: 
                            other = other + d
                    # Now add to list to check in Andersen files without doing wild for loops
                    if len(isolate) == 10: # If this is a correctly formatted isolate
                        # isolates.append(isolate)
                        # All headers are followed by sequences
                        to_append.append([isolate, line, lines[num + 1]])
                    else: # If this is some other isolate
                        to_append.append([other, line, lines[num + 1]])
        andersen_isolates[file_name.split("/")[-1][:-6]] = to_append



# print(to_remove_from_gisaid)

print((andersen_isolates["D1.1_PB2"][0]))
print(len(andersen_isolates["D1.1_PB2"]))

# for entry in to_remove_from_gisaid:
#     isolates.pop(entry)
# print(isolates)
# Now add remaining GISAID data to Andersen data
# isolates dictionary format: {isolate : [name, sequence]}

# gisaid_data = pd.DataFrame()

# display(metadata_genbank)

# Move the GISAID sequences to Andersen FASTA files

3296
3296
3296
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510
512
514
516
518
520
522
524
526
528
530
532
534
536
538
540
542
544
546
548
550
552
554
556
558
560
562
564
566
568
570
572
574
576
578
580
582
584
586
588
590
592
594
596
598
600
602
604
606
608
610
612
614
616
618
620
622
624
626
628
630
632
634
636
638
640
642
644
646
648
650
652
654
656
658
660
662
664
666
668
670
672
674
676
678
680
682
684
686
688
690
692
694
696
698
700
702
704
706
708
710
712
714
716
718
720
722
724
726
728
730
732
734
736
738
740
742
744
746
748
750
752
754
756
758
760
762
764
766
768
770
772
774
776
778
780
782
784
786
788
790
792
794
796
798
800
802
926
928
930
932
934
936
938
940
942
944
946
948
950
952
954
956
958
960
962
964
966
968
970
972
974
976
978
980
982
984
986
988
990
992
994
996
998
1000
1002
1004
1006
1008
1010
1012
1014
1016
1018
1020
1022
1024
1026
1028
1030
1032
1034
1036
1038
1040
1042
1044
1046
1048
1050
1052
1054
1056
1058
1060
1062
1064
1066
1068
1070
1072
1074
1076
1078
1080
1082
1084
1086
1088
1090
1092
1094
1096
1098
1100
1102
1104
1106
1108
1110
1112
1114
1116
1118
1120
1122
1124
1126
1128
1130
1132
1134
1136
1138
1140
1142
1144
1146
1148
1150
1152
1154
1156
1158
1160
1162
1164
1166
1168
1170
1172
1174
1176
1178
1180
1182
1184
1186
1188
1190
1192
1194
1196
1198
1200
1202
1204
1206
1208
1210
1212
1214
1216
1218
1220
1222
1224
1226
1228
1230
1232
1234
1236
1238
1240
1242
1244
1246
1248
1250
1252
1254
1256
1258
1260
1262
1264
1266
1268
1270
1272
1274
1276
1278
1280
1282
1284
1286
1288
1290
1292
1294
1296
1298
1300
1302
1304
1306
1308
1310
1312
1314
1316
1318
1320
1322
1324
1326
1328
1330
1332
1334
1336
1338
1340
1342
1344
1346
1348
1350
1352
1354
1356
1358
1360
1362
1364
1366
1368
1370
1372
1374
1376
1378
1380
1382
1384
1386
1388
1390
1392
1394
1396
1398
1400
1402
1404
1406
1408
1410
1412
1414
1416
1418
1420
1422
1424
1426
1428
1430
1432
1434
1436
1438
1440
1442
1444
1446
1448
1450
1452
1454
1456
1458
1460
1462
1464
1466
1468
1470
1472
1474
1476
1478
1480
1482
1484
1486
1488
1490
1492
1494
1496
1498
1500
1502
1504
1506
1508
1510
1512
1514
1516
1518
1520
1522
1524
1526
1528
1530
1532
1534
1536
1538
1540
1542
1544
1546
1548
1550
1552
1554
1556
1558
1560
1562
1564
1566
1568
1570
1572
1574
1576
1578
1580
1582
1584
1586
1588
1590
1592
1594
1596
1598
1600
1602
1604
1606
1608
1610
1612
1614
1616
1618
1620
1622
1624
1626
1628
1630
1632
1634
1636
1638
1640
1642
1644
1646
1648
1650
1652
1654
1656
1658
1660
1662
1664
1666
1668
1670
1672
1674
1676
1678
1680
1682
1684
1686
1688
1690
1692
1694
1696
1698
1700
1702
1704
1706
1708
1710
1712
1714
1716
1718
1720
1722
1724
1726
1728
1730
1732
1734
1736
1738
1740
1742
1744
1746
1748
1750
1752
1754
1756
1758
1760
1762
1764
1766
1768
1770
1772
1774
1776
1778
1780
1782
1784
1786
1788
1790
1792
1794
1796
1798
1800
1802
1804
1806
1808
1810
1812
1814
1816
1818
1820
1822
1824
1826
1828
1830
1832
1834
1836
1838
1840
1842
1844
1846
1848
1850
1852
1854
1856
1858
1860
1862
1864
1866
1868
1870
1872
1874
1876
1878
1880
1882
1884
1886
1888
1890
1892
1894
1896
1898
1900
1902
1904
1906
1908
1910
1912
1914
1916
1918
1920
1922
1924
1926
1928
1930
1932
1934
1936
1938
1940
1942
1944
1946
1948
1950
1952
1954
1956
1958
1960
1962
1964
1966
1968
1970
1972
1974
1976
1978
1980
1982
1984
1986
1988
1990
1992
1994
1996
1998
2000
2002
2004
2006
2008
2010
2012
2014
2016
2018
2020
2022
2024
2026
2028
2030
2032
2034
2036
2038
2040
2042
2044
2046
2048
2050
2052
2054
2056
2058
2060
2062
2064
2066
2068
2070
2072
2074
2076
2078
2080
2082
2084
2086
2088
2090
2092
2094
2096
2098
2100
2102
2104
2106
2108
2110
2112
2114
2116
2118
2120
2122
2124
2126
2128
2130
2132
2134
2136
2138
2140
2142
2144
2146
2148
2150
2152
2154
2156
2158
2160
2162
2164
2166
2168
2170
2172
2174
2176
2178
2180
2182
2184
2186
2188
2190
2192
2194
2196
2198
2200
2202
2204
2206
2208
2210
2212
2214
2216
2218
2220
2222
2224
2226
2228
2230
2232
2234
2236
2238
2240
2242
2244
2246
2248
2250
2252
2254
2256
2258
2260
2262
2264
2266
2268
2270
2272
2274
2276
2278
2280
2282
2284
2286
2288
2290
2292
2294
2296
2298
2300
2302
2304
2306
2308
2310
2312
2314
2316
2318
2320
2322
2324
2326
2328
2330
2332
2334
2336
2338
2340
2342
2344
2346
2348
2350
2352
2354
2356
2358
2360
2362
2364
2366
2368
2370
2372
2374
2376
2378
2380
2382
2384
2386
2388
2390
2392
2394
2396
2398
2400
2402
2404
2406
2408
2410
2412
2414
2416
2418
2420
2422
2424
2426
2428
2430
2432
2434
2436
2438
2440
2442
2444
2446
2448
2450
2452
2454
2456
2458
2460
2462
2464
2466
2468
2470
2472
2474
2476
2478
2480
2482
2484
2486
2488
2490
2492
2494
2496
2498
2500
2502
2504
2506
2508
2510
2512
2514
2516
2518
2520
2522
2524
2526
2528
2530
2532
2534
2536
2538
2540
2542
2544
2546
2548
2550
2552
2554
2556
2558
2560
2562
2564
2566
2568
2570
2572
2574
2576
2578
2580
2582
2584
2586
2588
2590
2592
2594
2596
2598
2600
2602
2604
2606
2608
2610
2612
2614
2616
2618
2620
2622
2624
2626
2628
2630
2632
2634
2636
2638
2640
2642
2644
2646
2648
2650
2652
2654
2656
2658
2660
2662
2664
2666
2668
2670
2672
2674
2676
2678
2680
2682
2684
2686
2688
2690
2692
2694
2696
2698
2700
2702
2704
2706
2708
2710
2712
2714
2716
2718
2720
2722
2724
2726
2728
2730
2732
2734
2736
2738
2740
2742
2744
2746
2748
2750
2752
2754
2756
2758
2760
2762
2764
2766
2768
2770
2772
2774
2776
2778
2780
2782
2784
2786
2788
2790
2792
2794
2796
2798
2800
2802
2804
2806
2808
2810
2812
2814
2816
2818
2820
2822
2824
2826
2828
2830
2832
2834
2836
2838
2840
2842
2844
2846
2848
2850
2852
2854
2856
2858
2860
2862
2864
2866
2868
2870
2872
2874
2876
2878
2880
2882
2884
2886
2888
2890
2892
2894
2896
2898
2900
2902
2904
2906
2908
2910
2912
2914
2916
2918
2920
2922
2924
2926
2928
2930
2932
2934
2936
2938
2940
2942
2944
2946
2948
2950
2952
2954
2956
2958
2960
2962
2964
2966
2968
2970
2972
2974
2976
2978
2980
2982
2984
2986
2988
2990
2992
2994
2996
2998
3000
3002
3004
3006
3008
3010
3012
3014
3016
3018
3020
3022
3024
3026
3028
3030
3032
3034
3036
3038
3040
3042
3044
3046
3048
3050
3052
3054
3056
3058
3060
3062
3064
3066
3068
3070
3072
3074
3076
3078
3080
3082
3084
3086
3088
3090
3092
3094
3096
3098
3100
3102
3104
3106
3108
3110
3112
3114
3116
3118
3120
3122
3124
3126
3128
3130
3132
3134
3136
3138
3140
3142
3144
3146
3148
3150
3152
3154
3156
3158
3160
3162
3164
3166
3168
3170
3172
3174
3176
3178
3180
3182
3184
3186
3188
3190
3192
3194
3196
3198
3200
3202
3204
3206
3208
3210
3212
3214
3216
3218
3220
3222
3224
3226
3228
3230
3232
3234
3236
3238
3240
3242
3244
3246
3248
3250
3252
3254
3256
3258
3260
3262
3264
3266
3268
3270
3272
3274
3276
3278
3280
3282
3284
3286
3288
3290
3292
3294
3296
3298
3300
3302
3304
3306
3308
3310
3312
3314
3316
3318
3320
3322
3324
3326
3328
3330
3332
3334
3336
3338
3340
3342
3344
3346
3348
3350
3352
3354
3356
3358
3360
3362
3364
3366
3368
3370
3372
3374
3376
3378
3380
3382
3384
3386
3388
3390
3392
3394
3396
3398
3400
3402
3404
3406
3408
3410
3412
3414
3416
3418
3420
3422
3424
3426
3428
3430
3432
3434
3436
3438
3440
3442
3444
3446
3448
3450
3452
3454
3456
3458
3460
3462
3464
3466
3468
3470
3472
3474
3476
3478
3480
3482
3484
3486
3488
3490
3492
3494
3496
3498
3500
3502
3504
3506
3508
3510
3512
3514
3516
3518
3520
3522
3524
3526
3528
3530
3532
3534
3536
3538
3540
3542
3544
3546
3548
3550
3552
3554
3556
3558
3560
3562
3564
3566
3568
3570
3572
3574
3576
3578
3580
3582
3584
3586
3588
3590
3592
3594
3596
3598
3600
3602
3604
3606
3608
3610
3612
3614
3616
3618
3620
3622
3624
3626
3628
3630
3632
3634
3636
3638
3640
3642
3644
3646
3648
3650
3652
3654
3656
3658
3660
3662
3664
3666
3668
3670
3672
3674
3676
3678
3680
3682
3684
3686
3688
3690
3692
3694
3696
3698
3700
3702
3704
3706
3708
3710
3712
3714
3716
3718
3720
3722
3724
3726
3728
3730
3732
3734
3736
3738
3740
3742
3744
3746
3748
3750
3752
3754
3756
3758
3760
3762
3764
3766
3768
3770
3772
3774
3776
3778
3780
3782
3784
3786
3788
3790
3792
3794
3796
3798
3800
3802
3804
3806
3808
3810
3812
3814
3816
3818
3820
3822
3824
3826
3828
3830
3832
3834
3836
3838
3840
3842
3844
3846
3848
3850
3852
3854
3856
3858
3860
3862
3864
3866
3868
3870
3872
3874
3876
3878
3880
3882
3884
3886
3888
3890
3892
3894
3896
3898
3900
3902
3904
3906
3908
3910
3912
3914
3916
3918
3920
3922
3924
3926
3928
3930
3932
3934
3936
3938
3940
3942
3944
3946
3948
3950
3952
3954
3956
3958
3960
3962
3964
3966
3968
3970
3972
3974
3976
3978
3980
3982
3984
3986
3988
3990
3992
3994
3996
3998
4000
4002
4004
4006
4008
4010
4012
4014
4016
4018
4020
4022
4024
4026
4028
4030
4032
4034
4036
4038
4040
4042
4044
4046
4048
4050
4052
4054
4056
4058
4060
4062
4064
4066
4068
4070
4072
4074
4076
4078
4080
4082
4084
4086
4088
4090
4092
4094
4096
4098
4100
4102
4104
4106
4108
4110
4112
4114
4116
4118
4120
4122
4124
4126
4128
4130
4132
4134
4136
4138
4140
4142
4144
4146
4148
4150
4152
4154
4156
4158
4160
4162
4164
4166
4168
4170
4172
4174
4176
4178
4180
4182
4184
4186
4188
4190
4192
4194
4196
4198
4200
4202
4204
4206
4208
4210
4212
4214
4216
4218
4220
4222
4224
4226
4228
4230
4232
4234
4236
4238
4240
4242
4244
4246
4248
4250
4252
4254
4256
4258
4260
4262
4264
4266
4268
4270
4272
4274
4276
4278
4280
4282
4284
4286
4288
4290
4292
4294
4296
4298
4300
4302
4304
4306
4308
4310
4312
4314
4316
4318
4320
4322
4324
4326
4328
4330
4332
4334
4336
4338
4340
4342
4344
4346
4348
4350
4352
4354
4356
4358
4360
4362
4364
4366
4368
4370
4372
4374
4376
4378
4380
4382
4384
4386
4388
4390
4392
4394
4396
4398
4400
4402
4404
4406
4408
4410
4412
4414
4416
4418
4420
4422
4424
4426
4428
4430
4432
4434
4436
4438
4440
4442
4444
4446
4448
4450
4452
4454
4456
4458
4460
4462
4464
4466
4468
4470
4472
4474
4476
4478
4480
4482
4484
4486
4488
4490
4492
4494
4496
4498
4500
4502
4504
4506
4508
4510
4512
4514
4516
4518
4520
4522
4524
4526
4528
4530
4532
4534
4536
4538
4540
4542
4544
4546
4548
4550
4552
4554
4556
4558
4560
4562
4564
4566
4568
4570
4572
4574
4576
4578
4580
4582
4584
4586
4588
4590
4592
4594
4596
4598
4600
4602
4604
4606
4608
4610
4612
4614
4616
4618
4620
4622
4624
4626
4628
4630
4632
4634
4636
4638
4640
4642
4644
4646
4648
4650
4652
4654
4656
4658
4660
4662
4664
4666
4668
4670
4672
4674
4676
4678
4680
4682
4684
4686
4688
4690
4692
4694
4696
4698
4700
4702
4704
4706
4708
4710
4712
4714
4716
4718
4720
4722
4724
4726
4728
4730
4732
4734
4736
4738
4740
4742
4744
4746
4748
4750
4752
4754
4756
4758
4760
4762
4764
4766
4768
4770
4772
4774
4776
4778
4780
4782
4784
4786
4788
4790
4792
4794
4796
4798
4800
4802
4804
4806
4808
4810
4812
4814
4816
4818
4820
4822
4824
4826
4828
4830
4832
4834
4836
4838
4840
4842
4844
4846
4848
4850
4852
4854
4856
4858
4860
4862
4864
4866
4868
4870
4872
4874
4876
4878
4880
4882
4884
4886
4888
4890
4892
4894
4896
4898
4900
4902
4904
4906
4908
4910
4912
4914
4916
4918
4920
4922
4924
4926
4928
4930
4932
4934
4936
4938
4940
4942
4944
4946
4948
4950
4952
4954
4956
4958
4960
4962
4964
4966
4968
4970
4972
4974
4976
4978
4980
4982
4984
4986
4988
4990
4992
4994
4996
4998
5000
5002
5004
5006
5008
5010
5012
5014
5016
5018
5020
5022
5024
5026
5028
5030
5032
5034
5036
5038
5040
5042
5044
5046
5048
5050
5052
5054
5056
5058
5060
5062
5064
5066
5068
5070
5072
5074
5076
5078
5080
5082
5084
5086
5088
5090
5092
5094
5096
5098
5100
5102
5104
5106
5108
5110
5112
5114
5116
5118
5120
5122
5124
5126
5128
5130
5132
5134
5136
5138
5140
5142
5144
5146
5148
5150
5152
5154
5156
5158
5160
5162
5164
5166
5168
5170
5172
5174
5176
5178
5180
5182
5184
5186
5188
5190
5192
5194
5196
5198
5200
5202
5204
5206
5208
5210
5212
5214
5216
5218
5220
5222
5224
5226
5228
5230
5232
5234
5236
5238
5240
5242
5244
5246
5248
5250
5252
5254
5256
5258
5260
5262
5264
5266
5268
5270
5272
5274
5276
5278
5280
5282
5284
5286
5288
5290
5292
5294
5296
5298
5300
5302
5304
5306
5308
5310
5312
5314
5316
5318
5320
5322
5324
5326
5328
5330
5332
5334
5336
5338
5340
5342
5344
5346
5348
5350
5352
5354
5356
5358
5360
5362
5364
5366
5368
5370
5372
5374
5376
5378
5380
5382
5384
5386
5388
5390
5392
5394
5396
5398
5400
5402
5404
5406
5408
5410
5412
5414
5416
5418
5420
5422
5424
5426
5428
5430
5432
5434
5436
5438
5440
5442
5444
5446
5448
5450
5452
5454
5456
5458
5460
5462
5464
5466
5468
5470
5472
5474
5476
5478
5480
5482
5484
5486
5488
5490
5492
5494
5496
5498
5500
5502
5504
5506
5508
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100
102
104
106
108
110
112
114
116
118
120
122
124
126
128
130
132
134
136
138
140
142
144
146
148
150
152
154
156
158
160
162
164
166
168
170
172
174
176
178
180
182
184
186
188
190
192
194
196
198
200
202
204
206
208
210
212
214
216
218
220
222
224
226
228
230
232
234
236
238
240
242
244
246
248
250
252
254
256
258
260
262
264
266
268
270
272
274
276
278
280
282
284
286
288
290
292
294
296
298
300
302
304
306
308
310
312
314
316
318
320
322
324
326
328
330
332
334
336
338
340
342
344
346
348
350
352
354
356
358
360
362
364
366
368
370
372
374
376
378
380
382
384
386
388
390
392
394
396
398
400
402
404
406
408
410
412
414
416
418
420
422
424
426
428
430
432
434
436
438
440
442
444
446
448
450
452
454
456
458
460
462
464
466
468
470
472
474
476
478
480
482
484
486
488
490
492
494
496
498
500
502
504
506
508
510
512
514
516
518
520
522
524
526
528
530
532
534
536
538
540
542
544
546
548
550
552
554
556
558
560
562
564
566
568
570
572
574
576
578
580
582
584
586
588
590
592
594
596
598
600
602
604
606
608
610
612
614
616
618
620
622
624
626
628
630
632
634
636
638
640
642
644
646
648
650
652
654
656
658
660
662
664
666
668
670
672
674
676
678
680
682
684
686
688
690
692
694
696
698
700
702
704
706
708
710
712
714
716
718
720
722
724
726
728
730
732
734
736
738
740
742
744
746
748
750
752
754
756
758
760
762
764
766
768
770
772
774
776
778
780
782
784
786
788
790
792
794
796
798
800
802
926
928
930
932
934
936
938
940
942
944
946
948
950
952
954
956
958
960
962
964
966
968
970
972
974
976
978
980
982
984
986
988
990
992
994
996
998
1000
1002
1004
1006
1008
1010
1012
1014
1016
1018
1020
1022
1024
1026
1028
1030
1032
1034
1036
1038
1040
1042
1044
1046
1048
1050
1052
1054
1056
1058
1060
1062
1064
1066
1068
1070
1072
1074
1076
1078
1080
1082
1084
1086
1088
1090
1092
1094
1096
1098
1100
1102
1104
1106
1108
1110
1112
1114
1116
1118
1120
1122
1124
1126
1128
1130
1132
1134
1136
1138
1140
1142
1144
1146
1148
1150
1152
1154
1156
1158
1160
1162
1164
1166
1168
1170
1172
1174
1176
1178
1180
1182
1184
1186
1188
1190
1192
1194
1196
1198
1200
1202
1204
1206
1208
1210
1212
1214
1216
1218
1220
1222
1224
1226
1228
1230
1232
1234
1236
1238
1240
1242
1244
1246
1248
1250
1252
1254
1256
1258
1260
1262
1264
1266
1268
1270
1272
1274
1276
1278
1280
1282
1284
1286
1288
1290
1292
1294
1296
1298
1300
1302
1304
1306
1308
1310
1312
1314
1316
1318
1320
1322
1324
1326
1328
1330
1332
1334
1336
1338
1340
1342
1344
1346
1348
1350
1352
1354
1356
1358
1360
1362
1364
1366
1368
1370
1372
1374
1376
1378
1380
1382
1384
1386
1388
1390
1392
1394
1396
1398
1400
1402
1404
1406
1408
1410
1412
1414
1416
1418
1420
1422
1424
1426
1428
1430
1432
1434
1436
1438
1440
1442
1444
1446
1448
1450
1452
1454
1456
1458
1460
1462
1464
1466
1468
1470
1472
1474
1476
1478
1480
1482
1484
1486
1488
1490
1492
1494
1496
1498
1500
1502
1504
1506
1508
1510
1512
1514
1516
1518
1520
1522
1524
1526
1528
1530
1532
1534
1536
1538
1540
1542
1544
1546
1548
1550
1552
1554
1556
1558
1560
1562
1564
1566
1568
1570
1572
1574
1576
1578
1580
1582
1584
1586
1588
1590
1592
1594
1596
1598
1600
1602
1604
1606
1608
1610
1612
1614
1616
1618
1620
1622
1624
1626
1628
1630
1632
1634
1636
1638
1640
1642
1644
1646
1648
1650
1652
1654
1656
1658
1660
1662
1664
1666
1668
1670
1672
1674
1676
1678
1680
1682
1684
1686
1688
1690
1692
1694
1696
1698
1700
1702
1704
1706
1708
1710
1712
1714
1716
1718
1720
1722
1724
1726
1728
1730
1732
1734
1736
1738
1740
1742
1744
1746
1748
1750
1752
1754
1756
1758
1760
1762
1764
1766
1768
1770
1772
1774
1776
1778
1780
1782
1784
1786
1788
1790
1792
1794
1796
1798
1800
1802
1804
1806
1808
1810
1812
1814
1816
1818
1820
1822
1824
1826
1828
1830
1832
1834
1836
1838
1840
1842
1844
1846
1848
1850
1852
1854
1856
1858
1860
1862
1864
1866
1868
1870
1872
1874
1876
1878
1880
1882
1884
1886
1888
1890
1892
1894
1896
1898
1900
1902
1904
1906
1908
1910
1912
1914
1916
1918
1920
1922
1924
1926
1928
1930
1932
1934
1936
1938
1940
1942
1944
1946
1948
1950
1952
1954
1956
1958
1960
1962
1964
1966
1968
1970
1972
1974
1976
1978
1980
1982
1984
1986
1988
1990
1992
1994
1996
1998
2000
2002
2004
2006
2008
2010
2012
2014
2016
2018
2020
2022
2024
2026
2028
2030
2032
2034
2036
2038
2040
2042
2044
2046
2048
2050
2052
2054
2056
2058
2060
2062
2064
2066
2068
2070
2072
2074
2076
2078
2080
2082
2084
2086
2088
2090
2092
2094
2096
2098
2100
2102
2104
2106
2108
2110
2112
2114
2116
2118
2120
2122
2124
2126
2128
2130
2132
2134
2136
2138
2140
2142
2144
2146
2148
2150
2152
2154
2156
2158
2160
2162
2164
2166
2168
2170
2172
2174
2176
2178
2180
2182
2184
2186
2188
2190
2192
2194
2196
2198
2200
2202
2204
2206
2208
2210
2212
2214
2216
2218
2220
2222
2224
2226
2228
2230
2232
2234
2236
2238
2240
2242
2244
2246
2248
2250
2252
2254
2256
2258
2260
2262
2264
2266
2268
2270
2272
2274
2276
2278
2280
2282
2284
2286
2288
2290
2292
2294
2296
2298
2300
2302
2304
2306
2308
2310
2312
2314
2316
2318
2320
2322
2324
2326
2328
2330
2332
2334
2336
2338
2340
2342
2344
2346
2348
2350
2352
2354
2356
2358
2360
2362
2364
2366
2368
2370
2372
2374
2376
2378
2380
2382
2384
2386
2388
2390
2392
2394
2396
2398
2400
2402
2404
2406
2408
2410
2412
2414
2416
2418
2420
2422
2424
2426
2428
2430
2432
2434
2436
2438
2440
2442
2444
2446
2448
2450
2452
2454
2456
2458
2460
2462
2464
2466
2468
2470
2472
2474
2476
2478
2480
2482
2484
2486
2488
2490
2492
2494
2496
2498
2500
2502
2504
2506
2508
2510
2512
2514
2516
2518
2520
2522
2524
2526
2528
2530
2532
2534
2536
2538
2540
2542
2544
2546
2548
2550
2552
2554
2556
2558
2560
2562
2564
2566
2568
2570
2572
2574
2576
2578
2580
2582
2584
2586
2588
2590
2592
2594
2596
2598
2600
2602
2604
2606
2608
2610
2612
2614
2616
2618
2620
2622
2624
2626
2628
2630
2632
2634
2636
2638
2640
2642
2644
2646
2648
2650
2652
2654
2656
2658
2660
2662
2664
2666
2668
2670
2672
2674
2676
2678
2680
2682
2684
2686
2688
2690
2692
2694
2696
2698
2700
2702
2704
2706
2708
2710
2712
2714
2716
2718
2720
2722
2724
2726
2728
2730
2732
2734
2736
2738
2740
2742
2744
2746
2748
2750
2752
2754
2756
2758
2760
2762
2764
2766
2768
2770
2772
2774
2776
2778
2780
2782
2784
2786
2788
2790
2792
2794
2796
2798
2800
2802
2804
2806
2808
2810
2812
2814
2816
2818
2820
2822
2824
2826
2828
2830
2832
2834
2836
2838
2840
2842
2844
2846
2848
2850
2852
2854
2856
2858
2860
2862
2864
2866
2868
2870
2872
2874
2876
2878
2880
2882
2884
2886
2888
2890
2892
2894
2896
2898
2900
2902
2904
2906
2908
2910
2912
2914
2916
2918
2920
2922
2924
2926
2928
2930
2932
2934
2936
2938
2940
2942
2944
2946
2948
2950
2952
2954
2956
2958
2960
2962
2964
2966
2968
2970
2972
2974
2976
2978
2980
2982
2984
2986
2988
2990
2992
2994
2996
2998
3000
3002
3004
3006
3008
3010
3012
3014
3016
3018
3020
3022
3024
3026
3028
3030
3032
3034
3036
3038
3040
3042
3044
3046
3048
3050
3052
3054
3056
3058
3060
3062
3064
3066
3068
3070
3072
3074
3076
3078
3080
3082
3084
3086
3088
3090
3092
3094
3096
3098
3100
3102
3104
3106
3108
3110
3112
3114
3116
3118
3120

In [126]:
# Check if the isolate (or other) is in the keys of the dictionary made above
to_check = []
to_remove_from_gisaid = []

for key in isolates.keys():
    for isolate in isolates[key]:
        to_check.append(isolate[1])

to_check2 = []
for key in andersen_isolates.keys():
    for isolate in andersen_isolates[key]:
        to_check2.append(isolate[0])
        # print(isolate[0])

to_check = list(set(to_check))
to_check2 = list(set(to_check2))

print(len(to_check))
print(len(to_check2))

print(to_check2[100])

for c in to_check:
    for cc in to_check2:
        if cc in c: # and c not in to_remove_from_gisaid:
            to_remove_from_gisaid.append(c)

to_remove_from_gisaid = list(set(to_remove_from_gisaid))
# for i in andersen_isolates[andersen_isolate]:
# print(andersen_isolates[andersen_isolate][0])
    # print(isolate[1])
    # if isolate[1] == c and c not in to_remove_from_gisaid: # We've seen it -- first is the isolate number
    # # print(isolate[1])
    #     # print(c)
    #     to_remove_from_gisaid.append(c) # Second is the actual header

print((andersen_isolates["D1.1_PB2"][0][1]))
print(to_remove_from_gisaid[0])
print(len(to_remove_from_gisaid))

print(len(isolates["B3.13_HA"]))

# Remove it from the list
give_to_andersen = {}
for key in isolates.keys():
    list_of_fastas = isolates[key]
    # print(list_of_fastas)
    # break
    for index, fasta in enumerate(list_of_fastas):
        # print(fasta)
        # break
        for num, header in enumerate(to_remove_from_gisaid):
            if fasta[1] == header and fasta[1] == fasta[1]: # If it's in the to_remove list and not nan
                # print(num, " remove: ", header)
                try:
                    del list_of_fastas[index]
                except:
                    "Cannot remove something that doesn't exist."
    give_to_andersen[key] = list_of_fastas
    # print(len(list_of_fastas))

    # print(list_of_fastas[0])

# print(give_to_andersen["B3.13_HA"])
print(len(give_to_andersen["B3.13_HA"]))

2398
3041
017584-009
>A/Chicken/WA/24-032809-002/2024|H5N1|05-Nov-2024|avian|D1.1

>A/turkey/Wisconsin/038658-001/2024|H5N1|2024-12-24|avian|D1.1

834
783
602

In [127]:
print(len(give_to_andersen["B3.13_HA"]))
print(len(isolates["B3.13_HA"]))
print(len(to_remove_from_gisaid))
print(len(andersen_isolates["B3.13_HA"]))

602
602
834
2694

In [128]:
print(len(fasta_files["B3.13_HA"]))

2755

In [129]:
for key in give_to_andersen.keys():
    for value in give_to_andersen[key]:
        andersen_isolates[key].append(value)

print(len(andersen_isolates["B3.13_HA"]))

3296

In [134]:
# Create fasta files 
os.chdir(complete_files)
for pair in andersen_isolates.keys():
    output_path = complete_files + pair + ".fasta" 

    output_file = open(output_path, "w")
    for item in andersen_isolates[pair]:
        # for item in item:
        # item = fasta_files[pair]
        try:
            name = str(item[1].values[0]) # See if this is one we didn't have a collection date for
        except:
            name = str(item[1])
        # print(name)
        # First is header, second is sequence
        # print(value)
        output_file.write(name)
        output_file.write(item[2])
    output_file.close()

In [ ]:
# def search_collection_date(biosample):
    
#     base_url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
#     search_url = base_url + "esearch.fcgi?db=biosample&term=" + biosample +"&usehistory=y&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

#     # Get Biosample ID from search_url
#     output = requests.get(search_url)
#     xml = output.content
#     root = ET.fromstring(xml)
#     sample_id = root.find("./IdList/Id").text

#     biosample_url = base_url + "elink.fcgi?dbfrom=biosample&db=nuccore&id=" + sample_id + "&cmd=neighbor_history&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"
    
#     # Get Nucleotide ID from biosample_url
#     output = requests.get(biosample_url)
#     xml = output.content
#     root = ET.fromstring(xml)
#     query_key = root.find(".//QueryKey").text
#     web_env = root.find(".//WebEnv").text

#     nucleotide_url = base_url + "esummary.fcgi?db=nuccore&query_key=" + query_key + "&WebEnv=" + web_env + "&version=2.0&api_key=2cbaf77ac9ec5ae7844ea350076ae6d56809"

#     output = requests.get(nucleotide_url) 
#     xml = output.content
#     root = ET.fromstring(xml)

#     # Grab collection date at the end of the sub name
#     collection_date = root.find(".//SubName").text.split("|")[-1]

#     # Avoid spamming the server
#     time.sleep(3)
    
#     return collection_date

In [ ]:
# example = search_collection_date("SAMN41019216")
# print(example)

In [ ]:

# unique_animals_all = sort_animals_anderson(metadata_new)

# # Flatten unique_animals
# every_unique_animal = []
# for animal in unique_animals_all:
#     every_unique_animal.append(animal)

# print(every_unique_animal)

# unique_animals_set = list(set(every_unique_animal))
# # animals_df = pd.DataFrame(columns=["avian", "cattle", "feline", "other_mammal", "human", "other"])
# # animals_df["other"] = unique_animals_set # to sort

# os.chdir(downloads)

# animals_ref = pd.read_csv("animals_ref.csv")


# # If animal not in ref1, put in ref2

# common_animals = []
# # Check if animals in unique_animals_set are in ref1
# for animal in unique_animals_set:
#     for col in animals_ref.columns:
#         if animal in animals_ref[col].values and type(animal) == str:
#             common_animals.append(animal)

# print(common_animals)
# print(len(common_animals))

# different_animals = []
# for animal in unique_animals_set:
#     if animal not in common_animals:
#         different_animals.append(animal)

# print(different_animals)

# # Add to dataframe
# animals_df = animals_ref
# # Make different_animals same length as dataframe, if shorter
# if len(different_animals) < len(animals_df):
#     number_of_times_to_add_nan = len(animals_df) - len(different_animals)
#     for i in range(number_of_times_to_add_nan):
#         different_animals.append(float('nan'))
# # If longer, deal with that later

# animals_df["new"] = (different_animals)

# print(animals_df)

# animals_df.to_csv("animals_ref_to_sort.csv")