# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI, by de-duplicating from Andersen/GISAID, and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import re
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [2]:
# Paths

# Dates
start_date = "04-14-2025"
end_date = "06-13-2025"
date_range = start_date + "--" + end_date
update_date = "06-16-2025"
genotypes = ["D1.1", "B3.2", "B3.6", "B3.13", "A3"]

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = home + "NCBI_Virus/downloads/" + date_range + "/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "/" # + "_B3_13/"
# gisaid_andersen = home + "Cats/Datasets/GISAID_Andersen/GISAID_Andersen_cats_only_6_5_2025/"
# combined_files = home + "Cats/Datasets/GISAID_Andersen_NCBI_Virus/cat_genotypes_" + update_date + "/" # 04-14-2025--06-05-2025"
gisaid_andersen = home + "Combinations/GISAID_Andersen/" # + date_range + "_" # B3_13/"
combined_files = home + "Combinations/GISAID_Andersen_NCBI_Virus/" # + update_date + "_B3_13/"
references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"
# references = "C:/Users/maksi/Documents/Statistics/projects/Avian_Flu/references/"

os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

os.chdir(downloads)

## De-Duplication

In [3]:
metadata = pd.read_csv("sequences.csv")

print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.SRA_Accession, as_index=False).size()

print(metadata_counts)

metadata_counted = metadata.merge(metadata_counts, on="SRA_Accession")

# Only keep those with size=8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates

metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="first") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]

metadata_segments

5751
    SRA_Accession  size
0     SRR30811257     8
1     SRR31254292     8
2     SRR31254312     8
3     SRR31254355     8
4     SRR31254366     8
..            ...   ...
644   SRR33508855     8
645   SRR33508856     8
646   SRR33508857     8
647   SRR33508858     8
648   SRR33508859     8

[649 rows x 2 columns]

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV709274.1,Influenza A virus,GenBank,NaN,SRR33369776,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,25-012798-008-original,...,1,USA: NY,NY,Anatidae,feces,2025-04-16,SAMN48199761,PRJNA980729,Influenza A virus (A/Duck/NY/25-012798-008-ori...,8
1,PV709275.1,Influenza A virus,GenBank,NaN,SRR33369776,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,25-012798-008-original,...,2,USA: NY,NY,Anatidae,feces,2025-04-16,SAMN48199761,PRJNA980729,Influenza A virus (A/Duck/NY/25-012798-008-ori...,8
2,PV709276.1,Influenza A virus,GenBank,NaN,SRR33369776,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,25-012798-008-original,...,3,USA: NY,NY,Anatidae,feces,2025-04-16,SAMN48199761,PRJNA980729,Influenza A virus (A/Duck/NY/25-012798-008-ori...,8
3,PV709277.1,Influenza A virus,GenBank,NaN,SRR33369776,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,25-012798-008-original,...,4,USA: NY,NY,Anatidae,feces,2025-04-16,SAMN48199761,PRJNA980729,Influenza A virus (A/Duck/NY/25-012798-008-ori...,8
4,PV709278.1,Influenza A virus,GenBank,NaN,SRR33369776,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,25-012798-008-original,...,5,USA: NY,NY,Anatidae,feces,2025-04-16,SAMN48199761,PRJNA980729,Influenza A virus (A/Duck/NY/25-012798-008-ori...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5187,PV494554.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,4,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5188,PV494555.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,5,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5189,PV494556.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,6,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5190,PV494557.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,7,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5191,PV494558.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,8,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8

In [5]:
# De-duplicate from Andersen/GISAID using isolate

# If even one isolate in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
gisaid_isolates = []
andersen_isolates = []
# Grab files
for genotype in genotypes:
    # print(gisaid_andersen + genotype.replace(".", "_") + "/")
    for dirpath, dirs, files in os.walk(gisaid_andersen + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "/"):
        for file in files:
            file_name = os.path.join(dirpath, file)
            # print(file_name)
            if ".fasta" in file_name:
                fasta_file = fasta_df(file_name, states_ref) # Convert fasta file to dataframe
                print(fasta_file)
                # isolates = fasta_file["Isolate_Name"].apply(lambda x: x.split("/")[3])
                isolates = fasta_file["Isolate_Id"]
                for index, value in isolates.items():
                    gisaid_isolates.append(value)

                isolate_ids = fasta_file["Identifier"]
                for index, value in isolates.items():
                    if "SRR" in value:
                        andersen_isolates.append(value)
            
        break 

gisaid_isolates = list(set(gisaid_isolates))

print(len(gisaid_isolates))
print(gisaid_isolates)

['A', 'CATTLE', 'USA', '25-006783-001', '2025']
['A', 'QUAIL', 'USA', '25-006346-009', '2025']
['A', 'DUCK', 'USA', '25-007078-002', '2025']
['A', 'DUCK', 'USA', '25-007078-001', '2025']
['A', 'DUCK', 'USA', '25-006674-002', '2025']
['A', 'CHICKEN', 'USA', '25-007056-001', '2025']
['A', 'CHICKEN', 'USA', '25-006346-008', '2025']
['A', 'CHICKEN', 'USA', '25-006346-007', '2025']
['A', 'CHICKEN', 'USA', '25-006346-004', '2025']
['A', 'DUCK', 'USA', '25-004480-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-005869-001', '2025']
['A', 'CAT', 'USA', '25-006047-001', '2025']
['A', 'CANADA GOOSE', 'USA', '25-004415-006', '2025']
['A', 'CANADA GOOSE', 'USA', '25-004376-001', '2025']
['A', 'CANADA GOOSE', 'USA', '25-002735-001', '2025']
['A', 'MALLARD', 'USA', '25-005927-005', '2025']
['A', 'MALLARD', 'USA', '25-005882-005', '2025']
['A', 'HOODED MERGANSER', 'USA', '25-005880-001', '2025']
['A', 'GLAUCOUS GULL', 'USA', '25-004499-006', '2025']
['A', 'GADWALL', 'USA', '25-005882-002', '2025']
['A', 'BLACK VULTURE', 'USA', '25-006120-003', '2025']
['A', 'BLACK VULTURE', 'USA', '25-005756-005', '2025']
['A', 'BLACK VULTURE', 'USA', '25-005756-004', '2025']
['A', 'BLACK VULTURE', 'USA', '25-005754-005', '2025']
['A', 'BLACK VULTURE', 'USA', '25-005754-004', '2025']
['A', 'BLACK VULTURE', 'USA', '25-004339-009', '2025']
['A', 'BLUE JAY', 'USA', '25-005880-002', '2025']
['A', 'WESTERN GULL', 'USA', '25-004499-004', '2025']
['A', 'WESTERN GULL', 'USA', '25-004493-002', '2025']
['A', 'SNOW GOOSE', 'USA', '25-006183-002', '2025']
['A', 'SNOW GOOSE', 'USA', '25-005870-001', '2025']
['A', 'SNOWY EGRET', 'USA', '25-004423-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-004415-001', '2025']
['A', 'MALLARD', 'USA', '25-006143-013', '2025']
['A', 'MALLARD', 'USA', '25-006143-011', '2025']
['A', 'MALLARD', 'USA', '25-006143-002', '2025']
['A', 'MALLARD', 'USA', '25-006143-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-004422-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-004420-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-006401-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-006343-001', '2025']
['A', 'MALLARD X AMERICAN BLACK DUCK HYBRID', 'USA', '25-004433-002', '2025']
['A', 'MALLARD X AMERICAN BLACK DUCK HYBRID', 'USA', '25-006143-061', '2025']
['A', 'MALLARD', 'USA', '25-004376-002', '2025']
['A', 'MALLARD', 'USA', '25-006144-064', '2025']
['A', 'MALLARD', 'USA', '25-006144-060', '2025']
['A', 'MALLARD', 'USA', '25-006144-059', '2025']
['A', 'MALLARD', 'USA', '25-006144-052', '2025']
['A', 'MALLARD', 'USA', '25-006144-034', '2025']
['A', 'MALLARD', 'USA', '25-006144-025', '2025']
['A', 'MALLARD', 'USA', '25-006144-010', '2025']
['A', 'MALLARD', 'USA', '25-006143-057', '2025']
['A', 'MALLARD', 'USA', '25-006143-049', '2025']
['A', 'MALLARD', 'USA', '25-006143-043', '2025']
['A', 'BALD EAGLE', 'USA', '25-006329-001', '2025']
['A', 'MALLARD', 'USA', '25-006143-036', '2025']
['A', 'MALLARD', 'USA', '25-006143-019', '2025']
['A', 'MALLARD', 'USA', '25-006143-018', '2025']
['A', 'BALD EAGLE', 'USA', '25-006328-004', '2025']
['A', 'CHICKEN', 'USA', '25-011483-006', '2025']
['A', 'BLACK VULTURE', 'USA', '25-011728-001', '2025']
['A', 'SNOW GOOSE', 'USA', '25-011281-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-011728-003', '2025']
['A', 'SKUNK', 'USA', '25-011119-002', '2025']
['A', 'SKUNK', 'USA', '25-010819-004', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-011426-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-011418-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-011104-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-010338-003', '2025']
['A', 'BALD EAGLE', 'USA', '25-011024-006', '2025']
['A', 'RED-BREASTED MERGANSER', 'USA', '25-011271-008', '2025']
['A', 'Duck', 'USA', '25-012397-002', '2025']
['A', 'MALLARD', 'USA', '25-012246-013', '2025']
['A', 'MALLARD', 'USA', '25-012246-029', '2025']
['A', 'TURKEY VULTURE', 'USA', '25-012249-001', '2025']
['A', 'TRUMPETER SWAN', 'USA', '25-011816-001', '2025']
['A', 'SNOWY OWL', 'USA', '25-012050-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-012740-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-012058-002', '2025']
['A', 'CAT', 'USA', '25-012358-001', '2025']
['A', 'CANADA GOOSE', 'USA', '25-007071-002', '2025']
['A', 'CANADA GOOSE', 'USA', '25-012052-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-007118-047', '2025']
['A', 'BLACK VULTURE', 'USA', '25-012059-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-011842-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-012508-002', '2025']
['A', 'BALD EAGLE', 'USA', '25-008467-001', '2025']
['A', 'GUINEA', 'USA', '25-013275-005', '2025']
['A', 'SNOW GOOSE', 'USA', '25-012827-001', '2025']
['A', 'RACCOON', 'USA', '25-012811-001', '2025']
['A', "COOPER'S HAWK", 'USA', '25-012813-008', '2025']
['A', 'BARN OWL', 'USA', '25-000514-002', '2025']
['A', 'BALD EAGLE', 'USA', '25-010788-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-010747-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-010570-002', '2025']
['A', 'BALD EAGLE', 'USA', '25-010568-001', '2025']
['A', 'DUCK', 'USA', '25-010532-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-010429-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-005056-002', '2025']
['A', 'CANADA GOOSE', 'USA', '25-005034-001', '2025']
['A', 'SNOW GOOSE', 'USA', '25-005030-001', '2025']
['A', 'RED-BREASTED MERGANSER', 'USA', '25-005001-001', '2025']
['A', 'SKUNK', 'USA', '25-010819-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-004859-001', '2025']
['A', 'GULL', 'USA', '25-003254-007', '2025']
['A', 'CANADA GOOSE', 'USA', '25-003254-006', '2025']
['A', 'WESTERN GULL', 'USA', '25-003254-004', '2025']
['A', 'LESSER SCAUP', 'USA', '25-001543-001', '2025']
['A', 'CANADA GOOSE', 'USA', '25-001541-012', '2025']
['A', 'CANADA GOOSE', 'USA', '25-013428-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-013658-006', '2025']
['A', 'TURKEY VULTURE', 'USA', '25-013490-001', '2025']
['A', 'RED FOX', 'USA', '25-013749-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-013658-004', '2025']
['A', 'TURKEY VULTURE', 'USA', '25-014164-001', '2025']
['A', 'TURKEY VULTURE', 'USA', '25-014160-001', '2025']
['A', 'SAND CRANE', 'USA', '25-014081-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-014162-001', '2025']
['A', 'COMMON MERGANSER', 'USA', '25-014535-012', '2025']
['A', 'COMMON MERGANSER', 'USA', '25-014535-010', '2025']
['A', 'COMMON MERGANSER', 'USA', '25-014535-009', '2025']
['A', 'COMMON MERGANSER', 'USA', '25-014535-008', '2025']
['A', 'COMMON MERGANSER', 'USA', '25-014535-007', '2025']
['A', 'COMMON MERGANSER', 'USA', '25-014535-006', '2025']
['A', 'BOBCAT', 'USA', '25-014574-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-014762-003', '2025']
['A', 'BLACK VULTURE', 'USA', '25-013413-001', '2025']
['A', 'BLACK VULTURE', 'USA', '25-014761-001', '2025']
['A', 'TURKEY', 'USA', '25-015216-002', '2025']
['A', 'TURKEY', 'USA', '25-015216-001', '2025']
['A', 'FOX', 'USA', '25-015209-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-015388-002', '2025']
['A', 'BALD EAGLE', 'USA', '25-013929-001', '2025']
['A', 'CATTLE', 'USA', '25-013772-001', '2025']
['A', 'RED-TAILED HAWK', 'USA', '25-013427-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-015562-001', '2025']
['A', 'BALD EAGLE', 'USA', '25-015759-001', '2025']
['A', 'northern_pintail', 'USA', 'IZ24_0780', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0772', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0763', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0760', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0689', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0684', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0683', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0566', '2024']
['A', 'northern_pintail', 'USA', 'IZ24_0555', '2024']
['A', 'mallard', 'USA', 'IZ24_0675', '2024']
['A', 'American_green-winged_teal', 'USA', 'IZ24_0777', '2024']
['A', 'American_green-winged_teal', 'USA', 'IZ24_0776', '2024']
['A', 'turkey_vulture', 'USA', '014650-001', '2025']
['A', 'turkey_vulture', 'USA', '014690-001', '2025']
['A', 'bald_eagle', 'USA', '014598-004', '2025']
['A', 'black_vulture', 'USA', '013887-001', '2025']
['A', 'bufflehead', 'USA', '014655-003', '2025']
['A', 'common_merganser', 'USA', '014535-002', '2025']
['A', 'cougar', 'USA', '014656-001', '2025']
['A', 'bald_eagle', 'USA', '014542-001', '2025']
['A', 'red-tailed_hawk', 'USA', '012969-001', '2025']
['A', 'cougar', 'USA', '014656-002', '2025']
['A', 'great_blue_heron', 'USA', '014655-001', '2025']
['A', 'owl', 'USA', '014765-001', '2025']
['A', 'falcon', 'USA', '014651-001', '2025']
['A', 'red-tailed_hawk', 'USA', '014532-001', '2025']
['A', 'sanderling', 'USA', '014540-001', '2025']
['A', 'sanderling', 'USA', '014540-002', '2025']
['A', 'snow_goose', 'USA', '014079-003', '2025']
['A', 'turkey_vulture', 'USA', '014161-001', '2025']
['A', 'bald_eagle', 'USA', '014598-002', '2025']
['A', 'British_Columbia', 'PHL-2032-recombinant', '2025']
['A', 'red-tailed_hawk', 'USA', '014530-001', '2025']
['A', 'red-tailed_hawk', 'USA', '014618-001', '2025']
['A', 'turkey_vulture', 'USA', '014056-001', '2025']
['A', 'duck', 'USA', '015044-004', '2025']
['A', 'bald_eagle', 'USA', '014598-001', '2025']
['A', 'snow_goose', 'USA', '014079-001', '2025']
['A', 'turkey_vulture', 'USA', '014165-001', '2025']
['A', 'american_coot', 'USA', '014079-002', '2025']
['A', 'black_vulture', 'USA', '014762-001', '2025']
['A', 'black_vulture', 'USA', '014762-002', '2025']
['A', 'canada_goose', 'USA', '014080-001', '2025']
['A', 'common_merganser', 'USA', '014535-001', '2025']
['A', 'common_merganser', 'USA', '014535-011', '2025']
['A', 'duck', 'USA', '015044-006', '2025']
['A', 'goose', 'USA', '014293-001-R', '2025']
['A', 'black_vulture', 'USA', '014761-003', '2025']
['A', 'common_merganser', 'USA', '014535-004', '2025']
['A', 'great_horned_owl', 'USA', '014531-001', '2025']
['A', 'barred_owl', 'USA', '014163-001', '2025']
['A', 'black_vulture', 'USA', '014761-002', '2025']
['A', 'common_merganser', 'USA', '014535-003', '2025']
['A', 'common_merganser', 'USA', '014535-005', '2025']
['A', 'bald_eagle', 'USA', '014541-002', '2025']
['A', 'falcon', 'USA', '014541-001', '2025']
['A', 'herring_gull', 'USA', '014295-001', '2025']
['A', 'common_goldeneye', 'USA', '013182-002', '2025']
['A', 'great_horned_owl', 'USA', '011271-007', '2025']
['A', 'great_horned_owl', 'USA', '012987-002', '2025']
['A', 'great_horned_owl', 'USA', '012989-004', '2025']
['A', 'herring_gull', 'USA', '011271-010', '2025']
['A', 'red-tailed_hawk', 'USA', '012988-001', '2025']
['A', 'bald_eagle', 'USA', '011271-001', '2025']
['A', 'bald_eagle', 'USA', '011271-002', '2025']
['A', 'canada_goose', 'USA', '013218-002', '2025']
['A', 'western_gull', 'USA', '012995-001', '2025']
['A', 'Unknown', 'Durango', 'CPA-00563-25', '2025']
['A', 'black_vulture', 'USA', '013141-001', '2025']
['A', 'Goose', 'Durango', 'CPA-00444-25', '2025']
['A', 'chicken', 'USA', '013300-001', '2025']
['A', 'partridge', 'USA', '013275-009', '2025']
['A', 'chicken', 'USA', '013149-001', '2025']
['A', 'turkey', 'Iowa', '25-005292-002-R2', '2025']
['A', 'chicken', 'USA', '013149-002', '2025']
['A', 'turkey', 'Iowa', '25-005292-001-R2', '2025']
['A', 'chicken', 'USA', '013275-002', '2025']
['A', 'chicken', 'USA', '013275-007', '2025']
['A', 'chicken', 'USA', '013275-010', '2025']
['A', 'duck', 'USA', '012798-007-R', '2025']
['A', 'duck', 'USA', '013275-004', '2025']
['A', 'western_gull', 'USA', '012993-001', '2025']
['A', 'canada_goose', 'USA', '013305-001', '2025']
['A', 'skunk', 'USA', '012814-001', '2025']
['A', 'skunk', 'USA', '012991-001', '2025']
['A', 'snow_goose', 'USA', '012987-001', '2025']
['A', 'snow_goose', 'USA', '012989-007', '2025']
['A', 'dunlin', 'USA', '012989-001', '2025']
['A', 'great_horned_owl', 'USA', '012989-005', '2025']
['A', 'bald_eagle', 'USA', '011271-003', '2025']
['A', 'falcon', 'USA', '012990-002', '2025']
['A', 'Ostrich', 'Sonora', 'CPA-00009-25', '2025']
['A', 'red-tailed_hawk', 'USA', '011271-006', '2025']
['A', 'red-tailed_hawk', 'USA', '013142-001', '2025']
['A', 'red-tailed_hawk', 'USA', '013174-001', '2025']
['A', 'bald_eagle', 'USA', '013105-001', '2025']
['A', 'chicken', 'New_York', '25-002734-001-R', '2025']
['A', 'chicken', 'Nebraska', '25-005224-001-R2', '2025']
['A', 'guineafowl', 'USA', '014146-002', '2025']
['A', 'red-tailed_hawk', 'USA', '013657-001', '2025']
['A', 'turkey_vulture', 'USA', '013422-003', '2025']
['A', 'red-shouldered_hawk', 'USA', '013810-002', '2025']
['A', 'black_vulture', 'USA', '013810-001', '2025']
['A', 'guineafowl', 'USA', '014146-001', '2025']
['A', 'chicken', 'USA', '013882-002', '2025']
['A', 'chicken', 'USA', '014151-001', '2025']
['A', 'chicken', 'USA', '014151-002', '2025']
['A', 'chicken', 'USA', '013882-001', '2025']
['A', 'chicken', 'USA', '014151-003', '2025']
['A', 'cat', 'USA', '013751-001', '2025']
['A', 'falcon', 'USA', '013658-001', '2025']
['A', 'red-tailed_hawk', 'USA', '013658-002', '2025']
['A', 'turkey_vulture', 'USA', '013659-001', '2025']
['A', 'bald_eagle', 'USA', '013658-003', '2025']
['A', 'chicken', 'USA', '015760-002', '2025']
['A', 'chicken', 'USA', '015760-003', '2025']
['A', 'chicken', 'USA', '015760-004', '2025']
['A', 'chicken', 'USA', '015760-005', '2025']
['A', 'chicken', 'USA', '015760-006', '2025']
['A', 'chicken', 'USA', '015760-008', '2025']
['A', 'chicken', 'USA', '015760-009', '2025']
['A', 'chicken', 'USA', '015760-010', '2025']
['A', 'cat', 'USA', '015467-001', '2025']
['A', 'great_horned_owl', 'USA', '013382-001-R2', '2025']
['A', 'chicken', 'USA', '014921-001', '2025']
['A', 'chicken', 'USA', '015760-001', '2025']
['A', 'chicken', 'USA', '015760-012', '2025']
['A', 'chicken', 'USA', '015760-014', '2025']
['A', 'chicken', 'USA', '015760-015', '2025']
['A', 'chicken', 'USA', '015760-016', '2025']
['A', 'chicken', 'USA', '015760-017', '2025']
['A', 'chicken', 'USA', '015760-018', '2025']
['A', 'chicken', 'USA', '015760-019', '2025']
['A', 'chicken', 'USA', '015760-020', '2025']
['A', 'mink', 'USA', '010686-001-tile', '2025']
['A', 'turkey_vulture', 'USA', '014877-001', '2025']
['A', 'turkey_vulture', 'USA', '014877-002', '2025']
['A', 'sharp-shinned_hawk', 'USA', '013219-001', '2025']
['A', 'dairy_cow', 'USA', '007484-009-R2', '2025']
['A', 'dairy_cow', 'USA', '007985-001-R2', '2025']
['A', 'dairy_cow', 'USA', '011565-001-R2', '2025']
['A', 'turkey_vulture', 'USA', '012813-002', '2025']
['A', 'turkey_vulture', 'USA', '012813-003', '2025']
['A', 'turkey_vulture', 'USA', '012989-006', '2025']
['A', 'black_vulture', 'USA', '012888-001', '2025']
['A', 'turkey_vulture', 'USA', '013045-001', '2025']
['A', 'black_vulture', 'USA', '013218-001', '2025']
['A', 'sand_crane', 'USA', '012990-001', '2025']
['A', 'turkey_vulture', 'USA', '015561-001', '2025']
['A', 'great_horned_owl', 'USA', '015870-001', '2025']
['A', 'chicken', 'USA', '016339-008', '2025']
['A', 'chicken', 'USA', '016339-005', '2025']
['A', 'chicken', 'USA', '016339-001', '2025']
['A', 'chicken', 'USA', '016338-002', '2025']
['A', 'chicken', 'USA', '016339-004', '2025']
['A', 'chicken', 'USA', '016339-007', '2025']
['A', 'chicken', 'USA', '016339-009', '2025']
['A', 'turkey_vulture', 'USA', '013422-002-R2', '2025']
['A', 'common_grackle', 'USA', '015755-001', '2025']
['A', 'turkey_vulture', 'USA', '013422-001-R2', '2025']
['A', 'bald_eagle', 'USA', '013426-001-R2', '2025']
['A', 'black_vulture', 'USA', '015563-001', '2025']
['A', 'red-tailed_hawk', 'USA', '013424-001-R2', '2025']
['A', 'chicken', 'USA', '016339-002', '2025']
['A', 'chicken', 'USA', '016339-003', '2025']
['A', 'chicken', 'USA', '016339-006', '2025']
['A', 'dunlin', 'USA', '004499-002', '2025']
['A', 'dunlin', 'USA', '004497-005', '2025']
['A', 'mute_swan', 'USA', '004421-001', '2025']
['A', 'american_black_duck', 'USA', '005883-002', '2025']
['A', 'mallard', 'USA', '005882-007', '2025']
['A', 'bald_eagle', 'USA', '004415-015', '2025']
['A', 'dunlin', 'USA', '004497-004', '2025']
['A', 'cat', 'USA', '006491-001', '2025']
['A', 'duck', 'USA', '004477-001', '2025']
['A', 'chicken', 'USA', '012098-003', '2025']
['A', 'duck', 'USA', '011483-004', '2025']
['A', 'chicken', 'USA', '011365-001', '2025']
['A', 'chicken', 'USA', '011365-002', '2025']
['A', 'skunk', 'USA', '011279-001', '2025']
['A', 'chicken', 'USA', '011237-001', '2025']
['A', 'turkey', 'USA', '011106-003', '2025']
['A', 'red_fox', 'USA', '012694-001', '2025']
['A', 'rock_goose', 'USA', '012362-001', '2025']
['A', 'red-tailed_hawk', 'USA', '011782-001', '2025']
['A', 'great_horned_owl', 'USA', '012288-002', '2025']
['A', 'great_horned_owl', 'USA', '007118-029-R2', '2025']
['A', 'great_horned_owl', 'USA', '012397-001', '2025']
['A', 'red-tailed_hawk', 'USA', '012695-001', '2025']
['A', 'red-tailed_hawk', 'USA', '012741-002', '2025']
['A', 'skunk', 'USA', '012361-001', '2025']
['A', 'snow_goose', 'USA', '037947-001-R3', '2024']
['A', 'black_vulture', 'USA', '006120-002-R2', '2025']
['A', 'black_vulture', 'USA', '012471-001', '2025']
['A', 'black_vulture', 'USA', '012471-002', '2025']
['A', 'black_vulture', 'USA', '012472-001', '2025']
['A', 'black_vulture', 'USA', '012472-002', '2025']
['A', 'black_vulture', 'USA', '012741-001', '2025']
['A', 'bufflehead', 'USA', '011074-001', '2025']
['A', 'cat', 'USA', '009981-001-R2', '2025']
['A', 'great_horned_owl', 'USA', '012057-001', '2025']
['A', 'great_horned_owl', 'USA', '012288-001', '2025']
['A', 'hooded_merganser', 'USA', '007118-068-R', '2025']
['A', 'mallard', 'USA', '012246-005', '2025']
['A', 'snow_goose', 'USA', '012363-001', '2025']
['A', 'snow_goose', 'USA', '012364-001', '2025']
['A', 'turkey_vulture', 'USA', '012059-002', '2025']
['A', 'turkey_vulture', 'USA', '012510-002', '2025']
['A', 'vulture', 'USA', '012105-001', '2025']
['A', 'vulture', 'USA', '012105-002', '2025']
['A', 'vulture', 'USA', '012105-003', '2025']
['A', 'vulture', 'USA', '012105-004', '2025']
['A', 'herring_gull', 'USA', '012508-006', '2025']
['A', 'chicken', 'USA', '011508-001-R2', '2025']
['A', 'duck', 'USA', '012798-008', '2025']
['A', 'turkey', 'USA', '009630-002', '2025']
['A', 'american_crow', 'USA', '012469-001', '2025']
['A', 'bald_eagle', 'USA', '012508-001', '2025']
['A', 'bald_eagle', 'USA', '012508-003', '2025']
['A', 'bald_eagle', 'USA', '012508-008', '2025']
['A', 'bald_eagle', 'USA', '012739-001', '2025']
['A', 'black_vulture', 'USA', '011841-001', '2025']
['A', 'cat', 'USA', '010413-001', '2025']
['A', 'snow_goose', 'USA', '001251-001', '2025']
['A', 'canada_goose', 'USA', '001439-001', '2025']
['A', 'trumpeter_swan', 'USA', '001541-003', '2025']
['A', 'canada_goose', 'USA', '001541-004', '2025']
['A', 'hawk', 'USA', '000514-001', '2025']
['A', 'snow_goose', 'USA', '035974-001-R2', '2024']
['A', 'sanderling', 'USA', '003254-001', '2025']
['A', 'chicken', 'USA', '006346-005', '2025']
['A', 'dairy_cow', 'USA', '006533-001', '2025']
['A', 'dairy_cow', 'USA', '006538-001', '2025']
['A', 'canada_goose', 'USA', '001541-006', '2025']
['A', 'cat', 'USA', '010413-002', '2025']
['A', 'greater_scaup', 'USA', '001543-002', '2025']
['A', 'snow_goose', 'USA', '037860-003', '2024']
['A', 'chicken', 'USA', '010935-005', '2025']
['A', 'chicken', 'USA', '010935-007', '2025']
['A', 'chicken', 'USA', '010935-008', '2025']
['A', 'mallard', 'USA', '001541-005', '2025']
['A', 'red-tailed_hawk', 'USA', '010882-001', '2025']
['A', 'goose', 'USA', '034332-002', '2024']
['A', 'goose', 'USA', '035950-001', '2024']
['A', 'goose', 'USA', '035950-002', '2024']
['A', 'snow_goose', 'USA', '036680-005', '2024']
['A', 'snow_goose', 'USA', '037540-001', '2024']
['A', 'skunk', 'USA', '010819-006', '2025']
['A', 'red-tailed_hawk', 'USA', '010427-001', '2025']
['A', 'black_vulture', 'USA', '010531-001', '2025']
['A', 'duck', 'USA', '010532-003', '2025']
['A', 'canada_goose', 'USA', '010570-001', '2025']
['A', 'american_crow', 'USA', '010623-002', '2025']
['A', 'black_vulture', 'USA', '010745-001', '2025']
['A', 'black_vulture', 'USA', '010745-003', '2025']
['A', 'bald_eagle', 'USA', '010786-001', '2025']
['A', "ross's_goose", 'USA', '011280-001', '2025']

In [7]:
# Remove duplicates from GISAID/Andersen

print(len(metadata_segments))

count = 0
isolate_partial = {}
for value in metadata_segments["Isolate"].values:
    # partial = value.split("_")[-1] # If 25_, get the last bit
    # print(partial)
    digits = value.split("-")
    isolate = ""
    # other = ""
    for d in digits:
        # print(d)
        if len(d) == 6 and d.isnumeric(): # If it's just digits and not one of those weird isolates
            isolate = d + "-"
        elif len(d) == 3 and d.isnumeric():
            isolate = isolate + d
        # elif d.isnumeric() == False: # If it's a weird isolate
        #     other = d + "-"
        # else: # If it's a weird isolate
        #     other = other + d
    # Now add to list to check in Andersen files without doing wild for loops
    if len(isolate) == 10: # If this is a correctly formatted isolate
        # isolates.append(isolate)
        # All headers are followed by sequences
        isolate_partial[value] = isolate
    else: # If this is some other isolate
        isolate_partial[value] = value
    # print(isolate)
# for index, value in metadata_segments["Isolate"].items():




to_remove = andersen_isolates
for value in isolate_partial.keys():
    isolate = isolate_partial[value]
    # print(isolate)
    r = re.compile(".*" + isolate + ".*")
    # print(r)
    if len(list(filter(r.search, gisaid_isolates))) > 0:
        for i in list(filter(r.search, gisaid_isolates)):
            to_remove.append(value) 
    # print(to_remove)
    # if isolate_partial[value] in gisaid_andersen_isolates:
    # if value in gisaid_andersen_isolates:
    #     count += 1
    #     to_remove.append(value)
            # metadata_segments = metadata_segments.drop(index)

print(to_remove)
print(len(to_remove))

for value in to_remove:
    if "SRR" in value:
        metadata_segments = metadata_segments[metadata_segments["SRA_Accession"] != value]
    # print(value)
    # print(isolate_partial[value])
    else:
        metadata_segments = metadata_segments[metadata_segments["Isolate"] != value]

print(len(metadata_segments))
print(len(isolate_partial))
metadata_segments
# print(count)

5192
['25-012798-008-original', '25-009630-002-original', '24-036138-001-original-repeat2', '24-036138-002-original-repeat2', '24-036187-001-original-repeat2', '24-036187-002-original-repeat2', '24-036203-001-original-repeat2', '24-036203-002-original-repeat2', '24-036204-001-original-repeat2', '25-006243-001-original', '25-006243-002-original', '25-006243-005-original', '25-006243-006-original', '25-011907-002-original', '25-011907-003-original', '25-011907-006-original', '25-011907-007-original', '25-011907-008-original', '25-011907-009-original', '25-010517-001-original', '25-010517-002-original', '25-010517-003-original', '25-010517-005-original', '25-012114-001-original', '25-012125-001-original', '25-012132-001-original', '25-011508-001-original-repeat2', '25-009621-002-original', '25-010935-009-original', '25-010935-010-original', '25-010935-011-original', '25-010935-003-original', '25-010935-004-original', '25-010817-001-original', '25-009630-001-original', '25-009647-001-original', '25-011002-001-original', '25-011002-002-original', '25-006274-001-original', '25-006274-002-original', '25-006274-003-original', '25-006274-004-original', '25-006274-006-original', '25-010626-001-original', '25-010626-002-original', '25-010626-003-original', '25-010626-004-original', '25-010626-005-original', '25-010642-001-original', '25-010642-003-original', '25-010642-004-original', '25-010642-005-original', '25-010642-006-original', '25-010642-007-original', '25-010523-001-original', '25-009621-001-original', '25-010791-001-original', '25-010791-002-original', '25-010935-001-original', '25-010935-002-original', '25-010935-005-original', '25-010935-006-original', '25-010935-007-original', '25-010935-008-original', '25-002734-001-original-repeat', '25-006508-005-original-repeat', '25-006508-007-original-repeat', '25-006508-009-original-repeat', '25-006511-005-original-repeat', '25-006507-001-original-repeat', '25-006508-003-original-repeat', '25-006508-008-original-repeat', '25-006506-003-original-repeat', '25-006508-010-original-repeat', '25-006511-002-original-repeat', '25-005292-001-original-repeat2', '25-005292-002-original-repeat2', '25-005207-001-original', '25-006508-011-original-repeat', '25-006508-012-original-repeat', '25-006510-002-original-repeat', '25-007549-048-original', '25-007549-049-original', '25-007549-053-original', '25-007549-054-original', '25-007549-055-original', '25-007549-056-original', '25-007549-057-original', '25-007549-058-original', '25-007549-059-original', '25-007549-060-original', '25-007549-061-original', '25-007549-062-original', '25-007549-063-original', '25-007549-064-original', '25-007549-065-original', '25-007549-066-original', '25-007549-067-original', '25-007549-068-original', '25-007549-069-original', '25-007549-070-original', '25-007549-071-original', '25-007549-072-original', '25-007549-073-original', '25-007549-074-original', '25-007549-075-original', '25-007549-076-original', '25-007549-077-original', '25-007549-078-original', '25-007549-079-original', '25-007549-080-original', '25-007549-081-original', '25-007549-082-original', '25-007549-083-original', '25-007549-084-original', '25-007549-085-original', '25-007549-086-original', '25-007549-087-original', '25-007549-088-original', '25-007549-089-original', '25-007549-090-original', '25-007549-106-original', '25-007549-109-original', '25-007549-110-original', '25-007549-118-original', '25-007549-119-original', '25-007549-120-original', '25-007549-121-original', '25-007549-122-original', '25-007549-123-original', '25-007549-124-original', '25-007549-125-original', '25-007549-126-original', '25-007549-127-original', '25-007549-128-original', '25-007549-129-original', '25-007549-130-original', '25-007549-131-original', '25-007549-132-original', '25-007549-133-original', '25-007549-134-original', '25-007549-135-original', '25-005224-001-original-repeat2', '25-006346-010-original', '25-006674-002-original', '25-006674-004-original', '25-006202-007-original', '25-007078-001-original', '25-007078-002-original', '25-007078-003-original', '25-007078-004-original', '25-006346-002-original', '25-006346-003-original', '25-006346-011-original', '25-006638-001-original', '25-006543-001-original', '25-006544-001-original', '25-007097-001-original', '25-007097-002-original', '25-006020-001-original', '25-006020-002-original', '25-006026-001-original', '25-006028-001-original', '25-006029-002-original', '25-006263-003-original', '25-006263-004-original', '25-006263-005-original', '25-006535-001-original', '25-006538-001-original', '25-006542-001-original', '25-006542-002-original', '25-006542-003-original', '25-006814-001-original', '25-006814-002-original', '25-006816-001-original', '25-006816-002-original', '25-006816-003-original', '25-006664-001-original', '25-006674-001-original', '25-006674-003-original', '25-006486-001-original', '25-007056-001-original', '25-006931-001-original', '25-007069-001-original', '25-006346-004-original', '25-006346-005-original', '25-006346-007-original', '25-006346-008-original', '25-006943-001-original', '25-006943-002-original', '25-006943-003-original', '25-007078-005-original', '25-006346-001-original', '24-033172-001-original', '24-033172-002-original', '24-033172-003-original', '25-000112-002-original', '25-000604-001-original', '25-000604-002-original', '25-004923-001-original', '25-004923-002-original', '24-034835-001-original-repeat2', '25-000610-001-original']
203
3568
649

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
16,PV709290.1,Influenza A virus,GenBank,NaN,SRR30811257,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,24-027096-002-original,...,1,USA: CA,CA,Bos taurus,mammalian milk,2024-09-12,SAMN43929871,PRJNA1102327,Influenza A virus (A/cattle/CA/24-027096-002-o...,8
17,PV709291.1,Influenza A virus,GenBank,NaN,SRR30811257,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,24-027096-002-original,...,2,USA: CA,CA,Bos taurus,mammalian milk,2024-09-12,SAMN43929871,PRJNA1102327,Influenza A virus (A/cattle/CA/24-027096-002-o...,8
18,PV709292.1,Influenza A virus,GenBank,NaN,SRR30811257,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,24-027096-002-original,...,3,USA: CA,CA,Bos taurus,mammalian milk,2024-09-12,SAMN43929871,PRJNA1102327,Influenza A virus (A/cattle/CA/24-027096-002-o...,8
19,PV709293.1,Influenza A virus,GenBank,NaN,SRR30811257,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,24-027096-002-original,...,4,USA: CA,CA,Bos taurus,mammalian milk,2024-09-12,SAMN43929871,PRJNA1102327,Influenza A virus (A/cattle/CA/24-027096-002-o...,8
20,PV709294.1,Influenza A virus,GenBank,NaN,SRR30811257,"Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...",USDA Animal Plant Health Inspection Service-Na...,USA,2025-05-30,24-027096-002-original,...,5,USA: CA,CA,Bos taurus,mammalian milk,2024-09-12,SAMN43929871,PRJNA1102327,Influenza A virus (A/cattle/CA/24-027096-002-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5187,PV494554.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,4,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5188,PV494555.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,5,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5189,PV494556.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,6,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5190,PV494557.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,7,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8
5191,PV494558.1,Influenza A virus,GenBank,GCA_049648785.1,SRR32415223,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-14,25-003975-001-original,...,8,USA: CA,CA,Bos taurus,mammalian milk,2025-01-29,SAMN46921925,PRJNA1102327,Influenza A virus (A/cattle/CA/25-003975-001-o...,8

In [8]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title


# print(metadata_segments["GenBank_Title"].iloc[0])

# Get sequences and headers together
headers = []
isolates = []
sras = []
headers_seqs = {}
with open("sequences.fasta") as f:
    lines = f.readlines()
    for num, line in enumerate(lines):
        if line[0] == ">": # If this is a header
            if line.strip() not in headers: # And is not a header we've seen before
                header = line.strip() 
                # print(header)
                split_header = header.split("|")
                # print(split_header)
                headers.append(header) 
                if num < len(lines): # If we're not at the last line
                    # for i, l in enumerate(lines[num + 1:]):
                    i = num
                    sequence = ""
                    # print(lines[i])
                    # print(lines[i + 1])
                    while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                        sequence = sequence + lines[i + 1].strip()
                        i += 1
                    headers_seqs[header] = sequence # Add next lines to sequences
                # name = split_header[-1] # Last part gives GenBank name, with segment and isolate
                isolate = split_header[2]
                isolates.append(isolate)
                sra = split_header[7]
                sras.append(sra)
    f.close()



# print(mask_all.all(axis=1))

In [9]:
# Double-check de-duplication
mask = metadata_segments["Isolate"].isin(isolates) # Check if isolate is in fasta
mask_sra = metadata_segments["SRA_Accession"].isin(sras) # Check if sra is in fasta

metadata_masked = metadata_segments[mask] # Some do not have isolates, so check sra too
metadata_masked_sra = metadata_segments[mask_sra]

merged_metadata = metadata_masked.merge(metadata_masked_sra, how="outer")
merged_metadata = merged_metadata.drop_duplicates(keep="first")

print(len(headers_seqs))
print(len(merged_metadata))

5751
3568

In [10]:
# Add sequences to a dataframe 
headers_seqs_df = pd.DataFrame.from_dict(headers_seqs, orient="index")
headers_seqs_df = headers_seqs_df.reset_index()
headers_seqs_df["GenBank_Title"] = headers_seqs_df["index"].apply(lambda x: x[1:].split("|")[-1])
headers_seqs_df = headers_seqs_df.rename(columns={0: "Sequence", "index": "Header"})

# Add sequences to the dataframe
metadata_seqs = merged_metadata.merge(headers_seqs_df, on="GenBank_Title", how="left")

print(metadata_seqs)

       Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     PV493074.1  Influenza A virus        GenBank  GCA_049650035.1
1     PV493075.1  Influenza A virus        GenBank  GCA_049650035.1
2     PV493076.1  Influenza A virus        GenBank  GCA_049650035.1
3     PV493077.1  Influenza A virus        GenBank  GCA_049650035.1
4     PV493078.1  Influenza A virus        GenBank  GCA_049650035.1
...          ...                ...            ...              ...
3563  PV709565.1  Influenza A virus        GenBank              NaN
3564  PV709566.1  Influenza A virus        GenBank              NaN
3565  PV709567.1  Influenza A virus        GenBank              NaN
3566  PV709568.1  Influenza A virus        GenBank              NaN
3567  PV709569.1  Influenza A virus        GenBank              NaN

     SRA_Accession                                         Submitters  \
0      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
1      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
2      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
3563   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3564   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3565   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3566   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3567   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
0     USDA Animal Plant Health Inspection Service-Na...          USA
1     USDA Animal Plant Health Inspection Service-Na...          USA
2     USDA Animal Plant Health Inspection Service-Na...          USA
3     USDA Animal Plant Health Inspection Service-Na...          USA
4     USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
3563  USDA Animal Plant Health Inspection Service-Na...          USA
3564  USDA Animal Plant Health Inspection Service-Na...          USA
3565  USDA Animal Plant Health Inspection Service-Na...          USA
3566  USDA Animal Plant Health Inspection Service-Na...          USA
3567  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... USA           Host  \
0      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
1      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
2      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
3      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
4      2025-04-14  25-005339-003-original  ...  IN  Gallus gallus
...           ...                     ...  ...  ..            ...
3563   2025-05-30  25-010514-002-original  ...  ID     Bos taurus
3564   2025-05-30  25-010514-002-original  ...  ID     Bos taurus
3565   2025-05-30  25-010514-002-original  ...  ID     Bos taurus
3566   2025-05-30  25-010514-002-original  ...  ID     Bos taurus
3567   2025-05-30  25-010514-002-original  ...  ID     Bos taurus

     Tissue_Specimen_Source Collection_Date     BioSample    BioProject  \
0            oronasopharynx      2025-02-12  SAMN47130968   PRJNA980729
1            oronasopharynx      2025-02-12  SAMN47130968   PRJNA980729
2            oronasopharynx      2025-02-12  SAMN47130968   PRJNA980729
3            oronasopharynx      2025-02-12  SAMN47130968   PRJNA980729
4            oronasopharynx      2025-02-12  SAMN47130968   PRJNA980729
...                     ...             ...           ...           ...
3563         mammalian milk      2025-03-24  SAMN47843733  PRJNA1102327
3564         mammalian milk      2025-03-24  SAMN47843733  PRJNA1102327
3565         mammalian milk      2025-03-24  SAMN47843733  PRJNA1102327
3566         mammalian milk      2025-03-24  SAMN47843733  PRJNA1102327
3567         mammalian milk      2025-03-24  SAMN47843733  PRJNA1102327

                                          GenBank_Title size  \
0     Influenza A virus (A/chicken/IN/25-005339-003-...    8
1     Influenza A virus (A/chicken/IN/25-005339-003-...    8
2     Influenza A virus (A/chicken/IN/25-005339-003-...    8
3     Influenza A virus (A/chicken/IN/25-005339-003-...    8
4     Influenza A virus (A/chicken/IN/25-005339-003-...    8
...                                                 ...  ...
3563  Influenza A virus (A/cattle/ID/25-010514-002-o...    8
3564  Influenza A virus (A/cattle/ID/25-010514-002-o...    8
3565  Influenza A virus (A/cattle/ID/25-010514-002-o...    8
3566  Influenza A virus (A/cattle/ID/25-010514-002-o...    8
3567  Influenza A virus (A/cattle/ID/25-010514-002-o...    8

                                                 Header  \
0     >Influenza A virus |USA: IN|25-005339-003-orig...
1     >Influenza A virus |USA: IN|25-005339-003-orig...
2     >Influenza A virus |USA: IN|25-005339-003-orig...
3     >Influenza A virus |USA: IN|25-005339-003-orig...
4     >Influenza A virus |USA: IN|25-005339-003-orig...
...                                                 ...
3563  >Influenza A virus |USA: ID|25-010514-002-orig...
3564  >Influenza A virus |USA: ID|25-010514-002-orig...
3565  >Influenza A virus |USA: ID|25-010514-002-orig...
3566  >Influenza A virus |USA: ID|25-010514-002-orig...
3567  >Influenza A virus |USA: ID|25-010514-002-orig...

                                               Sequence
0     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1     ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2     ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
3     ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4     ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
...                                                 ...
3563  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
3564  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
3565  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
3566  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
3567  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...

[3568 rows x 26 columns]

In [11]:
# Create FASTA files per Header

metadata_seqs["Partial_Header"] = metadata_seqs["Header"].apply(lambda x: "|".join(x.split("|")[:-1]))

unique_partial_headers = []

# Each header should repeat 8 times
for partial_header in metadata_seqs["Partial_Header"].values:
    if partial_header not in unique_partial_headers: # Only use the first occurence
        unique_partial_headers.append(partial_header)

print(len(unique_partial_headers)) # Sanity check

446

In [12]:
df_list = []
for partial_header in unique_partial_headers:
    # Get smaller dataframe
    df = metadata_seqs[metadata_seqs["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    df = df[["Header", "Sequence"]]
    df = df.rename(columns={"Header": "full_header", "Sequence": "sequence"}) # For utils function
    df["full_header"] = df["full_header"].apply(lambda x: ">" + x.split("|")[-1].replace(" ", "_"))
    # Make sure there are 8 segments
    if len(df) == 8:
        df_list.append(df)

In [13]:
print(df_list[0])
print(len(df_list))

                                         full_header  \
0  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
1  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
2  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
3  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
4  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
5  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
6  >Influenza_A_virus_(A/chicken/IN/25-005339-003...
7  >Influenza_A_virus_(A/chicken/IN/25-005339-003...

                                            sequence
0  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
1  ATGGATGTCAATCCGACTTTACTTTTCTTAAAAGTGCCAGCGCAAG...
2  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATCGTCGAGC...
3  ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
4  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
5  ATGAATCCAAATCAAAGGATAATAACCACTGGATCAATCTGTATGG...
6  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
7  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...
446

In [14]:
# Make fasta files. Finally

os.chdir(temp_files)

for df in df_list:
    # print(df)
    file_name = df["full_header"].apply(lambda x: x.split("|")[-1]).values[0] + "_temp.fasta"
    # Forbidden characters
    for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
        file_name = file_name.replace(c, "")
    # print(file_name)
    output_file = open(temp_files + file_name, "w")

    for index, row in df.iterrows():
        name = df.loc[index, "full_header"]
        # print(name)
        sequence = df.loc[index, "sequence"]
        # print(sequence)
        # break 
    # First is header, second is sequence
        output_file.write(name + "\n")
        output_file.write(sequence + "\n")
    output_file.close()

## Re-Labeling Using GenoFlu

In [15]:
# Merging

os.chdir(downloads)

output_genoflu = pd.read_csv("output.tsv", delimiter="\t")

# print(output_genoflu)

# print(metadata_seqs["Header"])

file_name = metadata_seqs["Header"].apply(lambda x: x.split("|")[-1].replace(" ", "_") + "_temp.fasta")
for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
    file_name = file_name.apply(lambda x: x.replace(c, ""))

metadata_seqs["File Name"] = file_name

metadata_genoflu = metadata_seqs.merge(output_genoflu, how="left", on="File Name")

metadata_genoflu = metadata_genoflu.ffill()



print(metadata_genoflu)

       Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     PV493074.1  Influenza A virus        GenBank  GCA_049650035.1
1     PV493075.1  Influenza A virus        GenBank  GCA_049650035.1
2     PV493076.1  Influenza A virus        GenBank  GCA_049650035.1
3     PV493077.1  Influenza A virus        GenBank  GCA_049650035.1
4     PV493078.1  Influenza A virus        GenBank  GCA_049650035.1
...          ...                ...            ...              ...
3563  PV709565.1  Influenza A virus        GenBank  GCA_050773895.1
3564  PV709566.1  Influenza A virus        GenBank  GCA_050773895.1
3565  PV709567.1  Influenza A virus        GenBank  GCA_050773895.1
3566  PV709568.1  Influenza A virus        GenBank  GCA_050773895.1
3567  PV709569.1  Influenza A virus        GenBank  GCA_050773895.1

     SRA_Accession                                         Submitters  \
0      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
1      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
2      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
4      SRR32512883  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
3563   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3564   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3565   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3566   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3567   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
0     USDA Animal Plant Health Inspection Service-Na...          USA
1     USDA Animal Plant Health Inspection Service-Na...          USA
2     USDA Animal Plant Health Inspection Service-Na...          USA
3     USDA Animal Plant Health Inspection Service-Na...          USA
4     USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
3563  USDA Animal Plant Health Inspection Service-Na...          USA
3564  USDA Animal Plant Health Inspection Service-Na...          USA
3565  USDA Animal Plant Health Inspection Service-Na...          USA
3566  USDA Animal Plant Health Inspection Service-Na...          USA
3567  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ...  \
0      2025-04-14  25-005339-003-original  ...
1      2025-04-14  25-005339-003-original  ...
2      2025-04-14  25-005339-003-original  ...
3      2025-04-14  25-005339-003-original  ...
4      2025-04-14  25-005339-003-original  ...
...           ...                     ...  ...
3563   2025-05-30  25-010514-002-original  ...
3564   2025-05-30  25-010514-002-original  ...
3565   2025-05-30  25-010514-002-original  ...
3566   2025-05-30  25-010514-002-original  ...
3567   2025-05-30  25-010514-002-original  ...

                                         Partial_Header  \
0     >Influenza A virus |USA: IN|25-005339-003-orig...
1     >Influenza A virus |USA: IN|25-005339-003-orig...
2     >Influenza A virus |USA: IN|25-005339-003-orig...
3     >Influenza A virus |USA: IN|25-005339-003-orig...
4     >Influenza A virus |USA: IN|25-005339-003-orig...
...                                                 ...
3563  >Influenza A virus |USA: ID|25-010514-002-orig...
3564  >Influenza A virus |USA: ID|25-010514-002-orig...
3565  >Influenza A virus |USA: ID|25-010514-002-orig...
3566  >Influenza A virus |USA: ID|25-010514-002-orig...
3567  >Influenza A virus |USA: ID|25-010514-002-orig...

                                              File Name     sample  \
0     Influenza_A_virus_AchickenIN25005339003origina...  Influenza
1     Influenza_A_virus_AchickenIN25005339003origina...  Influenza
2     Influenza_A_virus_AchickenIN25005339003origina...  Influenza
3     Influenza_A_virus_AchickenIN25005339003origina...  Influenza
4     Influenza_A_virus_AchickenIN25005339003origina...  Influenza
...                                                 ...        ...
3563  Influenza_A_virus_AcattleID25010514002original...  Influenza
3564  Influenza_A_virus_AcattleID25010514002original...  Influenza
3565  Influenza_A_virus_AcattleID25010514002original...  Influenza
3566  Influenza_A_virus_AcattleID25010514002original...  Influenza
3567  Influenza_A_virus_AcattleID25010514002original...  Influenza

                     date  Genotype_y  \
0     2025-06-06_10-23-01        D1.3
1     2025-06-06_10-23-01        D1.3
2     2025-06-06_10-23-01        D1.3
3     2025-06-06_10-23-01        D1.3
4     2025-06-06_10-23-01        D1.3
...                   ...         ...
3563  2025-06-06_10-21-16       B3.13
3564  2025-06-06_10-21-16       B3.13
3565  2025-06-06_10-21-16       B3.13
3566  2025-06-06_10-21-16       B3.13
3567  2025-06-06_10-21-16       B3.13

                            Genotype List Used, >=98.0%  \
0     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
1     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
2     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
4     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
3563  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3564  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3565  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3566  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3567  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...

                             Genotype Sample Title List  \
0     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
3563  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3564  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3565  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3566  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3567  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...

                            Genotype Percent Match List  \
0     99.56%, 99.29%, 99.44%, 99.53%, 99.47%, 98.58%...
1     99.56%, 99.29%, 99.44%, 99.53%, 99.47%, 98.58%...
2     99.56%, 99.29%, 99.44%, 99.53%, 99.47%, 98.58%...
3     99.56%, 99.29%, 99.44%, 99.53%, 99.47%, 98.58%...
4     99.56%, 99.29%, 99.44%, 99.53%, 99.47%, 98.58%...
...                                                 ...
3563  98.42%, 99.38%, 99.16%, 98.53%, 99.06%, 98.51%...
3564  98.42%, 99.38%, 99.16%, 98.53%, 99.06%, 98.51%...
3565  98.42%, 99.38%, 99.16%, 98.53%, 99.06%, 98.51%...
3566  98.42%, 99.38%, 99.16%, 98.53%, 99.06%, 98.51%...
3567  98.42%, 99.38%, 99.16%, 98.53%, 99.06%, 98.51%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0        10, 16, 12, 8, 8, 20, 1, 11       Ran on FASTA - No Coverage Report
1        10, 16, 12, 8, 8, 20, 1, 11       Ran on FASTA - No Coverage Report
2        10, 16, 12, 8, 8, 20, 1, 11       Ran on FASTA - No Coverage Report
3        10, 16, 12, 8, 8, 20, 1, 11       Ran on FASTA - No Coverage Report
4        10, 16, 12, 8, 8, 20, 1, 11       Ran on FASTA - No Coverage Report
...                              ...                                     ...
3563  36, 14, 18, 25, 14, 21, 14, 12       Ran on FASTA - No Coverage Report
3564  36, 14, 18, 25, 14, 21, 14, 12       Ran on FASTA - No Coverage Report
3565  36, 14, 18, 25, 14, 21, 14, 12       Ran on FASTA - No Coverage Report
3566  36, 14, 18, 25, 14, 21, 14, 12       Ran on FASTA - No Coverage Report
3567  36, 14, 18, 25, 14, 21, 14, 12       Ran on FASTA - No Coverage Report

[3568 rows x 36 columns]

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [16]:
# Re-Labeling

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

fix_animals_andersen(metadata_genoflu, animals_ref)

metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# print(metadata_genoflu["Host_Type"])

names = ">" + metadata_genoflu["SRA_Accession"] + "|A/" + metadata_genoflu["Host"] + "/" + metadata_genoflu["Geo_Location"].apply(lambda x: x.split(": ")[-1]) + "/" + metadata_genoflu["Isolate"] + "/" + metadata_genoflu["Years"].apply(lambda x: str(x)) + "|" + metadata_genoflu["Genotype_x"] + "|" + metadata_genoflu["Geo_Location"].apply(lambda x: x.replace(": ", "-")) + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype_y"]

metadata_genoflu["Name"] = names

print(metadata_genoflu["Name"])

0       >SRR32512883|A/gallus gallus/IN/25-005339-003-...
1       >SRR32512883|A/gallus gallus/IN/25-005339-003-...
2       >SRR32512883|A/gallus gallus/IN/25-005339-003-...
3       >SRR32512883|A/gallus gallus/IN/25-005339-003-...
4       >SRR32512883|A/gallus gallus/IN/25-005339-003-...
                              ...
3563    >SRR33029762|A/bos taurus/ID/25-010514-002-ori...
3564    >SRR33029762|A/bos taurus/ID/25-010514-002-ori...
3565    >SRR33029762|A/bos taurus/ID/25-010514-002-ori...
3566    >SRR33029762|A/bos taurus/ID/25-010514-002-ori...
3567    >SRR33029762|A/bos taurus/ID/25-010514-002-ori...
Name: Name, Length: 3568, dtype: object

## Merge all datasets and de-duplicate again

In [17]:
# # Set up segments

# segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}

# metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].map(segments)

# # print(metadata_genoflu["Segment_Name"])

# # Separate into several dataframes based on genotype + segment
# segment_genotype_dfs = []
# for segment in segments.values():
#     print(segment)
#     m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
#     print(m_g)
#     for genotype in list(set(m_g["Genotype_y"].values)):
#         if "Not assigned:" not in genotype:
#             df = m_g[(m_g["Genotype_y"] == genotype)] # & (metadata_genoflu["Segment"] == segment)]
#             segment_genotype_dfs.append(df)
#             # pair = genotype + "_" + segment
#             # print(pair)

# print(segment_genotype_dfs[3])

# # print(metadata_genoflu["Header"].apply(lambda x: x.split("|")[-1].split("/")[-1].split(")")[2:]))

In [18]:
# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}



metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].map(segments)

# print(metadata_genoflu["Segment_Name"])

# Separate into several dataframes based on genotype + segment
# b313_count = 0
segment_genotype_dfs = []
for segment in segments.values():
    # print(segment)
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    # print(m_g)
    for genotype in list(set(m_g["Genotype_y"].values)):
        # if "B3.13" in genotype:
        if genotype in genotypes:
            # b313_count += 1
            df = m_g[(m_g["Genotype_y"] == genotype)] # & (metadata_genoflu["Segment"] == segment)]
            # b313_count += len(df)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

# print(b313_count)
print(segment_genotype_dfs[8])

B3.13_PB2
B3.6_PB2
D1.1_PB2
B3.13_PB1
B3.6_PB1
D1.1_PB1
B3.13_PA
B3.6_PA
D1.1_PA
B3.13_HA
B3.6_HA
D1.1_HA
B3.13_NP
B3.6_NP
D1.1_NP
B3.13_NA
B3.6_NA
D1.1_NA
B3.13_MP
B3.6_MP
D1.1_MP
B3.13_NS
B3.6_NS
D1.1_NS
       Accession      Organism_Name GenBank_RefSeq         Assembly  \
10    PV493084.1  Influenza A virus        GenBank  GCA_049649315.1
74    PV493148.1  Influenza A virus        GenBank  GCA_049649815.1
82    PV493156.1  Influenza A virus        GenBank  GCA_049649255.1
90    PV493164.1  Influenza A virus        GenBank  GCA_049649825.1
98    PV493172.1  Influenza A virus        GenBank  GCA_049649275.1
...          ...                ...            ...              ...
3058  PV625424.1  Influenza A virus        GenBank  GCA_050387085.1
3066  PV625432.1  Influenza A virus        GenBank  GCA_050387155.1
3074  PV625440.1  Influenza A virus        GenBank  GCA_050387165.1
3082  PV625448.1  Influenza A virus        GenBank  GCA_050387175.1
3090  PV625456.1  Influenza A virus        GenBank  GCA_050381685.1

     SRA_Accession                                         Submitters  \
10     SRR32512908  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
74     SRR32512877  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
82     SRR32512875  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
90     SRR32512874  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
98     SRR32512873  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
3058   SRR33029749  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3066   SRR33029739  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3074   SRR33029738  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3082   SRR33029737  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3090   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
10    USDA Animal Plant Health Inspection Service-Na...          USA
74    USDA Animal Plant Health Inspection Service-Na...          USA
82    USDA Animal Plant Health Inspection Service-Na...          USA
90    USDA Animal Plant Health Inspection Service-Na...          USA
98    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
3058  USDA Animal Plant Health Inspection Service-Na...          USA
3066  USDA Animal Plant Health Inspection Service-Na...          USA
3074  USDA Animal Plant Health Inspection Service-Na...          USA
3082  USDA Animal Plant Health Inspection Service-Na...          USA
3090  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
10     2025-04-14  25-004982-001-original  ...       D1.1
74     2025-04-14  25-004785-001-original  ...       D1.1
82     2025-04-14  25-004785-002-original  ...       D1.1
90     2025-04-14  25-004785-003-original  ...       D1.1
98     2025-04-14  25-004785-004-original  ...       D1.1
...           ...                     ...  ...        ...
3058   2025-05-09  25-010293-002-original  ...       D1.1
3066   2025-05-09  25-010255-001-original  ...       D1.1
3074   2025-05-09  25-010255-002-original  ...       D1.1
3082   2025-05-09  25-010255-003-original  ...       D1.1
3090   2025-05-09  24-035866-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
10    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
74    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
82    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
90    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
98    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
3058  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3066  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3074  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3082  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3090  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
10    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
74    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
82    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
90    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
98    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
3058  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3066  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3074  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3082  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3090  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
10    99.65%, 99.25%, 99.44%, 99.53%, 99.67%, 99.43%...
74    99.61%, 99.38%, 99.58%, 99.53%, 99.73%, 99.57%...
82    99.65%, 99.34%, 99.58%, 99.53%, 99.73%, 99.57%...
90    99.65%, 99.34%, 99.58%, 99.53%, 99.73%, 99.57%...
98    99.65%, 99.38%, 99.58%, 99.53%, 99.73%, 99.57%...
...                                                 ...
3058  99.61%, 99.25%, 99.58%, 99.53%, 99.60%, 99.43%...
3066  99.65%, 99.30%, 99.58%, 99.41%, 99.73%, 99.57%...
3074  99.65%, 99.30%, 99.63%, 99.47%, 99.73%, 99.57%...
3082  99.65%, 99.25%, 99.53%, 99.47%, 99.73%, 99.43%...
3090  99.74%, 99.21%, 99.77%, 99.35%, 99.80%, 99.64%...

         Genotype Mismatch List Genotype Average Depth of Coverage List  \
10     8, 17, 12, 8, 5, 8, 2, 6       Ran on FASTA - No Coverage Report
74      9, 14, 9, 8, 4, 6, 2, 9       Ran on FASTA - No Coverage Report
82     8, 15, 9, 8, 4, 6, 2, 10       Ran on FASTA - No Coverage Report
90      8, 15, 9, 8, 4, 6, 2, 9       Ran on FASTA - No Coverage Report
98      8, 14, 9, 8, 4, 6, 2, 9       Ran on FASTA - No Coverage Report
...                         ...                                     ...
3058    9, 17, 9, 8, 6, 8, 2, 9       Ran on FASTA - No Coverage Report
3066  8, 16, 9, 10, 4, 6, 3, 10       Ran on FASTA - No Coverage Report
3074   8, 16, 8, 9, 4, 6, 3, 10       Ran on FASTA - No Coverage Report
3082  8, 17, 10, 9, 4, 8, 3, 10       Ran on FASTA - No Coverage Report
3090   6, 18, 5, 11, 3, 5, 0, 8       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
10       avian  2025  >SRR32512908|A/gallus gallus/WY/25-004982-001-...
74       avian  2025  >SRR32512877|A/anatidae/PA/25-004785-001-origi...
82       avian  2025  >SRR32512875|A/anatidae/PA/25-004785-002-origi...
90       avian  2025  >SRR32512874|A/anatidae/PA/25-004785-003-origi...
98       avian  2025  >SRR32512873|A/anatidae/PA/25-004785-004-origi...
...        ...   ...                                                ...
3058     avian  2025  >SRR33029749|A/gallus gallus/NY/25-010293-002-...
3066     avian  2025  >SRR33029739|A/gallus gallus/PA/25-010255-001-...
3074     avian  2025  >SRR33029738|A/gallus gallus/PA/25-010255-002-...
3082     avian  2025  >SRR33029737|A/gallus gallus/PA/25-010255-003-...
3090     avian  2024  >SRR33029746|A/anatidae/CA/24-035866-001-origi...

     Segment_Name
10             PA
74             PA
82             PA
90             PA
98             PA
...           ...
3058           PA
3066           PA
3074           PA
3082           PA
3090           PA

[135 rows x 40 columns]

In [20]:
# Create FASTA files

os.chdir(complete_files)

names = []

for df in segment_genotype_dfs:
    if len(df["Genotype_y"].values[0]) > 0:
        file_name = df["Genotype_y"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + update_date + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            names.append(name)
            # print(name)
            sequence = df.loc[index, "Sequence"]
            # print(sequence)
            # break 
        # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        output_file.close()

print(len(names))

3120

In [21]:
print(segment_genotype_dfs)

[       Accession      Organism_Name GenBank_RefSeq         Assembly  \
288   PV493362.1  Influenza A virus        GenBank  GCA_049648905.1
296   PV493370.1  Influenza A virus        GenBank  GCA_049649545.1
304   PV493378.1  Influenza A virus        GenBank  GCA_049647975.1
312   PV493386.1  Influenza A virus        GenBank  GCA_049648345.1
320   PV493394.1  Influenza A virus        GenBank  GCA_049647955.1
...          ...                ...            ...              ...
3520  PV709474.1  Influenza A virus        GenBank  GCA_050512555.1
3528  PV709482.1  Influenza A virus        GenBank  GCA_050512555.1
3536  PV709490.1  Influenza A virus        GenBank  GCA_050512555.1
3552  PV709554.1  Influenza A virus        GenBank  GCA_050773895.1
3560  PV709562.1  Influenza A virus        GenBank  GCA_050773895.1

     SRA_Accession                                         Submitters  \
288    SRR32512688  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
296    SRR32512687  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
304    SRR31254377  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
312    SRR31254366  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
320    SRR31254355  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
3520   SRR32868643  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3528   SRR32868632  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3536   SRR32973866  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3552   SRR33029763  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3560   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
288   USDA Animal Plant Health Inspection Service-Na...          USA
296   USDA Animal Plant Health Inspection Service-Na...          USA
304   USDA Animal Plant Health Inspection Service-Na...          USA
312   USDA Animal Plant Health Inspection Service-Na...          USA
320   USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
3520  USDA Animal Plant Health Inspection Service-Na...          USA
3528  USDA Animal Plant Health Inspection Service-Na...          USA
3536  USDA Animal Plant Health Inspection Service-Na...          USA
3552  USDA Animal Plant Health Inspection Service-Na...          USA
3560  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
288    2025-04-14  25-004391-001-original  ...      B3.13
296    2025-04-14  25-004756-001-original  ...      B3.13
304    2025-04-14  24-030033-007-original  ...      B3.13
312    2025-04-14  24-030034-001-original  ...      B3.13
320    2025-04-14  24-030034-002-original  ...      B3.13
...           ...                     ...  ...        ...
3520   2025-05-30  25-007921-007-original  ...      B3.13
3528   2025-05-30  25-007921-009-original  ...      B3.13
3536   2025-05-30  25-009041-001-original  ...      B3.13
3552   2025-05-30  25-010514-001-original  ...      B3.13
3560   2025-05-30  25-010514-002-original  ...      B3.13

                            Genotype List Used, >=98.0%  \
288   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
296   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
304   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
312   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
320   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                 ...
3520  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3528  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3536  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3552  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3560  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...

                             Genotype Sample Title List  \
288   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
296   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
304   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
312   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
320   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                 ...
3520  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3528  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3536  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3552  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3560  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...

                            Genotype Percent Match List  \
288   98.60%, 99.52%, 99.02%, 98.53%, 98.93%, 98.94%...
296   98.51%, 99.47%, 99.07%, 98.59%, 99.00%, 98.94%...
304   98.64%, 99.52%, 99.07%, 98.53%, 99.06%, 98.86%...
312   98.64%, 99.47%, 98.98%, 98.47%, 99.00%, 98.94%...
320   98.64%, 99.47%, 98.98%, 98.47%, 99.00%, 98.94%...
...                                                 ...
3520  98.64%, 99.34%, 98.70%, 98.36%, 98.60%, 98.86%...
3528  98.64%, 99.34%, 98.70%, 98.36%, 98.60%, 98.86%...
3536  98.64%, 99.43%, 98.70%, 98.36%, 98.66%, 98.86%...
3552  98.42%, 99.38%, 99.16%, 98.59%, 99.06%, 98.51%...
3560  98.42%, 99.38%, 99.16%, 98.53%, 99.06%, 98.51%...

              Genotype Mismatch List Genotype Average Depth of Coverage List  \
288    32, 11, 21, 25, 16, 15, 11, 9       Ran on FASTA - No Coverage Report
296    34, 12, 20, 24, 15, 15, 12, 9       Ran on FASTA - No Coverage Report
304    31, 11, 20, 25, 14, 16, 10, 8       Ran on FASTA - No Coverage Report
312    31, 12, 22, 26, 15, 15, 11, 8       Ran on FASTA - No Coverage Report
320    31, 12, 22, 26, 15, 15, 11, 8       Ran on FASTA - No Coverage Report
...                              ...                                     ...
3520   31, 15, 28, 28, 21, 16, 12, 7       Ran on FASTA - No Coverage Report
3528   31, 15, 28, 28, 21, 16, 12, 7       Ran on FASTA - No Coverage Report
3536   31, 13, 28, 28, 20, 16, 12, 7       Ran on FASTA - No Coverage Report
3552  36, 14, 18, 24, 14, 21, 14, 12       Ran on FASTA - No Coverage Report
3560  36, 14, 18, 25, 14, 21, 14, 12       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
288     feline  2025  >SRR32512688|A/felis catus/OR/25-004391-001-or...
296     feline  2025  >SRR32512687|A/felis catus/OR/25-004756-001-or...
304     cattle  2024  >SRR31254377|A/bos taurus/CA/24-030033-007-ori...
312     cattle  2024  >SRR31254366|A/bos taurus/CA/24-030034-001-ori...
320     cattle  2024  >SRR31254355|A/bos taurus/CA/24-030034-002-ori...
...        ...   ...                                                ...
3520    cattle  2025  >SRR32868643|A/bos taurus/CA/25-007921-007-ori...
3528    cattle  2025  >SRR32868632|A/bos taurus/CA/25-007921-009-ori...
3536    cattle  2025  >SRR32973866|A/bos taurus/CA/25-009041-001-ori...
3552    cattle  2025  >SRR33029763|A/bos taurus/ID/25-010514-001-ori...
3560    cattle  2025  >SRR33029762|A/bos taurus/ID/25-010514-002-ori...

     Segment_Name
288           PB2
296           PB2
304           PB2
312           PB2
320           PB2
...           ...
3520          PB2
3528          PB2
3536          PB2
3552          PB2
3560          PB2

[254 rows x 40 columns],        Accession      Organism_Name GenBank_RefSeq         Assembly  \
3000  PV625366.1  Influenza A virus        GenBank  GCA_050386555.1

     SRA_Accession                                         Submitters  \
3000   SRR33029741  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
3000  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
3000   2025-05-09  25-009984-001-original  ...       B3.6

                            Genotype List Used, >=98.0%  \
3000  PB2:am5, PB1:am4, PA:ea1, HA:ea1, NP:am1.4.1, ...

                             Genotype Sample Title List  \
3000  am5:23-001855-001:PB2, am4:23-001855-001:PB1, ...

                            Genotype Percent Match List  \
3000  98.99%, 98.99%, 98.70%, 98.30%, 99.00%, 98.01%...

              Genotype Mismatch List Genotype Average Depth of Coverage List  \
3000  23, 23, 28, 29, 15, 28, 15, 10       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
3000     avian  2025  >SRR33029741|A/gallus gallus/FL/25-009984-001-...

     Segment_Name
3000          PB2

[1 rows x 40 columns],        Accession      Organism_Name GenBank_RefSeq         Assembly  \
8     PV493082.1  Influenza A virus        GenBank  GCA_049649315.1
72    PV493146.1  Influenza A virus        GenBank  GCA_049649815.1
80    PV493154.1  Influenza A virus        GenBank  GCA_049649255.1
88    PV493162.1  Influenza A virus        GenBank  GCA_049649825.1
96    PV493170.1  Influenza A virus        GenBank  GCA_049649275.1
...          ...                ...            ...              ...
3056  PV625422.1  Influenza A virus        GenBank  GCA_050387085.1
3064  PV625430.1  Influenza A virus        GenBank  GCA_050387155.1
3072  PV625438.1  Influenza A virus        GenBank  GCA_050387165.1
3080  PV625446.1  Influenza A virus        GenBank  GCA_050387175.1
3088  PV625454.1  Influenza A virus        GenBank  GCA_050381685.1

     SRA_Accession                                         Submitters  \
8      SRR32512908  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
72     SRR32512877  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
80     SRR32512875  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
88     SRR32512874  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
96     SRR32512873  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
3056   SRR33029749  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3064   SRR33029739  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3072   SRR33029738  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3080   SRR33029737  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3088   SRR33029746  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
8     USDA Animal Plant Health Inspection Service-Na...          USA
72    USDA Animal Plant Health Inspection Service-Na...          USA
80    USDA Animal Plant Health Inspection Service-Na...          USA
88    USDA Animal Plant Health Inspection Service-Na...          USA
96    USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
3056  USDA Animal Plant Health Inspection Service-Na...          USA
3064  USDA Animal Plant Health Inspection Service-Na...          USA
3072  USDA Animal Plant Health Inspection Service-Na...          USA
3080  USDA Animal Plant Health Inspection Service-Na...          USA
3088  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
8      2025-04-14  25-004982-001-original  ...       D1.1
72     2025-04-14  25-004785-001-original  ...       D1.1
80     2025-04-14  25-004785-002-original  ...       D1.1
88     2025-04-14  25-004785-003-original  ...       D1.1
96     2025-04-14  25-004785-004-original  ...       D1.1
...           ...                     ...  ...        ...
3056   2025-05-09  25-010293-002-original  ...       D1.1
3064   2025-05-09  25-010255-001-original  ...       D1.1
3072   2025-05-09  25-010255-002-original  ...       D1.1
3080   2025-05-09  25-010255-003-original  ...       D1.1
3088   2025-05-09  24-035866-001-original  ...       D1.1

                            Genotype List Used, >=98.0%  \
8     PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
72    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
80    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
88    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
96    PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
...                                                 ...
3056  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3064  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3072  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3080  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3088  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
8     am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
72    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
80    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
88    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
96    am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                 ...
3056  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3064  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3072  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3080  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3088  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
8     99.65%, 99.25%, 99.44%, 99.53%, 99.67%, 99.43%...
72    99.61%, 99.38%, 99.58%, 99.53%, 99.73%, 99.57%...
80    99.65%, 99.34%, 99.58%, 99.53%, 99.73%, 99.57%...
88    99.65%, 99.34%, 99.58%, 99.53%, 99.73%, 99.57%...
96    99.65%, 99.38%, 99.58%, 99.53%, 99.73%, 99.57%...
...                                                 ...
3056  99.61%, 99.25%, 99.58%, 99.53%, 99.60%, 99.43%...
3064  99.65%, 99.30%, 99.58%, 99.41%, 99.73%, 99.57%...
3072  99.65%, 99.30%, 99.63%, 99.47%, 99.73%, 99.57%...
3080  99.65%, 99.25%, 99.53%, 99.47%, 99.73%, 99.43%...
3088  99.74%, 99.21%, 99.77%, 99.35%, 99.80%, 99.64%...

         Genotype Mismatch List Genotype Average Depth of Coverage List  \
8      8, 17, 12, 8, 5, 8, 2, 6       Ran on FASTA - No Coverage Report
72      9, 14, 9, 8, 4, 6, 2, 9       Ran on FASTA - No Coverage Report
80     8, 15, 9, 8, 4, 6, 2, 10       Ran on FASTA - No Coverage Report
88      8, 15, 9, 8, 4, 6, 2, 9       Ran on FASTA - No Coverage Report
96      8, 14, 9, 8, 4, 6, 2, 9       Ran on FASTA - No Coverage Report
...                         ...                                     ...
3056    9, 17, 9, 8, 6, 8, 2, 9       Ran on FASTA - No Coverage Report
3064  8, 16, 9, 10, 4, 6, 3, 10       Ran on FASTA - No Coverage Report
3072   8, 16, 8, 9, 4, 6, 3, 10       Ran on FASTA - No Coverage Report
3080  8, 17, 10, 9, 4, 8, 3, 10       Ran on FASTA - No Coverage Report
3088   6, 18, 5, 11, 3, 5, 0, 8       Ran on FASTA - No Coverage Report

     Host_Type Years                                               Name  \
8        avian  2025  >SRR32512908|A/gallus gallus/WY/25-004982-001-...
72       avian  2025  >SRR32512877|A/anatidae/PA/25-004785-001-origi...
80       avian  2025  >SRR32512875|A/anatidae/PA/25-004785-002-origi...
88       avian  2025  >SRR32512874|A/anatidae/PA/25-004785-003-origi...
96       avian  2025  >SRR32512873|A/anatidae/PA/25-004785-004-origi...
...        ...   ...                                                ...
3056     avian  2025  >SRR33029749|A/gallus gallus/NY/25-010293-002-...
3064     avian  2025  >SRR33029739|A/gallus gallus/PA/25-010255-001-...
3072     avian  2025  >SRR33029738|A/gallus gallus/PA/25-010255-002-...
3080     avian  2025  >SRR33029737|A/gallus gallus/PA/25-010255-003-...
3088     avian  2024  >SRR33029746|A/anatidae/CA/24-035866-001-origi...

     Segment_Name
8             PB2
72            PB2
80            PB2
88            PB2
96            PB2
...           ...
3056          PB2
3064          PB2
3072          PB2
3080          PB2
3088          PB2

[135 rows x 40 columns],        Accession      Organism_Name GenBank_RefSeq         Assembly  \
289   PV493363.1  Influenza A virus        GenBank  GCA_049648905.1
297   PV493371.1  Influenza A virus        GenBank  GCA_049649545.1
305   PV493379.1  Influenza A virus        GenBank  GCA_049647975.1
313   PV493387.1  Influenza A virus        GenBank  GCA_049648345.1
321   PV493395.1  Influenza A virus        GenBank  GCA_049647955.1
...          ...                ...            ...              ...
3521  PV709475.1  Influenza A virus        GenBank  GCA_050512555.1
3529  PV709483.1  Influenza A virus        GenBank  GCA_050512555.1
3537  PV709491.1  Influenza A virus        GenBank  GCA_050512555.1
3553  PV709555.1  Influenza A virus        GenBank  GCA_050773895.1
3561  PV709563.1  Influenza A virus        GenBank  GCA_050773895.1

     SRA_Accession                                         Submitters  \
289    SRR32512688  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
297    SRR32512687  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
305    SRR31254377  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
313    SRR31254366  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
321    SRR31254355  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
...            ...                                                ...
3521   SRR32868643  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3529   SRR32868632  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3537   SRR32973866  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3553   SRR33029763  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...
3561   SRR33029762  Aufderhar,M., Franzen,K., Killian,M.L., Lantz,...

                                           Organization Org_location  \
289   USDA Animal Plant Health Inspection Service-Na...          USA
297   USDA Animal Plant Health Inspection Service-Na...          USA
305   USDA Animal Plant Health Inspection Service-Na...          USA
313   USDA Animal Plant Health Inspection Service-Na...          USA
321   USDA Animal Plant Health Inspection Service-Na...          USA
...                                                 ...          ...
3521  USDA Animal Plant Health Inspection Service-Na...          USA
3529  USDA Animal Plant Health Inspection Service-Na...          USA
3537  USDA Animal Plant Health Inspection Service-Na...          USA
3553  USDA Animal Plant Health Inspection Service-Na...          USA
3561  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ... Genotype_y  \
289    2025-04-14  25-004391-001-original  ...      B3.13
297    2025-04-14  25-004756-001-original  ...      B3.13
305    2025-04-14  24-030033-007-original  ...      B3.13
313    2025-04-14  24-030034-001-original  ...      B3.13
321    2025-04-14  24-030034-002-original  ...      B3.13
...           ...                     ...  ...        ...
3521   2025-05-30  25-007921-007-original  ...      B3.13
3529   2025-05-30  25-007921-009-original  ...      B3.13
3537   2025-05-30  25-009041-001-original  ...      B3.13
3553   2025-05-30  25-010514-001-original  ...      B3.13
3561   2025-05-30  25-010514-002-original  ...      B3.13

                            Genotype List Used, >=98.0%  \
289   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
297   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
305   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
313   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
321   PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                 ...
3521  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3529  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3537  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3553  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3561  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...

                             Genotype Sample Title List  \
289   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
297   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
305   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
313   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
321   am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                 ...

In [23]:
# Concatenate

os.chdir(combined_files)

filenames_gisaid_andersen = []
for genotype in genotypes:
    # print(gisaid_andersen + genotype.replace(".", "_") + "/")
    for dirpath, dirs, files in os.walk(gisaid_andersen + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "/"):
    # for dirpath, dirs, files in os.walk(gisaid_andersen): # Find the fasta file
        for file in files:
            file_name = os.path.join(dirpath, file) # Get file name
            filenames_gisaid_andersen.append(file_name)
        break 

print(filenames_gisaid_andersen)

filenames_ncbi = []
for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
    for file in files:
        file_name = os.path.join(dirpath, file) # Get file name
        filenames_ncbi.append(file_name)
    break 

print(filenames_ncbi)

do_not_do_these_partials = []
for ga_file in filenames_gisaid_andersen:
    partial_filename_ga = ga_file.split("_")[-4].split("/")[-1] + "_" + ga_file.split("_")[-3]
    for nv_file in filenames_ncbi:
        partial_filename_nv = nv_file.split("_")[-3].split("/")[-1] + "_" + nv_file.split("_")[-2]
        if partial_filename_ga == partial_filename_nv:
            do_not_do_these_partials.append(partial_filename_ga)
            print(partial_filename_nv)
            filenames = [ga_file, nv_file]
            with open(combined_files + partial_filename_ga + "_combined_" + update_date + ".fasta", 'w') as outfile:
                for fname in filenames:
                    with open(fname) as infile:
                        for line in infile:
                            outfile.write(line)

for ga_file in filenames_gisaid_andersen:
    partial_filename_ga = ga_file.split("_")[-4].split("/")[-1] + "_" + ga_file.split("_")[-3]
    if partial_filename_ga not in do_not_do_these_partials:
        with open(combined_files + partial_filename_ga + "_combined_" + update_date + ".fasta", 'w') as outfile2:
            # for fname in filenames_gisaid_andersen:
            with open(ga_file) as infile1:
                for line in infile1:
                    outfile2.write(line)
    

# lines = 0

# fns_seen = set()
# for filename in filenames_ncbi:
#     print("NCBI_Virus", filename)
#     # lines = 0
#     # filename.split("_")[-5] + "." +   
#     partial_filename = filename.split("_")[-3].split("/")[-1] + "_" + filename.split("_")[-2] 
#     print(partial_filename)
    
#     for fn in filenames_gisaid_andersen:
#         # print(fns_seen)
#         if partial_filename in fn: # and partial_filename not in fns_seen: # If partial filenames match
#             fns_seen.add(fn)
#         #     fns_seen.add(partial_filename)
#             # print("hi", partial_filename)
#             filenames = [filename, fn]
#             with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile:
#                 for fname in filenames:
#                     with open(fname) as infile1:
#                         for line in infile1:
#                             outfile.write(line)

# for fn in filenames_gisaid_andersen: # Extra files
#     if fn not in fns_seen:
#         partial_filename = fn.split("_")[-4].split("/")[-1] + "_" + fn.split("_")[-3] 
#         with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile:
#             for fname in filenames:
#                 with open(fname) as infile1:
#                     for line in infile1:
#                         outfile.write(line)
    
#                             # if line[0] == ">":
#                             #     lines += 1
#             #         infile.close()
#             # outfile.close()
#         # elif partial_filename not in fns_seen: # Save the ones that aren't shared -- if partial filename was not seen before
#         #     # print("hello", partial_filename)
#         #     fns_seen.add(partial_filename)
#         #     with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'w') as outfile2:
#         #         # Copy
#         #         with open(fn) as infile2:
#         #             for line in infile2:
#         #                 outfile2.write(line)
#         # else: # If partial filename doesn't match AND if partial filename has been seen before
#         #     continue 
#         #                 # if line[0] == ">":
#         #                 #     lines += 1
#         #             # infile.close()
#         #         with open(fn) as infile3:
#         #             for line in infile3:
#         #                 outfile2.write(line)
#         #                 # if line[0] == ">":
#                         #     lines += 1
#             #     infile.close()
#         outfile.close()


#     # break 

#     # print(lines)

# # lines = 0
# # Counting
#     with open(combined_files + partial_filename + "_combined_" + update_date + ".fasta", 'r') as outfile:
#         for line in outfile.readlines():
#             if line[0] == ">":
#                 lines += 1

# print(lines)

['C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_HA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_MP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_NA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_NP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_NS_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_PA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_PB1_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/D1_1/04-14-2025--06-13-2025_D1_1/D1.1_PB2_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_HA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_MP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_NA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_NP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_NS_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_PA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_PB1_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_6/04-14-2025--06-13-2025_B3_6/B3.6_PB2_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_HA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_MP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_NA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_NP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_NS_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_PA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_PB1_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/B3_13/04-14-2025--06-13-2025_B3_13/B3.13_PB2_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_HA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_MP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_NA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_NP_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_NS_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_PA_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_PB1_combined_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/Combinations/GISAID_Andersen/A3/04-14-2025--06-13-2025_A3/A3_PB2_combined_06-16-2025.fasta']
['C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_HA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_MP_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_NA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_NP_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_NS_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_PA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_PB1_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.13_PB2_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_HA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_MP_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_NA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_NP_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_NS_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_PA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_PB1_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/B3.6_PB2_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_HA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_MP_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_NA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_NP_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_NS_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_PA_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_PB1_06-16-2025.fasta', 'C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/NCBI_Virus/complete/04-14-2025--06-13-2025/D1.1_PB2_06-16-2025.fasta']
D1.1_HA
D1.1_MP
D1.1_NA
D1.1_NP
D1.1_NS
D1.1_PA
D1.1_PB1
D1.1_PB2
B3.6_HA
B3.6_MP
B3.6_NA
B3.6_NP
B3.6_NS
B3.6_PA
B3.6_PB1
B3.6_PB2
B3.13_HA
B3.13_MP
B3.13_NA
B3.13_NP
B3.13_NS
B3.13_PA
B3.13_PB1
B3.13_PB2

In [24]:
# # Mega fasta file
# all_files = []
# for dirpath, dirs, files in os.walk(combined_files):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         all_files.append(file_name)

# with open(combined_files + "all_files_combined_" + update_date + ".fasta", 'w') as outfile3:
#     for fname in all_files:
#         with open(fname) as infile4:
#             for line in infile4:
#                 outfile3.write(line)
# #         infile.close()
# # outfile.close()

In [25]:
# Animals 

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['meleagris gallopavo', 'galliformes', 'felis catus', 'bos taurus', 'gallus gallus', 'numididae sp.', 'anatidae']
[]
                avian               cattle        feline   other_mammal  \
0    great_horned_owl            dairy_cow           cat     deer mouse
1        common_raven               cattle  domestic_cat    house_mouse
2       cooper's_hawk  cattle milk product     feral_cat          skunk
3        coopers_hawk          bovine_milk        feline  striped_skunk
4             peafowl              bovine   domestic-cat     norway rat
..                ...                  ...           ...            ...
415         gyrfalcon                  NaN           NaN            NaN
416  american_goshawk                  NaN           NaN            NaN
417      king_vulture                  NaN           NaN            NaN
418     american coot                  NaN           NaN            NaN
419        barred owl                  NaN           NaN            NaN

          human         other  new
0    washington         mixed  NaN
1        nevada   environment  NaN
2       wyoming  multispecies  NaN
3    california       unknown  NaN
4      michigan             -  NaN
..          ...           ...  ...
415         NaN           NaN  NaN
416         NaN           NaN  NaN
417         NaN           NaN  NaN
418         NaN           NaN  NaN
419         NaN           NaN  NaN

[420 rows x 7 columns]