# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI, by de-duplicating from Andersen/GISAID, and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
from collections import defaultdict
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [15]:
# Paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = home + "NCBI_Virus_Downloads/11-01-2021--04-14-2025/"
temp_files = home + "NCBI_Virus_Temp_Files/"
complete_files = home + "NCBI_Virus_Complete_Files/"
gisaid_andersen = home + "Complete_Combined_Files/11-01-2021--04-14-2025_all_genotypes/11-01-2021--04-14-2025_all_genotypes/"

# Day we're updating data
update_date = "04-14-2025"

os.chdir(downloads)

## De-Duplication

In [3]:
metadata = pd.read_csv("sequences.csv")

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.SRA_Accession, as_index=False).size()

print(metadata_counts)

metadata_counted = metadata.merge(metadata_counts, on="SRA_Accession")

# Only keep those with size=8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates

metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="first") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]

metadata_segments

     SRA_Accession  size
0      SRR23852495     8
1      SRR28752446     8
2      SRR28752447     8
3      SRR28752448     8
4      SRR28752449     8
...            ...   ...
4141   SRR33124773     8
4142   SRR33124774     8
4143   SRR33124775     8
4144   SRR33124776     8
4145   SRR33124777     8

[4146 rows x 2 columns]

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV571926,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,1,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
1,PV571927,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,2,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
2,PV571928,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,3,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
3,PV571929,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,4,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
4,PV571930,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,5,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37035,OQ565628,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,4,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37036,OQ565629,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,5,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37037,OQ565630,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,6,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37038,OQ565631,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,7,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37039,OQ565632,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,8,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8

In [4]:
# De-duplicate from Andersen/GISAID using isolate

# If even one isolate in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
gisaid_andersen_isolates = []
# Grab files
for dirpath, dirs, files in os.walk(gisaid_andersen):
    for file in files:
        file_name = os.path.join(dirpath, file)
        # print(file_name)
        if ".fasta" in file_name:
            fasta_file = fasta_df(file_name) # Convert fasta file to dataframe
            isolates = fasta_file["Isolate_Id"].apply(lambda x: x.split("/")[3])
            for index, value in isolates.items():
                gisaid_andersen_isolates.append(value)
         
    break 

gisaid_andersen_isolates = list(set(gisaid_andersen_isolates))

print(gisaid_andersen_isolates)

['W22-199D', '22-026118-002', '24-035157-003', '026360-005', '22-036768-001', '22-029901-002-R', '031285-013', 'FAV-0415-7', '24_034221-001', '036403-004', '006223-001', '22-017940-010', '22-019668-001-original', 'W241070094-25', '22-018423-002', '007113-001', '24-020285-004', '23-037672-002', '033876-002', '22-036105-005', '002281-001', '22-015021-001', '036563-004', '22-024871-017', '004074-009', '24_034194-001', '031666-028', '24_018154-001', 'AIVPHL-1151', '22-028884-003', '22-008483-001', '24-008357-001', '002143-001', '038278-001', 'AIVPHL-23', '038947-002', '078707-24-10', 'FAV-0833-30', '24-009315-003-original', '037207-001', '24_034232-001', '035654-001', 'USDA-011034-001', '22-017507-007', '23-009211-001', '23-034904-001', 'B24OSU-472', 'AIVPHL-1443', 'FAV-0300-05', '22-012047-001', 'FAV-1010-3', '23-035121-001-original', '002467-001', '015884-014', '22-039352-016', '22-014661-002', '23-034924-012-original', '24_009110-017', '22-014175-003', '007839-001', '032038-001', '23-040358-001-original', '007118-010', '22-032604-001', '24-035288-001', '22-015577-002', '23-033304-001', 'FAV-1166-1', '000300-002', '037225-008', '22-025064-001', '22-017507-002', '22-012248-001', '22-028569-005', '000076-001', 'FAV-0235-3', '25_004231-003', '036536-001', '24_017662-006', '23-036928-001', '23-032370-004', 'FAV-0076-3', '035658-001', '22-027421-003', 'USDA-011578-005', 'FAV-0035-4', '000937-001', '037556-001', '004757-002', '24_033171-002', '033691-001', '003927-016', '24_009110-005', '22MM00467', '004982-001', 'FAV-1188-1', 'FAV-0696-1', '23-034369-002', '007118-006', '007921-006', '23-002693-030', '24-018153-001', '004295-002', 'USDA-010159-001', '22-041400-002', '038628-003', 'USDA-011039-003', '24_016437-004', '23-034300-001', '22-033874-001', '22-035512-002', '22-008890-004', 'FAV-0928-51', '23-026504-001', '24_009109-002', 'USDA-008372-001', '038319-002', '24_013395-001', '031285-008', '23-035568-002-original', 'FAV-0153-1', '007118-023', '007668-004', '22-007677-001', 'FAV-0906-3', 'FAV-0629-1', '033249-007', '033857-003', '22-036627-005', 'USDA-007696-004', '22-011778-001', '22-026980-006', 'FAV-414-08', '23-005532-001', '002650-002', '24-013706-002', '22-026557-001', '24_010330-006-300', '23-036744-001', '22-013053-001', '009022-005', 'B2408700-PBS-9', '24_009586-003', '23-005695-001', 'FAV-1616-1', 'FAV-0029-2', '24_009109-006', '24_019476-001', '23-027703-008-original', '037410-004', '005339-002', '22-042011-001', '037225-012', '002325-001', '009285-002', 'FAV-0266', '24_019886-006', 'USDA-008980-001', '24-016669-001', '23-039417-007-original', '22-035724-001', 'FAV-1385-1', 'W22-162', '002', 'W23-939A', '22-041130-005', '22-007391-001', '037571-001', '004132-001', '22-013490-001', '032013-001', '031862-006', '22-027995-002', '22-013445-001', 'USDA-012056-005', '036124-002', '006506-001-R', '24_028248-001', '22-017713-001', 'FAV-1188-2', 'FAV-04602', '24-018153-002', '007118-051', '007627-002', '007549-134', '008088-005', '007458-001', '23-034287-002-original', '24_009497-005', '23-034416-018-original', '22-039971-001', '23-035616-001', '23-030994-006-original', '037225-064', '005508-004', '22-033401-002', 'FAV-0582-1', '004227-001', 'FAV-0446-2', '23-034943-001-original', '23-008517-001', '22-039758-001-3', 'OH22-7075', '22-015759-003', '25_004231-002', '24-010303-002', '036832-002', '23-000279-001', '24_018151-005', '22-013369-001', '22-037438-001', 'FAV-0053-25', 'USDA-012771-002', '23-003717-001', '22-014327-003', '23-030961-001', '23-015040-001', '23-014706-004-original', 'FAV-0904-6', '032658-002', '22-024871-011', '22-016599-003', '028759-002', '24_023570-001', '23-002762-018', '007841-002', '013021-011', '027662-001', 'FAV-0145-1', '23-009044-004-original', '025747-004', '22-032511-063-R', 'W22-623', '22-032045-001', 'FAV-1528-2', '22-040790-001', 'OTH-0134-7', '22-009058-002', '028495-001', '22-024602-001', '24_020284-005', 'USDA-008982-002', '23-005533-022', 'FAV-0956-2', 'FAV-1258-18', 'W22-750A', 'FAV-0068-6', '007813-004', '24_020731-006', '23-003283-001', 'FAV-0118-3', 'USDA-011101-007', '22HP00127', '22-025261-003', '22-010991-002', '24_010513-002', '22-030855-002', '24_020797-002', '23-032269-046-original', '24_015457-003', '23-030180-001', '078707-24-1', '24_018871-003', 'FAV-1621-1', 'FAV-0353-2', '22-026981-001', '24_019381-007', 'FAV-0053-44', '012377-009', '24_010202-012', '22-016611-001', '036093-002', '22-011521-003', '22-016599-009', '24_008749-002', 'FAV-0856-9', '24-017049-003', '23-037960-001', '22-014336-007', '22-016599-006', '24_035006-003', '22-030915-001', '22-037517-003', '23-033231-002', '006012-005', '008882-002', '24-004649-001-original', '021589-001', '22-010611-001', '004290-004', 'AIVPHL-203', '22-015805-001', 'W232510072-3-1', '22-030784-001', 'FAV-0162-157', '24_032021-004', '035979-008', '003298-002', 'FAV-0934-1', '007118-011', '007118-093', '037225-010', '22-013321-002', '002363-003', '037219-034', '24_022172-001', '005481-006', '004757-013', '24_017652-021', '24_024948-001', '007627-001', 'W22-404A', '007549-009', 'FAV-0181-1', '22-036614-001', '24_018772-013', '24-016003-002', '22-031351-010-R', 'AIVPHL-876', '24-010928-002-original', '036402-001', '003370-001', '030030-003', 'AIVPHL-1388', '22-027406-001', '23-015073-001', '23-013078-005', '23-039991-002-original', 'USDA-010682-004', '23-036561-001', '22-038785-001-R', '22-025319-002', '004637-006', '004294-005', '22-029125-003', 'USDA-001329-001', '006140-001', '24_018029-005', '24-005705-002-original', '24-020796-004', '034196-002', '22-039436-012', 'USDA-012022-002', '22-039688-006', '23-029312-002-original', '23-001397-019', '24_033004-001', '24_009495-010', '037821-002', '005857-002', 'USDA-008506-003', '031666-012', '24_020797-012', '23-035001-003-original', 'USDA-011517-010', '22-030338-001', '034002-001', '23-013078-031', '23-039481-004-original', '006260-001', '23-034856-002', '24-037488-003', '22-013015-001', '22-009720-001', '24_016288-007', '000481-001', 'FAV-0122-4', 'AIVPHL-2926', 'FAV-1683-1', '006331-002', '22-015309-001', '22-031261-003', 'AIVPHL-2624', '038993-001', '035979-001', '22-030423-040', 'B2410989-URINE-54', '22-026137-025', '24-037988-003', '24_027655-001', '22-014968-006', 'W24-1068B', '22-040462-002', '22-014339-004', 'USDA-010129-001', '23-004808-007', '24-034441-003', 'FAV-0704-1', '22-011101-008', '036403-002', 'CEIRR-303', '22-037519-002', 'FAV-0029-5', '22-032950-002', '22-016611-016', '035634-001', 'USDA-011569-004', '22-016077-001-original', '018721-001', '22-021121-001', 'FAV-0489-2', '22-014336-002', '019981-001', '007118-082', 'FAV-0833-65', '001480-003', 'USDA-007696-002', '24_034194-003', 'AIVPHL-1412', '001318-001', '009172-001', 'FAV-1150', '24_009310-005', '001886-001', '007729-007', 'FAV-0268-18', '22-035476-001', '22-039688-004', '24_010202-009', '22-032452-002', '22-016602-004', '51_LUL', 'FAV-0876-2', '22-031163-004-R', '014126-016', '009367-002', '23-034181-001-original', 'FAV-0268-24', 'FAV-0218-1', '22-014275-003', '22-036105-011', '24-004245-002-original', '23-034666-001', '037166-001', 'FAV-0855-1', '22-027571-001', '008067-006', '037225-066', '24_018271-001', 'USDA-005646-001', 'FAV-0429-2', '22-027231-001', '22-012098-001', '23-025001-003', '004847-001', 'USDA-009411-001', 'AIVPHL-764', '24_034008-004', 'FAV-0833-85', 'W22-1223C', '24_008765-001', 'FAV-0568-3', '24_031329-001', 'FAV-1053-1', 'OTH-0097-1', '24-002154-009-original', '22-019264-001-original', '037578-001', '24-020796-010', '22HP00148', '22-015791-001', '24_009028-002', '22-036798-001', 'FAV-0023-2', 'FAV-0568-1', '034807-001', 'FAV-0923-7', 'FAV-1679-2', 'FAV-0860-2', '008065-005', '001', 'USDA-003417-053', 'FAV-0561-6', '23-025001-004', '033522-001', 'USDA-008571-002', '24-037521-002', 'FAV-1166-15', '034220-002', 'FAV-1628-9', '22-020416-014', 'FAV-0216-4', 'FAV-0903-2', '22-031280-005-R', '035890-001', '24_015457-001', '22-032921-003', 'FAV-0833-80', 'FAV-0829-12', '035979-002', '001518-001', 'USDA-013148-003', '23-038881-005-original2', '031285-012', '22-010848-002', 'USDA-002768-003', '003044-001', '24_017662-002', 'USDA-009207-003', '23-008247-002-original', 'USDA-011695-001', '014126-010', 'USDA-011237-001', '036395-004', 'FAV-1166-8', '22-010312-001', '005882-006', '22-009227-001', '032668-001', '24_031617-001', 'AIVPHL-292', '24_031165-008', '24-004334-027-original', '24_021996-002', '005224-001-R2', '23-004704-001', 'USDA-011789-003', 'USDA-010995-006', '038656-004', 'USDA-003935-013', 'USDA-005893-002', '22-014295-003', 'FAV-0301-4', '026550-001', '22-033000-001', '22-011871-007', 'FAV-0300-06', 'FAV-1366-5', 'AIVPHL-1433', '24-036590-007', 'FAV-1595-1', '22-014371-001', '24_015837-001', '23-002762-002', 'AIVPHL-2573', 'FAV-0652-1', 'FAV-0149-1', 'FAV-0400-1', 'FAV-0802-84', 'FAV-0918-19', '22-008702-002', 'FAV-0053-33', '25-000074-001', '009374-001', 'FAV-0802-11', '24_012341-004', 'FAV-0802-65', '22-018476-001', '002234-001', 'GBBG_20220615_1', '038445-001', 'USDA-011517-009', 'FAV-0527-5', '22-014534-001', 'FAV-0035-5', '22-015036-002', '004213-001', '036005-002', '22-037712-001', '001989-004', '034998-001', '23-032410-002', 'USDA-007919-003', '22-028597-001', 'FAV-0346-1', '24-035157-002', '22-021035-001', '22-013056-002', '035889-003', '22-033929-001', 'FAV-0802-85', '22-014025-001', '009038-001', 'FAV-0863-5', '22-017052-005', '000046-001', 'FAV-1077-1', '002070-002', 'FAV-0899-4', '000049-003', '22-009985-001', '22-015023-001', '012377-001', '22-032745-034', '24-013169-001', '22-033190-002', '004050-002', '24_017152-001', '23-034842-001', '24-003120-021-original', '004381-001', '24_034007-003', '035603-001', 'FAV-0632-1', 'USDA-007915-001', 'USDA-004008-010', '22-033477-002', '22-041771-002', 'USDA-009941-001', 'FAV-0895-10', '004865-019', '22-010992-002', '24_009108-007', '23-007957-003-original', '24-013169-002', 'FAV-0687-2', 'FAV-0469-1', '22-018929-001', '22-040812-001', 'FAV-0340-12022', '027656-001', '23-033857-001', '007549-064', '24_018028-007', '037427-003', '003805-002', 'FAV-0833-61', 'FAV-1443-1', '24_017152-014', '031666-004', '23-001085-001', 'FAV-1444-2', 'FAV-1294-10', 'BI-MD-034', '004631-001', '029612-001', 'FAV-0575-8', 'OTH-0142-5', '23-000949-001', '22-010994-001', '22-013275-001', 'FAV-0376-1', '23-034577-002', 'FAV-1173-3', 'FAV-0903-1', '029620-001', '037225-061', '22-016645-002-original', 'USDA-012000-003', '004677-002', 'USDA-011875-001', '008328-002', 'FAV-0268-32', '007549-056', 'FAV-0772-1', '23-038719-001-original', '003579-001', '24_022855-001', '22-012045-001', '24_020731-004', 'FAV-0141-1', '038180-001', '035563-001', '008296-002', 'B24OSU-494', '037225-031', '23-038918-003-original', 'USDA-009478-012', 'FAV-0410-1', '037986-004', 'FAV-0934-76', 'USDA-009593-002', 'FAV-0895-3', '24_020712-002', 'FAV-0459-1', '23-038112-052-original', '23-037500-001-original', 'FAV-1035-2', '22-024871-001', '23-037817-001', '002248-002', '22-030321-001', '028975-001', '22-017864-001', '007609-010', '22-015054-004', '24-020796-002', '24_033011-005', '22-029081-002', '036190-003', '24_018028-014', '008592-001', 'USDA-011426-001', 'FAV-0660-14', '008819-001', '24_015975-008', '038653-003', '23-001466-002', '22-035144-001', '22-042014-001', '22-012407-001', '22-038802-001', 'USDA-010663-003', 'FAV-0634-1', '24_014338-008', '24-008552-023', '006013-002', '028537-003', '22-006948-001', '22-017013-001-original', '22-022526-013', '23-001397-014', '22-014532-002', '006543-001', 'FAV-0840-3', '007626-002', '22-029397-001', '23-000336-001', '22-035580-001', '22-028981-005', '23-033311-005-original2', '036009-002', '035660-001', '24_032656-001', '003574-003', '22-016602-002', '23-013393-001', '22-036753-054-R', '23-003143-001', '22-015926-001', '004081-001', '24-004334-002-original', '037236-001', 'FAV-1294-14', '003807-016', '036542-003', 'FAV-1628-19', '22-014430-001', '004076-001', '23-033113-002', '24-035260-002', '23-033721-004', '23-040173-006-original', '23-008103-002-original', '009864-004', 'FAV-0792-1', '008666-004', '23-015846-001-original', '001332-002', '23-001514-001', '005292-001-R2', '23-031337-002', '003858-001', '22-027923-002', '22-016599-007', 'USDA-004372-001', '037219-028', '24-012234-002', 'FAV-0876-3', '24_033514-001', '014126-040', '24_010661-005', '039016-002', '007729-023', '24_017584-003', '24-015328-002', 'FAV-0122-1', 'USDA-010663-023', '22-029888-002', 'W24-005', 'FAV-0056-3', 'W232140074-1', 'FAV-1004-2', 'USDA-011036-002', '005783-001', '22-011792-002', '24_009309-004', '22-008239-002', '007118-061', '22-014536-007', '002644-002', '22-034199-001', '24-004559-001-original', '22-017510-001', 'AIVPHL-2057', '22-032401-001', 'FAV-0833-19', '24_034694-003', 'FAV-1266-1', '002898-003', 'IZ22_0891', 'USDA-007376-007', '23-031346-002', 'FAV-0860-4', 'USDA-011517-008', 'FAV-0527-4', 'FAV-0899-3', 'USDA-010927-001', 'AIVPHL-2530', 'CEIRR-287', 'AIVPHL-982', '037804-001', '22-025788-001', '22-037930-001', '004134-001', 'FAV-0505-40', '22-017872-001-original', '000096-002', '006508-008-R', '22-013871-001', '22-010639-001', '22-034331-001-R', '22-033002-001', '24-007313-001-original', '22-009605-001', 'FAV-0660-8', 'FAV-1166-16', '23-033841-002', 'COTE_20220612_1', 'AIVPHL-3101', 'FAV-0135-3', 'USDA-011871-001', '22-036139-032', '22-037213-001', '004499-003', '23-005533-020', 'FAV-0002-2', '24_027490-001-R2', '22-021733-010', '22-031098-001-R', '24_016134-232', '22-026130-001', '22-010765-001', 'FAV-0505-08', '24_026219-013-R2', 'W241070094-13', '23-011213-001', '23-033233-001', 'FAV-0802-74', '22MM00463', '22-022596-002', 'USDA-010035-001', '23-023703-002', '24_027097-001', '23-038669-001-original', 'AIVPHL-213', '23-040997-002-original', '22-030201-001', '24_014336-010', '23-036928-002', 'USDA-011578-007', '004295-003', '22-024357-001', 'FAV-0039-1', '22-031162-001-R', '23-029624-001', '034808-001', '23-037049-001', 'USDA-006020-001', '24-000133-004-original', '008065-001', 'USDA-008935-001', 'FAV-0855-5', 'USDA-010027-002', '035907-001', '028537-004', '22-010127-002', 'USDA-008719-003', '078707-24-12', '22-036623-001-R2', '24_016437-017', 'USDA-007184-001', '22-041085-001', '24_031085-001', 'FAV-0824-01', '003592-003', '000050-001', '036413-003', '22-029889-007', '24_019886-004', 'USDA-012125-003', '24_009491-007', 'FAV-1294-3', '036093-001', '004425-001', '038987-006', '24_010661-004', '24_015675-002', 'FAV-0918-33', 'FAV-0918-30', '22-037031-004-R', '23-005533-027', 'W24-219B', 'FAV-0216-06', '22-013517-010', 'USDA-008745-001', 'AIVPHL-133', 'W241220059-15', '23-002762-013', '001388-002', '25-000137-001', '001670-001', '007118-064', 'USDA-009478-011', 'FAV-0474-3', '24_009110-010', '007118-092', '22-012331-001', '22-028071-001', '22-029882-002', '013021-007', '25_000604-002', 'FAV-0282-4', '23-004706-001', '026360-011', '003803-003', '003352-005', '038123-002', 'FAV-1633-2', '22-024975-001', '033224-003', '23-038109-032-original', '22-016457-010', 'USDA-011141-003', '22-029146-001', '027654-001', '033249-002', '22-020665-001-original', 'USGS-0890', '24-034804-001', '24_009497-007', 'FAV-0469-10', '24_016523-025', '23-033638-008', '22-030915-002', '22-035250-001', 'AIVPHL-85', '22-033918-001', '22-036181-002', '036542-006', '22-033479-023', '22-027995-013', '22-034833-001', '035860-001', 'AIVPHL-188', '004865-003', 'FAV-0833-57', '22-033004-001', 'AIVPHL-669', '22-032745-046', '24-020793-001', '22-020399-001-original', 'FAV-1332-2', 'AIVPHL-1125', '001329-004', '22-037240-002-R', '24_018028-005', '24_031165-011', '22-036181-003', '23-001041-002', 'FAV-0559-1', '22-015816-001', '24_034235-001', '22-027419-001', '036407-001', '031663-003', 'AIVPHL-225', 'FAV-0833-52', '006507-001-R', '22-006569-001', '23-036530-005-original', 'USDA-011810-001', '014130-001', 'FAV-1658-3', '009616-002', '24_023561-001', 'USDA-012759-003', 'FAV-1068-22', 'FAV-1051-2', '22-009934-002', '24_032631-001', '006704-001', '22-035956-007', '24_032027-001', '22-027793-001', '028305-002', 'FAV-0438-2', '24_010354-001', 'W22-619A', '004339-001', '22-010085-001', '035842-001', '22-038546-001', 'AIVPHL-71', '22-030556-005', '036550-004', 'FAV-0856-18', '007119-011', '033974-001', 'IZ22_0627', '007549-035', '23-038130-006-original', '004415-014', '23-000497-001', '23-035003-003-original', '22-010671-001', '22-032661-001', '23-005533-021', 'USDA-010682-001', '009058-003', '22-015197-002', '22-028571-001', '22-030404-001-R', '22-039694-001', '24_010354-006-300', '037219-021', '24-014975-001', 'FAV-0903-3', '22-021733-007', '24_010661-002', 'USDA-012040-003', 'FAV-0761-1', '22-009839-001', '031666-030', '24-003250-001-original', '22-017348-002-original', '24_024710-004', '003385-001', '017048-011', 'FAV-0688-2', '22-034812-002', '005865-001', 'AIVPHL-56', 'FAV-0802-3', 'AIVPHL-925', '007813-006', '24-018507-002', '22-009326-002', '22-042020-005', '22-012454-001', '22-024351-001', 'W23-949A', '22-016060-001', '23-032152-001', '003062-007', 'FAV-0349-2', '032635-001', 'USDA-010663-004', 'FAV-0104-4', '23-038593-002-original', 'W241220059-3', '24_018766-007', '24-031667-003', '22-006945-001', 'USDA-007918-001', 'W24-974A', 'FAV-0833-71', 'FAV-0684-1', '032191-001', '22-014003-002', 'USDA-010936-001', '23-005533-013', '22-038703-001', '22-037634-001', '020176-005', '23-016828-001', '22-013222-004', '063224-24-1', '22-009981-004', '22-033260-001', 'FAV-1294-4', '23-032220-005', '22-027484-001', '037410-011', 'W22-723A', '22-000345-001', '009028-002', '24-008850-002', '028356-002', '23-007063-001-original', 'FAV-0474-2', '23-036678-012-original', '039394-001', '22-013488-001', 'FAV-1033-9', '23-022051-007-original', '038123-005', '006346-001', '22-016611-002', '22-013517-002', '24-037429-001', '23-035544-001', 'FAV-0288', 'FAV-1006-4', '037225-046', '22-032951-001', '037218-002', '003128-003', 'FAV-1688-1', 'BI-MF-021', '22-037357-001', '23-000757-001', '24_016134-066', 'W23-930J', 'W22-723B', '22-014183-003', 'USGS-0226', 'FAV-1627-1', 'FAV-1623-1', 'USDA-007919-004', '22-028887-001', '24_016252-010', '23-034438-002', '008872-007', '006013-003', 'FAV-0860-6', '24_017652-002', '036358-001', '23-011452-002', '036542-004', '006263-005', '24_018028-019', 'USDA-008935-004', 'FAV-0053-31', '012168-002', '24_017478-005', '014126-058', '22-009287-002', '002402-006', 'AIVPHL-128', '037232-001', '23-001056-003', '22-041130-006', 'AIVPHL-58', '24_008767-001', '005542-001', '000807-001', '007471-001', '22-037940-001', 'USDA-011033-005', 'FAV-0239-2', '22-036621-002', 'FAV-0829-4', 'USDA-008384-004', 'FAV-0978-5', 'USDA-005153-004', '038625-001', '22-032677-004', 'FAV-0505-11', '22-015036-001', '007549-122', '24-012740-002-original', 'FAV-0218-2', '033249-001', '007807-002', '004295-006', '24_018334-006', '23-037336-001-original', '009321-002', 'W22-1215A', '22-009195-003', '007549-121', '23-001574-001', '23-037249-001', '004164-001', 'USDA-009481-017', '22-009286-002', '22-014378-001', 'FAV-0153-3', '23-034577-001', '22-014734-001', '22-016611-003', '23-029854-022-original', 'FAV-0368-3', '22-034097-002', '22-014366-001', '22-006118-001', '037410-010', '22-016567-001-original', '038619-001', '006816-001', '22-041131-001', '24-009027-004', '22-027421-004', 'FAV-1089-1', '23-035569-010-original', '24-011062-010', 'FAV-0575-13', '23-013080-001', 'FAV-0341-12022', 'FAV-0912-22', 'B24OSU-351', '002924-002', 'USDA-008152-003', '23-033317-020-original2', 'USDA-012030-001', '006251-002', 'USDA-003935-024', '24_016370-003', '24-037988-001', '22-017013-006-original', 'FAV-0550-1', '22-014035-001', '038654-002', '23-034082-001', '24-012046-002', '24_033973-001', 'FAV-0575-16', '002423-001', '035506-017', '004498-002', '22-017549-002-original', '22-012931-001', 'W23-889', '22-020377-003-original', '033692-001', '007066-001', 'FAV-0853-3', 'FAV-0179-10', '001073-002', '22-013447-001', '24_034697-002', '24-009116-002', 'USDA-011350-001', '22-024353-001', 'A240920343-90', '24_032050-001', '22-037670-001', 'FAV-1679-1', 'FAV-0505-30', 'AIVPHL-2038', '004792-001', 'USDA-011871-013', 'OTH-0150-1', 'FAV-0127-141A', '22-0

In [5]:
# Remove duplicates from GISAID/Andersen

print(len(metadata_segments))

for index, value in metadata_segments["Isolate"].items():
    if value in gisaid_andersen_isolates:
        metadata_segments = metadata_segments.drop(index)

print(len(metadata_segments))

metadata_segments

29400
29248

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV571926,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,1,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
1,PV571927,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,2,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
2,PV571928,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,3,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
3,PV571929,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,4,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
4,PV571930,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,5,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37035,OQ565628,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,4,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37036,OQ565629,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,5,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37037,OQ565630,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,6,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37038,OQ565631,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,7,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37039,OQ565632,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,8,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8

In [6]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title


# print(metadata_segments["GenBank_Title"].iloc[0])

# Get sequences and headers together
headers = []
isolates = []
sras = []
headers_seqs = {}
with open("sequences.fasta") as f:
    lines = f.readlines()
    for num, line in enumerate(lines):
        if line[0] == ">": # If this is a header
            if line.strip() not in headers: # And is not a header we've seen before
                header = line.strip() 
                # print(header)
                split_header = header.split("|")
                # print(split_header)
                headers.append(header) 
                if num < len(lines): # If we're not at the last line
                    # for i, l in enumerate(lines[num + 1:]):
                    i = num
                    sequence = ""
                    # print(lines[i])
                    # print(lines[i + 1])
                    while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                        sequence = sequence + lines[i + 1].strip()
                        i += 1
                    headers_seqs[header] = sequence # Add next lines to sequences
                # name = split_header[-1] # Last part gives GenBank name, with segment and isolate
                isolate = split_header[2]
                isolates.append(isolate)
                sra = split_header[7]
                sras.append(sra)
    f.close()



# print(mask_all.all(axis=1))

In [7]:
# Double-check de-duplication
mask = metadata_segments["Isolate"].isin(isolates) # Check if isolate is in fasta
mask_sra = metadata_segments["SRA_Accession"].isin(sras) # Check if sra is in fasta

metadata_masked = metadata_segments[mask] # Some do not have isolates, so check sra too
metadata_masked_sra = metadata_segments[mask_sra]

merged_metadata = metadata_masked.merge(metadata_masked_sra, how="outer")
merged_metadata = merged_metadata.drop_duplicates(keep="first")

print(len(headers_seqs))
print(len(merged_metadata))

75007
29248

In [8]:
# Add sequences to a dataframe 
headers_seqs_df = pd.DataFrame.from_dict(headers_seqs, orient="index")
headers_seqs_df = headers_seqs_df.reset_index()
headers_seqs_df["GenBank_Title"] = headers_seqs_df["index"].apply(lambda x: x[1:].split("|")[-1])
headers_seqs_df = headers_seqs_df.rename(columns={0: "Sequence", "index": "Header"})

# Add sequences to the dataframe
metadata_seqs = merged_metadata.merge(headers_seqs_df, on="GenBank_Title", how="left")

print(metadata_seqs)

      Accession      Organism_Name GenBank_RefSeq         Assembly  \
0      OQ565625  Influenza A virus        GenBank  GCA_039342815.1
1      OQ565626  Influenza A virus        GenBank  GCA_039342815.1
2      OQ565627  Influenza A virus        GenBank  GCA_039342815.1
3      OQ565628  Influenza A virus        GenBank  GCA_039342815.1
4      OQ565629  Influenza A virus        GenBank  GCA_039342815.1
...         ...                ...            ...              ...
29251  PV573369  Influenza A virus        GenBank  GCA_049972655.1
29252  PV573370  Influenza A virus        GenBank  GCA_049972655.1
29253  PV573371  Influenza A virus        GenBank  GCA_049972655.1
29254  PV573372  Influenza A virus        GenBank  GCA_049972655.1
29255  PV573373  Influenza A virus        GenBank  GCA_049972655.1

      SRA_Accession                                         Submitters  \
0       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
1       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
2       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
3       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
4       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
...             ...                                                ...
29251   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29252   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29253   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29254   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29255   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                            Organization Org_location  \
0           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
1           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
2           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
3           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
4           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
...                                                  ...          ...
29251  USDA Animal Plant Health Inspection Service-Na...          USA
29252  USDA Animal Plant Health Inspection Service-Na...          USA
29253  USDA Animal Plant Health Inspection Service-Na...          USA
29254  USDA Animal Plant Health Inspection Service-Na...          USA
29255  USDA Animal Plant Health Inspection Service-Na...          USA

      Release_Date                 Isolate  ...  USA       Host  \
0       2023-03-08                VFAR-140  ...  NaN  Pelecanus
1       2023-03-08                VFAR-140  ...  NaN  Pelecanus
2       2023-03-08                VFAR-140  ...  NaN  Pelecanus
3       2023-03-08                VFAR-140  ...  NaN  Pelecanus
4       2023-03-08                VFAR-140  ...  NaN  Pelecanus
...            ...                     ...  ...  ...        ...
29251   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29252   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29253   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29254   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29255   2025-04-28  25-006346-001-original  ...   PA   Anatidae

      Tissue_Specimen_Source Collection_Date     BioSample   BioProject  \
0                       lung         2022-12  SAMN33745292  PRJNA944237
1                       lung         2022-12  SAMN33745292  PRJNA944237
2                       lung         2022-12  SAMN33745292  PRJNA944237
3                       lung         2022-12  SAMN33745292  PRJNA944237
4                       lung         2022-12  SAMN33745292  PRJNA944237
...                      ...             ...           ...          ...
29251                  feces      2025-02-20  SAMN47941403  PRJNA980729
29252                  feces      2025-02-20  SAMN47941403  PRJNA980729
29253                  feces      2025-02-20  SAMN47941403  PRJNA980729
29254                  feces      2025-02-20  SAMN47941403  PRJNA980729
29255                  feces      2025-02-20  SAMN47941403  PRJNA980729

                                           GenBank_Title size  \
0      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
1      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
2      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
3      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
4      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
...                                                  ...  ...
29251  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29252  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29253  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29254  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29255  Influenza A virus (A/goose/PA/25-006346-001-or...    8

                                                  Header  \
0      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
1      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
2      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
3      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
4      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
...                                                  ...
29251  >Influenza A virus |USA: PA|25-006346-001-orig...
29252  >Influenza A virus |USA: PA|25-006346-001-orig...
29253  >Influenza A virus |USA: PA|25-006346-001-orig...
29254  >Influenza A virus |USA: PA|25-006346-001-orig...
29255  >Influenza A virus |USA: PA|25-006346-001-orig...

                                                Sequence
0      AAAAGCARGTCAARTATATTCAATATGGAGAGAAKAAAAGARCTAA...
1      AGCGAAAGCAAACAAACCATTTGAATGGATGTCAATCCGAYTTTRC...
2      CAAATGCNNKTRCTGATTYAAAATGGAAGACTTTGTGCGACAATGC...
3      GTCAAAATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTG...
4      TAGATAATCACTCACTGAGTGRYATSCACATCATGGCRTMYCARGR...
...                                                  ...
29251  ATGGAAAACATAGTACTTCTTCTTGCAATATTTAGCCTTGTTAAAG...
29252  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
29253  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
29254  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
29255  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...

[29256 rows x 26 columns]

In [24]:
# Create FASTA files per Header

metadata_seqs["Partial_Header"] = metadata_seqs["Header"].apply(lambda x: "|".join(x.split("|")[:-1]))

unique_partial_headers = []
df_list = []
# Each header should repeat 8 times
for partial_header in metadata_seqs["Partial_Header"].values:
    if partial_header not in unique_partial_headers: # Only use the first occurence
        unique_partial_headers.append(partial_header)

print(len(unique_partial_headers)) # Sanity check

3657

In [25]:
for partial_header in unique_partial_headers:
    # Get smaller dataframe
    df = metadata_seqs[metadata_seqs["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    df = df[["Header", "Sequence"]]
    df = df.rename(columns={"Header": "full_header", "Sequence": "sequence"}) # For utils function
    # Make sure there are 8 segments
    if len(df) == 8:
        df_list.append(df)

In [49]:
# Make fasta files. Finally

os.chdir(temp_files)

for df in df_list:
    print(df)
    file_name = df["full_header"].apply(lambda x: "".join(x.split("|")[:-2])).values[0] + "temp.fasta"
    # Forbidden characters
    for c in [">", "/", "|", " ", ":", ",", "(", ")"]:
        file_name = file_name.replace(c, "")
    print(file_name)
    df_to_fasta(df, file_name, temp_files)

                                         full_header  \
0  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
1  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
2  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
3  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
4  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
5  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
6  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
7  >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...

                                            sequence
0  AAAAGCARGTCAARTATATTCAATATGGAGAGAAKAAAAGARCTAA...
1  AGCGAAAGCAAACAAACCATTTGAATGGATGTCAATCCGAYTTTRC...
2  CAAATGCNNKTRCTGATTYAAAATGGAAGACTTTGTGCGACAATGC...
3  GTCAAAATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTG...
4  TAGATAATCACTCACTGAGTGRYATSCACATCATGGCRTMYCARGR...
5  CCATTGGATCARTCTGTATGGTAATTGGGATAGTCAGYTTGATGCT...
6  TTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCT...
7  GCTACAGCWGGGTGACAAAAACATAATGGATTCCAACACTGTGTCA...
InfluenzaAvirusPeruVFAR-140H5N12022-12PelecanusGenBankSRR23852495SAMN33745292temp.fasta
                                          full_header  \
15  >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
14  >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
13  >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
8   >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
11  >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
10  >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
9   >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
12  >Influenza A virus |USA||H5N1|2024-03-16|Turdu...

                                             sequence
15  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
14  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
13  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
8   ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
11  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
10  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
9   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
12  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-16TurdusmerulaGenBankSRR28752446SAMN41019184temp.fasta
                                          full_header  \
23  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
22  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
21  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
16  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
19  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
18  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
17  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
20  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                             sequence
23  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
22  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
21  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
16  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
19  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
18  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
17  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
20  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752475SAMN41019211temp.fasta
                                          full_header  \
31  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
30  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
29  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
24  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
27  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
26  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
25  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
28  >Influenza A virus |USA||H5N1|2024-03-22|Felis...

                                             sequence
31  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
30  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
29  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
24  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
27  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
26  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
25  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
28  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-22FeliscatusGenBankSRR28752524SAMN41019206temp.fasta
                                          full_header  \
39  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
38  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
37  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
32  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
35  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
34  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
33  >Influenza A virus |USA||H5N1|2024-03-22|Felis...
36  >Influenza A virus |USA||H5N1|2024-03-22|Felis...

                                             sequence
39  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
38  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
37  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
32  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
35  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
34  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
33  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
36  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-22FeliscatusGenBankSRR28752523SAMN41019207temp.fasta
                                          full_header  \
47  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
46  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
45  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
40  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
43  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
42  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
41  >Influenza A virus |USA||H5N1|2024-03-20|Felis...
44  >Influenza A virus |USA||H5N1|2024-03-20|Felis...

                                             sequence
47  ATGGAGAGAATAAAGGAACTGAGAGATCTAATGTCACAGTCTCGCA...
46  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
45  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
40  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
43  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
42  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
41  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
44  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20FeliscatusGenBankSRR28752474SAMN41019212temp.fasta
                                          full_header  \
55  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
54  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
53  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
48  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
51  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
50  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
49  >Influenza A virus |USA||H5N1|2024-03-20|Icter...
52  >Influenza A virus |USA||H5N1|2024-03-20|Icter...

                                             sequence
55  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
54  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
53  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
48  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
51  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
50  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
49  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
52  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20IcteridaeGenBankSRR28752521SAMN41019208temp.fasta
                                          full_header  \
63  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
62  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
61  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
56  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
59  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
58  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
57  >Influenza A virus |USA||H5N1|2024-03-20|Colum...
60  >Influenza A virus |USA||H5N1|2024-03-20|Colum...

                                             sequence
63  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
62  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
61  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
56  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
59  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
58  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
57  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
60  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20ColumbidaeGenBankSRR28834855SAMN41100350temp.fasta
                                          full_header  \
71  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
70  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
69  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
64  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
67  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
66  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
65  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
68  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                             sequence
71  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
70  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
69  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
64  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
67  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
66  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
65  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
68  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752456SAMN41019228temp.fasta
                                          full_header  \
79  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
78  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
77  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
72  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
75  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
74  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
73  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...
76  >Influenza A virus |USA||H5N1|2024-03-21|Bos t...

                                             sequence
79  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
78  ATGGATGTCAATCCGACTTTACTCTTCTTGAAAGTTCCAGCGCAAA...
77  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
72  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
75  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
74  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
73  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
76  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-21BostaurusGenBankSRR28752455SAMN41019229temp.fasta
                                          full_header  \
87  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
86  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
85  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
80  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
83  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
82  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
81  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
84  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                             sequence
87  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
86  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
85  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
80  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
83  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
82  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
81  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
84  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752454SAMN41019230temp.fasta
                                          full_header  \
95  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
94  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
93  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
88  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
91  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
90  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
89  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
92  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...

                                             sequence
95  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
94  ATGGATGTCAACCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
93  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
88  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
91  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
90  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
89  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
92  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-13BostaurusGenBankSRR28752453SAMN41019231temp.fasta
                                           full_header  \
103  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
102  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
101  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
96   >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
99   >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
98   >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
97   >Influenza A virus |USA||H5N1|2024-03-13|Bos t...
100  >Influenza A virus |USA||H5N1|2024-03-13|Bos t...

                                              sequence
103  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
102  ATGGATGTCAACCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
101  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
96   ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
99   ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
98   ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
97   ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
100  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-13BostaurusGenBankSRR28752452SAMN41019232temp.fasta
                                           full_header  \
111  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
110  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
109  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
104  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
107  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
106  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
105  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
108  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                              sequence
111  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
110  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
109  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
104  ATGGAGAACATAGTACTACTTCTTGCAATAATTAGCCTTGTTAAAA...
107  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
106  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
105  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
108  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752463SAMN41019222temp.fasta
                                           full_header  \
119  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
118  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
117  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
112  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
115  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
114  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
113  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
116  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                              sequence
119  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
118  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
117  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
112  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
115  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
114  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
113  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
116  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752462SAMN41019223temp.fasta
                                           full_header  \
127  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
126  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
125  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
120  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
123  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
122  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
121  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
124  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                              sequence
127  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
126  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
125  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
120  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
123  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
122  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
121  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
124  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752461SAMN41019224temp.fasta
                                           full_header  \
135  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
134  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
133  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
128  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
131  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
130  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
129  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
132  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                              sequence
135  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
134  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
133  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
128  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
131  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
130  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
129  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
132  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752460SAMN41019225temp.fasta
                                           full_header  \
143  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
142  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
141  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
136  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
139  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
138  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
137  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
140  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                              sequence
143  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
142  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
141  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
136  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
139  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
138  ATGAATCCAAATCAAAAGATAACAACCATTGGATCAATCTGTATGG...
137  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
140  ATGGATTCCAACACTGTGTTAAGCTTTCAGGTAGACTGCTTTCTTT...
InfluenzaAvirusUSAH5N12024-03-20BostaurusGenBankSRR28752459SAMN41019226temp.fasta
                                           full_header  \
151  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
150  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
149  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
144  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
147  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
146  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
145  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
148  >Influenza A virus |USA||H5N1|2024-03-20|Bos t...

                                              sequence
151  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...
150  ATGGATGTCAATCCGACCTTACTCTTCTTGAAAGTTCCAGCGCAAA...
149  ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...
144  ATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTGTTAAAA...
147  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...