# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [2]:
# Paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 3): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")

# Dates and locations
start_date = "11-01-2021"
end_date = "12-05-2025"
date_range = start_date + "--" + end_date
locations = "Antarctica,North America,South America"

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" # "_Antarctica_North_America_South_America/"
andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"
os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

genotypes_df = pd.read_excel("genotype_key.xlsx")
genotypes = list(genotypes_df["Genotype"])

# serotype = "H5N1"
# genotypes = ["B3.13", "D1.1", "D1.3"]
# genotypes = ["B3.2", "B3.6", "B3.7", "B3.5", "A3", "B3.13", "D1.1", "D1.3"]

## Downloading Data

In [3]:


# browser = "Chrome"
# sleep_time = "3"
# locations = "South America"
# start_date = "07-01-2025"
# end_date = "07-25-2025"

In [4]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

    # Move downloaded files to saved downloads
    for dirpath, dirs, files in os.walk(downloads):
        if len(files) > 0: # If we have any files that need to be moved
            for file in files:
                file_name = os.path.join(dirpath, file)
                destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                try:
                    shutil.move(file_name, destination_path)
                except:
                    print("Error moving file", file_name)
                    continue 
        else: # If we don't have any downloaded files
            # Get files
            open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

            # Re-try 
            for dirpath, dirs, files in os.walk(downloads):
                if len(files) > 0: # If we have any files that need to be moved
                    for file in files:
                        file_name = os.path.join(dirpath, file)
                        destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                        try:
                            shutil.move(file_name, destination_path)
                        except:
                            print("Error moving file", file_name)
                            continue 
                break 
        break

## De-Duplication

In [263]:
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Isolate, as_index=False).size()
# print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Isolate")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments.head()

118144

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Cygnus atratus,NaN,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8

In [264]:
# # De-duplicate from Andersen using SRA Accession

# # If even one SRA Accession in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
# andersen_sras = []
# # Grab files
# for dirpath, dirs, files in os.walk(andersen):
#     for file in files:
#         file_name = os.path.join(dirpath, file)
#         if ".fasta" in file_name:
#             fasta_file = fasta_df_complete(file_name, states_ref) # Convert fasta file to dataframe
#             sra_accessions = fasta_file["Identifier"]
#             for value in sra_accessions.values:
#                 if "SRR" in value:
#                     andersen_sras.append(value)
#             isolates = fasta_file["Isolate_Id"]
#             for value in isolates.values:
#                 andersen_sras.append(value)
#             partials = fasta_file["Partials"]
#             for value in partials.values:
#                 andersen_sras.append(value)
#     break 

# # Grab more files
# # for dirpath, dirs, files in os.walk(andersen_dedup):
# #     for file in files:
# #         file_name = os.path.join(dirpath, file)
# #         if ".fasta" in file_name:
# #             fasta_file = fasta_df_complete(file_name, states_ref) # Convert fasta file to dataframe
# #             sra_accessions = fasta_file["Identifier"]
# #             for value in sra_accessions.values:
# #                 if "SRR" in value:
# #                     andersen_sras.append(value)
            
# metadata_segments["Partials"] = metadata_segments["Isolate"].apply(lambda x: partial_isolate(x) if x == x else x)
# # Remove duplicates from Andersen
# for value in andersen_sras: # to remove
#     if "SRR" in value:
#         metadata_segments = metadata_segments[metadata_segments["SRA_Accession"] != value]
    
#     metadata_segments = metadata_segments[metadata_segments["Isolate"] != value]
#     metadata_segments = metadata_segments[metadata_segments["Partials"] != value]
#     # print(value)
    
# print(len(metadata_segments))
# # metadata_segments
# # print(count)

## Add sequences to dataframe

In [265]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title | Accession

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

# Filter dataframe to only include filtered SRA accessions
# sequences_fasta = sequences_fasta[sequences_fasta["full_header"].str.contains("|".join(list(metadata_segments["SRA_Accession"].values)))]
# sequences_fasta["SRA_Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-4])
sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-1][:-1])

# Extract segment number so that we can add the correct sequences to the correct sample
sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on=["Accession", "Segment"])

118144
                                         full_header  \
0  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
1  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
2  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
3  >Influenza A virus |Brazil: SapucaiaSulBR|1246...
4  >Influenza A virus |Brazil: SapucaiaSulBR|1246...

                                            sequence   Accession  Segment
0  AGCRAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  PV659823.1        1
1  AGCRAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...  PV659824.1        2
2  AGCRAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...  PV659825.1        3
3  AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...  PV659826.1        4
4  AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...  PV659827.1        5
101856

In [266]:
# # Make sure H5N1 is the only serotype we have

# metadata_segments["serotype"] = metadata_segments["full_header"].apply(lambda x: re.search(r'H.N.', x).group(0))

# metadata_segments = metadata_segments[metadata_segments["serotype"] == serotype]

## Find genotype using old genoflu results or Andersen Lab genoflu output

In [268]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCRAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCRAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCRAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Carnegie,L., Ot...","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,1.0,2025-05-12,2025-12-04,ssRNA(-),8,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101851,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
101852,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
101853,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
101854,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
101855,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

In [269]:
genoflu_old = pd.read_csv("output.tsv", delimiter="\t")
genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"})
# print(genoflu_old)
metadata_segments["Partial_Header"] = metadata_segments["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
metadata_segments["Partial_Header"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(">", ""))
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
    metadata_segments["Partial_Header"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(c, "_"))
# metadata_segments["Accession_Root"] = metadata_segments["Accession"].values[0].split(".")[0]
# print(metadata_segments["Partial_Header"])

metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header") # .dropna(subset="SRA_Accession")
metadata_segments_new = metadata_segments.merge(genoflu_old,indicator = True, how='left', on="Partial_Header").loc[lambda x : x['_merge']!='both'] # .dropna(subset="SRA_Accession")

print(len(metadata_segments_old))
print(len(metadata_segments_new))

101992
168

In [270]:
metadata_segments_new

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,sequence,Partial_Header,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Date run,_merge
8,PV660431.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
9,PV660432.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,PV660433.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,PV660434.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,PV660435.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100575,OQ747867.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100579,OQ747877.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100583,OQ747893.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100595,OQ747888.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100599,OQ747899.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [281]:
os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"})

metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
metadata_segments_known = pd.merge(metadata_segments_old, metadata_segments_known_andersen, how="left") # .drop_duplicates(keep="last", inplace=True) # Since we know both of these

print(genoflu_andersen)

    Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0  PQ135274.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
1  PQ135275.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
2  PQ135276.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
3  PQ135277.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
4  PQ135278.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
5  PQ135279.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
6  PQ135280.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
7  PQ135281.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987

     BioProject      Organism_Name                         Species  \
0  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
1  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
2  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
3  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
5  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
6  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
7  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                 Genus            Family  ... Date run     _merge  \
0  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
5  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
6  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
7  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                  date       File Name  Genotype  \
0  2025-05-09_10-48-12  SRR29694483.fa     B3.13
1  2025-05-09_10-48-12  SRR29694483.fa     B3.13
2  2025-05-09_10-48-12  SRR29694483.fa     B3.13
3  2025-05-09_10-48-12  SRR29694483.fa     B3.13
4  2025-05-09_10-48-12  SRR29694483.fa     B3.13
5  2025-05-09_10-48-12  SRR29694483.fa     B3.13
6  2025-05-09_10-48-12  SRR29694483.fa     B3.13
7  2025-05-09_10-48-12  SRR29694483.fa     B3.13

                       Genotype List Used, >=98.0%_y  \
0  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
1  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
2  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
3  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
4  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
5  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
6  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...
7  NA:ea1, NP:am8, PA:ea1, MP:ea1, NS:am1.1, PB1:...

                        Genotype Sample Title List_y  \
0  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
1  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
2  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
3  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
4  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
5  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
6  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...
7  ea1:22-003707-003:NA, am8:23-032005-001:NP, ea...

                       Genotype Percent Match List_y  \
0  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
1  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
2  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
3  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
4  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
5  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
6  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...
7  98.94%, 99.40%, 99.02%, 98.78%, 99.28%, 99.56%...

       Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
1  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
2  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
3  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
4  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
5  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
6  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report
7  15, 9, 21, 12, 6, 10, 24, 27         Ran on FASTA - No Coverage Report

[8 rows x 48 columns]
      SRA_Accession                 date       File Name  \
0       SRR30789580  2025-05-09_10-49-10  SRR30789580.fa
1       SRR32973809  2025-05-09_10-52-30  SRR32973809.fa
2       SRR32125669  2025-05-09_10-47-22  SRR32125669.fa
3       SRR31597237  2025-05-09_10-47-24  SRR31597237.fa
4       SRR31605135  2025-05-09_10-47-38  SRR31605135.fa
...             ...                  ...             ...
13280   SRR36212538  2025-11-28_05-40-32  SRR36212538.fa
13281   SRR36212539  2025-11-28_05-40-32  SRR36212539.fa
13282   SRR36212540  2025-11-28_05-40-31  SRR36212540.fa
13283   SRR36212541  2025-11-28_05-40-32  SRR36212541.fa
13284   SRR36212542  2025-11-28_05-40-17  SRR36212542.fa

                                                Genotype  \
0      Not assigned: Only 0 segments >98.0% match fou...
1                                                   D1.3
2                                                  B3.13
3                                                  B3.13
4                                                  B3.13
...                                                  ...
13280                                               D1.1
13281                                               D1.1
13282  Not assigned: Only 7 segments >98.0% match fou...
13283                                               D1.1
13284                                               D1.1

                             Genotype List Used, >=98.0%  \
0                                        PB1:am4, PA:ea1
1      PB1:ea3, HA:ea3, PB2:am24, NP:am13, NS:ea3, PA...
2      MP:ea1, PA:ea1, HA:ea1, NP:am8, PB2:am2.2, NA:...
3      NP:am8, PB2:am2.2, NA:ea1, MP:ea1, NS:am1.1, P...
4      HA:ea1, NP:am8, PB1:am4, NS:am1.1, PA:ea1, MP:...
...                                                  ...
13280  PA:am4, HA:ea3, NS:ea3, PB2:am24, NA:am4N1, PB...
13281  NS:ea3, NP:am13, PB1:ea3, PB2:am24, NA:am4N1, ...
13282  PB1:ea3, HA:ea3, MP:ea3, NP:am13, NS:ea3, PB2:...
13283  NP:am13, NA:am4N1, PB1:ea3, HA:ea3, MP:ea3, NS...
13284  NS:ea3, NP:am13, PA:am4, NA:am4N1, MP:ea3, PB1...

                              Genotype Sample Title List  \
0      am4:23-001855-001:PB1, ea1:22-003707-003:PA, a...
1      ea3:22-013001-001:PB1, ea3:22-013001-001:HA, a...
2      ea1:22-003707-003:MP, ea1:22-003707-003:PA, ea...
3      am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...
4      ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
...                                                  ...
13280  am4:24-030039-001:PA, ea3:22-013001-001:HA, ea...
13281  ea3:22-013001-001:NS, am13:24-030039-001:NP, e...
13282  ea3:22-013001-001:PB1, am4N1:24-030039-001:NA,...
13283  am13:24-030039-001:NP, am4N1:24-030039-001:NA,...
13284  ea3:22-013001-001:NS, am13:24-030039-001:NP, a...

                             Genotype Percent Match List  \
0         98.12%, 98.31%, 93.08%, 97.57%, 97.44%, 96.58%
1      99.21%, 99.59%, 99.56%, 99.47%, 98.93%, 99.58%...
2      98.98%, 98.88%, 98.41%, 98.93%, 98.68%, 98.86%...
3      99.06%, 98.60%, 98.86%, 98.98%, 99.05%, 99.07%...
4      98.47%, 99.06%, 99.47%, 99.17%, 99.02%, 98.98%...
...                                                  ...
13280  99.32%, 99.41%, 99.05%, 99.52%, 98.75%, 99.34%...
13281  98.81%, 99.53%, 99.16%, 99.56%, 98.78%, 99.35%...
13282  98.94%, 97.16%, 99.53%, 99.69%, 99.47%, 98.93%...
13283  99.60%, 98.76%, 99.21%, 99.53%, 99.80%, 98.93%...
13284  98.93%, 99.53%, 99.37%, 98.95%, 99.69%, 99.03%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0                  3, 3, 13, 5, 3, 4       Ran on FASTA - No Coverage Report
1          18, 7, 10, 8, 9, 9, 0, 19       Ran on FASTA - No Coverage Report
2      10, 24, 27, 16, 30, 16, 7, 12       Ran on FASTA - No Coverage Report
3      14, 32, 16, 10, 8, 20, 11, 26       Ran on FASTA - No Coverage Report
4      26, 14, 12, 7, 21, 10, 31, 15       Ran on FASTA - No Coverage Report
...                              ...                                     ...
13280    12, 10, 8, 11, 13, 15, 7, 3       Ran on FASTA - No Coverage Report
13281   10, 7, 19, 10, 14, 11, 12, 3       Ran on FASTA - No Coverage Report
13282      24, 40, 8, 3, 8, 9, 9, 15       Ran on FASTA - No Coverage Report
13283     6, 14, 18, 8, 2, 9, 14, 11       Ran on FASTA - No Coverage Report
13284    9, 7, 11, 11, 3, 22, 10, 10       Ran on FASTA - No Coverage Report

[13285 rows x 9 columns]

In [282]:
# metadata_segments_known = metadata_segments_known.dropna(subset="SRA_Accession")

metadata_segments_known["Genotype_y"]

0         Not assigned: Only 4 segments >98.0% match fou...
1         Not assigned: Only 4 segments >98.0% match fou...
2         Not assigned: Only 4 segments >98.0% match fou...
3         Not assigned: Only 4 segments >98.0% match fou...
4         Not assigned: Only 4 segments >98.0% match fou...
                                ...
101987    Not assigned: Only 0 segments >98.0% match fou...
101988    Not assigned: Only 0 segments >98.0% match fou...
101989    Not assigned: Only 0 segments >98.0% match fou...
101990    Not assigned: Only 0 segments >98.0% match fou...
101991    Not assigned: Only 0 segments >98.0% match fou...
Name: Genotype_y, Length: 101992, dtype: object

In [ ]:
# metadata_segments_unknown = metadata_segments_new.drop("_merge", axis=1).merge(metadata_segments_known.drop("_merge", axis=1), indicator = True, how='left', on="SRA_Accession").loc[lambda x : x['_merge']!='both']
# metadata_segments_unknown = metadata_segments_new[~metadata_segments_new["SRA_Accession"].apply(tuple,1).isin(metadata_segments_known["SRA_Accession"].apply(tuple,1))]
# metadata_segments_unknown = pd.concat([metadata_segments_new, metadata_segments_known]).drop_duplicates(subset=["Accession", "Segment"], keep="last")

In [ ]:
metadata_segments_unknown = metadata_segments_new

In [293]:

metadata_segments_known["Genotype_y"]

0         Not assigned: Only 4 segments >98.0% match fou...
1         Not assigned: Only 4 segments >98.0% match fou...
2         Not assigned: Only 4 segments >98.0% match fou...
3         Not assigned: Only 4 segments >98.0% match fou...
4         Not assigned: Only 4 segments >98.0% match fou...
                                ...
101987    Not assigned: Only 0 segments >98.0% match fou...
101988    Not assigned: Only 0 segments >98.0% match fou...
101989    Not assigned: Only 0 segments >98.0% match fou...
101990    Not assigned: Only 0 segments >98.0% match fou...
101991    Not assigned: Only 0 segments >98.0% match fou...
Name: Genotype_y, Length: 101992, dtype: object

In [287]:
# metadata_segments_unknown = metadata_segments_unknown.dropna(subset="SRA_Accession")

metadata_segments_unknown

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,sequence,Partial_Header,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Date run,_merge
8,PV660431.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
9,PV660432.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
10,PV660433.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
11,PV660434.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
12,PV660435.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100575,OQ747867.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100579,OQ747877.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGAAGACTTTGTGCGACAATGCTTCAATCCAATGATTGTCGAGC...,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100583,OQ747893.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100595,OQ747888.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
100599,OQ747899.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

## Create FASTA files of unknown genotypes using deduplicated sequences

In [217]:
# # Create 1 fasta file per header
# metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))

# # Create list of dataframes
# df_list = []
# for partial_header in list(set(metadata_segments_unknown["Partial_Header"].values)): # Unique partial headers only
#     # Get smaller dataframe
#     df = metadata_segments_unknown[metadata_segments_unknown["Partial_Header"] == partial_header]
#     df = df.sort_values(by="Segment")
#     # Make sure there are 8 segments
#     if len(df) == 8:
#         # Forbidden characters in headers
#         for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
#             df["full_header"] = df["full_header"].apply(lambda x: x.replace(c, "_"))
#             df_list.append(df)

# # Make fasta files
# for df in df_list:
#     # Forbidden characters in file name 
#     title = df["Accession"].values[0].split(".")[0]
#     # for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
#     #     title = title.replace(c, "_")
#     df_to_fasta(df, title + ".fasta", temp_files)

In [288]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))

# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_unknown["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_unknown[metadata_segments_unknown["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # print(partial_header)
    # print(df["Segment"])
    # break 
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            # if c == "-":
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_unknown["Partial_Header"])

print(df_list[0]["full_header"])

# Make fasta files
for df in df_list:
    # Forbidden characters in file name 
    # title = df["Accession"].values[0].split(".")[0]
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    # print(df)
    # print(segments)
    # break 
    # for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
    #     title = title.replace(c, "_")
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        # print(one_row["full_header"])
        # print(segment)
        # break 
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)
    # break

8         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
9         >Influenza A virus |Brazil: SapucaiaSulBR|1246...
10        >Influenza A virus |Brazil: SapucaiaSulBR|1246...
11        >Influenza A virus |Brazil: SapucaiaSulBR|1246...
12        >Influenza A virus |Brazil: SapucaiaSulBR|1246...
                                ...
100575    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
100579    >Influenza A virus |Peru|A273|H5N1|2022-12||Ge...
100583    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
100595    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
100599    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
Name: Partial_Header, Length: 168, dtype: object
24    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
25    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
26    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
27    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
28    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
29    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
31    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
30    >Influenza_A_virus__Brazil__MateusLemeBR_1367_...
Name: full_header, dtype: object

## Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "output.tsv" is in the downloads directory.

In [305]:
'''
To run GenoFLU-multi, first change directories (and activate genoflu conda environment):

conda activate genoflu
cd GenoFLU-multi

And then call the python script:

python bin/genoflu-multi.py -f <FASTA_directory>
'''

'\nTo run GenoFLU-multi, first change directories (and activate genoflu conda environment):\n\nconda activate genoflu\ncd GenoFLU-multi\n\nAnd then call the python script:\n\npython bin/genoflu-multi.py -f <FASTA_directory>\n'

In [306]:
metadata_segments_unknown

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Partial_Header,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Date run,_merge,Strain
8,PV660431.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
9,PV660432.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
10,PV660433.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
11,PV660434.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
12,PV660435.1,GenBank,GCA_053847005.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100575,OQ747867.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
100579,OQ747877.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...
100583,OQ747893.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
100595,OQ747888.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
100599,OQ747899.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...

In [307]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t")

metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
    metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(c, "_"))

metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(">", ""))

metadata_segments_unknown["Strain"] = metadata_segments_unknown["Partial_Header"]

metadata_genoflu = metadata_segments_unknown.merge(output_genoflu, how="left", on="Strain", suffixes=('_left', '_right')) 

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill()

print(metadata_genoflu)

print(metadata_genoflu["Genotype_x"])

print(metadata_genoflu.columns)

      Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0    PV660431.1        GenBank  GCA_053847005.1           NaN           NaN
1    PV660432.1        GenBank  GCA_053847005.1           NaN           NaN
2    PV660433.1        GenBank  GCA_053847005.1           NaN           NaN
3    PV660434.1        GenBank  GCA_053847005.1           NaN           NaN
4    PV660435.1        GenBank  GCA_053847005.1           NaN           NaN
..          ...            ...              ...           ...           ...
163  OQ747867.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
164  OQ747877.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
165  OQ747893.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
166  OQ747888.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987
167  OQ747899.1        GenBank  GCA_041198955.1   SRR29694483  SAMN42278987

       BioProject      Organism_Name                         Species  \
0             NaN  Influenza A virus  Alphainfluenzavirus influenzae
1             NaN  Influenza A virus  Alphainfluenzavirus influenzae
2             NaN  Influenza A virus  Alphainfluenzavirus influenzae
3             NaN  Influenza A virus  Alphainfluenzavirus influenzae
4             NaN  Influenza A virus  Alphainfluenzavirus influenzae
..            ...                ...                             ...
163  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
164  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
165  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
166  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
167  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                   Genus            Family  ... Date run_left     _merge  \
0    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
1    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
2    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
3    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
4    Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
..                   ...               ...  ...           ...        ...
163  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
164  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
165  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
166  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only
167  Alphainfluenzavirus  Orthomyxoviridae  ...           NaN  left_only

                                                Strain  \
0    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
1    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
2    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
3    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
4    Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
..                                                 ...
163  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
164  Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...
165  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
166  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
167  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...

                                              Genotype  \
0    Not assigned: Only 4 segments >98.0% match fou...
1    Not assigned: Only 4 segments >98.0% match fou...
2    Not assigned: Only 4 segments >98.0% match fou...
3    Not assigned: Only 4 segments >98.0% match fou...
4    Not assigned: Only 4 segments >98.0% match fou...
..                                                 ...
163                                              B3.13
164                                              B3.13
165                                              B3.13
166                                              B3.13
167                                              B3.13

                     Genotype List Used, >=98.0%_right  \
0                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
1                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
2                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
3                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
4                     HA:ea1, NP:am1.1, NA:ea1, MP:ea1
..                                                 ...
163  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
164  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
165  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
166  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
167  PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...

                      Genotype Sample Title List_right  \
0    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
1    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
2    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
3    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
4    am2.1:22-009329-001:PB2, am2:22-031266-001:PB1...
..                                                 ...
163  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
164  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
165  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
166  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
167  am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...

                     Genotype Percent Match List_right  \
0    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
1    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
2    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
3    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
4    86.90%, 89.10%, 86.61%, 98.30%, 98.26%, 98.23%...
..                                                 ...
163  98.73%, 99.43%, 98.93%, 98.77%, 99.40%, 99.08%...
164  98.73%, 99.43%, 98.93%, 98.77%, 99.40%, 99.08%...
165  98.73%, 99.43%, 98.93%, 98.77%, 99.40%, 99.08%...
166  98.73%, 99.43%, 98.93%, 98.77%, 99.40%, 99.08%...
167  98.73%, 99.43%, 98.93%, 98.77%, 99.40%, 99.08%...

          Genotype Mismatch List_right  \
0    295, 246, 288, 29, 26, 25, 13, 72
1    295, 246, 288, 29, 26, 25, 13, 72
2    295, 246, 288, 29, 26, 25, 13, 72
3    295, 246, 288, 29, 26, 25, 13, 72
4    295, 246, 288, 29, 26, 25, 13, 72
..                                 ...
163       29, 13, 23, 21, 9, 13, 16, 7
164       29, 13, 23, 21, 9, 13, 16, 7
165       29, 13, 23, 21, 9, 13, 16, 7
166       29, 13, 23, 21, 9, 13, 16, 7
167       29, 13, 23, 21, 9, 13, 16, 7

    Genotype Average Depth of Coverage List_right       Date run_right
0               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
1               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
2               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
3               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
4               Ran on FASTA - No Coverage Report  2025-12-08_13-19-57
..                                            ...                  ...
163             Ran on FASTA - No Coverage Report  2025-12-08_13-19-47
164             Ran on FASTA - No Coverage Report  2025-12-08_13-19-47
165             Ran on FASTA - No Coverage Report  2025-12-08_13-19-47
166             Ran on FASTA - No Coverage Report  2025-12-08_13-19-47
167             Ran on FASTA - No Coverage Report  2025-12-08_13-19-47

[168 rows x 48 columns]
0      H5N1
1      H5N1
2      H5N1
3      H5N1
4      H5N1
       ...
163    H5N1
164    H5N1
165    H5N1
166    H5N1
167    H5N1
Name: Genotype_x, Length: 168, dtype: object
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header', 'Genotype_y',
       'Genotype List Used, >=98.0%_left', 'Genotype Sample Title List_left',
       'Genotype Percent Match List_left', 'Genotype Mismatch List_left',
       'Genotype Average Depth of Coverage List_left', 'Date run_left',
       '_merge', 'Strain', 'Genotype', 'Genotype List Used, >=98.0%_right',
       'Genotype Sample Title List_right', 'Genotype Percent Match List_right',
       'Genotype Mismatch List_right',
       'Genotype Average Depth of Coverage List_right', 'Date run_right'],
      dtype='object')

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_9864\3408649063.py:19: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill()

# Concatenate with known genotypes

In [308]:
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

metadata_genoflu = pd.concat([metadata_genoflu, metadata_segments_known])

metadata_genoflu.columns

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header', 'Genotype_y',
       'Genotype List Used, >=98.0%_left', 'Genotype Sample Title List_left',
       'Genotype Percent Match List_left', 'Genotype Mismatch List_left',
       'Genotype Average Depth of Coverage List_left', 'Date run_left',
       '_merge', 'Strain', 'Genotype', 'Genotype List Used, >=98.0%_right',
       'Genotype Sample Title List_right', 'Genotype Percent Match List_right',
       'Genotype Mismatch List_right',
       'Genotype Average Depth of Coverage List_right', 'Date run_right',
       'Genotype_official', 'Serotype', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'date', 'File Name', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y'],
      dtype='object')

In [309]:
metadata_segments_known # .dropna(subset="SRA_Accession")

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Genotype_official,Serotype
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101987,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101988,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101989,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101990,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101991,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2

In [310]:
metadata_genoflu = metadata_genoflu[["Accession", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header", "Strain"]]

metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] )
metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1])

# metadata_genoflu = metadata_genoflu.dropna(subset="SRA_Accession")
# metadata_genoflu = metadata_genoflu[~metadata_genoflu.duplicated(["Segment", "SRA_Accession"], keep=False).groupby(df["SRA_Accession"]).transform('sum').ge(8)]
# metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["SRA_Accession", "Segment"], keep="first", inplace=True)

metadata_genoflu # [metadata_genoflu["Genotype"]  == "B3.13"]

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name
0,PV660431.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,H5N1,1,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
1,PV660432.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
2,PV660433.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
3,PV660434.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
4,PV660435.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,Cygnus melancoryphus,2025-05-12,NaN,1246-N7-2025,Not assigned: Only 4 segments >98.0% match fou...,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,H5N1,5,NaN,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101987,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101988,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101989,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101990,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101991,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995

In [311]:
metadata_genoflu["Serotype"]

0         H5N1
1         H5N1
2         H5N1
3         H5N1
4         H5N1
          ...
101987    H5N2
101988    H5N2
101989    H5N2
101990    H5N2
101991    H5N2
Name: Serotype, Length: 102160, dtype: object

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [313]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['dunlin', 'snowy egret', 'coopers hawk', 'bald eagle', 'barred owl', 'fisher', 'alpaca', 'sula leucogaster', 'michigan', 'fancy chicken', 'western snowy plover', 'american crow', 'wild bird', 'blue-winged and cinnamon teal', 'hooded merganser', 'glaucous gull', 'south american sea lion', 'backyard chicken', 'nasua nasua', 'lesser white-fronted goose', 'raccoon', 'cormorant', 'otaria flavescens', 'merlin', 'eurasian collared dove', 'franklins gull', 'burrowing owl', 'cinnamon teal', 'cattle milk product', 'crested caracara', 'sanderling', 'great-tailed grackle', 'grackle', 'wild duck', 'eastern screech owl', 'emperor goose', 'vulture', 'american white pelican', 'mountain lion', 'chukar', 'gadwall duck', 'ostrich', 'numida meleagris', 'gallus gallus', 'skunk', 'striped skunk', 'great shearwater', 'common murre', 'teal', 'sparrow', 'iceland gull', 'willet', 'unknown', 'wood duck', 'turkey vulture', 'pelican', 'blue-winged teal', 'anatinae', 'green-winged teal', 'great grey owl', 'dog', 'pig', 'waterfowl', 'snowy owl', 'pelecanus thagus', 'irere', 'northern fulmar', 'northern gannet', 'mallard duck', 'atlantic white-sided dolphin', 'mottled duck', 'black-necked swan', 'black brant', 'dairy cattle', 'gallus gallus domesticus', 'broad-winged hawk', 'parrot', 'black swan', 'colorado', 'common eider', 'backyard bird', 'american green-winged teal', 'western grebe', 'western sandpiper', 'taiwanese chicken', 'black-billed magpie', 'cackling goose', 'california', 'pluvialis dominica', 'green heron', 'goat', 'tiger', 'quail', 'redhead', 'gannet', 'great horned owl', 'flamingo', 'black-crowned night-heron', 'polar bear', 'greater yellowlegs', 'great blue heron', 'blue jay', 'guinea fowl', 'peregrine falcon', 'razorbill', 'hawk', 'black bear', 'black skimmer', 'sandhill crane', 'ring-billed gull', 'bobcat', 'herring gull', 'domestic grower', 'common barn owl', 'lesser scaup', 'great egret', 'green winged teal', 'caspian tern', 'eared grebe', 'chicken', 'ferruginous hawk', 'owl', 'royal tern', 'thalasseus acuflavidus', 'crow', 'mergus', 'brown pelican', 'red-necked phalarope', 'mallard', 'gadwall', 'common loon', 'common tern', 'emu', 'short-eared owl', 'antofagasta', 'fregata magnificens', 'cattle', 'merganser', 'environment', 'common raven', 'feral cat', 'horned grebe', 'parasitic jaeger', 'american wigeon', 'gull', 'swine', 'gallus', 'manx shearwater', 'muscovy duck', 'serval', 'magpie', 'vulpes vulpes', 'great black-backed gull', 'dairy cow', 'red-shouldered hawk', 'house mouse', 'heron', 'american coot', 'aves', 'ruffed grouse', 'bufflehead', 'northwestern crow', 'snowy plover', 'pintail', 'domestic turkey', 'american wood stork', 'california gull', 'long-eared owl', 'great-horned owl', 'mute swan', 'wild turkey', 'surf scoter', 'gyrfalcon', 'louisiana', 'laridae', 'western screech owl', 'white-winged scoter', 'eagle', 'seabird', 'nannopterum brasilianus', 'gray seal', 'cygnus melancoryphus', 'pinniped', 'duck', 'redhead duck', 'panthera leo', 'neotropic cormorant', 'guineafowl', 'american goshawk', 'short-billed gull', 'snow goose', 'mink', 'south american tern', 'furnarius rufus', 'northern pintail', 'crane', 'rosss goose', 'american woodcock', 'golden eagle', 'fish crow', 'black turnstone', 'red fox', 'raven', 'american robin', 'backyard duck', 'dovekie', 'osprey', 'black-legged kittiwake', 'common merganser', 'guanay cormorant', 'peruvian booby', 'ohio', 'trumpeter swan', 'swainsons hawk', 'baikal teal', 'lesser snow goose blue-morph', 'peacock', 'raptor', 'lesser snow goose white-morph', 'brant', 'broiler breeders chicken', 'swan', 'procellaria aequinoctialis', 'south american fur seal', 'domestic cat', 'harbor seal', 'washington', 'sharp-shinned hawk', 'roseate spoonbill', 'texas', 'common goldeneye', 'pet food', 'backyard turkey', 'black scoter', 'lynx', 'thalasseus maximus', 'red-necked grebe', 'goose', 'peafowl', 'house sparrow', 'sandwich tern', 'white-winged dove', 'arctic tern', 'avian', 'layer chicken', 'ring-necked duck', 'sterna hirundo', 'american pelican', 'atlantic puffin', 'pheasant', 'greater scaup', 'lesser snow goose', 'raw pet food', 'black vulture', 'bovine', 'northern harrier', 'poultry', 'cygnus atratus', 'glaucous-winged gull', 'dendrocygna viduata', 'partridge', 'turkey', 'graylag goose', 'american kestrel', 'dove', 'silver pheasant', 'american-kestrel', 'pigeon', 'red-breasted merganser', 'rock pigeon', 'bos taurus', 'savannah cat', 'ring-necked pheasant', 'megascops choliba', 'black-crowned night heron', 'eider', 'collared plover', 'pekin duck', 'rough-legged hawk', 'guinea', 'southern elephant seal', 'double-crested cormorant', 'red-tailed hawk', 'greater white-fronted goose', 'rosy-billed pochard', 'california condor', 'buteogallus urubitinga', 'pelecanus', 'northern shoveler', 'american black duck', 'wyoming', 'tundra swan', 'dromaius novaehollandiae', 'domestic bird', 'dolphin', 'western gull', 'thayers gull', 'black swift', 'feline', 'barn owl', 'cat', 'american blue-winged teal', 'canada goose', 'nevada', 'south polar skua']
[]
               wild_avian domestic_avian               cattle        feline  \
0        great_horned_owl       pheasant            dairy_cow           cat
1            common_raven         turkey               cattle  domestic_cat
2           cooper's_hawk        chicken  cattle milk product     feral_cat
3            coopers_hawk          goose          bovine_milk        feline
4                 peafowl    guinea_fowl              bovine   domestic-cat
...                   ...            ...                  ...           ...
1080    cygnus buccinator            NaN                  NaN           NaN
1081    shoveler northern            NaN                  NaN           NaN
1082       whooping_crane            NaN                  NaN           NaN
1083      furnarius rufus            NaN                  NaN           NaN
1084  dendrocygna viduata            NaN                  NaN           NaN

       other_mammal       human         other      pet_food  new
0        deer mouse  washington         mixed      pet food  NaN
1       house_mouse      nevada   environment  raw pet food  NaN
2             skunk     wyoming  multispecies  raw_pet_food  NaN
3     striped_skunk  california       unknown      pet_food  NaN
4        norway rat    michigan             '           NaN  NaN
...             ...         ...           ...           ...  ...
1080            NaN         NaN           NaN           NaN  NaN
1081            NaN         NaN           NaN           NaN  NaN
1082            NaN         NaN           NaN           NaN  NaN
1083            NaN         NaN           NaN           NaN  NaN
1084            NaN         NaN           NaN           NaN  NaN

[1085 rows x 9 columns]

In [318]:
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Not assigned" if "Not assigned" in str(x) else x)
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"]

In [319]:
metadata_genoflu

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name,Host_Type,Years,Geo_Location_Abrv,Genotype
0,PV660431.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,cygnus melancoryphus,2025-05-12,,1246-N7-2025,Not assigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...,H5N1,1,,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,wild_avian,2025,Brazil-ES,Not assigned
1,PV660432.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,cygnus melancoryphus,2025-05-12,,1246-N7-2025,Not assigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,wild_avian,2025,Brazil-ES,Not assigned
2,PV660433.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,cygnus melancoryphus,2025-05-12,,1246-N7-2025,Not assigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGTACTGATCCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,wild_avian,2025,Brazil-ES,Not assigned
3,PV660434.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,cygnus melancoryphus,2025-05-12,,1246-N7-2025,Not assigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGGTTCATTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,wild_avian,2025,Brazil-ES,Not assigned
4,PV660435.1,Influenza A virus (A/Cygnus melancoryphus/Sapu...,cygnus melancoryphus,2025-05-12,,1246-N7-2025,Not assigned,Brazil: SapucaiaSulBR,>Influenza A virus |Brazil: SapucaiaSulBR|1246...,AGCAAAAGCAGGGTAGATAATCACTCACTGAGTGACATCCACATCA...,H5N1,5,,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...,A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...,wild_avian,2025,Brazil-ES,Not assigned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101987,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,,28159-398,Not assigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,,Influenza_A_virus__Mexico__Veracruz_28159_398_...,,A/chicken/Veracruz/28159-398/1995,domestic_avian,1995,USA-NM,Not assigned
101988,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,,28159-398,Not assigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,,Influenza_A_virus__Mexico__Veracruz_28159_398_...,,A/chicken/Veracruz/28159-398/1995,domestic_avian,1995,USA-NM,Not assigned
101989,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,,28159-398,Not assigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,,Influenza_A_virus__Mexico__Veracruz_28159_398_...,,A/chicken/Veracruz/28159-398/1995,domestic_avian,1995,USA-NM,Not assigned
101990,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,,28159-398,Not assigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,,Influenza_A_virus__Mexico__Veracruz_28159_398_...,,A/chicken/Veracruz/28159-398/1995,domestic_avian,1995,USA-NM,Not assigned
101991,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,,28159-398,Not assigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,,Influenza_A_virus__Mexico__Veracruz_28159_398_...,,A/chicken/Veracruz/28159-398/1995,domestic_avian,1995,USA-NM,Not assigned

In [320]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        "USA"
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


# Make new labels
names = ">" + metadata_genoflu["SRA_Accession"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names

print(metadata_genoflu["Geo_Location_Abrv"])

0         Brazil-ES
1         Brazil-ES
2         Brazil-ES
3         Brazil-ES
4         Brazil-ES
            ...
101987       USA-NM
101988       USA-NM
101989       USA-NM
101990       USA-NM
101991       USA-NM
Name: Geo_Location_Abrv, Length: 102160, dtype: object

## Rename segments and make complete FASTA files

In [321]:
# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"}
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)
        elif "Not assigned" in genotype:
            print(genotype)
            df = m_g[(m_g["Genotype"].str.contains("Not assigned"))] 
            df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = "Unassigned_" + segment
            print(pair)

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_9864\3807190993.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_9864\3807190993.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)

B5.1_PB2
Minor65_PB2
Minor105_PB2
Minor13_PB2
Not assigned
Unassigned_PB2
Minor81_PB2
Minor50_PB2
B3.13_PB2
D1.3_PB2
Minor19_PB2
Minor45_PB2
Minor12_PB2
B1.3_PB2
B3.7_PB2
B4.1_PB2
Minor34_PB2
Minor11_PB2
B3.3_PB2
A4_PB2
Minor63_PB2
Minor87_PB2
B1.2_PB2
Minor77_PB2
B3.2_PB2
B2.2_PB2
Minor90_PB2
B2.1_PB2
Minor102_PB2
A6_PB2
Minor08_PB2
Minor07_PB2
Minor04_PB2
B3.1_PB2
Minor101_PB2
Minor01_PB2
D1.2_PB2
D1.1_PB2
Minor91_PB2
Minor98_PB2
A5_PB2
A1_PB2
C2.1_PB2
B3.6_PB2
B3.10_PB2
B1.1_PB2
Minor14_PB2
B3.4_PB2
B3.5_PB2
A3_PB2
Minor94_PB2
Minor09_PB2
Minor104_PB2
Minor28_PB2
A2_PB2
B3.12_PB2
B5.1_PB1
Minor65_PB1
Minor105_PB1
Minor13_PB1
Not assigned
Unassigned_PB1
Minor81_PB1
Minor50_PB1
B3.13_PB1
D1.3_PB1
Minor19_PB1
Minor45_PB1
Minor12_PB1
B1.3_PB1
B3.7_PB1
B4.1_PB1
Minor34_PB1
Minor11_PB1
B3.3_PB1
A4_PB1
Minor63_PB1
Minor87_PB1
B1.2_PB1
Minor77_PB1
B3.2_PB1
B2.2_PB1
Minor90_PB1
B2.1_PB1
Minor102_PB1
A6_PB1
Minor08_PB1
Minor07_PB1
Minor04_PB1
B3.1_PB1
Minor101_PB1
Minor01_PB1
D1.2_PB1
D1.1_PB1
Minor91_PB1
Minor98_PB1
A5_PB1
A1_PB1
C2.1_PB1
B3.6_PB1
B3.10_PB1
B1.1_PB1
Minor14_PB1
B3.4_PB1
B3.5_PB1
A3_PB1
Minor94_PB1
Minor09_PB1
Minor104_PB1
Minor28_PB1
A2_PB1
B3.12_PB1
B5.1_PA
Minor65_PA
Minor105_PA
Minor13_PA
Not assigned
Unassigned_PA
Minor81_PA
Minor50_PA
B3.13_PA
D1.3_PA
Minor19_PA
Minor45_PA
Minor12_PA
B1.3_PA
B3.7_PA
B4.1_PA
Minor34_PA
Minor11_PA
B3.3_PA
A4_PA
Minor63_PA
Minor87_PA
B1.2_PA
Minor77_PA
B3.2_PA
B2.2_PA
Minor90_PA
B2.1_PA
Minor102_PA
A6_PA
Minor08_PA
Minor07_PA
Minor04_PA
B3.1_PA
Minor101_PA
Minor01_PA
D1.2_PA
D1.1_PA
Minor91_PA
Minor98_PA
A5_PA
A1_PA
C2.1_PA
B3.6_PA
B3.10_PA
B1.1_PA
Minor14_PA
B3.4_PA
B3.5_PA
A3_PA
Minor94_PA
Minor09_PA
Minor104_PA
Minor28_PA
A2_PA
B3.12_PA
B5.1_HA
Minor65_HA
Minor105_HA
Minor13_HA
Not assigned
Unassigned_HA
Minor81_HA
Minor50_HA
B3.13_HA
D1.3_HA
Minor19_HA
Minor45_HA
Minor12_HA
B1.3_HA
B3.7_HA
B4.1_HA
Minor34_HA
Minor11_HA
B3.3_HA
A4_HA
Minor63_HA
Minor87_HA
B1.2_HA
Minor77_HA
B3.2_HA
B2.2_HA
Minor90_HA
B2.1_HA
Minor102_HA
A6_HA
Minor08_HA
Minor07_HA
Minor04_HA
B3.1_HA
Minor101_HA
Minor01_HA
D1.2_HA
D1.1_HA
Minor91_HA
Minor98_HA
A5_HA
A1_HA
C2.1_HA
B3.6_HA
B3.10_HA
B1.1_HA
Minor14_HA
B3.4_HA
B3.5_HA
A3_HA
Minor94_HA
Minor09_HA
Minor104_HA
Minor28_HA
A2_HA
B3.12_HA
B5.1_NP
Minor65_NP
Minor105_NP
Minor13_NP
Not assigned
Unassigned_NP
Minor81_NP
Minor50_NP
B3.13_NP
D1.3_NP
Minor19_NP
Minor45_NP
Minor12_NP
B1.3_NP
B3.7_NP
B4.1_NP
Minor34_NP
Minor11_NP
B3.3_NP
A4_NP
Minor63_NP
Minor87_NP
B1.2_NP
Minor77_NP
B3.2_NP
B2.2_NP
Minor90_NP
B2.1_NP
Minor102_NP
A6_NP
Minor08_NP
Minor07_NP
Minor04_NP
B3.1_NP
Minor101_NP
Minor01_NP
D1.2_NP
D1.1_NP
Minor91_NP
Minor98_NP
A5_NP
A1_NP
C2.1_NP
B3.6_NP
B3.10_NP
B1.1_NP
Minor14_NP
B3.4_NP
B3.5_NP
A3_NP
Minor94_NP
Minor09_NP
Minor104_NP
Minor28_NP
A2_NP
B3.12_NP
B5.1_NA
Minor65_NA
Minor105_NA
Minor13_NA
Not assigned
Unassigned_NA
Minor81_NA
Minor50_NA
B3.13_NA
D1.3_NA
Minor19_NA
Minor45_NA
Minor12_NA
B1.3_NA
B3.7_NA
B4.1_NA
Minor34_NA
Minor11_NA
B3.3_NA
A4_NA
Minor63_NA
Minor87_NA
B1.2_NA
Minor77_NA
B3.2_NA
B2.2_NA
Minor90_NA
B2.1_NA
Minor102_NA
A6_NA
Minor08_NA
Minor07_NA
Minor04_NA
B3.1_NA
Minor101_NA
Minor01_NA
D1.2_NA
D1.1_NA
Minor91_NA
Minor98_NA
A5_NA
A1_NA
C2.1_NA
B3.6_NA
B3.10_NA
B1.1_NA
Minor14_NA
B3.4_NA
B3.5_NA
A3_NA
Minor94_NA
Minor09_NA
Minor104_NA
Minor28_NA
A2_NA
B3.12_NA
B5.1_MP
Minor65_MP
Minor105_MP
Minor13_MP
Not assigned
Unassigned_MP
Minor81_MP
Minor50_MP
B3.13_MP
D1.3_MP
Minor19_MP
Minor45_MP
Minor12_MP
B1.3_MP
B3.7_MP
B4.1_MP
Minor34_MP
Minor11_MP
B3.3_MP
A4_MP
Minor63_MP
Minor87_MP
B1.2_MP
Minor77_MP
B3.2_MP
B2.2_MP
Minor90_MP
B2.1_MP
Minor102_MP
A6_MP
Minor08_MP
Minor07_MP
Minor04_MP
B3.1_MP
Minor101_MP
Minor01_MP
D1.2_MP
D1.1_MP
Minor91_MP
Minor98_MP
A5_MP
A1_MP
C2.1_MP
B3.6_MP
B3.10_MP
B1.1_MP
Minor14_MP
B3.4_MP
B3.5_MP
A3_MP
Minor94_MP
Minor09_MP
Minor104_MP
Minor28_MP
A2_MP
B3.12_MP
B5.1_NS
Minor65_NS
Minor105_NS
Minor13_NS
Not assigned
Unassigned_NS
Minor81_NS
Minor50_NS
B3.13_NS
D1.3_NS
Minor19_NS
Minor45_NS
Minor12_NS
B1.3_NS
B3.7_NS
B4.1_NS
Minor34_NS
Minor11_NS
B3.3_NS
A4_NS
Minor63_NS
Minor87_NS
B1.2_NS
Minor77_NS
B3.2_NS
B2.2_NS
Minor90_NS
B2.1_NS
Minor102_NS
A6_NS
Minor08_NS
Minor07_NS
Minor04_NS
B3.1_NS
Minor101_NS
Minor01_NS
D1.2_NS
D1.1_NS
Minor91_NS
Minor98_NS
A5_NS
A1_NS
C2.1_NS
B3.6_NS
B3.10_NS
B1.1_NS
Minor14_NS
B3.4_NS
B3.5_NS
A3_NS
Minor94_NS
Minor09_NS
Minor104_NS
Minor28_NS
A2_NS
B3.12_NS

In [322]:
# print(metadata_genoflu[metadata_genoflu["Genotype"] == "B3.2"])

In [323]:
# Create FASTA files

os.chdir(complete_files)

# names = []

for df in segment_genotype_dfs:
    print(df)
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0:
        # print(df)
        if "Not assigned" not in df["Genotype"].values[0]:
            file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
            output_file = open(complete_files + file_name, "w")

            for index, row in df.iterrows():
                name = df.loc[index, "Name"]
                name = name.replace(" ", "_")
                # names.append(name)
                sequence = df.loc[index, "sequence"]
                # First is header, second is sequence
                output_file.write(name + "\n")
                output_file.write(sequence + "\n")
        else:
            file_name = "Unassigned_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
            output_file = open(complete_files + file_name, "w")

            for index, row in df.iterrows():
                name = df.loc[index, "Name"]
                name = name.replace(" ", "_")
                # names.append(name)
                sequence = df.loc[index, "sequence"]
                # First is header, second is sequence
                output_file.write(name + "\n")
                output_file.write(sequence + "\n")
    output_file.close()

        Accession                                      GenBank_Title  \
19088  PV312885.1  Influenza A virus (A/Great Horned Owl/AB/FAV-0...

                   Host Collection_Date SRA_Accession           Isolate  \
19088  great horned owl      2022-05-12                FAV-0833-17-2022

      Genotype_official Geo_Location  \
19088              B5.1   Canada: AB

                                             full_header  \
19088  >Influenza A virus |Canada: AB|FAV-0833-17-202...

                                                sequence  ... File Name  \
19088  ATGGAGAGAATAAAAGAGCTAAGAGATTTGATGTCGCAATCTCGCA...  ...

                                          Partial_Header Strain  \
19088  Influenza_A_virus__Canada__AB_FAV_0833_17_2022...

                                      genbank_name   Host_Type Years  \
19088  A/Great Horned Owl/AB/FAV-0833-17-2022/2022  wild_avian  2022

      Geo_Location_Abrv Genotype  \
19088         Canada-AB     B5.1

                                                    Name Segment_Name
19088  >|A/Great Horned Owl/AB/FAV-0833-17-2022/2022|...          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
24040  PV317837.1  Influenza A virus (A/Snow Goose/ON/FAV-0457-2-...

             Host Collection_Date SRA_Accession          Isolate  \
24040  snow goose      2023-11-29                FAV-0457-2-2023

      Genotype_official Geo_Location  \
24040           Minor65   Canada: ON

                                             full_header  \
24040  >Influenza A virus |Canada: ON|FAV-0457-2-2023...

                                                sequence  ... File Name  \
24040  ATGGAGAGAATAAAAGAACTAAGAGACCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
24040  Influenza_A_virus__Canada__ON_FAV_0457_2_2023_...

                               genbank_name   Host_Type Years  \
24040  A/Snow Goose/ON/FAV-0457-2-2023/2023  wild_avian  2023

      Geo_Location_Abrv Genotype  \
24040         Canada-ON  Minor65

                                                    Name Segment_Name
24040  >|A/Snow Goose/ON/FAV-0457-2-2023/2023|H5N1|Ca...          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title     Host  \
48920  PV162084.1  Influenza A virus (A/chicken/MN/25-000082-001-...  chicken
48928  PV162092.1  Influenza A virus (A/chicken/MN/25-000082-002-...  chicken

      Collection_Date SRA_Accession                 Isolate Genotype_official  \
48920      2024-12-31   SRR32006874  25-000082-001-original          Minor105
48928      2024-12-31   SRR32006872  25-000082-002-original          Minor105

      Geo_Location                                        full_header  \
48920      USA: MN  >Influenza A virus |USA: MN|25-000082-001-orig...
48928      USA: MN  >Influenza A virus |USA: MN|25-000082-002-orig...

                                                sequence  ... File Name  \
48920  ATGGAGAGAATAAAGGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
48928  ATGGAGAGAATAAAGGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
48920  Influenza_A_virus__USA__MN_25_000082_001_origi...
48928  Influenza_A_virus__USA__MN_25_000082_002_origi...

                                   genbank_name       Host_Type Years  \
48920  A/chicken/MN/25-000082-001-original/2024  domestic_avian  2024
48928  A/chicken/MN/25-000082-002-original/2024  domestic_avian  2024

      Geo_Location_Abrv  Genotype  \
48920            USA-MN  Minor105
48928            USA-MN  Minor105

                                                    Name Segment_Name
48920  >SRR32006874|A/chicken/MN/25-000082-001-origin...          PB2
48928  >SRR32006872|A/chicken/MN/25-000082-002-origin...          PB2

[2 rows x 22 columns]
        Accession                                      GenBank_Title  \
91536  OQ959521.1  Influenza A virus (A/Bald Eagle/Nebraska/22-00...

             Host Collection_Date SRA_Accession        Isolate  \
91536  bald eagle      2022-03-15                22-008225-001

      Genotype_official   Geo_Location  \
91536           Minor13  USA: Nebraska

                                             full_header  \
91536  >Influenza A virus |USA: Nebraska|22-008225-00...

                                                sequence  ... File Name  \
91536  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
91536  Influenza_A_virus__USA__Nebraska_22_008225_001...

                                   genbank_name   Host_Type Years  \
91536  A/Bald Eagle/Nebraska/22-008225-001/2022  wild_avian  2022

      Geo_Location_Abrv Genotype  \
91536            USA-NE  Minor13

                                                    Name Segment_Name
91536  >|A/Bald Eagle/Nebraska/22-008225-001/2022|H5N...          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
0      PV660431.1  Influenza A virus (A/Cygnus melancoryphus/Sapu...
2304   PX441028.1  Influenza A virus (A/cattle/CA/25-022240-001-o...
5136   PX127282.1  Influenza A virus (A/cattle/CA/25-017369-001-o...
6072   PV949116.1  Influenza A virus (A/Duck/NY/24-035330-001-ori...
6088   PV949132.1  Influenza A virus (A/Duck/PA/24-034866-001-ori...
6104   PV949140.1  Influenza A virus (A/Duck/PA/24-035135-002-ori...
6120   PV949148.1  Influenza A virus (A/Duck/PA/24-035135-004-ori...
6136   PV949156.1  Influenza A virus (A/Duck/PA/24-038397-001-ori...
6152   PV949164.1  Influenza A virus (A/Duck/PA/24-038397-002-ori...
6168   PV949172.1  Influenza A virus (A/Duck/PA/24-038397-004-ori...
6184   PV949180.1  Influenza A virus (A/Duck/PA/24-038397-005-ori...
6488   PV949660.1  Influenza A virus (A/cattle/CA/25-017354-001-o...
7000   PV950172.1  Influenza A virus (A/cattle/ID/25-016724-002-o...
7216   PV950412.1  Influenza A virus (A/chicken/PA/24-035135-001-...
7256   PV950476.1  Influenza A virus (A/goose/NY/25-014296-001-or...
7272   PV950484.1  Influenza A virus (A/goose/PA/24-035135-003-or...
31016  PV904386.1  Influenza A virus (A/cattle/CA/25-015677-001-o...
31024  PV904394.1  Influenza A virus (A/cattle/CA/25-015677-002-o...
31032  PV904402.1  Influenza A virus (A/cattle/CA/25-015677-003-o...
31056  PV904426.1  Influenza A virus (A/cattle/CO/25-016187-001-o...
33792  PV792554.1  Influenza A virus (A/cattle/MN/25-011973-001-o...
34096  PV709498.1  Influenza A virus (A/cattle/CA/25-009041-005-o...
79632  PQ652148.1  Influenza A virus (A/cattle/Michigan/Broad_ME_...
79648  PQ645021.1  Influenza A virus (A/cattle/Texas/Broad_MD_027...
79664  PQ645029.1  Influenza A virus (A/cattle/Colorado/Broad_MF_...
80544  PQ373644.1  Influenza A virus (A/cattle/Colorado/Broad_MD_...
80592  PQ373668.1  Influenza A virus (A/cattle/Colorado/Broad_ME_...
80640  PQ373692.1  Influenza A virus (A/cattle/Idaho/Broad_ME_018...
80656  PQ373700.1  Influenza A virus (A/cattle/Idaho/Broad_ME_020...
80720  PQ373732.2  Influenza A virus (A/cattle/Colorado/Broad_MF_...

                       Host Collection_Date  \
0      cygnus melancoryphus      2025-05-12
2304                 cattle      2025-08-04
5136                 cattle      2025-06-03
6072                   duck      2024-11-25
6088                   duck      2024-11-19
6104                   duck      2024-11-22
6120                   duck      2024-11-22
6136                   duck      2024-12-20
6152                   duck      2024-12-20
6168                   duck      2024-12-20
6184                   duck      2024-12-20
6488                 cattle      2025-06-03
7000                 cattle      2025-05-26
7216                chicken      2024-11-22
7256                  goose      2025-04-30
7272                  goose      2024-11-22
31016                cattle      2025-05-13
31024                cattle      2025-05-13
31032                cattle      2025-05-13
31056                cattle      2025-05-19
33792                cattle      2025-04-03
34096                cattle      2025-03-11
79632                cattle      2024-06-24
79648                cattle      2024-06-09
79664                cattle      2024-07-02
80544                cattle      2024-06-10
80592                cattle      2024-06-24
80640                cattle      2024-06-24
80656                cattle      2024-06-24
80720                cattle      2024-07-02

                                           SRA_Accession  \
0
2304                                         SRR35150456
5136                                         SRR33993044
6072                                         SRR34270367
6088                                         SRR34270372
6104                                         SRR34270370
6120                                         SRR34270368
6136                                         SRR34270351
6152                                         SRR34270350
6168                                         SRR34270349
6184                                         SRR34270348
6488                                         SRR33993047
7000                                         SRR33943344
7216                                         SRR34270371
7256                                         SRR34270339
7272                                         SRR34270369
31016                                        SRR33830361
31024                                        SRR33830448
31032                                        SRR33830447
31056                                        SRR33830382
33792                                        SRR33369823
34096                                        SRR32973865
79632  SRR30789566,SRR30789579,SRR30789603,SRR3078961...
79648  SRR30789567,SRR30789611,SRR30789621,SRR3078963...
79664  SRR30789570,SRR30789576,SRR30789583,SRR3078958...
80544                            SRR30789627,SRR30789607
80592                            SRR30789604,SRR30789623
80640  SRR30789565,SRR30789616,SRR30789620,SRR3078963...
80656                            SRR30789598,SRR30789615
80720    SRR30789571,SRR30789577,SRR30789584,SRR30789591

                              Isolate Genotype_official  \
0                        1246-N7-2025      Not assigned
2304           25-022240-001-original      Not assigned
5136           25-017369-001-original      Not assigned
6072           24-035330-001-original      Not assigned
6088   24-034866-001-original-repeat2      Not assigned
6104           24-035135-002-original      Not assigned
6120           24-035135-004-original      Not assigned
6136           24-038397-001-original      Not assigned
6152           24-038397-002-original      Not assigned
6168           24-038397-004-original      Not assigned
6184           24-038397-005-original      Not assigned
6488           25-017354-001-original      Not assigned
7000           25-016724-002-original      Not assigned
7216           24-035135-001-original      Not assigned
7256           25-014296-001-original      Not assigned
7272           24-035135-003-original      Not assigned
31016          25-015677-001-original      Not assigned
31024          25-015677-002-original      Not assigned
31032          25-015677-003-original      Not assigned
31056          25-016187-001-original      Not assigned
33792          25-011973-001-original      Not assigned
34096          25-009041-005-original      Not assigned
79632                    Broad_ME_010      Not assigned
79648                    Broad_MD_027      Not assigned
79664                    Broad_MF_016      Not assigned
80544                    Broad_MD_041      Not assigned
80592                    Broad_ME_003      Not assigned
80640                    Broad_ME_018      Not assigned
80656                    Broad_ME_020      Not assigned
80720                    Broad_MF_011      Not assigned

                Geo_Location  \
0      Brazil: SapucaiaSulBR
2304                 USA: CA
5136                 USA: CA
6072                 USA: NY
6088                 USA: PA
6104                 USA: PA
6120                 USA: PA
6136                 USA: PA
6152                 USA: PA
6168                 USA: PA
6184                 USA: PA
6488                 USA: CA
7000                 USA: ID
7216                 USA: PA
7256                 USA: NY
7272                 USA: PA
31016                USA: CA
31024                USA: CA
31032                USA: CA
31056                USA: CO
33792                USA: MN
34096                USA: CA
79632          USA: Michigan
79648             USA: Texas
79664          USA: Colorado
80544          USA: Colorado
80592          USA: Colorado
80640             USA: Idaho
80656             USA: Idaho
80720          USA: Colorado

                                             full_header  \
0      >Influenza A virus |Brazil: SapucaiaSulBR|1246...
2304   >Influenza A virus |USA: CA|25-022240-001-orig...
5136   >Influenza A virus |USA: CA|25-017369-001-orig...
6072   >Influenza A virus |USA: NY|24-035330-001-orig...
6088   >Influenza A virus |USA: PA|24-034866-001-orig...
6104   >Influenza A virus |USA: PA|24-035135-002-orig...
6120   >Influenza A virus |USA: PA|24-035135-004-orig...
6136   >Influenza A virus |USA: PA|24-038397-001-orig...
6152   >Influenza A virus |USA: PA|24-038397-002-orig...
6168   >Influenza A virus |USA: PA|24-038397-004-orig...
6184   >Influenza A virus |USA: PA|24-038397-005-orig...
6488   >Influenza A virus |USA: CA|25-017354-001-orig...
7000   >Influenza A virus |USA: ID|25-016724-002-orig...
7216   >Influenza A virus |USA: PA|24-035135-001-orig...
7256   >Influenza A virus |USA: NY|25-014296-001-orig...
7272   >Influenza A virus |USA: PA|24-035135-003-orig...
31016  >Influenza A virus |USA: CA|25-015677-001-orig...
31024  >Influenza A virus |USA: CA|25-015677-002-orig...
31032  >Influenza A virus |USA: CA|25-015677-003-orig...
31056  >Influenza A virus |USA: CO|25-016187-001-orig...
33792  >Influenza A virus |USA: MN|25-011973-001-orig...
34096  >Influenza A virus |USA: CA|25-009041-005-orig...
79632  >Influenza A virus |USA: Michigan|Broad_ME_010...
79648  >Influenza A virus |USA: Texas|Broad_MD_027|H5...
79664  >Influenza A virus |USA: Colorado|Broad_MF_016...
80544  >Influenza A virus |USA: Colorado|Broad_MD_041...
80592  >Influenza A virus |USA: Colorado|Broad_ME_003...
80640  >Influenza A virus |USA: Idaho|Broad_ME_018|H5...
80656  >Influenza A virus |USA: Idaho|Broad_ME_020|H5...
80720  >Influenza A virus |USA: Colorado|Broad_MF_011...

                                                sequence  ... File Name  \
0      AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATCAAAGAAT...  ...
2304   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
5136   ATGGAGAGAATGAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
6072   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6088   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6104   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6120   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6136   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6152   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6168   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6184   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
6488   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
7000   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
7216   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
7256   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
7272   ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCGCAGTCTCGCA...  ...
31016  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
31024  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
31032  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
31056  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
33792  ATGGAGAGAACAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
34096  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
79632  ACAGTCTCGCACTCGCGAGATACTAACCAAAACCACTGTTGACCAC...  ...
79648  TGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCAC...  ...
79664  ACAGTCTCGCACTCGCGAGATACTAACCAAAACCACTGTTGACCAC...  ...
80544  ACAGTCTCGCACTCGCGAGATACTAACCAAAACCACTGTTGACCAC...  ...
80592  ACAGTCTCGCACTCGCGAGATACTAACCAAAACCACTGTTGACCAC...  ...
80640  ACAGTCTCGCACTCGCGAGATACTAACCAAAACCACTGTTGACCAC...  ...
80656  TGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCAC...  ...
80720  AAAACCACTGTTGACCACATGGCCATAATCAAGAAGTACACATCAG...  ...

                                          Partial_Header  \
0      Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
2304   Influenza_A_virus__USA__CA_25_022240_001_origi...
5136   Influenza_A_virus__USA__CA_25_017369_001_origi...
6072   Influenza_A_virus__USA__NY_24_035330_001_origi...
6088   Influenza_A_virus__USA__PA_24_034866_001_origi...
6104   Influenza_A_virus__USA__PA_24_035135_002_origi...
6120   Influenza_A_virus__USA__PA_24_035135_004_origi...
6136   Influenza_A_virus__USA__PA_24_038397_001_origi...
6152   Influenza_A_virus__USA__PA_24_038397_002_origi...
6168   Influenza_A_virus__USA__PA_24_038397_004_origi...
6184   Influenza_A_virus__USA__PA_24_038397_005_origi...
6488   Influenza_A_virus__USA__CA_25_017354_001_origi...
7000   Influenza_A_virus__USA__ID_25_016724_002_origi...
7216   Influenza_A_virus__USA__PA_24_035135_001_origi...
7256   Influenza_A_virus__USA__NY_25_014296_001_origi...
7272   Influenza_A_virus__USA__PA_24_035135_003_origi...
31016  Influenza_A_virus__USA__CA_25_015677_001_origi...
31024  Influenza_A_virus__USA__CA_25_015677_002_origi...
31032  Influenza_A_virus__USA__CA_25_015677_003_origi...
31056  Influenza_A_virus__USA__CO_25_016187_001_origi...
33792  Influenza_A_virus__USA__MN_25_011973_001_origi...
34096  Influenza_A_virus__USA__CA_25_009041_005_origi...
79632  Influenza_A_virus__USA__Michigan_Broad_ME_010_...
79648  Influenza_A_virus__USA__Texas_Broad_MD_027_H5N...
79664  Influenza_A_virus__USA__Colorado_Broad_MF_016_...
80544  Influenza_A_virus__USA__Colorado_Broad_MD_041_...
80592  Influenza_A_virus__USA__Colorado_Broad_ME_003_...
80640  Influenza_A_virus__USA__Idaho_Broad_ME_018_H5N...
80656  Influenza_A_virus__USA__Idaho_Broad_ME_020_H5N...
80720  Influenza_A_virus__USA__Colorado_Broad_MF_011_...

                                                  Strain  \
0      Influenza_A_virus__Brazil__SapucaiaSulBR_1246_...
2304
5136
6072
6088
6104
6120
6136
6152
6168
6184
6488
7000
7216
7256
7272
31016
31024
31032
31056
33792
34096
79632
79648
79664
80544
80592
80640
80656
80720

                                            genbank_name       Host_Type  \
0      A/Cygnus melancoryphus/SapucaiaSulBR/1246-N7-2...      wild_avian
2304             A/cattle/CA/25-022240-001-original/2025          cattle
5136             A/cattle/CA/25-017369-001-original/2025          cattle
6072               A/Duck/NY/24-035330-001-original/2024  domestic_avian
6088       A/Duck/PA/24-034866-001-original-repeat2/2024  domestic_avian
6104               A/Duck/PA/24-035135-002-original/2024  domestic_avian
6120               A/Duck/PA/24-035135-004-original/2024  domestic_avian
6136               A/Duck/PA/24-038397-001-original/2024  domestic_avian
6152               A/Duck/PA/24-038397-002-original/2024  domestic_avian
6168               A/Duck/PA/24-038397-004-original/2024  domestic_avian
6184               A/Duck/PA/24-038397-005-original/2024  domestic_avian
6488             A/cattle/CA/25-017354-001-original/2025          cattle
7000             A/cattle/ID/25-016724-002-original/2025          cattle
7216            A/chicken/PA/24-035135-001-original/2024  domestic_avian
7256              A/goose/NY/25-014296-001-original/2025  domestic_avian
7272              A/goose/PA/24-035135-003-original/2024  domestic_avian
31016            A/cattle/CA/25-015677-001-original/2025          cattle
31024            A/cattle/CA/25-015677-002-original/2025          cattle

In [324]:
# # Concatenate with new Andersen sequences

# os.chdir(combined_files)

# # andersen = home + "Andersen/complete/" + date_range + "/"

# # Andersen files
# filenames_andersen = []
# for genotype in genotypes:
#     # print(gisaid_andersen + genotype.replace(".", "_") + "/")
#     # for dirpath, dirs, files in os.walk(gisaid_andersen + genotype.replace(".", "_") + "/" + date_range + "_" + genotype.replace(".", "_") + "/"):
#     for dirpath, dirs, files in os.walk(andersen): # Find the fasta file
#         for file in files:
#             file_name = os.path.join(dirpath, file) # Get file name
#             filenames_andersen.append(file_name)
#         break 

# # NCBI Virus files
# filenames_ncbi = []
# for dirpath, dirs, files in os.walk(complete_files): # Find the fasta file
#     for file in files:
#         file_name = os.path.join(dirpath, file) # Get file name
#         filenames_ncbi.append(file_name)
#     break 

# print(filenames_ncbi)

# common_genotypes = set()
# # Concatenate the two -- should not have any overlap due to dates and deduplication 
# for a_file in filenames_andersen:
#     partial_filename_a = a_file.split("_")[-4].split("/")[-1] + "_" + a_file.split("_")[-3]
#     for nv_file in filenames_ncbi:
#         partial_filename_nv = nv_file.split("_")[-3].split("/")[-1] + "_" + nv_file.split("_")[-2]
#         if partial_filename_a == partial_filename_nv:
#             common_genotypes.add(partial_filename_a)
#             filenames = [a_file, nv_file]
#             with open(combined_files + partial_filename_a + "_combined_" + date_range + ".fasta", 'w') as outfile:
#                 for fname in filenames:
#                     with open(fname) as infile:
#                         for line in infile:
#                             outfile.write(line)
#                         infile.close()
#                 outfile.close()

# print(common_genotypes)

# for a_file in filenames_andersen:
#     partial_filename_a = a_file.split("_")[-4].split("/")[-1] + "_" + a_file.split("_")[-3]
#     # If genotype not found in NCBI Virus, include it as well
#     if partial_filename_a not in common_genotypes:
#         with open(combined_files + partial_filename_a + "_combined_" + date_range + ".fasta", 'w') as outfile2:
#             with open(a_file) as infile2:
#                 for line in infile2:
#                     outfile2.write(line)
#                 infile2.close()
#             outfile2.close()