# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences.

In [1]:
# Housekeeping

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [2]:
# Paths and input

# Input
browser = input("Browser (Firefox, Chrome, or Edge): ")
sleep_time = input("Seconds to wait in between clicks (recommended 3): ")
# locations = input("Locations (separate with commas and no spaces in between locations): ")
# start_date = input("Start date (format: MM-DD-YYYY): ")
# end_date = input("End date: (format: MM-DD-YYYY): ")

# Dates and locations
locations = "Antarctica,North America,South America"
start_date = "11-01-2021"
end_date = "01-02-2026"
date_range = start_date + "--" + end_date


# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
# downloads = "C:/Users/maksi/Downloads/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = "C:/Users/maksiaevai.NCBI_NT/Downloads/" # MUST be downloads folder. Clean out downloads folder after each use. 
downloads_saved = home + "NCBI_Virus/downloads/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/" # "_Antarctica_North_America_South_America/"
andersen = home + "Andersen/avian-influenza/metadata/"
temp_files = home + "NCBI_Virus/temp/"
complete_files = home + "NCBI_Virus/complete/" + date_range + "_" + locations.replace(",", "_").replace(" ", "_") + "/"
if not os.path.exists(complete_files): # checking if the directory exists or not
    os.makedirs(complete_files) # if the directory is not present then create it

references = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu/references/"
# references = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu/references/"
os.chdir(references)
states_ref = pd.read_csv("states_ref.csv")

genotypes_df = pd.read_excel("genotype_key.xlsx")
genotypes = list(genotypes_df["Genotype"])

# serotype = "H5N1"
# genotypes = ["B3.13", "D1.1", "D1.3"]
# genotypes = ["B3.2", "B3.6", "B3.7", "B3.5", "A3", "B3.13", "D1.1", "D1.3"]

## Downloading Data

In [3]:
os.chdir(downloads)

if not os.path.exists(downloads_saved): # checking if the directory exists or not
    os.makedirs(downloads_saved) # if the directory is not present then create it

    # Move downloaded files to saved downloads
    for dirpath, dirs, files in os.walk(downloads):
        if len(files) > 0: # If we have any files that need to be moved
            for file in files:
                file_name = os.path.join(dirpath, file)
                destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                try:
                    shutil.move(file_name, destination_path)
                except:
                    print("Error moving file", file_name)
                    continue 
        else: # If we don't have any downloaded files
            # Get files
            open_ncbi_virus(browser, sleep_time, locations, start_date, end_date)

            # Re-try 
            for dirpath, dirs, files in os.walk(downloads):
                if len(files) > 0: # If we have any files that need to be moved
                    for file in files:
                        file_name = os.path.join(dirpath, file)
                        destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                        try:
                            shutil.move(file_name, destination_path)
                        except:
                            print("Error moving file", file_name)
                            continue 
                break 
        break

## De-Duplication

In [4]:
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Isolate, as_index=False).size()
# print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Isolate")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments

122194

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
18,PQ284576.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Sterna hirundo,NaN,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8
19,PQ284577.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Sterna hirundo,NaN,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8
20,PQ284578.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Sterna hirundo,NaN,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8
21,PQ284579.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Sterna hirundo,NaN,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8
22,PQ284580.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Sterna hirundo,NaN,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114200,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
114201,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
114202,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
114203,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8
114204,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8

## Add sequences to dataframe

In [5]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title | Accession

# Get sequences and headers together
# headers = []
# isolates = []
# sras = []
# headers_seqs = {}

os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

# Filter dataframe to only include filtered SRA accessions
# sequences_fasta = sequences_fasta[sequences_fasta["full_header"].str.contains("|".join(list(metadata_segments["SRA_Accession"].values)))]
# sequences_fasta["SRA_Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-4])
sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split("|")[-1][:-1])

print(sequences_fasta["full_header"])

# Extract segment number so that we can add the correct sequences to the correct sample
# sequences_fasta["Segment"] = sequences_fasta["full_header"].apply(lambda x: int(re.search(r'segment (.?) ', x.split("|")[-2]).group(1)))

# Double-check the de-duplication
print(len(sequences_fasta)) 
print(sequences_fasta.head())
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on=["Accession"]) # , "Segment"])

0         >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
1         >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
2         >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
3         >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
4         >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
                                ...
122189    >Influenza A virus |Mexico: Veracruz|28159-398...
122190    >Influenza A virus |Mexico: Veracruz|28159-398...
122191    >Influenza A virus |Mexico: Veracruz|28159-398...
122192    >Influenza A virus |Mexico: Veracruz|28159-398...
122193    >Influenza A virus |Mexico: Veracruz|28159-398...
Name: full_header, Length: 122194, dtype: object
122194
                                         full_header  \
0  >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
1  >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
2  >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
3  >Influenza A virus |Chile||H5N1|2025-01-13|Ste...
4  >Influenza A virus |Chile||H5N1|2025-01-13|Ste...

                                            sequence   Accession
0  AGCAGAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGT...  PX373540.1
1  AGCAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAACT...  PX373541.1
2  AGCAGAAAGCAGGAGTTCAAAATGAATCCAAATCAAAAGATAACAA...  PX373542.1
3  AGCGAAAGCAGGGTGACAAAAACATAATGGATTCCAACACTGTGTC...  PX373543.1
4  AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...  PX373544.1
105528

In [6]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PQ284576.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...
1,PQ284577.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...
2,PQ284578.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...
3,PQ284579.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...
4,PQ284580.1,GenBank,GCA_054311525.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Rivetti,A.V. Jr., Reischak,D., Oliveira,C.H.S....","Ministerio da Agricultura e Pecuaria, Laborato...",Brazil,NaN,2024-04-05,2025-12-31,ssRNA(-),8,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCGAAAGCAGGGTAGATAATCACTCACTGAGTGACATTCACATCA...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105523,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...
105524,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...
105525,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...
105526,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...
105527,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,1995,2021-11-01,ssRNA(-),8,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...

## Find genotype using old genoflu results or Andersen Lab genoflu output

Old genoflu results should accumulate into one file to avoid having to genotype anything again.

In [7]:
genoflu_old = pd.read_csv("output.tsv", delimiter="\t")
genoflu_old = genoflu_old.rename(columns={"Strain":"Partial_Header"}) # So we can merge
# print(genoflu_old)
metadata_segments["Partial_Header"] = metadata_segments["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
metadata_segments["Partial_Header"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(">", "")) # Get rid of header indicator
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]: # Forbidden punctuation
    metadata_segments["Partial_Header"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(c, "_"))
# metadata_segments["Accession_Root"] = metadata_segments["Accession"].values[0].split(".")[0]
# print(metadata_segments["Partial_Header"])

# Merge to get already-genotyped segments
metadata_segments_old = metadata_segments.merge(genoflu_old, how="inner", on="Partial_Header") # .dropna(subset="SRA_Accession")
# Isolate not-already-genotyped segments
metadata_segments_new = metadata_segments.merge(genoflu_old,indicator = True, how='left', on="Partial_Header").loc[lambda x : x['_merge']!='both'] # .dropna(subset="SRA_Accession")

print(len(metadata_segments_old))
print(len(metadata_segments_new))

101088
4640

In [26]:
metadata_segments_new[metadata_segments_new["Isolate"] == "A273"]

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Partial_Header,Genotype_y,"Genotype List Used, >=98.0%",Genotype Sample Title List,Genotype Percent Match List,Genotype Mismatch List,Genotype Average Depth of Coverage List,Date run,_merge,Strain
104123,OQ747762.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104127,OQ747769.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104131,OQ747882.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104143,OQ747867.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104147,OQ747877.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...
104151,OQ747893.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104163,OQ747888.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104167,OQ747899.1,GenBank,NaN,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...

In [9]:
# Get genoflu results from Andersen and see if any fit

os.chdir(andersen)

genoflu_andersen = pd.read_csv("genoflu_results.tsv", delimiter="\t")
genoflu_andersen = genoflu_andersen.rename(columns={"sample":"SRA_Accession"}) # So we can merge

# Find those genotyped by Andersen via merge
metadata_segments_known_andersen = metadata_segments_new.merge(genoflu_andersen, how="inner", on="SRA_Accession")
print(metadata_segments_known_andersen)
# Keep all known genotypes
metadata_segments_known = pd.merge(metadata_segments_old, metadata_segments_known_andersen, how="left") # .drop_duplicates(keep="last", inplace=True) # Since we know both of these

print(genoflu_andersen)

       Accession GenBank_RefSeq         Assembly SRA_Accession     BioSample  \
0     PX748036.1        GenBank  GCA_054196825.1   SRR36162763  SAMN53332038
1     PX748037.1        GenBank  GCA_054196825.1   SRR36162763  SAMN53332038
2     PX748038.1        GenBank  GCA_054196825.1   SRR36162763  SAMN53332038
3     PX748039.1        GenBank  GCA_054196825.1   SRR36162763  SAMN53332038
4     PX748040.1        GenBank  GCA_054196825.1   SRR36162763  SAMN53332038
...          ...            ...              ...           ...           ...
4435  PQ135389.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
4436  PQ135390.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
4437  PQ135391.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
4438  PQ135392.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998
4439  PQ135393.1        GenBank  GCA_041199025.1   SRR29694510  SAMN42278998

        BioProject      Organism_Name                         Species  \
0      PRJNA980729  Influenza A virus  Alphainfluenzavirus influenzae
1      PRJNA980729  Influenza A virus  Alphainfluenzavirus influenzae
2      PRJNA980729  Influenza A virus  Alphainfluenzavirus influenzae
3      PRJNA980729  Influenza A virus  Alphainfluenzavirus influenzae
4      PRJNA980729  Influenza A virus  Alphainfluenzavirus influenzae
...            ...                ...                             ...
4435  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4436  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4437  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4438  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae
4439  PRJNA1102327  Influenza A virus  Alphainfluenzavirus influenzae

                    Genus            Family  ... Date run     _merge  \
0     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
1     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
2     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
3     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4     Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
...                   ...               ...  ...      ...        ...
4435  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4436  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4437  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4438  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only
4439  Alphainfluenzavirus  Orthomyxoviridae  ...      NaN  left_only

                     date       File Name  Genotype  \
0     2025-11-25_05-21-14  SRR36162763.fa      D1.1
1     2025-11-25_05-21-14  SRR36162763.fa      D1.1
2     2025-11-25_05-21-14  SRR36162763.fa      D1.1
3     2025-11-25_05-21-14  SRR36162763.fa      D1.1
4     2025-11-25_05-21-14  SRR36162763.fa      D1.1
...                   ...             ...       ...
4435  2025-05-09_10-48-14  SRR29694510.fa     B3.13
4436  2025-05-09_10-48-14  SRR29694510.fa     B3.13
4437  2025-05-09_10-48-14  SRR29694510.fa     B3.13
4438  2025-05-09_10-48-14  SRR29694510.fa     B3.13
4439  2025-05-09_10-48-14  SRR29694510.fa     B3.13

                          Genotype List Used, >=98.0%_y  \
0     HA:ea3, NA:am4N1, MP:ea3, PB1:ea3, NP:am13, PA...
1     HA:ea3, NA:am4N1, MP:ea3, PB1:ea3, NP:am13, PA...
2     HA:ea3, NA:am4N1, MP:ea3, PB1:ea3, NP:am13, PA...
3     HA:ea3, NA:am4N1, MP:ea3, PB1:ea3, NP:am13, PA...
4     HA:ea3, NA:am4N1, MP:ea3, PB1:ea3, NP:am13, PA...
...                                                 ...
4435  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
4436  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
4437  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
4438  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...
4439  PB1:am4, PA:ea1, NA:ea1, HA:ea1, NS:am1.1, NP:...

                           Genotype Sample Title List_y  \
0     ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...
1     ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...
2     ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...
3     ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...
4     ea3:22-013001-001:HA, am4N1:24-030039-001:NA, ...
...                                                 ...
4435  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
4436  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
4437  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
4438  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...
4439  am4:23-001855-001:PB1, ea1:22-003707-003:PA, e...

                          Genotype Percent Match List_y  \
0     99.24%, 98.78%, 99.39%, 99.34%, 99.60%, 99.21%...
1     99.24%, 98.78%, 99.39%, 99.34%, 99.60%, 99.21%...
2     99.24%, 98.78%, 99.39%, 99.34%, 99.60%, 99.21%...
3     99.24%, 98.78%, 99.39%, 99.34%, 99.60%, 99.21%...
4     99.24%, 98.78%, 99.39%, 99.34%, 99.60%, 99.21%...
...                                                 ...
4435  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
4436  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
4437  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
4438  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...
4439  99.38%, 98.93%, 99.08%, 98.77%, 99.17%, 99.40%...

          Genotype Mismatch List_y Genotype Average Depth of Coverage List_y
0      13, 14, 6, 15, 6, 17, 9, 11         Ran on FASTA - No Coverage Report
1      13, 14, 6, 15, 6, 17, 9, 11         Ran on FASTA - No Coverage Report
2      13, 14, 6, 15, 6, 17, 9, 11         Ran on FASTA - No Coverage Report
3      13, 14, 6, 15, 6, 17, 9, 11         Ran on FASTA - No Coverage Report
4      13, 14, 6, 15, 6, 17, 9, 11         Ran on FASTA - No Coverage Report
...                            ...                                       ...
4435  14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
4436  14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
4437  14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
4438  14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report
4439  14, 23, 13, 21, 7, 9, 29, 16         Ran on FASTA - No Coverage Report

[4440 rows x 48 columns]
      SRA_Accession                 date       File Name  \
0       SRR30789580  2025-05-09_10-49-10  SRR30789580.fa
1       SRR32973809  2025-05-09_10-52-30  SRR32973809.fa
2       SRR32125669  2025-05-09_10-47-22  SRR32125669.fa
3       SRR31597237  2025-05-09_10-47-24  SRR31597237.fa
4       SRR31605135  2025-05-09_10-47-38  SRR31605135.fa
...             ...                  ...             ...
19024   SRR36628963  2025-12-31_21-22-37  SRR36628963.fa
19025   SRR36628964  2025-12-31_21-22-25  SRR36628964.fa
19026   SRR36628965  2025-12-31_21-22-37  SRR36628965.fa
19027   SRR36628966  2025-12-31_21-22-25  SRR36628966.fa
19028   SRR36650562  2025-12-31_21-22-37  SRR36650562.fa

                                                Genotype  \
0      Not assigned: Only 0 segments >98.0% match fou...
1                                                   D1.3
2                                                  B3.13
3                                                  B3.13
4                                                  B3.13
...                                                  ...
19024  Not assigned: Only 7 segments >98.0% match fou...
19025  Not assigned: Only 3 segments >98.0% match fou...
19026  Not assigned: Only 7 segments >98.0% match fou...
19027  Not assigned: Only 6 segments >98.0% match fou...
19028                                               D1.1

                             Genotype List Used, >=98.0%  \
0                                        PB1:am4, PA:ea1
1      PB1:ea3, HA:ea3, PB2:am24, NP:am13, NS:ea3, PA...
2      MP:ea1, PA:ea1, HA:ea1, NP:am8, PB2:am2.2, NA:...
3      NP:am8, PB2:am2.2, NA:ea1, MP:ea1, NS:am1.1, P...
4      HA:ea1, NP:am8, PB1:am4, NS:am1.1, PA:ea1, MP:...
...                                                  ...
19024  NS:ea3, HA:ea3, MP:ea3, NP:am13, NA:am4N1, PB2...
19025                           NP:am7, NS:am1.2, MP:am1
19026  NP:am13, NS:ea3, NA:am4N1, MP:ea3, PA:am4, HA:...
19027  NS:ea3, PB1:ea5, MP:ea3, HA:ea3, PA:ea3, PB2:am24
19028  PB1:ea3, MP:ea3, PA:am4, NA:am4N1, NP:am13, PB...

                              Genotype Sample Title List  \
0      am4:23-001855-001:PB1, ea1:22-003707-003:PA, a...
1      ea3:22-013001-001:PB1, ea3:22-013001-001:HA, a...
2      ea1:22-003707-003:MP, ea1:22-003707-003:PA, ea...
3      am8:23-032005-001:NP, am2.2:22-010445-001:PB2,...
4      ea1:22-003707-003:HA, am8:23-032005-001:NP, am...
...                                                  ...
19024  ea3:22-013001-001:NS, ea3:22-013001-001:HA, ea...
19025  am7:22-039089-005:NP, am27:24-037288-001:PB2, ...
19026  am13:24-030039-001:NP, ea3:22-013001-001:NS, a...
19027  am13:24-030039-001:NP, ea3:22-013001-001:NS, e...
19028  ea3:22-013001-001:PB1, ea3:22-013001-001:MP, a...

                             Genotype Percent Match List  \
0         98.12%, 98.31%, 93.08%, 97.57%, 97.44%, 96.58%
1      99.21%, 99.59%, 99.56%, 99.47%, 98.93%, 99.58%...
2      98.98%, 98.88%, 98.41%, 98.93%, 98.68%, 98.86%...
3      99.06%, 98.60%, 98.86%, 98.98%, 99.05%, 99.07%...
4      98.47%, 99.06%, 99.47%, 99.17%, 99.02%, 98.98%...
...                                                  ...
19024  99.28%, 99.41%, 100.00%, 99.80%, 99.04%, 99.87...
19025     98.46%, 96.56%, 98.93%, 97.59%, 99.39%, 94.72%
19026  99.67%, 99.05%, 99.62%, 99.80%, 99.83%, 99.47%...
19027  90.98%, 98.09%, 99.38%, 99.90%, 94.35%, 99.41%...
19028  99.07%, 99.57%, 99.21%, 99.23%, 99.52%, 99.37%...

              Genotype Mismatch List Genotype Average Depth of Coverage List
0                  3, 3, 13, 5, 3, 4       Ran on FASTA - No Coverage Report
1          18, 7, 10, 8, 9, 9, 0, 19       Ran on FASTA - No Coverage Report
2      10, 24, 27, 16, 30, 16, 7, 12       Ran on FASTA - No Coverage Report
3      14, 32, 16, 10, 8, 20, 11, 26       Ran on FASTA - No Coverage Report
4      26, 14, 12, 7, 21, 10, 31, 15       Ran on FASTA - No Coverage Report
...                              ...                                     ...
19024           6, 10, 0, 3, 9, 3, 0       Ran on FASTA - No Coverage Report
19025           23, 38, 9, 23, 6, 36       Ran on FASTA - No Coverage Report
19026        5, 8, 4, 2, 3, 9, 1, 77       Ran on FASTA - No Coverage Report
19027   135, 16, 1, 1, 58, 10, 0, 19       Ran on FASTA - No Coverage Report
19028    19, 4, 16, 7, 7, 14, 10, 11       Ran on FASTA - No Coverage Report

[19029 rows x 9 columns]

In [27]:
metadata_segments_unknown = metadata_segments_new # Variable rename so we don't break old code

print(metadata_segments_unknown[metadata_segments_unknown["Isolate"] == "A273"])

         Accession GenBank_RefSeq Assembly SRA_Accession BioSample BioProject  \
104123  OQ747762.1        GenBank      NaN           NaN       NaN        NaN
104127  OQ747769.1        GenBank      NaN           NaN       NaN        NaN
104131  OQ747882.1        GenBank      NaN           NaN       NaN        NaN
104143  OQ747867.1        GenBank      NaN           NaN       NaN        NaN
104147  OQ747877.1        GenBank      NaN           NaN       NaN        NaN
104151  OQ747893.1        GenBank      NaN           NaN       NaN        NaN
104163  OQ747888.1        GenBank      NaN           NaN       NaN        NaN
104167  OQ747899.1        GenBank      NaN           NaN       NaN        NaN

            Organism_Name                         Species  \
104123  Influenza A virus  Alphainfluenzavirus influenzae
104127  Influenza A virus  Alphainfluenzavirus influenzae
104131  Influenza A virus  Alphainfluenzavirus influenzae
104143  Influenza A virus  Alphainfluenzavirus influenzae
104147  Influenza A virus  Alphainfluenzavirus influenzae
104151  Influenza A virus  Alphainfluenzavirus influenzae
104163  Influenza A virus  Alphainfluenzavirus influenzae
104167  Influenza A virus  Alphainfluenzavirus influenzae

                      Genus            Family  ...  \
104123  Alphainfluenzavirus  Orthomyxoviridae  ...
104127  Alphainfluenzavirus  Orthomyxoviridae  ...
104131  Alphainfluenzavirus  Orthomyxoviridae  ...
104143  Alphainfluenzavirus  Orthomyxoviridae  ...
104147  Alphainfluenzavirus  Orthomyxoviridae  ...
104151  Alphainfluenzavirus  Orthomyxoviridae  ...
104163  Alphainfluenzavirus  Orthomyxoviridae  ...
104167  Alphainfluenzavirus  Orthomyxoviridae  ...

                                           Partial_Header Genotype_y  \
104123  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN
104127  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN
104131  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN
104143  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN
104147  Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...        NaN
104151  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN
104163  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN
104167  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...        NaN

        Genotype List Used, >=98.0% Genotype Sample Title List  \
104123                          NaN                        NaN
104127                          NaN                        NaN
104131                          NaN                        NaN
104143                          NaN                        NaN
104147                          NaN                        NaN
104151                          NaN                        NaN
104163                          NaN                        NaN
104167                          NaN                        NaN

        Genotype Percent Match List Genotype Mismatch List  \
104123                          NaN                    NaN
104127                          NaN                    NaN
104131                          NaN                    NaN
104143                          NaN                    NaN
104147                          NaN                    NaN
104151                          NaN                    NaN
104163                          NaN                    NaN
104167                          NaN                    NaN

       Genotype Average Depth of Coverage List Date run     _merge  \
104123                                     NaN      NaN  left_only
104127                                     NaN      NaN  left_only
104131                                     NaN      NaN  left_only
104143                                     NaN      NaN  left_only
104147                                     NaN      NaN  left_only
104151                                     NaN      NaN  left_only
104163                                     NaN      NaN  left_only
104167                                     NaN      NaN  left_only

                                                   Strain
104123  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104127  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104131  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104143  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104147  Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...
104151  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104163  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...
104167  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...

[8 rows x 41 columns]

## Create FASTA files of unknown genotypes

In [11]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))

# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments_unknown["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments_unknown[metadata_segments_unknown["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments_unknown["Partial_Header"])

print(df_list[0]["full_header"])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

0         >Influenza A virus |Brazil: SaoFranciscoItabap...
1         >Influenza A virus |Brazil: SaoFranciscoItabap...
2         >Influenza A virus |Brazil: SaoFranciscoItabap...
3         >Influenza A virus |Brazil: SaoFranciscoItabap...
4         >Influenza A virus |Brazil: SaoFranciscoItabap...
                                ...
104143    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
104147    >Influenza A virus |Peru|A273|H5N1|2022-12||Ge...
104151    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
104163    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
104167    >Influenza A virus |Peru|A273|H5N1|2022-12|Fal...
Name: Partial_Header, Length: 4640, dtype: object
1192    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1193    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1194    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1195    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1196    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1197    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1198    >Influenza_A_virus__USA__IN_25G02195_004_origi...
1199    >Influenza_A_virus__USA__IN_25G02195_004_origi...
Name: full_header, dtype: object

## Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the downloads directory.

In [12]:
'''
To run GenoFLU-multi, first change directories to Multi-GenoFLU directory (and activate genoflu conda environment):

conda activate genoflu
cd GenoFLU-multi

And then call the python script:

python bin/genoflu-multi.py -f <FASTA_directory>
'''

'\nTo run GenoFLU-multi, first change directories to Multi-GenoFLU directory (and activate genoflu conda environment):\n\nconda activate genoflu\ncd GenoFLU-multi\n\nAnd then call the python script:\n\npython bin/genoflu-multi.py -f <FASTA_directory>\n'

In [32]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t")

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["full_header"].apply(lambda x: "|".join(x.split("|")[:-2]))
for c in ["/", "|", " ", ":", ",", "(", ")", "-"]:
    metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(c, "_"))

metadata_segments_unknown["Partial_Header"] = metadata_segments_unknown["Partial_Header"].apply(lambda x: x.replace(">", ""))

metadata_segments_unknown["Strain"] = metadata_segments_unknown["Partial_Header"] # Renaming so we can merge

# Merge
metadata_genoflu = metadata_segments_unknown.merge(output_genoflu, how="left", on="Strain", suffixes=('_left', '_right')) 

# Fill the rest of the 8 segments with the same genotype
metadata_genoflu = metadata_genoflu.ffill(limit_area="inside")

print(metadata_genoflu[metadata_genoflu["Isolate"] == "A273"])

print(metadata_genoflu["Genotype_x"])

print(metadata_genoflu.columns)

       Accession GenBank_RefSeq Assembly SRA_Accession BioSample BioProject  \
4632  OQ747762.1        GenBank      NaN           NaN       NaN        NaN
4633  OQ747769.1        GenBank      NaN           NaN       NaN        NaN
4634  OQ747882.1        GenBank      NaN           NaN       NaN        NaN
4635  OQ747867.1        GenBank      NaN           NaN       NaN        NaN
4636  OQ747877.1        GenBank      NaN           NaN       NaN        NaN
4637  OQ747893.1        GenBank      NaN           NaN       NaN        NaN
4638  OQ747888.1        GenBank      NaN           NaN       NaN        NaN
4639  OQ747899.1        GenBank      NaN           NaN       NaN        NaN

          Organism_Name                         Species                Genus  \
4632  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4633  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4634  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4635  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4636  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4637  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4638  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus
4639  Influenza A virus  Alphainfluenzavirus influenzae  Alphainfluenzavirus

                Family  ... Date run_left     _merge  \
4632  Orthomyxoviridae  ...           NaN  left_only
4633  Orthomyxoviridae  ...           NaN  left_only
4634  Orthomyxoviridae  ...           NaN  left_only
4635  Orthomyxoviridae  ...           NaN  left_only
4636  Orthomyxoviridae  ...           NaN  left_only
4637  Orthomyxoviridae  ...           NaN  left_only
4638  Orthomyxoviridae  ...           NaN  left_only
4639  Orthomyxoviridae  ...           NaN  left_only

                                                 Strain Genotype  \
4632  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN
4633  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN
4634  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN
4635  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN
4636  Influenza_A_virus__Peru_A273_H5N1_2022_12__Gen...      NaN
4637  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN
4638  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN
4639  Influenza_A_virus__Peru_A273_H5N1_2022_12_Falc...      NaN

      Genotype List Used, >=98.0%_right Genotype Sample Title List_right  \
4632                                NaN                              NaN
4633                                NaN                              NaN
4634                                NaN                              NaN
4635                                NaN                              NaN
4636                                NaN                              NaN
4637                                NaN                              NaN
4638                                NaN                              NaN
4639                                NaN                              NaN

     Genotype Percent Match List_right Genotype Mismatch List_right  \
4632                               NaN                          NaN
4633                               NaN                          NaN
4634                               NaN                          NaN
4635                               NaN                          NaN
4636                               NaN                          NaN
4637                               NaN                          NaN
4638                               NaN                          NaN
4639                               NaN                          NaN

     Genotype Average Depth of Coverage List_right Date run_right
4632                                           NaN            NaN
4633                                           NaN            NaN
4634                                           NaN            NaN
4635                                           NaN            NaN
4636                                           NaN            NaN
4637                                           NaN            NaN
4638                                           NaN            NaN
4639                                           NaN            NaN

[8 rows x 48 columns]
0       H5N1
1       H5N1
2       H5N1
3       H5N1
4       H5N1
        ...
4635    H5N1
4636    H5N1
4637    H5N1
4638    H5N1
4639    H5N1
Name: Genotype_x, Length: 4640, dtype: object
Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header', 'Genotype_y',
       'Genotype List Used, >=98.0%_left', 'Genotype Sample Title List_left',
       'Genotype Percent Match List_left', 'Genotype Mismatch List_left',
       'Genotype Average Depth of Coverage List_left', 'Date run_left',
       '_merge', 'Strain', 'Genotype', 'Genotype List Used, >=98.0%_right',
       'Genotype Sample Title List_right', 'Genotype Percent Match List_right',
       'Genotype Mismatch List_right',
       'Genotype Average Depth of Coverage List_right', 'Date run_right'],
      dtype='object')

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\1\ipykernel_24504\3633387093.py:21: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  metadata_genoflu = metadata_genoflu.ffill(limit_area="inside")

# Concatenate with known genotypes

In [33]:
# Rename columns so we can concatenate
metadata_segments_known["Genotype_official"] = metadata_segments_known["Genotype_y"]
metadata_segments_known["Serotype"] = metadata_segments_known["Genotype_x"]
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype"]
metadata_genoflu["Serotype"] = metadata_genoflu["Genotype_x"]

# Concatenation
metadata_genoflu = pd.concat([metadata_genoflu, metadata_segments_known])

metadata_genoflu.columns

Index(['Accession', 'GenBank_RefSeq', 'Assembly', 'SRA_Accession', 'BioSample',
       'BioProject', 'Organism_Name', 'Species', 'Genus', 'Family',
       'Genotype_x', 'Isolate', 'Segment', 'GenBank_Title', 'Length',
       'Nuc_Completeness', 'Geo_Location', 'Country', 'USA', 'Host',
       'Tissue_Specimen_Source', 'Submitters', 'Organization', 'Org_location',
       'Publications', 'Collection_Date', 'Release_Date', 'Molecule_type',
       'size', 'full_header', 'sequence', 'Partial_Header', 'Genotype_y',
       'Genotype List Used, >=98.0%_left', 'Genotype Sample Title List_left',
       'Genotype Percent Match List_left', 'Genotype Mismatch List_left',
       'Genotype Average Depth of Coverage List_left', 'Date run_left',
       '_merge', 'Strain', 'Genotype', 'Genotype List Used, >=98.0%_right',
       'Genotype Sample Title List_right', 'Genotype Percent Match List_right',
       'Genotype Mismatch List_right',
       'Genotype Average Depth of Coverage List_right', 'Date run_right',
       'Genotype_official', 'Serotype', 'Genotype List Used, >=98.0%',
       'Genotype Sample Title List', 'Genotype Percent Match List',
       'Genotype Mismatch List', 'Genotype Average Depth of Coverage List',
       'Date run', 'Genotype List Used, >=98.0%_x',
       'Genotype Sample Title List_x', 'Genotype Percent Match List_x',
       'Genotype Mismatch List_x', 'Genotype Average Depth of Coverage List_x',
       'date', 'File Name', 'Genotype List Used, >=98.0%_y',
       'Genotype Sample Title List_y', 'Genotype Percent Match List_y',
       'Genotype Mismatch List_y',
       'Genotype Average Depth of Coverage List_y'],
      dtype='object')

In [34]:
metadata_segments_known # .dropna(subset="SRA_Accession")

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,date,File Name,Genotype,"Genotype List Used, >=98.0%_y",Genotype Sample Title List_y,Genotype Percent Match List_y,Genotype Mismatch List_y,Genotype Average Depth of Coverage List_y,Genotype_official,Serotype
0,PV659823.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
1,PV659824.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
2,PV659825.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
3,PV659826.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
4,PV659827.1,GenBank,GCA_053846995.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 4 segments >98.0% match fou...,H5N1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101083,OK205883.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101084,OK205884.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101085,OK205885.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101086,OK205886.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2
101087,OK205887.1,GenBank,GCA_038165665.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Not assigned: Only 0 segments >98.0% match fou...,H5N2

In [35]:
# Cut down to only columns we want
metadata_genoflu = metadata_genoflu[["Accession", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype_official", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "File Name", "Partial_Header", "Strain"]]

# Get genbank strain name
metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] )
metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1])

metadata_genoflu # [metadata_genoflu["Genotype"]  == "B3.13"]

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name
0,PQ284576.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...,H5N1,1,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...
1,PQ284577.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...
2,PQ284578.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...
3,PQ284579.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...
4,PQ284580.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCGAAAGCAGGGTAGATAATCACTCACTGAGTGACATTCACATCA...,H5N1,5,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101083,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101084,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101085,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101086,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995
101087,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Not assigned: Only 0 segments >98.0% match fou...,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995

In [36]:
metadata_genoflu["Serotype"]

0         H5N1
1         H5N1
2         H5N1
3         H5N1
4         H5N1
          ...
101083    H5N2
101084    H5N2
101085    H5N2
101086    H5N2
101087    H5N2
Name: Serotype, Length: 105728, dtype: object

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [37]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print(different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, deal with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['domestic cat', 'chukar', 'ring-necked pheasant', 'seabird', 'snowy owl', 'wild bird', 'black bear', 'peacock', 'emu', 'ferruginous hawk', 'gray seal', 'dog', 'pelecanus thagus', 'mountain lion', 'red-necked phalarope', 'nasua nasua', 'baikal teal', 'sharp-shinned hawk', 'blue-winged and cinnamon teal', 'lesser scaup', 'black scoter', 'crested caracara', 'lynx', 'goat', 'fregata magnificens', 'lesser snow goose blue-morph', 'american crow', 'raptor', 'alpaca', 'american coot', 'guinea fowl', 'waterfowl', 'turkey vulture', 'eared grebe', 'crane', 'gallus', 'pintail', 'american woodcock', 'brant', 'swine', 'common goldeneye', 'sandhill crane', 'ruffed grouse', 'green heron', 'polar bear', 'common barn owl', 'serval', 'sandwich tern', 'redhead duck', 'south american sea lion', 'domestic duck', 'black swift', 'greater white-fronted goose', 'broad-winged hawk', 'great-horned owl', 'american blue-winged teal', 'blue-winged teal', 'willet', 'pigeon', 'western sandpiper', 'herring gull', 'osprey', 'blue jay', 'manx shearwater', 'northern harrier', 'eider', 'northern shoveler', 'domestic goose', 'red-shouldered hawk', 'aves', 'american pelican', 'peregrine falcon', 'house sparrow', 'numida meleagris', 'taiwanese chicken', 'lesser white-fronted goose', 'grackle', 'dromaius novaehollandiae', 'fish crow', 'otaria flavescens', 'backyard chicken', 'cat', 'atlantic puffin', 'turkey', 'snow goose', 'red-breasted merganser', 'rosss goose', 'snowy egret', 'ostrich', 'hooded merganser', 'brown pelican', 'great egret', 'pig', 'black-necked swan', 'parrot', 'pelican', 'black-crowned night-heron', 'western snowy plover', 'gadwall', 'tundra swan', 'chicken', 'peruvian booby', 'merlin', 'mute swan', 'roseate spoonbill', 'crow', 'eagle', 'caspian tern', 'black vulture', 'gallus gallus domesticus', 'american goshawk', 'american black duck', 'bufflehead', 'dunlin', 'trumpeter swan', 'mottled duck', 'sula leucogaster', 'pinniped', 'pelecanus', 'antofagasta', 'red-tailed hawk', 'layer chicken', 'backyard bird', 'northern fulmar', 'pluvialis dominica', 'skunk', 'dovekie', 'thayers gull', 'neotropic cormorant', 'glaucous-winged gull', 'red fox', 'southern elephant seal', 'great horned owl', 'northern gannet', 'gyrfalcon', 'rough-legged hawk', 'domestic grower', 'owl', 'arctic tern', 'buteogallus urubitinga', 'surf scoter', 'thalasseus acuflavidus', 'mink', 'irere', 'horned grebe', 'cattle', 'atlantic white-sided dolphin', 'long-eared owl', 'mallard', 'great grey owl', 'peafowl', 'common merganser', 'black turnstone', 'partridge', 'gallus gallus', 'raven', 'bald eagle', 'california gull', 'northwestern crow', 'barred owl', 'mallard duck', 'pekin duck', 'common eider', 'furnarius rufus', 'franklins gull', 'feline', 'american robin', 'swainsons hawk', 'wild turkey', 'wild duck', 'anatinae', 'swan', 'white-winged scoter', 'great-tailed grackle', 'vulpes vulpes', 'pet food', 'wild goose', 'gull', 'bobcat', 'backyard duck', 'south american tern', 'procellaria aequinoctialis', 'cygnus melancoryphus', 'american wigeon', 'western gull', 'savannah cat', 'great black-backed gull', 'tiger', 'flamingo', 'megascops choliba', 'black skimmer', 'panthera leo', 'canada goose', 'emperor goose', 'vulture', 'red-breasted goose', 'wood duck', 'cattle milk product', 'guinea', 'sterna hirundo', 'common tern', 'royal tern', 'gadwall duck', 'barn owl', 'raw pet food', 'domestic bird', 'dairy cattle', 'ring-billed gull', 'coopers hawk', 'western screech owl', 'goose', 'washington', 'short-billed gull', 'california condor', 'western grebe', 'collared plover', 'black brant', 'dolphin', 'merganser', 'raccoon', 'domestic turkey', 'burrowing owl', 'rock pigeon', 'cackling goose', 'glaucous gull', 'american-kestrel', 'american green-winged teal', 'hawk', 'golden eagle', 'lesser snow goose white-morph', 'rosy-billed pochard', 'great shearwater', 'green winged teal', 'american kestrel', 'bovine', 'white-winged dove', 'gannet', 'fisher', 'bos taurus', 'razorbill', 'dove', 'cormorant', 'parasitic jaeger', 'green-winged teal', 'house mouse', 'cygnus atratus', 'american white pelican', 'guineafowl', 'common murre', 'laridae', 'black-crowned night heron', 'eastern screech owl', 'pheasant', 'greater yellowlegs', 'iceland gull', 'dairy cow', 'teal', 'avian', 'broiler breeders chicken', 'eurasian collared dove', 'striped skunk', 'backyard turkey', 'poultry', 'mergus', 'silver pheasant', 'double-crested cormorant', 'guanay cormorant', 'black-billed magpie', 'sanderling', 'nannopterum brasilianus', 'black-legged kittiwake', 'fancy chicken', 'ring-necked duck', 'sparrow', 'quail', 'american wood stork', 'greater scaup', 'dendrocygna viduata', 'magpie', 'common raven', 'lesser snow goose', 'northern pintail', 'muscovy duck', 'thalasseus maximus', 'south american fur seal', 'south polar skua', 'great blue heron', 'heron', 'short-eared owl', 'redhead', 'unknown', 'black swan', 'environment', 'cinnamon teal', 'feral cat', 'duck', 'snowy plover', 'common loon', 'red-necked grebe', 'graylag goose', 'harbor seal']
[]
                       wild_avian domestic_avian               cattle  \
0                great_horned_owl       pheasant            dairy_cow
1                    common_raven         turkey               cattle
2                   cooper's_hawk        chicken  cattle milk product
3                    coopers_hawk          goose          bovine_milk
4                         peafowl    guinea_fowl              bovine
...                           ...            ...                  ...
1127                   wild duckl            NaN                  NaN
1128  greater white fronted goose            NaN                  NaN
1129             barrow goldeneye            NaN                  NaN
1130                 cattle egret            NaN                  NaN
1131             wild duck hybrid            NaN                  NaN

            feline   other_mammal       human         other      pet_food  new
0              cat     deer mouse  washington         mixed      pet food  NaN
1     domestic_cat    house_mouse      nevada   environment  raw pet food  NaN
2        feral_cat          skunk     wyoming  multispecies  raw_pet_food  NaN
3           feline  striped_skunk  california       unknown      pet_food  NaN
4     domestic-cat     norway rat    michigan             '           NaN  NaN
...            ...            ...         ...           ...           ...  ...
1127           NaN            NaN         NaN           NaN           NaN  NaN
1128           NaN            NaN         NaN           NaN           NaN  NaN
1129           NaN            NaN         NaN           NaN           NaN  NaN
1130           NaN            NaN         NaN           NaN           NaN  NaN
1131           NaN            NaN         NaN           NaN           NaN  NaN

[1132 rows x 9 columns]

In [38]:
metadata_genoflu["Genotype_official"] = metadata_genoflu["Genotype_official"].apply(lambda x: "Unassigned" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"
metadata_genoflu["Genotype"] = metadata_genoflu["Genotype_official"] # Rename column again to not break old code

In [39]:
metadata_genoflu

,Accession,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype_official,Geo_Location,full_header,sequence,Serotype,Segment,File Name,Partial_Header,Strain,genbank_name,Genotype
0,PQ284576.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...,H5N1,1,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...,B3.2
1,PQ284577.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...,B3.2
2,PQ284578.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...,B3.2
3,PQ284579.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...,H5N1,4,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...,B3.2
4,PQ284580.1,Influenza A virus (A/Sterna hirundo/SaoFrancis...,Sterna hirundo,2024-04-05,NaN,1060-N-2024,B3.2,Brazil: SaoFranciscoItabapoanaBR,>Influenza A virus |Brazil: SaoFranciscoItabap...,AGCGAAAGCAGGGTAGATAATCACTCACTGAGTGACATTCACATCA...,H5N1,5,NaN,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,Influenza_A_virus__Brazil__SaoFranciscoItabapo...,A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...,B3.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101083,OK205883.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...,H5N2,4,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
101084,OK205884.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...,H5N2,5,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
101085,OK205885.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...,H5N2,6,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
101086,OK205886.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...,H5N2,7,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned
101087,OK205887.1,Influenza A virus (A/chicken/Veracruz/28159-39...,chicken,1995,NaN,28159-398,Unassigned,Mexico: Veracruz,>Influenza A virus |Mexico: Veracruz|28159-398...,AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...,H5N2,8,NaN,Influenza_A_virus__Mexico__Veracruz_28159_398_...,NaN,A/chicken/Veracruz/28159-398/1995,Unassigned

In [40]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# Get geographic locations
metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location"].apply(lambda x: 
                                                                        # If "x" has the state abbreviation (e.g. "MD")
                                                                        states_ref.loc[states_ref["Abbreviation"].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0] 
                                                                        + "-" + 
                                                                        x.split(" ")[-1]
                                                                        if states_ref["Abbreviation"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has the full state name (e.g. "Maryland")
                                                                        else states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Country'].iloc[0]
                                                                        + "-" + 
                                                                        states_ref.loc[states_ref['State'].str.contains('|'.join(re.sub(":? ", ",", x).replace(" ", "_").split(',')), regex=True), 'Abbreviation'].iloc[0] 
                                                                        if states_ref["State"].str.contains("|".join((re.sub(":? ", ",", x).replace(" ", "_").split(','))), regex=True).any()
                                                                        # If "x" has neither the state abbreviation nor the full state name nor is "USA"
                                                                        else 
                                                                        x
                                                                        )

metadata_genoflu["Geo_Location_Abrv"] = metadata_genoflu["Geo_Location_Abrv"].apply(lambda x: x.split("-")[0] if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] else x)


print(metadata_genoflu["Geo_Location_Abrv"])

0         Brazil-SaoFranciscoItabapoanaBR
1         Brazil-SaoFranciscoItabapoanaBR
2         Brazil-SaoFranciscoItabapoanaBR
3         Brazil-SaoFranciscoItabapoanaBR
4         Brazil-SaoFranciscoItabapoanaBR
                       ...
101083                    Mexico-Veracruz
101084                    Mexico-Veracruz
101085                    Mexico-Veracruz
101086                    Mexico-Veracruz
101087                    Mexico-Veracruz
Name: Geo_Location_Abrv, Length: 105728, dtype: object

In [ ]:
metadata_genoflu['SRA_Accession'] = np.where(metadata_genoflu['SRA_Accession'] == "", metadata_genoflu['Accession'].apply(lambda x: x.split(".")[0]), metadata_genoflu['SRA_Accession'])

# Make new labels
names = ">" + metadata_genoflu["SRA_Accession"].apply(lambda x: x.split(",")[0]) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_Abrv"] + "|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names


print(metadata_genoflu)

         Accession                                      GenBank_Title  \
0       PQ284576.1  Influenza A virus (A/Sterna hirundo/SaoFrancis...
1       PQ284577.1  Influenza A virus (A/Sterna hirundo/SaoFrancis...
2       PQ284578.1  Influenza A virus (A/Sterna hirundo/SaoFrancis...
3       PQ284579.1  Influenza A virus (A/Sterna hirundo/SaoFrancis...
4       PQ284580.1  Influenza A virus (A/Sterna hirundo/SaoFrancis...
...            ...                                                ...
101083  OK205883.1  Influenza A virus (A/chicken/Veracruz/28159-39...
101084  OK205884.1  Influenza A virus (A/chicken/Veracruz/28159-39...
101085  OK205885.1  Influenza A virus (A/chicken/Veracruz/28159-39...
101086  OK205886.1  Influenza A virus (A/chicken/Veracruz/28159-39...
101087  OK205887.1  Influenza A virus (A/chicken/Veracruz/28159-39...

                  Host Collection_Date SRA_Accession      Isolate  \
0       sterna hirundo      2024-04-05      PQ284576  1060-N-2024
1       sterna hirundo      2024-04-05      PQ284577  1060-N-2024
2       sterna hirundo      2024-04-05      PQ284578  1060-N-2024
3       sterna hirundo      2024-04-05      PQ284579  1060-N-2024
4       sterna hirundo      2024-04-05      PQ284580  1060-N-2024
...                ...             ...           ...          ...
101083         chicken            1995      OK205883    28159-398
101084         chicken            1995      OK205884    28159-398
101085         chicken            1995      OK205885    28159-398
101086         chicken            1995      OK205886    28159-398
101087         chicken            1995      OK205887    28159-398

       Genotype_official                      Geo_Location  \
0                   B3.2  Brazil: SaoFranciscoItabapoanaBR
1                   B3.2  Brazil: SaoFranciscoItabapoanaBR
2                   B3.2  Brazil: SaoFranciscoItabapoanaBR
3                   B3.2  Brazil: SaoFranciscoItabapoanaBR
4                   B3.2  Brazil: SaoFranciscoItabapoanaBR
...                  ...                               ...
101083        Unassigned                  Mexico: Veracruz
101084        Unassigned                  Mexico: Veracruz
101085        Unassigned                  Mexico: Veracruz
101086        Unassigned                  Mexico: Veracruz
101087        Unassigned                  Mexico: Veracruz

                                              full_header  \
0       >Influenza A virus |Brazil: SaoFranciscoItabap...
1       >Influenza A virus |Brazil: SaoFranciscoItabap...
2       >Influenza A virus |Brazil: SaoFranciscoItabap...
3       >Influenza A virus |Brazil: SaoFranciscoItabap...
4       >Influenza A virus |Brazil: SaoFranciscoItabap...
...                                                   ...
101083  >Influenza A virus |Mexico: Veracruz|28159-398...
101084  >Influenza A virus |Mexico: Veracruz|28159-398...
101085  >Influenza A virus |Mexico: Veracruz|28159-398...
101086  >Influenza A virus |Mexico: Veracruz|28159-398...
101087  >Influenza A virus |Mexico: Veracruz|28159-398...

                                                 sequence  ... Segment  \
0       AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...       1
1       AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...  ...       2
2       AGCAAAAGCAGGTACTGATTCAAAATGGAAGACTTTGTGCGACAAT...  ...       3
3       AGCAAAAGCAGGGGTTCACTCTGTCAAAATGGAGAACATAGTACTA...  ...       4
4       AGCGAAAGCAGGGTAGATAATCACTCACTGAGTGACATTCACATCA...  ...       5
...                                                   ...  ...     ...
101083  AGCAAAAGCAGGGGTATCAGATATCAAAATGGAAAGAATAGTGATT...  ...       4
101084  AGCAAAAGCAGGTTAGATAATCACTCACCGAGTGACATTCACATCA...  ...       5
101085  AGCAAAAGCAGGAGTGAAGATGAATCCAAATCAGAAGATAATAACA...  ...       6
101086  AGCAAAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTC...  ...       7
101087  AGCAAAAGCAGGGTGACAAATACATAATGGACTCCAACACGATAAC...  ...       8

        File Name                                     Partial_Header  \
0                  Influenza_A_virus__Brazil__SaoFranciscoItabapo...
1                  Influenza_A_virus__Brazil__SaoFranciscoItabapo...
2                  Influenza_A_virus__Brazil__SaoFranciscoItabapo...
3                  Influenza_A_virus__Brazil__SaoFranciscoItabapo...
4                  Influenza_A_virus__Brazil__SaoFranciscoItabapo...
...           ...                                                ...
101083             Influenza_A_virus__Mexico__Veracruz_28159_398_...
101084             Influenza_A_virus__Mexico__Veracruz_28159_398_...
101085             Influenza_A_virus__Mexico__Veracruz_28159_398_...
101086             Influenza_A_virus__Mexico__Veracruz_28159_398_...
101087             Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                   Strain  \
0       Influenza_A_virus__Brazil__SaoFranciscoItabapo...
1       Influenza_A_virus__Brazil__SaoFranciscoItabapo...
2       Influenza_A_virus__Brazil__SaoFranciscoItabapo...
3       Influenza_A_virus__Brazil__SaoFranciscoItabapo...
4       Influenza_A_virus__Brazil__SaoFranciscoItabapo...
...                                                   ...
101083
101084
101085
101086
101087

                                             genbank_name    Genotype  \
0       A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...        B3.2
1       A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...        B3.2
2       A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...        B3.2
3       A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...        B3.2
4       A/Sterna hirundo/SaoFranciscoItabapoanaBR/1060...        B3.2
...                                                   ...         ...
101083                  A/chicken/Veracruz/28159-398/1995  Unassigned
101084                  A/chicken/Veracruz/28159-398/1995  Unassigned
101085                  A/chicken/Veracruz/28159-398/1995  Unassigned
101086                  A/chicken/Veracruz/28159-398/1995  Unassigned
101087                  A/chicken/Veracruz/28159-398/1995  Unassigned

             Host_Type Years                Geo_Location_Abrv  \
0           wild_avian  2024  Brazil-SaoFranciscoItabapoanaBR
1           wild_avian  2024  Brazil-SaoFranciscoItabapoanaBR
2           wild_avian  2024  Brazil-SaoFranciscoItabapoanaBR
3           wild_avian  2024  Brazil-SaoFranciscoItabapoanaBR
4           wild_avian  2024  Brazil-SaoFranciscoItabapoanaBR
...                ...   ...                              ...
101083  domestic_avian  1995                  Mexico-Veracruz
101084  domestic_avian  1995                  Mexico-Veracruz
101085  domestic_avian  1995                  Mexico-Veracruz
101086  domestic_avian  1995                  Mexico-Veracruz
101087  domestic_avian  1995                  Mexico-Veracruz

                                                     Name
0       >PQ284576|A/Sterna hirundo/SaoFranciscoItabapo...
1       >PQ284577|A/Sterna hirundo/SaoFranciscoItabapo...
2       >PQ284578|A/Sterna hirundo/SaoFranciscoItabapo...
3       >PQ284579|A/Sterna hirundo/SaoFranciscoItabapo...
4       >PQ284580|A/Sterna hirundo/SaoFranciscoItabapo...
...                                                   ...
101083  >OK205883|A/chicken/Veracruz/28159-398/1995|H5...
101084  >OK205884|A/chicken/Veracruz/28159-398/1995|H5...
101085  >OK205885|A/chicken/Veracruz/28159-398/1995|H5...
101086  >OK205886|A/chicken/Veracruz/28159-398/1995|H5...
101087  >OK205887|A/chicken/Veracruz/28159-398/1995|H5...

[105728 rows x 21 columns]

In [42]:
# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

105728
105528

## Rename segments and make complete FASTA files

In [43]:
# Set up segments

genotypes.append("Unassigned") # Make sure unassigned genotypes are included
segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)

Minor07_PB2
Minor45_PB2
Minor14_PB2
B2.1_PB2
Minor28_PB2
Minor34_PB2
Unassigned_PB2
B3.12_PB2
Minor09_PB2
B3.3_PB2
Minor90_PB2
Minor50_PB2
D1.1_PB2
Minor63_PB2
B3.4_PB2
Minor91_PB2
B5.1_PB2
Minor11_PB2
Minor104_PB2
A2_PB2
B3.5_PB2
B2.2_PB2
Minor19_PB2
A3_PB2
Minor65_PB2
Minor13_PB2
Minor98_PB2
B1.1_PB2
Minor94_PB2
B3.10_PB2
C2.1_PB2
Minor81_PB2
B1.2_PB2
Minor77_PB2
Minor08_PB2
A1_PB2
Minor12_PB2
B3.1_PB2
Minor87_PB2
B3.2_PB2
A4_PB2
B3.7_PB2
Minor102_PB2
Minor04_PB2
B4.1_PB2
D1.3_PB2
B3.13_PB2
Minor101_PB2
A6_PB2
Minor01_PB2
A5_PB2
D1.2_PB2
B1.3_PB2
B3.6_PB2
Minor105_PB2
Minor07_PB1
Minor45_PB1
Minor14_PB1
B2.1_PB1
Minor28_PB1
Minor34_PB1
Unassigned_PB1
B3.12_PB1
Minor09_PB1
B3.3_PB1
Minor90_PB1
Minor50_PB1
D1.1_PB1
Minor63_PB1
B3.4_PB1
Minor91_PB1
B5.1_PB1
Minor11_PB1
Minor104_PB1
A2_PB1
B3.5_PB1
B2.2_PB1
Minor19_PB1
A3_PB1
Minor65_PB1
Minor13_PB1
Minor98_PB1
B1.1_PB1
Minor94_PB1
B3.10_PB1
C2.1_PB1
Minor81_PB1
B1.2_PB1
Minor77_PB1
Minor08_PB1
A1_PB1
Minor12_PB1
B3.1_PB1
Minor87_PB1
B3.2_PB1
A4_PB1
B3.7_PB1
Minor102_PB1
Minor04_PB1
B4.1_PB1
D1.3_PB1
B3.13_PB1
Minor101_PB1
A6_PB1
Minor01_PB1
A5_PB1
D1.2_PB1
B1.3_PB1
B3.6_PB1
Minor105_PB1
Minor07_PA
Minor45_PA
Minor14_PA
B2.1_PA
Minor28_PA
Minor34_PA
Unassigned_PA
B3.12_PA
Minor09_PA
B3.3_PA
Minor90_PA
Minor50_PA
D1.1_PA
Minor63_PA
B3.4_PA
Minor91_PA
B5.1_PA
Minor11_PA
Minor104_PA
A2_PA
B3.5_PA
B2.2_PA
Minor19_PA
A3_PA
Minor65_PA
Minor13_PA
Minor98_PA
B1.1_PA
Minor94_PA
B3.10_PA
C2.1_PA
Minor81_PA
B1.2_PA
Minor77_PA
Minor08_PA
A1_PA
Minor12_PA
B3.1_PA
Minor87_PA
B3.2_PA
A4_PA
B3.7_PA
Minor102_PA
Minor04_PA
B4.1_PA
D1.3_PA
B3.13_PA
Minor101_PA
A6_PA
Minor01_PA
A5_PA
D1.2_PA
B1.3_PA
B3.6_PA
Minor105_PA
Minor07_HA
Minor45_HA
Minor14_HA
B2.1_HA
Minor28_HA
Minor34_HA
Unassigned_HA
B3.12_HA
Minor09_HA
B3.3_HA
Minor90_HA
Minor50_HA
D1.1_HA
Minor63_HA
B3.4_HA
Minor91_HA
B5.1_HA
Minor11_HA
Minor104_HA
A2_HA
B3.5_HA
B2.2_HA
Minor19_HA
A3_HA
Minor65_HA
Minor13_HA
Minor98_HA
B1.1_HA
Minor94_HA
B3.10_HA
C2.1_HA
Minor81_HA
B1.2_HA
Minor77_HA
Minor08_HA
A1_HA
Minor12_HA
B3.1_HA
Minor87_HA
B3.2_HA
A4_HA
B3.7_HA
Minor102_HA
Minor04_HA
B4.1_HA
D1.3_HA
B3.13_HA
Minor101_HA
A6_HA
Minor01_HA
A5_HA
D1.2_HA
B1.3_HA
B3.6_HA
Minor105_HA
Minor07_NP
Minor45_NP
Minor14_NP
B2.1_NP
Minor28_NP
Minor34_NP
Unassigned_NP
B3.12_NP
Minor09_NP
B3.3_NP
Minor90_NP
Minor50_NP
D1.1_NP
Minor63_NP
B3.4_NP
Minor91_NP
B5.1_NP
Minor11_NP
Minor104_NP
A2_NP
B3.5_NP
B2.2_NP
Minor19_NP
A3_NP
Minor65_NP
Minor13_NP
Minor98_NP
B1.1_NP
Minor94_NP
B3.10_NP
C2.1_NP
Minor81_NP
B1.2_NP
Minor77_NP
Minor08_NP
A1_NP
Minor12_NP
B3.1_NP
Minor87_NP
B3.2_NP
A4_NP
B3.7_NP
Minor102_NP
Minor04_NP
B4.1_NP
D1.3_NP
B3.13_NP
Minor101_NP
A6_NP
Minor01_NP
A5_NP
D1.2_NP
B1.3_NP
B3.6_NP
Minor105_NP
Minor07_NA
Minor45_NA
Minor14_NA
B2.1_NA
Minor28_NA
Minor34_NA
Unassigned_NA
B3.12_NA
Minor09_NA
B3.3_NA
Minor90_NA
Minor50_NA
D1.1_NA
Minor63_NA
B3.4_NA
Minor91_NA
B5.1_NA
Minor11_NA
Minor104_NA
A2_NA
B3.5_NA
B2.2_NA
Minor19_NA
A3_NA
Minor65_NA
Minor13_NA
Minor98_NA
B1.1_NA
Minor94_NA
B3.10_NA
C2.1_NA
Minor81_NA
B1.2_NA
Minor77_NA
Minor08_NA
A1_NA
Minor12_NA
B3.1_NA
Minor87_NA
B3.2_NA
A4_NA
B3.7_NA
Minor102_NA
Minor04_NA
B4.1_NA
D1.3_NA
B3.13_NA
Minor101_NA
A6_NA
Minor01_NA
A5_NA
D1.2_NA
B1.3_NA
B3.6_NA
Minor105_NA
Minor07_MP
Minor45_MP
Minor14_MP
B2.1_MP
Minor28_MP
Minor34_MP
Unassigned_MP
B3.12_MP
Minor09_MP
B3.3_MP
Minor90_MP
Minor50_MP
D1.1_MP
Minor63_MP
B3.4_MP
Minor91_MP
B5.1_MP
Minor11_MP
Minor104_MP
A2_MP
B3.5_MP
B2.2_MP
Minor19_MP
A3_MP
Minor65_MP
Minor13_MP
Minor98_MP
B1.1_MP
Minor94_MP
B3.10_MP
C2.1_MP
Minor81_MP
B1.2_MP
Minor77_MP
Minor08_MP
A1_MP
Minor12_MP
B3.1_MP
Minor87_MP
B3.2_MP
A4_MP
B3.7_MP
Minor102_MP
Minor04_MP
B4.1_MP
D1.3_MP
B3.13_MP
Minor101_MP
A6_MP
Minor01_MP
A5_MP
D1.2_MP
B1.3_MP
B3.6_MP
Minor105_MP
Minor07_NS
Minor45_NS
Minor14_NS
B2.1_NS
Minor28_NS
Minor34_NS
Unassigned_NS
B3.12_NS
Minor09_NS
B3.3_NS
Minor90_NS
Minor50_NS
D1.1_NS
Minor63_NS
B3.4_NS
Minor91_NS
B5.1_NS
Minor11_NS
Minor104_NS
A2_NS
B3.5_NS
B2.2_NS
Minor19_NS
A3_NS
Minor65_NS
Minor13_NS
Minor98_NS
B1.1_NS
Minor94_NS
B3.10_NS
C2.1_NS
Minor81_NS
B1.2_NS
Minor77_NS
Minor08_NS
A1_NS
Minor12_NS
B3.1_NS
Minor87_NS
B3.2_NS
A4_NS
B3.7_NS
Minor102_NS
Minor04_NS
B4.1_NS
D1.3_NS
B3.13_NS
Minor101_NS
A6_NS
Minor01_NS
A5_NS
D1.2_NS
B1.3_NS
B3.6_NS
Minor105_NS

In [44]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files + file_name, "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

        Accession                                      GenBank_Title  \
15600  PV309253.1  Influenza A virus (A/Domestic bird/AB/FAV-0893...
89864  OQ958737.1  Influenza A virus (A/Backyard bird/Nebraska/22...

                Host Collection_Date SRA_Accession          Isolate  \
15600  domestic bird      2022-08-16      PV309253  FAV-0893-1-2022
89864  backyard bird      2022-04-26      OQ958737    22-013105-001

      Genotype_official   Geo_Location  \
15600           Minor07     Canada: AB
89864           Minor07  USA: Nebraska

                                             full_header  \
15600  >Influenza A virus |Canada: AB|FAV-0893-1-2022...
89864  >Influenza A virus |USA: Nebraska|22-013105-00...

                                                sequence  ... File Name  \
15600  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
89864  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
15600  Influenza_A_virus__Canada__AB_FAV_0893_1_2022_...
89864  Influenza_A_virus__USA__Nebraska_22_013105_001...

                                      genbank_name Genotype       Host_Type  \
15600      A/Domestic bird/AB/FAV-0893-1-2022/2022  Minor07  domestic_avian
89864  A/Backyard bird/Nebraska/22-013105-001/2022  Minor07      wild_avian

      Years Geo_Location_Abrv  \
15600  2022         Canada-AB
89864  2022            USA-NE

                                                    Name Segment_Name
15600  >PV309253|A/Domestic bird/AB/FAV-0893-1-2022/2...          PB2
89864  >OQ958737|A/Backyard bird/Nebraska/22-013105-0...          PB2

[2 rows x 22 columns]
        Accession                                      GenBank_Title  \
88104  PP802763.1  Influenza A virus (A/northern pintail/USA/IZ22...

                   Host Collection_Date SRA_Accession    Isolate  \
88104  northern pintail      2022-09-28      PP802763  IZ22_0615

      Genotype_official Geo_Location  \
88104           Minor45          USA

                                             full_header  \
88104  >Influenza A virus |USA|IZ22_0615|H5N1|2022-09...

                                                sequence  ... File Name  \
88104  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
88104  Influenza_A_virus__USA_IZ22_0615_H5N1_2022_09_...

                                genbank_name Genotype   Host_Type Years  \
88104  A/northern pintail/USA/IZ22_0615/2022  Minor45  wild_avian  2022

      Geo_Location_Abrv                                               Name  \
88104               USA  >PP802763|A/northern pintail/USA/IZ22_0615/202...

      Segment_Name
88104          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
93880  OQ962769.1  Influenza A virus (A/Pheasant/New York/22-0087...

           Host Collection_Date SRA_Accession        Isolate  \
93880  pheasant      2022-03-22      OQ962769  22-008760-010

      Genotype_official   Geo_Location  \
93880           Minor14  USA: New York

                                             full_header  \
93880  >Influenza A virus |USA: New York|22-008760-01...

                                                sequence  ... File Name  \
93880  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
93880  Influenza_A_virus__USA__New_York_22_008760_010...

                                 genbank_name Genotype       Host_Type Years  \
93880  A/Pheasant/New York/22-008760-010/2022  Minor14  domestic_avian  2022

      Geo_Location_Abrv                                               Name  \
93880            USA-NH  >OQ962769|A/Pheasant/New York/22-008760-010/20...

      Segment_Name
93880          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
7816   PV301462.1  Influenza A virus (A/Snow Goose/SK/FAV-0268-29...
9560   PV303213.1  Influenza A virus (A/American Crow/SK/FAV-0802...
9656   PV303309.1  Influenza A virus (A/American White Pelican/BC...
9928   PV303581.1  Influenza A virus (A/Bald Eagle/BC/FAV-0856-14...
9936   PV303589.1  Influenza A virus (A/Bald Eagle/BC/FAV-0856-15...
...           ...                                                ...
99128  OQ968033.1  Influenza A virus (A/goose/Minnesota/22-011138...
99136  OQ968041.1  Influenza A virus (A/goose/Minnesota/22-011138...
99144  OQ968049.1  Influenza A virus (A/goose/Minnesota/22-012373...
99168  OQ968073.1  Influenza A virus (A/goose/Wyoming/22-010936-0...
99497  OQ843962.1  Influenza A virus (A/environment/Wright County...

                         Host Collection_Date SRA_Accession           Isolate  \
7816               snow goose      2022-04-10      PV301462  FAV-0268-29-2022
9560            american crow      2022-05-20      PV303213  FAV-0802-84-2022
9656   american white pelican      2022-05-05      PV303309   OTH-0097-1-2022
9928               bald eagle      2022-06-10      PV303581  FAV-0856-14-2022
9936               bald eagle      2022-06-29      PV303589  FAV-0856-15-2022
...                       ...             ...           ...               ...
99128                   goose      2022-04-11      OQ968033     22-011138-001
99136                   goose      2022-04-11      OQ968041     22-011138-002
99144                   goose      2022-04-21      OQ968049     22-012373-002
99168                   goose      2022-04-07      OQ968073     22-010936-001
99497             environment      2022-04-14      OQ843962          Wright-A

      Genotype_official             Geo_Location  \
7816               B2.1               Canada: SK
9560               B2.1               Canada: SK
9656               B2.1               Canada: BC
9928               B2.1               Canada: BC
9936               B2.1               Canada: BC
...                 ...                      ...
99128              B2.1           USA: Minnesota
99136              B2.1           USA: Minnesota
99144              B2.1           USA: Minnesota
99168              B2.1             USA: Wyoming
99497              B2.1  USA:Wright County, Iowa

                                             full_header  \
7816   >Influenza A virus |Canada: SK|FAV-0268-29-202...
9560   >Influenza A virus |Canada: SK|FAV-0802-84-202...
9656   >Influenza A virus |Canada: BC|OTH-0097-1-2022...
9928   >Influenza A virus |Canada: BC|FAV-0856-14-202...
9936   >Influenza A virus |Canada: BC|FAV-0856-15-202...
...                                                  ...
99128  >Influenza A virus |USA: Minnesota|22-011138-0...
99136  >Influenza A virus |USA: Minnesota|22-011138-0...
99144  >Influenza A virus |USA: Minnesota|22-012373-0...
99168  >Influenza A virus |USA: Wyoming|22-010936-001...
99497  >Influenza A virus |USA:Wright County, Iowa|Wr...

                                                sequence  ... File Name  \
7816   ATGGAGAGAATAAAAGAATTAAGAGATCTAATGTCACAGTCTCGCA...  ...
9560   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
9656   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
9928   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
9936   ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
...                                                  ...  ...       ...
99128  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
99136  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
99144  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
99168  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...
99497  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
7816   Influenza_A_virus__Canada__SK_FAV_0268_29_2022...
9560   Influenza_A_virus__Canada__SK_FAV_0802_84_2022...
9656   Influenza_A_virus__Canada__BC_OTH_0097_1_2022_...
9928   Influenza_A_virus__Canada__BC_FAV_0856_14_2022...
9936   Influenza_A_virus__Canada__BC_FAV_0856_15_2022...
...                                                  ...    ...
99128  Influenza_A_virus__USA__Minnesota_22_011138_00...
99136  Influenza_A_virus__USA__Minnesota_22_011138_00...
99144  Influenza_A_virus__USA__Minnesota_22_012373_00...
99168  Influenza_A_virus__USA__Wyoming_22_010936_001_...
99497  Influenza_A_virus__USA_Wright_County__Iowa_Wri...

                                           genbank_name Genotype  \
7816              A/Snow Goose/SK/FAV-0268-29-2022/2022     B2.1
9560           A/American Crow/SK/FAV-0802-84-2022/2022     B2.1
9656   A/American White Pelican/BC/OTH-0097-1-2022/2022     B2.1
9928              A/Bald Eagle/BC/FAV-0856-14-2022/2022     B2.1
9936              A/Bald Eagle/BC/FAV-0856-15-2022/2022     B2.1
...                                                 ...      ...
99128              A/goose/Minnesota/22-011138-001/2022     B2.1
99136              A/goose/Minnesota/22-011138-002/2022     B2.1
99144              A/goose/Minnesota/22-012373-002/2022     B2.1
99168                A/goose/Wyoming/22-010936-001/2022     B2.1
99497         A/environment/Wright County/Wright-A/2022     B2.1

            Host_Type Years Geo_Location_Abrv  \
7816       wild_avian  2022         Canada-SK
9560       wild_avian  2022         Canada-SK
9656       wild_avian  2022         Canada-BC
9928       wild_avian  2022         Canada-BC
9936       wild_avian  2022         Canada-BC
...               ...   ...               ...
99128  domestic_avian  2022            USA-MN
99136  domestic_avian  2022            USA-MN
99144  domestic_avian  2022            USA-MN
99168  domestic_avian  2022            USA-WY
99497           other  2022          USA-Iowa

                                                    Name Segment_Name
7816   >PV301462|A/Snow Goose/SK/FAV-0268-29-2022/202...          PB2
9560   >PV303213|A/American Crow/SK/FAV-0802-84-2022/...          PB2
9656   >PV303309|A/American White Pelican/BC/OTH-0097...          PB2
9928   >PV303581|A/Bald Eagle/BC/FAV-0856-14-2022/202...          PB2
9936   >PV303589|A/Bald Eagle/BC/FAV-0856-15-2022/202...          PB2
...                                                  ...          ...
99128  >OQ968033|A/goose/Minnesota/22-011138-001/2022...          PB2
99136  >OQ968041|A/goose/Minnesota/22-011138-002/2022...          PB2
99144  >OQ968049|A/goose/Minnesota/22-012373-002/2022...          PB2
99168  >OQ968073|A/goose/Wyoming/22-010936-001/2022|H...          PB2
99497  >OQ843962|A/environment/Wright County/Wright-A...          PB2

[852 rows x 22 columns]
        Accession                                      GenBank_Title  \
76088  PQ717094.1  Influenza A virus (A/Ross's goose/MS/22-038267...

               Host Collection_Date SRA_Accession                 Isolate  \
76088  ross's goose      2022-11-21      PQ717094  22-038267-001-original

      Genotype_official Geo_Location  \
76088           Minor28      USA: MS

                                             full_header  \
76088  >Influenza A virus |USA: MS|22-038267-001-orig...

                                                sequence  ... File Name  \
76088  ATGGAGAGAATAAAAGAACTAAGAGATCTAATGTCACAGTCTCGCA...  ...

                                          Partial_Header Strain  \
76088  Influenza_A_virus__USA__MS_22_038267_001_origi...

                                        genbank_name Genotype   Host_Type  \
76088  A/Ross's goose/MS/22-038267-001-original/2022  Minor28  wild_avian

      Years Geo_Location_Abrv  \
76088  2022            USA-MS

                                                    Name Segment_Name
76088  >PQ717094|A/Ross's goose/MS/22-038267-001-orig...          PB2

[1 rows x 22 columns]
        Accession                                      GenBank_Title  \
65200  PQ706182.1  Influenza A virus (A/Blue-winged teal/MN/23-01...

                   Host Collection_Date SRA_Accession                 Isolate  \
65200  blue-winged teal      2022-09-17      PQ706182  23-013078-002-original

      Genotype_official Geo_Location  \
65200           Minor34      USA: MN

                                             full_header  \
65200  >Influenza A virus |USA: MN|23-013078-002-orig...

                                                sequence  ... File Name  \
65200  ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCCCGCA...  ...

                                          Partial_Header Strain  \
65200  Influenza_A_virus__USA__MN_23_013078_002_origi...

                                            genbank_name Genotype   Host_Type  \
65200  A/Blue-winged teal/MN/23-013078-002-original/2022  Minor34  wild_avian

      Years Geo_Location_Abrv  \
65200  2022            USA-MN

                                                    Name Segment_Name
65200  >PQ706182|A/Blue-winged teal/MN/23-013078-002-...          PB2

[1 rows x 22 columns]
         Accession                                      GenBank_Title  \
72      PX748100.1  Influenza A virus (A/Turkey/MN/25G02013-001-or...
136     PX748164.1  Influenza A virus (A/Turkey/MN/25G02321-002-or...
528     PX748556.1  Influenza A virus (A/Turkey/MN/25G02013-002-or...
728     PX748756.1  Influenza A virus (A/Domestic Duck/MN/25G01806...
1344    PX749380.1  Influenza A virus (A/Guineafowl/MN/25G01806-00...
...            ...                                                ...
101048  OK205848.1  Influenza A virus (A/chicken/San Luis Potosi/7...
101056  OK205856.1  Influenza A virus (A/chicken/Tabasco/234-8289/...
101064  OK205864.1  Influenza A virus (A/chicken/Veracruz/232-6169...
101072  OK205872.1  Influenza A virus (A/chicken/Veracruz/233-7607...
101080  OK205880.1  Influenza A virus (A/chicken/Veracruz/28159-39...

                 Host Collection_Date SRA_Accession                Isolate  \
72             turkey      2025-10-10   SRR36162727  25G02013-001-original
136            turkey      2025-10-16   SRR36162652  25G02321-002-original
528            turkey      2025-10-10   SRR36162807  25G02013-002-original
728     domestic duck      2025-10-07   SRR36162618  25G01806-001-original
1344       guineafowl      2025-10-07   SRR36162617  25G01806-003-original
...               ...             ...           ...                    ...
101048        chicken            1996      OK205848                   7651
101056        chicken            1998      OK205856               234-8289
101064        chicken            1998      OK205864               232-6169
101072        chicken            1998      OK205872               233-7607
101080        chicken            1995      OK205880              28159-398

       Genotype_official             Geo_Location  \
72            Unassigned                  USA: MN
136           Unassigned                  USA: MN
528           Unassigned                  USA: MN
728           Unassigned                  USA: MN
1344          Unassigned                  USA: MN
...                  ...                      ...
101048        Unassigned  Mexico: San Luis Potosi
101056        Unassigned          Mexico: Tabasco
101064        Unassigned         Mexico: Veracruz
101072        Unassigned         Mexico: Veracruz
101080        Unassigned         Mexico: Veracruz

                                              full_header  \
72      >Influenza A virus |USA: MN|25G02013-001-origi...
136     >Influenza A virus |USA: MN|25G02321-002-origi...
528     >Influenza A virus |USA: MN|25G02013-002-origi...
728     >Influenza A virus |USA: MN|25G01806-001-origi...
1344    >Influenza A virus |USA: MN|25G01806-003-origi...
...                                                   ...
101048  >Influenza A virus |Mexico: San Luis Potosi|76...
101056  >Influenza A virus |Mexico: Tabasco|234-8289|H...
101064  >Influenza A virus |Mexico: Veracruz|232-6169|...
101072  >Influenza A virus |Mexico: Veracruz|233-7607|...
101080  >Influenza A virus |Mexico: Veracruz|28159-398...

                                                 sequence  ... File Name  \
72      ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
136     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
528     ATGGAGAGAATAAAAGAACTGAGAGATCTAATGTCACAGTCTCGCA...  ...
728     ATGGAGAGAATAAAAGAACTGAGAGACCTAATGTCACAGTCTCGCA...  ...
1344    ATGGAGAGAATAAAAGAACTGAGAGACCTAATGTCACAGTCTCGCA...  ...
...                                                   ...  ...       ...
101048  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
101056  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
101064  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAGC...  ...
101072  AGCGAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...
101080  AGCAAAAGCAGGTCAAATATATTCAATATGGAGAGAATAAAAGAAC...  ...

                                           Partial_Header  \
72      Influenza_A_virus__USA__MN_25G02013_001_origin...
136     Influenza_A_virus__USA__MN_25G02321_002_origin...
528     Influenza_A_virus__USA__MN_25G02013_002_origin...
728     Influenza_A_virus__USA__MN_25G01806_001_origin...
1344    Influenza_A_virus__USA__MN_25G01806_003_origin...
...                                                   ...
101048  Influenza_A_virus__Mexico__San_Luis_Potosi_765...
101056  Influenza_A_virus__Mexico__Tabasco_234_8289_H5...
101064  Influenza_A_virus__Mexico__Veracruz_232_6169_H...
101072  Influenza_A_virus__Mexico__Veracruz_233_7607_H...
101080  Influenza_A_virus__Mexico__Veracruz_28159_398_...

                                                   Strain  \
72      Influenza_A_virus__USA__MN_25G02013_001_origin...
136     Influenza_A_virus__USA__MN_25G02321_002_origin...
528     Influenza_A_virus__USA__MN_25G02013_002_origin...
728     Influenza_A_virus__USA__MN_25G01806_001_origin...
1344    Influenza_A_virus__USA__MN_25G01806_003_origin...
...                                                   ...
101048
101056
101064
101072
101080

                                         genbank_name    Genotype  \
72             A/Turkey/MN/25G02013-001-original/2025  Unassigned
136            A/Turkey/MN/25G02321-002-original/2025  Unassigned
528            A/Turkey/MN/25G02013-002-original/2025  Unassigned
728     A/Domestic Duck/MN/25G01806-001-original/2025  Unassigned
1344       A/Guineafowl/MN/25G01806-003-original/2025  Unassigned
...                                               ...         ...
101048            A/chicken/San Luis Potosi/7651/1996  Unassigned
101056                A/chicken/Tabasco/234-8289/1998  Unassigned
101064               A/chicken/Veracruz/232-6169/1998  Unassigned
101072               A/chicken/Veracruz/233-7607/1998  Unassigned
101080              A/chicken/Veracruz/28159-398/1995  Unassigned

             Host_Type Years Geo_Location_Abrv  \
72      domestic_avian  2025            USA-MN
136     domestic_avian  2025            USA-MN
528     domestic_avian  2025            USA-MN
728     domestic_avian  2025            USA-MN
1344    domestic_avian  2025            USA-MN
...                ...   ...               ...
101048  domestic_avian  1996     Mexico-Potosi
101056  domestic_avian  1998    Mexico-Tabasco
101064  domestic_avian  1998   Mexico-Veracruz
101072  domestic_avian  1998   Mexico-Veracruz
101080  domestic_avian  1995   Mexico-Veracruz

                                                     Name Segment_Name
72      >SRR36162727|A/Turkey/MN/25G02013-001-original...          PB2
136     >SRR36162652|A/Turkey/MN/25G02321-002-original...          PB2
528     >SRR36162807|A/Turkey/MN/25G02013-002-original...          PB2
728     >SRR36162618|A/Domestic Duck/MN/25G01806-001-o...          PB2
1344    >SRR36162617|A/Guineafowl/MN/25G01806-003-orig...          PB2
...                                                   ...          ...
101048  >OK205848|A/chicken/San Luis Potosi/7651/1996|...          PB2
101056  >OK205856|A/chicken/Tabasco/234-8289/1998|H5N2...          PB2
101064  >OK205864|A/chicken/Veracruz/232-6169/1998|H5N...          PB2
101072  >OK205872|A/chicken/Veracruz/233-7607/1998|H5N...          PB2