# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI, by de-duplicating from Andersen/GISAID, and relabeling sequences.

In [ ]:
# Housekeeping

import os
import pandas as pd
import dateutil
import importlib
import utils  
importlib.reload(utils)
from utils import *

In [2]:
# Paths

# home = "C:/Users/maksi/Documents/Statistics/Projects/Avian_Flu_Files/"
home = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
# downloads = "C:/Users/maksiaevai.NCBI_NT/Documents/Avian_Flu_Files/"
downloads = home + "NCBI_Virus_Downloads/11-01-2021--04-14-2025/"
temp_files = home + "NCBI_Virus_Temp_Files/"
complete_files = home + "NCBI_Virus_Complete_Files/"
gisaid_andersen = home + "Complete_Combined_Files/11-01-2021--04-14-2025_all_genotypes/11-01-2021--04-14-2025_all_genotypes/"

# Day we're updating data
update_date = "04-14-2025"

os.chdir(downloads)

## De-Duplication

In [3]:
metadata = pd.read_csv("sequences.csv")

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.SRA_Accession, as_index=False).size()

print(metadata_counts)

metadata_counted = metadata.merge(metadata_counts, on="SRA_Accession")

# Only keep those with size=8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates

metadata_complete_segs = metadata_complete_segs.drop_duplicates(subset="GenBank_Title", keep="first") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]

metadata_segments

     SRA_Accession  size
0      SRR23852495     8
1      SRR28752446     8
2      SRR28752447     8
3      SRR28752448     8
4      SRR28752449     8
...            ...   ...
4141   SRR33124773     8
4142   SRR33124774     8
4143   SRR33124775     8
4144   SRR33124776     8
4145   SRR33124777     8

[4146 rows x 2 columns]

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV571926,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,1,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
1,PV571927,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,2,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
2,PV571928,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,3,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
3,PV571929,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,4,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
4,PV571930,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,5,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37035,OQ565628,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,4,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37036,OQ565629,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,5,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37037,OQ565630,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,6,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37038,OQ565631,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,7,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37039,OQ565632,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,8,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8

In [4]:
# De-duplicate from Andersen/GISAID using isolate

# If even one isolate in this list exists in the NCBI Virus dataframe, remove it from NCBI Virus dataframe
gisaid_andersen_isolates = []
# Grab files
for dirpath, dirs, files in os.walk(gisaid_andersen):
    for file in files:
        file_name = os.path.join(dirpath, file)
        # print(file_name)
        if ".fasta" in file_name:
            fasta_file = fasta_df(file_name) # Convert fasta file to dataframe
            isolates = fasta_file["Isolate_Id"].apply(lambda x: x.split("/")[3])
            for index, value in isolates.items():
                gisaid_andersen_isolates.append(value)
         
    break 

gisaid_andersen_isolates = list(set(gisaid_andersen_isolates))

print(gisaid_andersen_isolates)

['22-005647-002', 'AIVPHL-780', '22-006118-001', '24-000764-003', 'USDA-010027-002', '22-014416-001', '22-014479-001', 'USDA-011531-005', '001055-002', '007119-009', '24-019524-001', '24-004150-001-original', '23-005384-001', '057377-24-6', 'B24OSU-351', '028489-010', '004794-001', '005784-001', '22-009196-002', '24_020712-006', '22-032924-002', 'B24OSU-494', '038993-002', '23-039958-001-original', '036816-001', 'USDA-011678-001', '23-000336-001', '036311-001', '24_009497-010', '005481-005', '001575-001', '22-021013-003', 'USDA-011119-002', 'FAV-0225-127', '22-033190-002', '032641-001', '24_018029-001', '24-034639-002', '24_033011-004', '23-027703-003-original', '037225-045', '002235-001', '24-036597-001', 'USDA-005110-003', '24-010308-001-300', 'FAV-1685-1', 'USDA-008835-002', 'AIVPHL-2655', '003803-005', '24_034224-004', 'USDA-006544-005', '22-020455-002', '037573-003', '034220-002', '24_018334-007', '22-013651-001', '24_008765-001', '23-001334-001', 'USDA-006543-002', '035007-002', '24_018869-001', '22-015521-007', '24-010928-001-original', 'FAV-0802-78', 'USDA-003439-003', 'USDA-013145-004', 'USDA-012093-001', '003062-007', 'FAV-0254-1', '014126-068', '038353-002', '035654-001', '033987-001', '035262-001', '24_032636-003', '026360-002', '036579-002', '22-038828-001-R', 'FAV-0631-1', '24_034005-001', '036559-003', '23-037267-001', '063200-24-9', '22-038821-056', 'IZ22_0751', 'USDA-013142-001', 'FAV-0274-2', '22-017713-001', '008086-001', '22-032045-001', '031666-027', '24_031493-001', '037217-027', '24_013789-010', 'FAV-1166-17', '24-020796-010', '24_032597-001', '24-035295-001', '22-037656-002', '23-037500-001-original', '006140-002', 'FAV-1647-2', '003619-002', '22-027417-001', 'USDA-009801-001', '23-023002-005-original', 'USDA-007376-007', 'FAV-0792-1', '031666-019', 'AIVPHL-791', '24_020510-001', '22-036624-001-R', '002240-001', '22HP00192', '22-034017-003', '23-008369-005', 'USDA-009481-005', '009367-002', 'BI-ME-015', '23-001343-015', '23-013080-010', '24_012346-009', '22-025129-001', '23-035010-001-original', '007549-045', 'USDA-009361-011', '003957-003', '003927-016', '22-006945-001', '027662-001', '23-004157-006', 'FAV-0064-2', 'FAV-0104-4', '22-032580-001', '22-014523-001', '007117-004', 'W24_017', '24_016681-004', '22-030049-002', '23-011447-001', '22-021001-001', '22-034322-002-R', '057377-24-18', '24_015457-002', '24_009367-009', '007637-011', '002347-003', 'AIVPHL-2656', '24-001663-001-original', 'W241510022-4', '22-041852-001', '22-033479-014', '22-027890-001', 'AIVPHL-1425', '23-029854-015-original', '034199-001', '23-008296-002-original', 'FAV-0118-5', '006674-003', 'BI-ME-013', 'AIVPHL-2594', '002665-002', 'USDA-010664-001', 'FAV-0287-1', '23-002693-018', 'USDA-010505-001', '24-037518-001', '036553-005', 'FAV-1513-9', '003062-013', '034808-001', 'FAV-0053-3', '001318-001', 'AIVPHL-2839', '037225-015', 'USDA-009684-001', '23-000409-003', '23-036929-001', '23-033467-002', '007234-037', '24-004245-004-original', 'USDA-007679-009', '005350-002-R', '24_010330-012-300', '24_033001-002', '24-004235-003-original', '036593-001', '003295-003', '22-027736-001', 'USDA-012668-002', '24_032597-004', '22-013517-010', '003240-004', '24_022176-001', '22-027081-003', '063224-24-4', '22-032511-070', '24_033973-001', '031666-020', 'FAV-1616-2', '22-026112-046', '22-033918-001', '23-031508-002', '038281-001', '23-035045-002-original', 'USDA-008909-004', 'FAV-0923-1', 'FAV-0575-35', 'USDA-011034-002', '22-035567-003', 'FAV-0109-1', 'FAV-0284-001', '033484-002', 'NYCVH-160820', '033974-001', '036634-003', '22-024356-002', '24_031294-001', '028489-007', '22-020952-002', '24-008355-001', '24-030904-002', '22-009983-008', '036567-001', '23-001055-001', '007464-001', 'FAV-0833-66', '23-036742-003', '004785-007', 'USDA-009024-002', 'USGS-0326', '22-032412-001', '23-007468-001', 'FAV-0133-1', '22-031352-027-R', 'FAV-0699-1', '24-036792-002', 'FAV-0348-OS', '23-004612-009', '22-010346-002', 'USDA-008995-002', 'AIVPHL-777', 'FAV-0420-1', '22-015783-001', '22-013871-001', '23-000409-012', 'FAV-0802-1', '24_033007-004', '22-026962-005', '002205-001', '004311-004', '009864-005', '23-034209-003', '004922-003', '033826-001', '22-032218-001', '22-008483-001', '24_032424-004', '007156-002', '007549-065', '23-030402-001', 'USDA-009478-016', '036563-004', 'AIVPHL-1400', '007349-001', '22-040391-003', '24_016370-014', 'USDA-010231-001', '22-013642-001', '23-002762-001', '24-020282-001', '24_016437-019', 'FAV-0802-56', '23-001343-004', '002467-003', '23-002762-005', '22-012285-001', '24_033991-002', '22-013277-001', '23-036674-002', 'W22-205', 'FAV-0505-51', '004292-001', '22-012092-006', '037225-021', '035630-004', '22-014663-003', '24_017584-012', '23-027703-008-original', '23-036549-001', '007637-004', 'W22-1223A', '23-002762-024', '22-034995-001', '007118-027', '22-038611-001', 'FAV-1495-1', '23-000403-001', '24_034022-001', '22-033922-001', 'USDA-002491-002', '22-010094-002', '24-010832-001', '033434-015', '22-034797-001', '23-034346-006', 'USDA-001330-030', 'FAV-0360-2', 'FAV-0527-5', '22-017620-001', 'FAV-0940-11', '22-013436-001', '23-034449-002', '24_033206-003', 'FAV-0575-54', '22-015398-002', '002429-001', 'FAV-0182-3', 'FAV-0835-13', '22-009313-002', '007605-001', '22-018405-001', '23-005887-001', '23-013080-002', '23-000776-001', '005221-001', '031313-002', 'FAV-0802-14', '23-004704-001', 'USDA-009399-002', '22-017243-006', '24-017677-002', 'USGS-0251', '000286-001', 'FAV-0904-2', '24_035196-003-R3', '004677-002', '22-036180-008', 'W22-719B', 'FAV-1311-13', '22-029125-003', '000628-001', '23-031729-002', '22-024871-007', 'W22-481A', '22-037528-001', '005886-001', '038627-001', '009291-001', '22-023567-001', '24-021510-001', '22-017243-024', '22-013517-003', '009510-001', 'FAV-0083-125', '22-010132-001', '007379-002', '22-020831-002', '22-014402-001', '24-007946-001', '006816-003', '006223-001', '035658-002', 'B2408700-11', '034954-001', '24_011231-003', 'FAV-0605-02', '22-017243-013', '22-028071-001', '22-025285-002', '24_010308-007', 'OTH-0134-17', '23-000227-001', 'USDA-012032-001', '22-041409-003', '039394-001', '24_033004-002', 'FAV-0918-35', 'USDA-010679-002', '23-005533-018', '22-017947-002', 'FAV-0773-2', '005556-002', '036325-001', '24_015978-004', '24_034837-003-R2', '035650-001', '001886-001', '22-009192-003', '22-027421-003', 'AIVPHL-1499', '24_019381-012', '033876-005', 'FAV-0143-3', '22-009190-001', 'AIVPHL-2898', 'USDA-012668-009', '014126-032', '24_018766-001', '22-030263-001', '22-020416-012', '24-012167-001', '22-036180-004', 'FAV-0899-4', 'AIVPHL-2528', '25_000595-001', 'USDA-012013-002', '002697-001', 'FAV-0830-2', '003040-001', 'AIVPHL-242', 'FAV-1628-12', 'USDA-012003-002', '035870-002', '003850-006', 'FAV-0019-52022', '23-033983-010-original', '22-011946-004', '22-037516-001', '24_021992-001', '009428-005', '22-008366-001', '24-013710-009', '004865-010', '22-037439-001', '24_031617-001', '22-013105-001', '23-001494-006', '22-041777-001', '006028-001', '026360-010', '23-034259-003-original', 'FAV-0899-3', '23-003434-004', '033477-002', '22-027416-001', '24_010202-004', '007637-010', '005864-001', '24_027807-001', 'FAV-0282-4', 'W22-773', '035870-003', '23-001521-001', '24_034997-001', '007119-008', '23-036565-002-original', '22-015417-001', 'CEIRR-290', '22-021012-003', 'COTE_20220612_1', '22-032677-003', '22MM00802', '22-020455-005', '22-014336-010', '23-037837-001', '23-001467-001', '034633-001', '23-015413-001', 'FAV-0717-6', '035917-003', '24_017584-009', 'USDA-006945-003', 'FAV-0177-3', '033506-002', 'FAV-0853-3', '24-019375-001-R2', '22-014140-001', '22-026980-001', '003927-002', 'USDA-009481-007', '028536-002', '005142-002', 'USDA-001330-027', '007549-006', '22-032710-001', '003062-005', '24_016523-025', '033526-003', '037219-009', '22-013395-008', '22-033479-016', '007118-040', '037018-002', '24_017153-003', '007185-004-R', 'USDA-006328-019', '22-008259-001', '007097-001', '23-023703-002', '037177-002', 'AIVPHL-57', '24-004330-006-original', '23-034303-024-original', '23-036745-001', 'USDA-008980-007', '033434-013', '000345-002', '22-030423-022-R', 'W22-306', 'FAV-1529-9', 'FAV-0876-5', '24_019381-002', '007118-057', 'USDA-002578-009', 'OTH-0097-3', '009411-001', '22-016934-002', '23-034302-013-original', 'AIVPHL-334', 'FAV-1194-1', '033303-001', 'W241070094-5', '22-010127-002', 'USDA-012771-003', '22-036316-001', '22-015458-001', '007626-001-R', '24_034019-002', 'USDA-009478-004', 'W24-1015', '031286-007', 'FAV-0870-8', 'AIVPHL-186', 'USDA-006569-004', '007708-002', '23-004958-001', '22-013223-003', '031284-018', '22-012510-002', '23-038978-001-original', '24_020797-004', '034196-002', '23-037848-002', '22-033477-019', 'USDA-007700-004', '24-004334-017-original', '24_022173-001', '24-037493-001', '028536-001', '004790-001', 'FAV-0247-1', '22-036876-001', '026563-001', '23-003062-020', '037215-002', 'CEIRR-3856', '009164-002', 'FAV-0227-3', '010008-009', '22-015239-001', '22-016455-001', '22-011040-003', 'NYCVH-23-453', 'FAV-1682-2', '007071-001-R', '23-001508-001', '009176-002', 'FAV-0300-06', 'FAV-0149-1', 'AIVPHL-2580', '22-042014-001', '24_012341-020', '23-001343-006', '004499-001', '22-028162-001', '25_000586-007', '038443-001', '23-006664-001', 'USDA-001743-007', '22-038236-001', 'FAV-1262', '22-015248-001', '001640-001', 'FAV-0802-34', 'W24-017', '031666-012', 'AIVPHL-2700', 'FAV-0870-3', '24-034801-001', '22-020831-004', 'FAV-0897-03', '008583-002', 'FAV-0706-1', '22-041828-001', '019480-001', 'FAV-0324-1', '038155-004', '22-017953-006', '007549-082', '005959-006', '22-030200-001', '003371-001', '001495-001', '006183-001', '22-015666-001', '23-011580-001', '24-014328-008', 'FAV-0701-1', '22-034080-032', '23-001573-001', '22-027995-006', '24-013016-002', '22-013369-007', '22-036753-021-R', '24_035846-001-R2', '22-011793-001', '24-000724-001', '002060-001', 'AIVPHL-2057', '008328-003', '019481-002', '035869-003', '034223-002', 'W22-480B', '24_007953-001', '23-003641-005', 'FAV-0669-3', '038160-001', 'FAV-0688-2', 'FAV-0962-2', '24_016134-075', 'FAV-0833-62', '24_022332-018', '038987-007', 'FAV-0586-1', '015884-015', '009213-001', '22-009583-002', '014126-072', '22-040462-002', '24-034804-001', '22-025066-001', '037225-052', '037415-001', '003807-018', '22-012454-002', 'USDA-011287-001', '24-035157-002', '22-010994-002', 'FAV-0880-5', 'USDA-009404-002', 'FAV-0575-30', '23-036543-002', '004632-002', '003434-001', '24-035126-002', '24-000494-002', '22-014529-001', '24-003120-032-original', '033526-002', '031284-009', '037217-005', '22-040427-002', '007118-031', '004553-002', 'FAV-0941-1', 'USDA-012305-001', '23-002150-001', '24_009108-004', '22-039438-003', 'FAV-0035-5', '036417-001', '22-017953-004', '23-040073-002-original', 'USDA-009941-001', '006935-002', 'FAV-0189-2', '24_033001-004', 'USDA-012056-006', '23-004370-003', '24-015842-002', 'USDA-010715-001', '22-021192-001', '24_010202-012', 'USDA-007273-005', '033691-002', '22-010671-008', 'FAV-1625-2', '22-034331-004-R', '007111-001', '22-014536-004', '037219-012', 'USDA-008980-006', 'FAV-0410-2', 'USDA-013055-007', '009394-001', '24_034009-004', 'FAV-1444-2', 'FAV-0250-1', '003479-002', 'OTH-0134-4', '22-019272-001', 'FAV-1259-1', '003581-001', '24-003120-011-original', '24_009110-026', '22-018423-001', 'FAV-0252-1', '005229-001', '23-008247-001-original', 'FAV-0410-3', 'FAV-0934-84', 'FAV-0268-3', '22-017059-001', '004236-001', '007118-067', '22-015275-002', 'AIVPHL-2535', 'FAV-0116-1', 'USDA-013138-001', '23-041194-002-original', '23-034423-017-original', '24_032597-003', '22-032511-002', 'USDA-004958-001', '23-035084-001', '23-037474-002', '035913-008', '23-038249-002', 'FAV-0491-3', '22-015580-001', 'USDA-011792-004', 'FAV-0035-4', '22-035595-002', 'USDA-012062-001', '22-008114-001', '22-031265-001', '24_009109-006', '22-038785-001-R', 'USDA-012854-001', 'FAV-0167-101', '22-017695-001', '23-004366-001', '24-036523-001-R2', '027661-001', '000383-001', 'USDA-011789-003', 'FAV-0877-4', 'FAV-0578-1', '033434-003', '007471-001', '003989-002', '24_020027-006', '23-002535-001', '003807-006', '020176-006', '009499-001', '24_014001-002', '003899-002', '22-034128-001-R', '006938-002', '22-033479-011', 'FAV-0506-1', '23-034037-001-original', '005148-001', 'USDA-009481-008', '003670-003', '22-010312-001', '23-004612-018', 'FAV-1068-22', '24-003953-008-original', 'FAV-0753-1', 'USDA-003830-009', '22-034322-001-R', '007118-069', '23-038881-005-original2', '005856-001', '004430-001', '037225-062', '036398-002', 'USDA-009481-015', '030030-003', '24-015315-001', '22-022033-001-original', '23-032152-002', '22-029357-001', '23-038797-013-original', 'FAV-0802-87', '025747-005', '22-006976-004', 'FAV-0078-3', '22-034677-012-R2', '037219-029', 'W24-1031A', '23-034298-001', 'USDA-001330-017', 'USDA-009551-001', '22-014489-001', '008023-002', '22-036965-001', '24_031314-003', 'FAV-0364-3', '24-035690-002', '23-001576-001', '24_010661-014', '007706-001', '24_020284-011', '22-017048-003-original', '22-034030-001', '24-008850-001', '000300-002', '22-024975-003', '23-027066-011', '021648-001', '004969-002', '003062-009', '24-012046-003', 'AIVPHL-2576', '037219-034', '24-003120-002-original', '004227-001', '23-034416-008-original', '22-037636-003', '22-030274-001', '036006-001', 'USDA-008176-004', '24_017584-005', '22-017013-001-original', '22-034097-002', '002290-003', '006943-001', '22-013493-002', '025748-003', 'IZ22_0894', '24-031478-003', '22-026660-001', '23-002599-004', '24_016337-001', '22-033004-001', '24_013172-002', '007921-007', '24_029902-001', '012377-009', '22-017504-001', '24_032623-002', '22-035250-002', '22-021070-001', '037523-001', '24_017483-003', 'UGAI22-3889', '23-008141-001-original', '037219-003', '011659-001', '22-038820-006-R', '23-013080-008', '036766-003', '24_034224-002', 'W24-248A', 'USDA-008935-003', 'FAV-1650-13', '007549-024', 'FAV-0833-29', '22HP00127', '24_010193-003', '002310-001', 'FAV-1369-1', '22-018423-004', 'AIVPHL-2571', '22-006792-001', 'FAV-0802-72', '22-007376-001', '24-018880-002', '22-024871-005', 'FAV-0360-6', '24_016134-234', '033226-002', '24_032702-004', '24-034636-002', '23-025744-001', 'USDA-009884-002', 'W24-190R', '037215-003', 'FAV-0948-1', '23-035616-001', '23-040000-001-original', 'FAV-1595-2', '006507-001-R', '026360-001', 'FAV-0833-51', '007154-010', '23-010018-001', '007841-001', '003591-002', 'FAV-0605-01', '22-026962-034', '008872-009', '22-021793-001', '22-012855-004', '007152-002', '22-013642-002', '24_012341-013', 'USDA-009599-006', '22-010157-002', '037986-006', 'USDA-005893-001', '23-015042-001', '24-005140-001-original', '22-024181-003', '004133-001', '004135-005', '22-040427-001', '23-027066-010', '007118-025', '22-014431-005', '22-013424-001', '004426-001', 'W22-1057D', '036563-002', '004251-001', '033224-003', '003808-001', '23-000335-001', '22-014746-030', '22-027816-010', 'USDA-012670-001', '006707-001', '22-017953-001', 'FAV-0426-7', '031667-006', '23-000409-010', '23-038112-033-original', 'AIVPHL-165', '22-035805-002', '22-037527-001', '23-035662-001-original', '22-035744-001', 'FAV-0407-8', '24_010661-007', 'FAV-1627-2', 'FAV-0575-34', '24_012341-014', 'USDA-003496-007', '22-039688-006', 'FAV-0495-2', 'USDA-012936-009', 'W22-933C', '22-005647-001', 'USDA-012931-004', '22-029332-005', '23-036529-002-original', 'USDA-008377-005', '22-025499-001', '24_033516-001', '033000-002', 'W23-118', '23-032795-038', '24_033172-003', 'FAV-1580-1', '24_012341-015', '23-037957-001', 'UGAI22-2966', '22-022528-008', 'FAV-0189-3', 'MME-150-L', '23-031335-001', '22-011101-008', '23-034037-004-original', '007549-025', 'FAV-0969-2', '24_016523-011', '24_027102-002', '22-038658-001', 'FAV-0174-1', '002313-001', '007549-058', 'USDA-012327-004', '23-035544-002', '003803-002', '22-033477-017', '22-033477-008', '22-031886-001', '22-028148-007', '036520-001', '001388-002', 'W241140067-15', '24_031329-001', '22-016119-001', '24-005334-002-original', '24_016288-012', '22-013493-003', '23-004360-001', '000295-002', '24_017584-019', '23-034937-001', '035993-001', '22-015320-001', '033856-003', 'FAV-0992-2', '23-001514-001', '23-029854-024', '22-033679-001', 'FAV-0055-4', '24-007557-001-original', 'FAV-0272-1', 'FAV-0143-6', '22-015309-001', 'W241220059-3', 'AIVPHL-844', '22-014430-001', '24_032021-002', 'USDA-011578-007', '24_010661-008', 'USDA-012025-001', '029620-001', '006486-001', 'USDA-012026-001', '23-003429-003', 'FAV-0469-12', '23-039245-001-original', '22-028132-001', '006143-007', '22-014363-001', '036538-002', '22-029948-001-R', 'FAV-0864-3', '24-020285-002', '007608-007', '24_011573-005', '034426-003', '22-039352-002', '24_014883-006', '23-039417-007-original', '160820', '22-015585-001', '22-039352-015', '24_018871-004', '007118-032', '22-014359-002', '037219-013', 'COTE_20220614_2', '24_009309-002', 'W22-667D', '25_004920-001', '22-026328-002', 'AIVPHL-667', '002235-002', '008827-001', '002401-001', 'FAV-0816-7', '038987-001', '22-032452-001', 'FAV-0505-27', '22-041373-003', '22-037698-001', '005312-001', '24_017654-004', '24_034700-001', '23-022512-001-original', '22-027995-011', '22-004688-002', '003807-005', '24_018030-005', 'FAV-1470-11', '24_030591-001', 'FAV-1257-2', '035202-004', '22-009978-002', '22-018179-001', '22-041042-001', '036426-001', '23-015563-001-original', 'FAV-0268-29', '001177-001', '24-013169-001', '032424-006', '22-019205-001', '007549-017', '23-015846-003-original', 'OTH-0097-2', '037190-002', '22-015259-001', 'FAV-0259-12', 'FAV-0926-3', 'FAV-0568-1', '23-037131-002', '22-013321-002', '24_015196-005', '23-037422-001', '22-015201-003', '23-036896-001', '22-022527-002', '22-032950-003', '22-036755-019', '24_033532-001', 'USDA-012854-003', '22-016599-004', '22-032849-004', '24_035013-001', '24_017652-012', '004669-001', '22-008951-005', '22-024949-001', '22-033929-001', '24_018637-001', '24-020285-007', '22-033477-013', 'FAV-0939-2', '22-034677-056-R2', '004294-004', '003585-001', '22-011794-002', '035506-011', '22-008467-001', '24-031478-001', 'FAV-0415-15', '23-037681-002', '22-040812-001', '24_019691-010', '007185-005', '24-037810-001', '24-000134-001-original', '033876-004', '033999-001', '007627-001', '24_013789-009', 'FAV-0433-1', '24_018872-002', '22-014449-002', 'FAV-1126-2', '003975-001', '22-031157-002', '22-041408-001', 'FAV-0300-01', '22-013015-001', '004785-003', '003106-001', '036403-004', '24_010513-002', '22-037528-002', '001890-002', '007118-022', 'FAV-1309-4', '23-002236-001', '24_018976-007', '23-000771-001', '22-017243-001', '22-020983-003', '24_020731-003', '000205-002', '000049-005', '22-009980-001', 'USDA-012338-025', '24_015059-003', '22-022941-001', '008085-002', 'FAV-0617-1', 'FAV-1628-31', '005146-001', '037809-001', '034220-001', '22-029901-002-R', '22-010928-004', '22-010138-001', '001850-001-R2', '24-010655-002', '23-013975-001', 'FAV-1193-4', 'FAV-1633-1', 'B24OSU-413', '24_032021-001', '004135-006', '034237-001', '24_016437-011', '038343-004', '22-037670-001', '23-001053-005', '22-033852-001', '005993-001', '24_028248-004', '005339-003', '22-006639-001', '24-035912-003-R2', '24-037988-001', 'USDA-011517-008', '002663-005', '24_019693-007', '22-028137-001', '23-030445-012', '007392-001', '037225-002', 'FAV-1310-3', '031620-001', 'FAV-0918-19', 'AIVPHL-2631', '001347-001', '22-030264-001', '001989-003', 'FAV-0137-6', 'USDA-011586-003', '036368-003', '028772-001', '24-012707-001', 'FAV-0802-3', '003245-001', 'W22-675B', '22-008702-002', 'FAV-0415-17', '24-000650-001-original', '004164-001', '24_030034-004', '23-036805-003-original', '22-024700-001', '035205-001', '158', 'FAV-0923-7', '034244-002', '23-034293-006-original', '23-005533-008', '034222-001', '24-035703-002', '23-002693-029', '22-026112-027', 'FAV-0505-14', '015884-020', '24_017652-017', 'FAV-1655-2', '24-005701-001-original', 'AIVPHL-1404', '003216-001', '012168-002', '22-025261-005', 'USDA-007915-010', '22MM00724', '23-005533-023', '24-029152-001', 'FAV-1535-2', 'USDA-011570-001', '028516

In [5]:
# Remove duplicates from GISAID/Andersen

print(len(metadata_segments))

for index, value in metadata_segments["Isolate"].items():
    if value in gisaid_andersen_isolates:
        metadata_segments = metadata_segments.drop(index)

print(len(metadata_segments))

metadata_segments

29400
29248

,Accession,Organism_Name,GenBank_RefSeq,Assembly,SRA_Accession,Submitters,Organization,Org_location,Release_Date,Isolate,...,Segment,Geo_Location,USA,Host,Tissue_Specimen_Source,Collection_Date,BioSample,BioProject,GenBank_Title,size
0,PV571926,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,1,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
1,PV571927,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,2,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
2,PV571928,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,3,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
3,PV571929,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,4,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
4,PV571930,Influenza A virus,GenBank,GCA_049972485.1,SRR33124721,"Aufderhar,M., Franzen,K., Killian,M., Lantz,K....",USDA Animal Plant Health Inspection Service-Na...,USA,2025-04-28,25-006338-001-original,...,5,USA: IN,IN,Meleagris gallopavo,oronasopharynx,2025-02-20,SAMN47941411,PRJNA980729,Influenza A virus (A/Turkey/IN/25-006338-001-o...,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37035,OQ565628,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,4,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37036,OQ565629,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,5,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37037,OQ565630,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,6,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37038,OQ565631,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,7,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8
37039,OQ565632,Influenza A virus,GenBank,GCA_039342815.1,SRR23852495,"Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...","FARVET S.A.C., Laboratorio de Bioinformatica",Peru,2023-03-08,VFAR-140,...,8,Peru,NaN,Pelecanus,lung,2022-12,SAMN33745292,PRJNA944237,Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...,8

In [6]:
# NCBI Virus Naming Convention Example:
# Influenza A virus |USA: IN|25-006338-001-original|H5N1|2025-02-20|Meleagris gallopavo|GenBank|SRR33124721|SAMN47941411|PRJNA980729|Influenza A virus (A/Turkey/IN/25-006338-001-original/2025(H5N1)) segment 1 polymerase PB2 (PB2) gene, complete cds
# Organism_Name | Geo_Location | Isolate | Genotype | Collection_Date | Host | GenBank_RefSeq | SRA_Accession | BioSample | BioProject | GenBank_Title


# print(metadata_segments["GenBank_Title"].iloc[0])

# Get sequences and headers together
headers = []
isolates = []
sras = []
headers_seqs = {}
with open("sequences.fasta") as f:
    lines = f.readlines()
    for num, line in enumerate(lines):
        if line[0] == ">": # If this is a header
            if line.strip() not in headers: # And is not a header we've seen before
                header = line.strip() 
                # print(header)
                split_header = header.split("|")
                # print(split_header)
                headers.append(header) 
                if num < len(lines): # If we're not at the last line
                    # for i, l in enumerate(lines[num + 1:]):
                    i = num
                    sequence = ""
                    # print(lines[i])
                    # print(lines[i + 1])
                    while i < len(lines) - 1 and lines[i + 1][0] != ">": # While the next line is part of a sequence
                        sequence = sequence + lines[i + 1].strip()
                        i += 1
                    headers_seqs[header] = sequence # Add next lines to sequences
                # name = split_header[-1] # Last part gives GenBank name, with segment and isolate
                isolate = split_header[2]
                isolates.append(isolate)
                sra = split_header[7]
                sras.append(sra)
    f.close()



# print(mask_all.all(axis=1))

In [7]:
# Double-check de-duplication
mask = metadata_segments["Isolate"].isin(isolates) # Check if isolate is in fasta
mask_sra = metadata_segments["SRA_Accession"].isin(sras) # Check if sra is in fasta

metadata_masked = metadata_segments[mask] # Some do not have isolates, so check sra too
metadata_masked_sra = metadata_segments[mask_sra]

merged_metadata = metadata_masked.merge(metadata_masked_sra, how="outer")
merged_metadata = merged_metadata.drop_duplicates(keep="first")

print(len(headers_seqs))
print(len(merged_metadata))

75007
29248

In [8]:
# Add sequences to a dataframe 
headers_seqs_df = pd.DataFrame.from_dict(headers_seqs, orient="index")
headers_seqs_df = headers_seqs_df.reset_index()
headers_seqs_df["GenBank_Title"] = headers_seqs_df["index"].apply(lambda x: x[1:].split("|")[-1])
headers_seqs_df = headers_seqs_df.rename(columns={0: "Sequence", "index": "Header"})

# Add sequences to the dataframe
metadata_seqs = merged_metadata.merge(headers_seqs_df, on="GenBank_Title", how="left")

print(metadata_seqs)

      Accession      Organism_Name GenBank_RefSeq         Assembly  \
0      OQ565625  Influenza A virus        GenBank  GCA_039342815.1
1      OQ565626  Influenza A virus        GenBank  GCA_039342815.1
2      OQ565627  Influenza A virus        GenBank  GCA_039342815.1
3      OQ565628  Influenza A virus        GenBank  GCA_039342815.1
4      OQ565629  Influenza A virus        GenBank  GCA_039342815.1
...         ...                ...            ...              ...
29251  PV573369  Influenza A virus        GenBank  GCA_049972655.1
29252  PV573370  Influenza A virus        GenBank  GCA_049972655.1
29253  PV573371  Influenza A virus        GenBank  GCA_049972655.1
29254  PV573372  Influenza A virus        GenBank  GCA_049972655.1
29255  PV573373  Influenza A virus        GenBank  GCA_049972655.1

      SRA_Accession                                         Submitters  \
0       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
1       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
2       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
3       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
4       SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
...             ...                                                ...
29251   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29252   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29253   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29254   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
29255   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                            Organization Org_location  \
0           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
1           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
2           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
3           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
4           FARVET S.A.C., Laboratorio de Bioinformatica         Peru
...                                                  ...          ...
29251  USDA Animal Plant Health Inspection Service-Na...          USA
29252  USDA Animal Plant Health Inspection Service-Na...          USA
29253  USDA Animal Plant Health Inspection Service-Na...          USA
29254  USDA Animal Plant Health Inspection Service-Na...          USA
29255  USDA Animal Plant Health Inspection Service-Na...          USA

      Release_Date                 Isolate  ...  USA       Host  \
0       2023-03-08                VFAR-140  ...  NaN  Pelecanus
1       2023-03-08                VFAR-140  ...  NaN  Pelecanus
2       2023-03-08                VFAR-140  ...  NaN  Pelecanus
3       2023-03-08                VFAR-140  ...  NaN  Pelecanus
4       2023-03-08                VFAR-140  ...  NaN  Pelecanus
...            ...                     ...  ...  ...        ...
29251   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29252   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29253   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29254   2025-04-28  25-006346-001-original  ...   PA   Anatidae
29255   2025-04-28  25-006346-001-original  ...   PA   Anatidae

      Tissue_Specimen_Source Collection_Date     BioSample   BioProject  \
0                       lung         2022-12  SAMN33745292  PRJNA944237
1                       lung         2022-12  SAMN33745292  PRJNA944237
2                       lung         2022-12  SAMN33745292  PRJNA944237
3                       lung         2022-12  SAMN33745292  PRJNA944237
4                       lung         2022-12  SAMN33745292  PRJNA944237
...                      ...             ...           ...          ...
29251                  feces      2025-02-20  SAMN47941403  PRJNA980729
29252                  feces      2025-02-20  SAMN47941403  PRJNA980729
29253                  feces      2025-02-20  SAMN47941403  PRJNA980729
29254                  feces      2025-02-20  SAMN47941403  PRJNA980729
29255                  feces      2025-02-20  SAMN47941403  PRJNA980729

                                           GenBank_Title size  \
0      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
1      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
2      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
3      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
4      Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...    8
...                                                  ...  ...
29251  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29252  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29253  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29254  Influenza A virus (A/goose/PA/25-006346-001-or...    8
29255  Influenza A virus (A/goose/PA/25-006346-001-or...    8

                                                  Header  \
0      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
1      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
2      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
3      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
4      >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
...                                                  ...
29251  >Influenza A virus |USA: PA|25-006346-001-orig...
29252  >Influenza A virus |USA: PA|25-006346-001-orig...
29253  >Influenza A virus |USA: PA|25-006346-001-orig...
29254  >Influenza A virus |USA: PA|25-006346-001-orig...
29255  >Influenza A virus |USA: PA|25-006346-001-orig...

                                                Sequence
0      AAAAGCARGTCAARTATATTCAATATGGAGAGAAKAAAAGARCTAA...
1      AGCGAAAGCAAACAAACCATTTGAATGGATGTCAATCCGAYTTTRC...
2      CAAATGCNNKTRCTGATTYAAAATGGAAGACTTTGTGCGACAATGC...
3      GTCAAAATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTG...
4      TAGATAATCACTCACTGAGTGRYATSCACATCATGGCRTMYCARGR...
...                                                  ...
29251  ATGGAAAACATAGTACTTCTTCTTGCAATATTTAGCCTTGTTAAAG...
29252  ATGGCGTCTCAAGGCACCAAACGATCCTATGAACAAATGGAAACTG...
29253  ATGAATCCAAATCAAAAGATAATAACTATCGGGTCAATCTGCATGG...
29254  ATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCTATCGTCC...
29255  ATGGATTCCAACACTGTGTCAAGCTTTCAGGTAGACTGCTTTCTTT...

[29256 rows x 26 columns]

In [9]:
# Create FASTA files per Header

metadata_seqs["Partial_Header"] = metadata_seqs["Header"].apply(lambda x: "|".join(x.split("|")[:-1]))

unique_partial_headers = []

# Each header should repeat 8 times
for partial_header in metadata_seqs["Partial_Header"].values:
    if partial_header not in unique_partial_headers: # Only use the first occurence
        unique_partial_headers.append(partial_header)

print(len(unique_partial_headers)) # Sanity check

3657

In [10]:
df_list = []
for partial_header in unique_partial_headers:
    # Get smaller dataframe
    df = metadata_seqs[metadata_seqs["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    df = df[["Header", "Sequence"]]
    df = df.rename(columns={"Header": "full_header", "Sequence": "sequence"}) # For utils function
    df["full_header"] = df["full_header"].apply(lambda x: ">" + x.split("|")[-1].replace(" ", "_"))
    # Make sure there are 8 segments
    if len(df) == 8:
        df_list.append(df)

In [11]:
print(df_list[0])

                                         full_header  \
0  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
1  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
2  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
3  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
4  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
5  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
6  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...
7  >Influenza_A_virus_(A/Pelecanus/Peru/VFAR-140/...

                                            sequence
0  AAAAGCARGTCAARTATATTCAATATGGAGAGAAKAAAAGARCTAA...
1  AGCGAAAGCAAACAAACCATTTGAATGGATGTCAATCCGAYTTTRC...
2  CAAATGCNNKTRCTGATTYAAAATGGAAGACTTTGTGCGACAATGC...
3  GTCAAAATGGAGAACATAGTACTACTTCTTGCAATAGTTAGCCTTG...
4  TAGATAATCACTCACTGAGTGRYATSCACATCATGGCRTMYCARGR...
5  CCATTGGATCARTCTGTATGGTAATTGGGATAGTCAGYTTGATGCT...
6  TTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTTCTCTCT...
7  GCTACAGCWGGGTGACAAAAACATAATGGATTCCAACACTGTGTCA...

In [12]:
# # Make fasta files. Finally

# os.chdir(temp_files)

# for df in df_list:
#     # print(df)
#     file_name = df["full_header"].apply(lambda x: x.split("|")[-1]).values[0] + "_temp.fasta"
#     # Forbidden characters
#     for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
#         file_name = file_name.replace(c, "")
#     # print(file_name)
#     output_file = open(temp_files + file_name, "w")

#     for index, row in df.iterrows():
#         name = df.loc[index, "full_header"]
#         # print(name)
#         sequence = df.loc[index, "sequence"]
#         # print(sequence)
#         # break 
#     # First is header, second is sequence
#         output_file.write(name + "\n")
#         output_file.write(sequence + "\n")
#     output_file.close()

## Re-Labeling Using GenoFlu

In [23]:
# Merging

os.chdir(downloads)

output_genoflu = pd.read_csv("output.tsv", delimiter="\t")

# print(output_genoflu)

# print(metadata_seqs["Header"])

file_name = metadata_seqs["Header"].apply(lambda x: x.split("|")[-1].replace(" ", "_") + "_temp.fasta")
for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
    file_name = file_name.apply(lambda x: x.replace(c, ""))

metadata_seqs["File Name"] = file_name

metadata_genoflu = metadata_seqs.merge(output_genoflu, on="File Name")

print(metadata_genoflu)
# for df in df_list:

# file_name = df["full_header"].apply(lambda x: x.split("|")[-1]).values[0] + "_temp.fasta"
# # Forbidden characters
# for c in [">", "/", "|", " ", ":", ",", "(", ")", "-"]:
#     file_name = file_name.replace(c, "")
# print(file_name)

     Accession      Organism_Name GenBank_RefSeq         Assembly  \
0     OQ565625  Influenza A virus        GenBank  GCA_039342815.1
1     PP740729  Influenza A virus        GenBank  GCA_039251605.1
2     PP752607  Influenza A virus        GenBank  GCA_039463695.1
3     PP752615  Influenza A virus        GenBank  GCA_039463505.1
4     PP752623  Influenza A virus        GenBank  GCA_039464545.1
...        ...                ...            ...              ...
3648  PV573334  Influenza A virus        GenBank  GCA_049973995.1
3649  PV573342  Influenza A virus        GenBank  GCA_049973825.1
3650  PV573350  Influenza A virus        GenBank  GCA_049973855.1
3651  PV573358  Influenza A virus        GenBank  GCA_049973145.1
3652  PV573366  Influenza A virus        GenBank  GCA_049972655.1

     SRA_Accession                                         Submitters  \
0      SRR23852495  Fernandez-Diaz,M., Villanueva-Perez,D., Tataje...
1      SRR28752446  Nguyen,T., C,C., Markin,A., Thomas,M., Lantz,K...
2      SRR28752475  Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...
3      SRR28752524  Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...
4      SRR28752523  Nguyen,T., Hutter,C., Markin,A., Thomas,M., La...
...            ...                                                ...
3648   SRR32868570  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3649   SRR32868573  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3650   SRR32868572  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3651   SRR33124727  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....
3652   SRR33124730  Aufderhar,M., Franzen,K., Killian,M., Lantz,K....

                                           Organization Org_location  \
0          FARVET S.A.C., Laboratorio de Bioinformatica         Peru
1              National Animal Disease Center, USDA-ARS          USA
2              National Animal Disease Center, USDA-ARS          USA
3              National Animal Disease Center, USDA-ARS          USA
4              National Animal Disease Center, USDA-ARS          USA
...                                                 ...          ...
3648  USDA Animal Plant Health Inspection Service-Na...          USA
3649  USDA Animal Plant Health Inspection Service-Na...          USA
3650  USDA Animal Plant Health Inspection Service-Na...          USA
3651  USDA Animal Plant Health Inspection Service-Na...          USA
3652  USDA Animal Plant Health Inspection Service-Na...          USA

     Release_Date                 Isolate  ...  \
0      2023-03-08                VFAR-140  ...
1      2024-05-01                     NaN  ...
2      2024-05-03                     NaN  ...
3      2024-05-03                     NaN  ...
4      2024-05-03                     NaN  ...
...           ...                     ...  ...
3648   2025-04-28  25-008575-002-original  ...
3649   2025-04-28  25-008296-001-original  ...
3650   2025-04-28  25-008296-002-original  ...
3651   2025-04-28  25-007078-005-original  ...
3652   2025-04-28  25-006346-001-original  ...

                                         Partial_Header  \
0     >Influenza A virus |Peru|VFAR-140|H5N1|2022-12...
1     >Influenza A virus |USA||H5N1|2024-03-16|Turdu...
2     >Influenza A virus |USA||H5N1|2024-03-20|Bos t...
3     >Influenza A virus |USA||H5N1|2024-03-22|Felis...
4     >Influenza A virus |USA||H5N1|2024-03-22|Felis...
...                                                 ...
3648  >Influenza A virus |USA: NJ|25-008575-002-orig...
3649  >Influenza A virus |USA: NY|25-008296-001-orig...
3650  >Influenza A virus |USA: NY|25-008296-002-orig...
3651  >Influenza A virus |USA: OH|25-007078-005-orig...
3652  >Influenza A virus |USA: PA|25-006346-001-orig...

                                              File Name     sample  \
0     Influenza_A_virus_APelecanusPeruVFAR1402022H5N...  Influenza
1     Influenza_A_virus_AblackbirdTexas2400835400120...  Influenza
2     Influenza_A_virus_AcattleKansas240087670012024...  Influenza
3     Influenza_A_virus_Adomestic_catTexas2400876400...  Influenza
4     Influenza_A_virus_Adomestic_catTexas2400876400...  Influenza
...                                                 ...        ...
3648  Influenza_A_virus_AgooseNJ25008575002original2...  Influenza
3649  Influenza_A_virus_AgooseNY25008296001original2...  Influenza
3650  Influenza_A_virus_AgooseNY25008296002original2...  Influenza
3651  Influenza_A_virus_AgooseOH25007078005original2...  Influenza
3652  Influenza_A_virus_AgoosePA25006346001original2...  Influenza

                     date  Genotype_y  \
0     2025-05-07_11-47-02        B3.2
1     2025-05-07_12-05-37       B3.13
2     2025-05-07_13-02-48       B3.13
3     2025-05-07_13-52-21       B3.13
4     2025-05-07_13-52-23       B3.13
...                   ...         ...
3648  2025-05-07_13-53-58        D1.1
3649  2025-05-07_13-54-15        D1.1
3650  2025-05-07_13-54-17        D1.1
3651  2025-05-07_13-54-22        D1.1
3652  2025-05-07_13-54-49        D1.1

                            Genotype List Used, >=98.0%  \
0     PB2:am2.1, PB1:am1.2, PA:ea1, HA:ea1, NP:am1.4...
1     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
2     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
3     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
4     PB2:am2.2, PB1:am4, PA:ea1, HA:ea1, NP:am8, NA...
...                                                 ...
3648  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3649  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3650  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3651  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...
3652  PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am13, NA...

                             Genotype Sample Title List  \
0     am2.1:22-009329-001:PB2, am1.2:22-010085-001:P...
1     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
2     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
3     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
4     am2.2:22-010445-001:PB2, am4:23-001855-001:PB1...
...                                                 ...
3648  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3649  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3650  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3651  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3652  am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...

                            Genotype Percent Match List  \
0     98.99%, 99.12%, 99.58%, 99.06%, 98.65%, 99.21%...
1     98.90%, 99.52%, 99.16%, 98.77%, 99.33%, 99.08%...
2     98.86%, 99.56%, 99.12%, 98.71%, 99.40%, 99.08%...
3     98.82%, 99.52%, 99.21%, 98.77%, 99.27%, 98.94%...
4     98.82%, 99.52%, 99.16%, 98.77%, 99.27%, 98.94%...
...                                                 ...
3648  99.65%, 99.34%, 99.58%, 99.53%, 99.67%, 99.36%...
3649  99.78%, 99.21%, 99.86%, 99.47%, 99.80%, 99.57%...
3650  99.78%, 99.21%, 99.81%, 99.41%, 99.80%, 99.57%...
3651  99.69%, 99.43%, 99.63%, 99.24%, 99.80%, 99.50%...
3652  99.74%, 99.25%, 99.67%, 99.35%, 99.53%, 99.50%...

             Genotype Mismatch List Genotype Average Depth of Coverage List
0       23, 20, 9, 16, 20, 11, 7, 7       Ran on FASTA - No Coverage Report
1     25, 11, 18, 21, 10, 13, 11, 7       Ran on FASTA - No Coverage Report
2      26, 10, 19, 22, 9, 13, 11, 6       Ran on FASTA - No Coverage Report
3     27, 11, 17, 21, 11, 15, 11, 7       Ran on FASTA - No Coverage Report
4     27, 11, 18, 21, 11, 15, 11, 7       Ran on FASTA - No Coverage Report
...                             ...                                     ...
3648        8, 15, 9, 8, 5, 9, 3, 9       Ran on FASTA - No Coverage Report
3649       5, 18, 3, 9, 3, 6, 0, 10       Ran on FASTA - No Coverage Report
3650      5, 18, 4, 10, 3, 6, 0, 11       Ran on FASTA - No Coverage Report
3651       7, 13, 8, 13, 3, 7, 0, 8       Ran on FASTA - No Coverage Report
3652       6, 17, 7, 11, 7, 7, 0, 9       Ran on FASTA - No Coverage Report

[3653 rows x 36 columns]

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

In [40]:
# Re-Labeling
import dateutil

os.chdir(home)
animals_ref = pd.read_csv("animals_ref.csv")

fix_animals_andersen(metadata_genoflu, animals_ref)

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")

metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

# print(metadata_genoflu["Host_Type"])

names = ">A/" + metadata_genoflu["Host"] + "/" + metadata_genoflu["Geo_Location"] + "/" + metadata_genoflu["Isolate"] + "/" + metadata_genoflu["Years"].apply(lambda x: str(x)) + "|H5N1|" + metadata_genoflu["Collection_Date"] + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype_y"]

metadata_genoflu["Name"] = names

print(metadata_genoflu["Name"])

0       >A/Pelecanus/Peru/VFAR-140/2022|H5N1|2022-12|a...
1       >A/Turdus merula/USA//2024|H5N1|2024-03-16|avi...
2       >A/Bos taurus/USA//2024|H5N1|2024-03-20|cattle...
3       >A/Felis catus/USA//2024|H5N1|2024-03-22|felin...
4       >A/Felis catus/USA//2024|H5N1|2024-03-22|felin...
                              ...
3648    >A/Anatidae/USA: NJ/25-008575-002-original/202...
3649    >A/Anatidae/USA: NY/25-008296-001-original/202...
3650    >A/Anatidae/USA: NY/25-008296-002-original/202...
3651    >A/Anatidae/USA: OH/25-007078-005-original/202...
3652    >A/Anatidae/USA: PA/25-006346-001-original/202...
Name: Name, Length: 3653, dtype: object

## Merge all datasets and de-duplicate again

In [ ]:
# # Animals 

# os.chdir(home)
# animals_ref = pd.read_csv("animals_ref.csv")

# # Create animals ref if needed

# unique_animals_all = sort_animals_andersen(metadata_genoflu)

# # Flatten unique_animals_all
# every_unique_animal = []
# for animal in unique_animals_all:
#     every_unique_animal.append(animal)

# print(every_unique_animal)

# unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# # If animal not in ref1, put in ref2

# common_animals = []
# # Check if animals in unique_animals_set are in ref1
# for animal in unique_animals_set:
#     for col in animals_ref.columns:
#         if animal in animals_ref[col].values and type(animal) == str:
#             common_animals.append(animal)

# # If not in ref1, make a list of the new animals
# different_animals = []
# for animal in unique_animals_set:
#     if animal not in common_animals:
#         different_animals.append(animal)

# print(different_animals)

# # Add to dataframe
# animals_df = animals_ref
# # Make different_animals same length as dataframe, if shorter
# if len(different_animals) < len(animals_df):
#     number_of_times_to_add_nan = len(animals_df) - len(different_animals)
#     for i in range(number_of_times_to_add_nan):
#         different_animals.append(float('nan'))
# # If longer, deal with that later

# animals_df["new"] = (different_animals)

# print(animals_df)

# animals_df.to_csv("animals_ref_to_sort.csv") # Make sure name is different to avoid overwriting the first reference

['', 'athene cunicularia', 'mephitidae', 'procyon lotor', 'felis catus', 'accipitridae', 'numididae', 'cairina moschata', 'corvus', 'gallus gallus', 'scolopax minor', 'sus scrofa', 'lynx', 'ardea herodias', 'mareca americana', 'branta hutchinsii', 'turdus merula', 'branta canadensis', 'streptopelia decaocto', 'leptailurus serval', 'phasianinae', 'puma concolor', 'bubo scandiacus', 'numididae sp.', 'vicugna pacos', 'lynx rufus', 'anas carolinensis', 'buteo jamaicensis', 'nycticorax nycticorax', 'strigidae', 'columbidae', 'falco peregrinus', 'mareca strepera', 'tyto alba', 'alectoris chukar', 'corvus corax', 'cygnus olor', 'buteo lineatus', 'galliformes', 'mus musculus', 'aix sponsa', 'cathartes aura', 'vulpes vulpes', 'zenaida asiatica', 'anas platyrhynchos', 'haliaeetus leucocephalus', 'larus occidentalis', 'icteridae', 'lophodytes cucullatus', 'bos taurus', 'dromaius novaehollandiae', 'capra hircus', 'meleagris gallopavo', 'anatidae', 'pelecanus', 'passer domesticus', 'pavo', 'gruidae', 'pelecanidae', 'bubo virginianus', 'anser caerulescens', 'corvus brachyrhynchos', 'columba livia', 'turdus migratorius', 'aves', 'calidris mauri', 'phoenicopterus roseus', 'gyps fulvus', 'panthera tigris']
['', 'athene cunicularia', 'mephitidae', 'procyon lotor', 'felis catus', 'accipitridae', 'numididae', 'cairina moschata', 'panthera tigris', 'corvus', 'gallus gallus', 'scolopax minor', 'sus scrofa', 'ardea herodias', 'mareca americana', 'branta hutchinsii', 'turdus merula', 'branta canadensis', 'streptopelia decaocto', 'leptailurus serval', 'phasianinae', 'puma concolor', 'bubo scandiacus', 'numididae sp.', 'vicugna pacos', 'lynx rufus', 'anas carolinensis', 'buteo jamaicensis', 'nycticorax nycticorax', 'strigidae', 'columbidae', 'mareca strepera', 'tyto alba', 'alectoris chukar', 'corvus corax', 'cygnus olor', 'buteo lineatus', 'mus musculus', 'aix sponsa', 'cathartes aura', 'vulpes vulpes', 'zenaida asiatica', 'anas platyrhynchos', 'haliaeetus leucocephalus', 'larus occidentalis', 'icteridae', 'lophodytes cucullatus', 'bos taurus', 'dromaius novaehollandiae', 'capra hircus', 'meleagris gallopavo', 'anatidae', 'passer domesticus', 'pavo', 'gruidae', 'pelecanidae', 'bubo virginianus', 'anser caerulescens', 'corvus brachyrhynchos', 'columba livia', 'turdus migratorius', 'galliformes', 'calidris mauri', 'phoenicopterus roseus', 'gyps fulvus', 'aves']
                  avian               cattle        feline   other_mammal  \
0      great_horned_owl            dairy_cow           cat     deer mouse
1          common_raven               cattle  domestic_cat    house_mouse
2         cooper's_hawk  cattle milk product     feral_cat          skunk
3          coopers_hawk          bovine_milk        feline  striped_skunk
4               peafowl              bovine   domestic-cat     norway rat
..                  ...                  ...           ...            ...
340  pluvialis_dominica                  NaN           NaN            NaN
341       gallus_gallus                  NaN           NaN            NaN
342      antarctic_tern                  NaN           NaN            NaN
343          brown_skua                  NaN           NaN            NaN
344  south_georgia_shag                  NaN           NaN            NaN

          human         other                 new
0    washington         mixed
1        nevada   environment  athene cunicularia
2       wyoming  multispecies          mephitidae
3    california           NaN       procyon lotor
4      michigan           NaN         felis catus
..          ...           ...                 ...
340         NaN           NaN                 NaN
341         NaN           NaN                 NaN
342         NaN           NaN                 NaN
343         NaN           NaN                 NaN
344         NaN           NaN                 NaN

[345 rows x 7 columns]