# NCBI Virus Dataset Creation

Author: Alexander Maksiaev

Purpose: Create dataset using NCBI and relabeling sequences. 

Notes:
* This file must be in the same folder as "utils.py"

## Housekeeping

### Libraries

In [1]:
# Libraries

import os
import pandas as pd
import dateutil
import re
import shutil 
import numpy as np
import importlib
from pathlib import Path
import utils  
importlib.reload(utils)
from utils import * # If changing utils, must restart this file for changes to take effect

### Input

Change these variables to what you need. The locations must be a string with each continent separated by a comma and space. The serotypes and genotypes must be lists. The dates must be strings.

In [2]:
# Dates and locations
locations = "Antarctica, North America, South America"
serotypes = ["H5N1"]
# genotypes = ["A3"]
start_date = "11-01-2021"
end_date = "08-07-2026"

# Make a date range
date_range = start_date + "--" + end_date

### Paths

Make sure these paths fit your schema. Here is the general tree structure: </br>

* Avian Flu: This is where the code in this repository is housed. "references" is a subdirectory here.
* Avian Flu Files: This is a sister directory to the repository -- that is, the code repository and the input/output files both have the same parent directory, which is the "home" variable.
* Avian Flu Files/NCBI Virus: This is the NCBI Virus directory. There are three subdirectories here: "downloads", "temp", and "complete".
* NCBI Virus/downloads: input data
* NCBI Virus/temp: intermediate data created between input and output. A subdirectory is created for this specific date range.
* NCBI Virus/complete: output data

<img src="../Avian_Flu_Files/Presentations/ncbi_virus_file_tree.png" width="500" height="250" alt="NCBI Virus file tree structure">

In [74]:
# Paths

home = Path.home() / "OneDrive - National Institutes of Health/Documents/Virus_Evolution/"
avian_flu_files = home / "Avian_Flu_Files" # Avian flu files is a sister directory of the directory this code is housed in
references = home / "Avian_Flu" / "references"
downloads = Path.home() / "Downloads"

downloads_saved = avian_flu_files / "NCBI_Virus/downloads" / (date_range + "_" + locations.replace(", ", "_").replace(" ", "_"))  

temp_files = avian_flu_files / "NCBI_Virus/temp" / ("segments_" + date_range)
if not temp_files.exists():
    Path.mkdir(temp_files, parents=True, exist_ok=True)
complete_files = avian_flu_files / "NCBI_Virus/complete" / (date_range + "_" + locations.replace(", ", "_").replace(" ", "_"))
if not complete_files.exists(): # checking if the directory exists or not
    Path.mkdir(complete_files, parents=True, exist_ok=True) # if the directory is not present then create it

states_ref = pd.read_csv(references / "states_ref.csv")

genotypes_df = pd.read_excel(references / "genotype_key.xlsx")
genotypes = list(genotypes_df["Genotype"].values)
genotypes.append("Not") 

print(genotypes)

['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'B1.1', 'B1.2', 'B1.3', 'B2.1', 'B2.2', 'B3.1', 'B3.2', 'B3.3', 'B3.4', 'B3.5', 'B3.6', 'B4.1', 'B5.1', 'Minor01', 'Minor04', 'Minor07', 'Minor08', 'Minor09', 'Minor10', 'Minor11', 'Minor12', 'Minor13', 'Minor14', 'Minor15', 'Minor16', 'Minor17', 'Minor18', 'Minor19', 'Minor24', 'Minor25', 'Minor26', 'Minor27', 'Minor28', 'Minor29', 'Minor30', 'Minor31', 'Minor32', 'Minor33', 'Minor34', 'Minor35', 'Minor36', 'Minor37', 'Minor38', 'Minor39', 'Minor40', 'Minor41', 'Minor42', 'Minor43', 'Minor44', 'Minor45', 'Minor46', 'Minor47', 'Minor48', 'B3.7', 'Minor50', 'Minor51', 'C1.1', 'Minor52', 'Minor53', 'B3.11', 'Minor55', 'Minor56', 'Minor57', 'Minor58', 'B3.10', 'C2.1', 'Minor60', 'Minor61', 'B3.8', 'Minor62', 'Minor63', 'B3.12', 'Minor65', 'Minor66', 'Minor67', 'B3.9', 'Minor70', 'Minor71', 'B3.13', 'Minor73', 'Minor74', 'Minor75', 'Minor76', 'Minor77', 'Minor78', 'Minor79', 'Minor80', 'Minor81', 'Minor82', 'Minor83', 'Minor84', 'C3.1', 'Minor86', 'Minor87', 'Minor89', 'Minor90', 'Minor91', 'Minor92', 'Minor93', 'Minor94', 'D1.1', 'D1.2', 'D2.1', 'Minor95', 'D1.3', 'Minor98', 'Minor99', 'Minor100', 'Minor101', 'Minor97', 'Minor102', 'Minor103', 'Minor104', 'Minor105', 'Minor106', 'Not']

## Downloading Data

In [4]:
os.chdir(downloads)

if not downloads_saved.exists(): # checking if the directory exists or not
    Path.mkdir(downloads_saved, parents=True, exist_ok=True) # if the directory is not present then create it

# Move downloaded files to saved downloads
for dirpath, dirs, files in os.walk(downloads_saved):
    if len(files) != 0: # If we have downloaded files already, skip
        break 
    else: # If we don't have any downloaded files, get files
        for dirpath, dirs, files in os.walk(downloads):
            if len(files) > 0: # If we have any files that need to be moved
                for file in files:
                    file_name = os.path.join(dirpath, file)
                    destination_path = os.path.join(downloads_saved, os.path.basename(file_name))
                    try:
                        shutil.move(file_name, destination_path)
                    except:
                        print("Error moving file", file_name)
                        continue 
            break 
    break

## De-Duplication

In [5]:
# Get metadata
os.chdir(downloads_saved)
metadata = pd.read_csv("sequences.csv")
print(len(metadata))

# Make sure we only have completed sequences -- 8 segments each 

metadata_counts = metadata.groupby(metadata.Assembly, as_index=False).size()
print(metadata_counts)
metadata_counted = metadata.merge(metadata_counts, on="Assembly")

# Only keep those with size >= 8

metadata_complete_segs = metadata_counted[metadata_counted["size"] >= 8] # May have duplicates
metadata_complete_segs = metadata_counted.drop_duplicates(subset="GenBank_Title", keep="last") # Get rid of duplicate segments

# Now only accept == 8 segments

metadata_segments = metadata_complete_segs[metadata_complete_segs["size"] == 8]
metadata_segments = metadata_complete_segs
metadata_segments

167143
              Assembly  size
0      GCA_038929245.1     8
1      GCA_038932225.1     8
2      GCA_038932275.1     8
3      GCA_038932295.1     8
4      GCA_038933705.1     8
...                ...   ...
19181  GCA_059952155.1     8
19182  GCA_059952165.1     8
19183  GCA_059952175.1     8
19184  GCA_059952205.1     8
19185  GCA_059952255.1     8

[19186 rows x 2 columns]

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Host,Tissue_Specimen_Source,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size
0,PZ803360.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Branta hutchinsii,"oronasopharynx, feces",Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8
1,PZ803361.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Branta hutchinsii,"oronasopharynx, feces",Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8
2,PZ803362.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Branta hutchinsii,"oronasopharynx, feces",Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8
3,PZ803363.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Branta hutchinsii,"oronasopharynx, feces",Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8
4,PZ803364.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Branta hutchinsii,"oronasopharynx, feces",Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153467,OK205699.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8
153468,OK205700.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8
153469,OK205701.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8
153470,OK205702.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8
153471,OK205703.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Gallus gallus,allantoic fluid,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8

## Add sequences to dataframe

In [6]:
os.chdir(downloads_saved)

sequences_fasta = df_from_fasta("sequences.fasta") # Turn fasta into a dataframe

sequences_fasta["Accession"] = sequences_fasta["full_header"].apply(lambda x: x.split(" |")[0].replace(">",""))

print(sequences_fasta["full_header"])

# Double-check the de-duplication
print(len(sequences_fasta)) 
print(len(metadata_segments))

# Add sequences to the dataframe
metadata_segments = pd.merge(metadata_segments, sequences_fasta, on="Accession") # , "Segment"])

0         >PZ803346.1 |Influenza A virus (A/Canada Goose...
1         >PZ803347.1 |Influenza A virus (A/Canada Goose...
2         >PZ803348.1 |Influenza A virus (A/Canada Goose...
3         >PZ803349.1 |Influenza A virus (A/Canada Goose...
4         >PZ803350.1 |Influenza A virus (A/Canada Goose...
                                ...
167138    >OK205883.1 |Influenza A virus (A/chicken/Vera...
167139    >OK205884.1 |Influenza A virus (A/chicken/Vera...
167140    >OK205885.1 |Influenza A virus (A/chicken/Vera...
167141    >OK205886.1 |Influenza A virus (A/chicken/Vera...
167142    >OK205887.1 |Influenza A virus (A/chicken/Vera...
Name: full_header, Length: 167143, dtype: object
167143
151960

In [7]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Submitters,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence
0,PZ803360.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803360.1 |Influenza A virus (A/Cackling Goo...,ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...
1,PZ803361.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803361.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAA...
2,PZ803362.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803362.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGGTGACAAAAACATAATGGATTCCAACACTGTGTCAAGC...
3,PZ803363.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803363.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTACTTTT...
4,PZ803364.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,Direct Submission,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803364.1 |Influenza A virus (A/Cackling Goo...,ATGAATCCAAATCAAAAGATAACAACTATCGGGTCAATCTGCATGG...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151955,OK205699.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205699.1 |Influenza A virus (A/chicken/Mexi...,CAACTGTCAAAATGGAAAGGATAGTAATTGCCTTTGCAATAATCAG...
151956,OK205700.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205700.1 |Influenza A virus (A/chicken/Mexi...,GTAGATAATCACTCACTGAGTGACATTCACATCATGGCGTCTCAAG...
151957,OK205701.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205701.1 |Influenza A virus (A/chicken/Mexi...,ATGAATCCAAATCAGAAAATACTAACAATAGGCTCCACCTCTCTAA...
151958,OK205702.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205702.1 |Influenza A virus (A/chicken/Mexi...,TAGATGTTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...
151959,OK205703.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"Youk,S., Leyson,C., Parris,D., Suarez,D., Pant...","USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205703.1 |Influenza A virus (A/chicken/Mexi...,GTGACAAAGACATAATGGACTCCAACACTATAACCTCGTTTCAGGT...

## Find genotypes

Set up files that are friendly to multi-genoflu, then run multi-genoflu.

In [8]:
metadata_segments["Partial_Header_temp"] = metadata_segments["Isolate"] # Get only isolate

for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments["Partial_Header_temp"] = metadata_segments["Partial_Header_temp"].apply(lambda x: x.replace(c, "_") if x == x else x)

print(len(metadata_segments))

151960

### Create FASTA files of unknown genotypes

In [9]:
metadata_segments

,Accession,GenBank_RefSeq,Assembly,SRA_Accession,BioSample,BioProject,Organism_Name,Species,Genus,Family,...,Organization,Org_location,Publications,Collection_Date,Release_Date,Molecule_type,size,full_header,sequence,Partial_Header_temp
0,PZ803360.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803360.1 |Influenza A virus (A/Cackling Goo...,ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...,A_Cackling_Goose_North_Dakota_2740_2026
1,PZ803361.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803361.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAA...,A_Cackling_Goose_North_Dakota_2740_2026
2,PZ803362.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803362.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGGTGACAAAAACATAATGGATTCCAACACTGTGTCAAGC...,A_Cackling_Goose_North_Dakota_2740_2026
3,PZ803363.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803363.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTACTTTT...,A_Cackling_Goose_North_Dakota_2740_2026
4,PZ803364.1,GenBank,GCA_059951935.1,NaN,NaN,PRJNA297868,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,St. Jude Center of Excellence for Influenza Re...,USA,NaN,2026-03-24,2026-08-07,ssRNA(-),8,>PZ803364.1 |Influenza A virus (A/Cackling Goo...,ATGAATCCAAATCAAAAGATAACAACTATCGGGTCAATCTGCATGG...,A_Cackling_Goose_North_Dakota_2740_2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151955,OK205699.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205699.1 |Influenza A virus (A/chicken/Mexi...,CAACTGTCAAAATGGAAAGGATAGTAATTGCCTTTGCAATAATCAG...,1864
151956,OK205700.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205700.1 |Influenza A virus (A/chicken/Mexi...,GTAGATAATCACTCACTGAGTGACATTCACATCATGGCGTCTCAAG...,1864
151957,OK205701.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205701.1 |Influenza A virus (A/chicken/Mexi...,ATGAATCCAAATCAGAAAATACTAACAATAGGCTCCACCTCTCTAA...,1864
151958,OK205702.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205702.1 |Influenza A virus (A/chicken/Mexi...,TAGATGTTGAAAGATGAGTCTTCTAACCGAGGTCGAAACGTACGTT...,1864
151959,OK205703.1,GenBank,GCA_039174385.1,NaN,NaN,NaN,Influenza A virus,Alphainfluenzavirus influenzae,Alphainfluenzavirus,Orthomyxoviridae,...,"USDA ARS SEPRL, Exotic & Emerging Avian Viral ...",USA,NaN,2019-09-03,2021-11-01,ssRNA(-),8,>OK205703.1 |Influenza A virus (A/chicken/Mexi...,GTGACAAAGACATAATGGACTCCAACACTATAACCTCGTTTCAGGT...,1864

In [10]:
# Create 8 fasta files per segment

# Get all the segments
metadata_segments["Partial_Header"] = metadata_segments["Partial_Header_temp"].apply(lambda x: ">" + x if x == x else x) # .apply(lambda x: x.split("|")[-1].split(")")[0]) # Get only genbank name
metadata_segments = metadata_segments.dropna(subset="Partial_Header")

print(metadata_segments["Partial_Header"].values[0:5])

['>A_Cackling_Goose_North_Dakota_2740_2026'
 '>A_Cackling_Goose_North_Dakota_2740_2026'
 '>A_Cackling_Goose_North_Dakota_2740_2026'
 '>A_Cackling_Goose_North_Dakota_2740_2026'
 '>A_Cackling_Goose_North_Dakota_2740_2026']

In [11]:
# Create list of dataframes
df_list = []
for partial_header in list(set(metadata_segments["Partial_Header"].values)): # Unique partial headers only
    # Get smaller dataframe
    df = metadata_segments[metadata_segments["Partial_Header"] == partial_header]
    df = df.sort_values(by="Segment")
    # Make sure there are 8 segments
    if len(df) == 8:
        # Forbidden characters in headers
        for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]:
            df["Partial_Header"] = df["Partial_Header"].apply(lambda x: x.replace(c, "_"))
            
        df["full_header"] = df["Partial_Header"]
        df_list.append(df)

print(metadata_segments["Partial_Header"])

print(df_list[0]["full_header"].values[:10])

# Make fasta files
for df in df_list:
    segments = list(set(df["Segment"].apply(lambda x: int(x)).values))
    for segment in segments:
        one_row = df[df["Segment"] == segment]
        df_to_fasta(one_row, str(segment) + "_seg.fasta", temp_files)

KeyboardInterrupt:

### Re-Labeling Using GenoFlu

**STOP HERE AND USE GENOFLU TO FIND NEW GENOTYPES.** Then, make sure "results.tsv" is in the NCBI_Virus downloads directory. <br>

To avoid job kill:
```
sinteractive
```
To activate genoflu conda environment in BioWulf:
```
source myconda
conda activate genoflu
```

To run GenoFLU-multi, change directories to Multi-GenoFLU directory:
``` 
cd GenoFLU-multi
```

And then call the python script:

``` 
python bin/genoflu-multi.py -f <FASTA_directory>
```

In [ ]:
# Ensure that user does the above
input("Use genoflu. Afterwards, press ENTER to continue.")

''

In [84]:
# Merging

os.chdir(downloads_saved)

# Read in genoflu results
output_genoflu = pd.read_csv("results.tsv", delimiter="\t") # This also shows the IDs of the new sequences -- incorporate into sequences report

# Create partial headers to merge genoflu results with previously unknown segments
metadata_segments["Partial_Header_Merge"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(">", ""))
for c in ["/", "|", " ", ":", ",", "(", ")", "-", "."]: # Forbidden punctuation
    metadata_segments["Partial_Header_Merge"] = metadata_segments["Partial_Header_Merge"].apply(lambda x: x.replace(c, "_") if x==x else x)

# Reformat so we can merge
output_genoflu["Partial_Header_Merge"] = output_genoflu["Strain"] #.apply(lambda x: re.split(r'Influenza_A_virus__\D*__\D*_', x)[-1])

# Merge
metadata_genoflu = metadata_segments.merge(output_genoflu, how="inner", on="Partial_Header_Merge") #, suffixes=('_left', '_right')) 
metadata_genoflu = metadata_genoflu.rename(columns={"Genotype_y":"Genotype", "Genotype_x":"Serotype"})

print(metadata_genoflu)

C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_3256\3183371152.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_segments["Partial_Header_Merge"] = metadata_segments["Partial_Header"].apply(lambda x: x.replace(">", ""))
C:\Users\maksiaevai.NCBI_NT\AppData\Local\Temp\2\ipykernel_3256\3183371152.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  metadata_segments["Partial_Header_Merge"] = metadata_segments["Partial_Header_Merge"].apply(lambda x: x.replace(c, "_") if x==x else x)

         Accession GenBank_RefSeq         Assembly SRA_Accession BioSample  \
0       PZ803360.1        GenBank  GCA_059951935.1           NaN       NaN
1       PZ803361.1        GenBank  GCA_059951935.1           NaN       NaN
2       PZ803362.1        GenBank  GCA_059951935.1           NaN       NaN
3       PZ803363.1        GenBank  GCA_059951935.1           NaN       NaN
4       PZ803364.1        GenBank  GCA_059951935.1           NaN       NaN
...            ...            ...              ...           ...       ...
151883  OK205699.1        GenBank  GCA_039174385.1           NaN       NaN
151884  OK205700.1        GenBank  GCA_039174385.1           NaN       NaN
151885  OK205701.1        GenBank  GCA_039174385.1           NaN       NaN
151886  OK205702.1        GenBank  GCA_039174385.1           NaN       NaN
151887  OK205703.1        GenBank  GCA_039174385.1           NaN       NaN

         BioProject      Organism_Name                         Species  \
0       PRJNA297868  Influenza A virus  Alphainfluenzavirus influenzae
1       PRJNA297868  Influenza A virus  Alphainfluenzavirus influenzae
2       PRJNA297868  Influenza A virus  Alphainfluenzavirus influenzae
3       PRJNA297868  Influenza A virus  Alphainfluenzavirus influenzae
4       PRJNA297868  Influenza A virus  Alphainfluenzavirus influenzae
...             ...                ...                             ...
151883          NaN  Influenza A virus  Alphainfluenzavirus influenzae
151884          NaN  Influenza A virus  Alphainfluenzavirus influenzae
151885          NaN  Influenza A virus  Alphainfluenzavirus influenzae
151886          NaN  Influenza A virus  Alphainfluenzavirus influenzae
151887          NaN  Influenza A virus  Alphainfluenzavirus influenzae

                      Genus            Family  ...  \
0       Alphainfluenzavirus  Orthomyxoviridae  ...
1       Alphainfluenzavirus  Orthomyxoviridae  ...
2       Alphainfluenzavirus  Orthomyxoviridae  ...
3       Alphainfluenzavirus  Orthomyxoviridae  ...
4       Alphainfluenzavirus  Orthomyxoviridae  ...
...                     ...               ...  ...
151883  Alphainfluenzavirus  Orthomyxoviridae  ...
151884  Alphainfluenzavirus  Orthomyxoviridae  ...
151885  Alphainfluenzavirus  Orthomyxoviridae  ...
151886  Alphainfluenzavirus  Orthomyxoviridae  ...
151887  Alphainfluenzavirus  Orthomyxoviridae  ...

                                  Partial_Header  \
0       >A_Cackling_Goose_North_Dakota_2740_2026
1       >A_Cackling_Goose_North_Dakota_2740_2026
2       >A_Cackling_Goose_North_Dakota_2740_2026
3       >A_Cackling_Goose_North_Dakota_2740_2026
4       >A_Cackling_Goose_North_Dakota_2740_2026
...                                          ...
151883                                     >1864
151884                                     >1864
151885                                     >1864
151886                                     >1864
151887                                     >1864

                           Partial_Header_Merge  \
0       A_Cackling_Goose_North_Dakota_2740_2026
1       A_Cackling_Goose_North_Dakota_2740_2026
2       A_Cackling_Goose_North_Dakota_2740_2026
3       A_Cackling_Goose_North_Dakota_2740_2026
4       A_Cackling_Goose_North_Dakota_2740_2026
...                                         ...
151883                                     1864
151884                                     1864
151885                                     1864
151886                                     1864
151887                                     1864

                                         Strain  \
0       A_Cackling_Goose_North_Dakota_2740_2026
1       A_Cackling_Goose_North_Dakota_2740_2026
2       A_Cackling_Goose_North_Dakota_2740_2026
3       A_Cackling_Goose_North_Dakota_2740_2026
4       A_Cackling_Goose_North_Dakota_2740_2026
...                                         ...
151883                                     1864
151884                                     1864
151885                                     1864
151886                                     1864
151887                                     1864

                                                 Genotype  \
0                     Not assigned: No Matching Genotypes
1                     Not assigned: No Matching Genotypes
2                     Not assigned: No Matching Genotypes
3                     Not assigned: No Matching Genotypes
4                     Not assigned: No Matching Genotypes
...                                                   ...
151883  Not assigned: Only 0 segments >98.0% match fou...
151884  Not assigned: Only 0 segments >98.0% match fou...
151885  Not assigned: Only 0 segments >98.0% match fou...
151886  Not assigned: Only 0 segments >98.0% match fou...
151887  Not assigned: Only 0 segments >98.0% match fou...

                              Genotype List Used, >=98.0%  \
0       PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am1.1, N...
1       PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am1.1, N...
2       PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am1.1, N...
3       PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am1.1, N...
4       PB2:am24, PB1:ea3, PA:am4, HA:ea3, NP:am1.1, N...
...                                                   ...
151883                                                NaN
151884                                                NaN
151885                                                NaN
151886                                                NaN
151887                                                NaN

                               Genotype Sample Title List  \
0       am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
1       am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
2       am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
3       am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
4       am24:24-030039-001:PB2, ea3:22-013001-001:PB1,...
...                                                   ...
151883  am8:23-004320-002:PB2, am8:22-035443-007:PB1, ...
151884  am8:23-004320-002:PB2, am8:22-035443-007:PB1, ...
151885  am8:23-004320-002:PB2, am8:22-035443-007:PB1, ...
151886  am8:23-004320-002:PB2, am8:22-035443-007:PB1, ...
151887  am8:23-004320-002:PB2, am8:22-035443-007:PB1, ...

                              Genotype Percent Match List  \
0       99.39%, 99.08%, 99.26%, 98.83%, 98.66%, 99.15%...
1       99.39%, 99.08%, 99.26%, 98.83%, 98.66%, 99.15%...
2       99.39%, 99.08%, 99.26%, 98.83%, 98.66%, 99.15%...
3       99.39%, 99.08%, 99.26%, 98.83%, 98.66%, 99.15%...
4       99.39%, 99.08%, 99.26%, 98.83%, 98.66%, 99.15%...
...                                                   ...
151883  91.36%, 94.11%, 87.09%, 76.95%, 89.05%, 85.22%...
151884  91.36%, 94.11%, 87.09%, 76.95%, 89.05%, 85.22%...
151885  91.36%, 94.11%, 87.09%, 76.95%, 89.05%, 85.22%...
151886  91.36%, 94.11%, 87.09%, 76.95%, 89.05%, 85.22%...
151887  91.36%, 94.11%, 87.09%, 76.95%, 89.05%, 85.22%...

                      Genotype Mismatch List  \
0              14, 21, 16, 20, 20, 12, 5, 11
1              14, 21, 16, 20, 20, 12, 5, 11
2              14, 21, 16, 20, 20, 12, 5, 11
3              14, 21, 16, 20, 20, 12, 5, 11
4              14, 21, 16, 20, 20, 12, 5, 11
...                                      ...
151883  195, 134, 272, 374, 162, 172, 85, 84
151884  195, 134, 272, 374, 162, 172, 85, 84
151885  195, 134, 272, 374, 162, 172, 85, 84
151886  195, 134, 272, 374, 162, 172, 85, 84
151887  195, 134, 272, 374, 162, 172, 85, 84

       Genotype Average Depth of Coverage List             Date run
0            Ran on FASTA - No Coverage Report  2026-08-14_15-15-01
1            Ran on FASTA - No Coverage Report  2026-08-14_15-15-01
2            Ran on FASTA - No Coverage Report  2026-08-14_15-15-01
3            Ran on FASTA - No Coverage Report  2026-08-14_15-15-01
4            Ran on FASTA - No Coverage Report  2026-08-14_15-15-01
...                                        ...                  ...
151883       Ran on FASTA - No Coverage Report  2026-08-14_15-33-27
151884       Ran on FASTA - No Coverage Report  2026-08-14_15-33-27
151885       Ran on FASTA - No Coverage Report  2026-08-14_15-33-27
151886       Ran on FASTA - No Coverage Report  2026-08-14_15-33-27
151887       Ran on FASTA - No Coverage Report  2026-08-14_15-33-27

[151888 rows x 42 columns]

In [85]:
# Cut down to only columns we want
metadata_genoflu = metadata_genoflu[["Accession", "Assembly", "GenBank_Title", "Host", "Collection_Date", "SRA_Accession", "Isolate", "Genotype", "Geo_Location", "full_header", "sequence", "Serotype", "Segment", "Partial_Header_Merge"]] #, "Strain"]]

# Get genbank strain name
 
metadata_genoflu["genbank_name"] = metadata_genoflu["GenBank_Title"].apply(lambda x: x.split("(")[1] if x == x else x)
metadata_genoflu["Host"] = metadata_genoflu["genbank_name"].apply(lambda x: x.split("/")[1] if x == x else x)

metadata_genoflu = metadata_genoflu.dropna(subset="genbank_name")

In [86]:
metadata_genoflu

# Make sure we only have the serotype(s) we want -- this code only works for a single serotype, so change it if multiple are ever needed
for serotype in serotypes:
    metadata_genoflu = metadata_genoflu[metadata_genoflu["Serotype"] == serotype]

## Relabeling Sequences

We want:
* Host
* Geo-Location
* Isolate
* Year
* Collection Date
* Host Type
* Genotype

After running the below code, **STOP TO CHECK** if any new animals appear

In [87]:
# Animals 

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Create animals ref if needed

unique_animals_all = sort_animals_andersen(metadata_genoflu)

# Flatten unique_animals_all
every_unique_animal = []
for animal in unique_animals_all:
    every_unique_animal.append(animal)

print(every_unique_animal)

unique_animals_set = list(set(every_unique_animal)) # Get rid of duplicates

# If animal not in ref1, put in ref2

common_animals = []
# Check if animals in unique_animals_set are in ref1
for animal in unique_animals_set:
    for col in animals_ref.columns:
        if animal in animals_ref[col].values and type(animal) == str:
            common_animals.append(animal)

# If not in ref1, make a list of the new animals
different_animals = []
for animal in unique_animals_set:
    if animal not in common_animals:
        different_animals.append(animal)

print("New animals to add to reference:", different_animals)

# Add to dataframe
animals_df = animals_ref
# Make different_animals same length as dataframe, if shorter
if len(different_animals) < len(animals_df):
    number_of_times_to_add_nan = len(animals_df) - len(different_animals)
    for i in range(number_of_times_to_add_nan):
        different_animals.append(float('nan'))
# If longer, write code dealing with that later

animals_df["new"] = (different_animals)

print(animals_df)

animals_df.to_csv("animals_ref_to_sort.csv", index=False) # Make sure name is different to avoid overwriting the first reference

['snowy egret', 'double-crested cormorant', 'wyoming', 'peacock', 'irere', 'humboldt penguin', 'silver pheasant', 'megascops choliba', 'duck', 'guanay cormorant', 'seabird', 'whooper swan', 'chinese goose', 'redhead', 'short-eared owl', 'bottlenose dolphin', 'common tern', 'striped skunk', 'great-tailed grackle', 'common eider', 'greater scaup', 'blackbird', 'thalasseus maximus', 'serval', 'royal tern', 'american robin', 'gyrfalcon', 'american crow', 'wood duck', 'great grebe', 'norway rat', 'domestic turkey', 'arctic tern', 'sharp-shinned hawk', 'poultry', 'washington', 'bird', 'bear', 'great blue heron', 'snow goose', 'antofagasta', 'american widgeon', 'green winged teal', 'michigan', 'lesser scaup', 'dunlin', 'crested caracara', 'ring-necked duck', 'mottled duck', 'willet', 'turkey vulture', 'layer chicken', 'barn owl', 'penguin', 'ermine', 'ohio', 'common raven', 'northern elephant seal', 'tiger', 'neotropic cormorant', 'aves', 'rock pigeon', 'golden eagle', 'mergus', 'great horned owl', 'sandwich tern', 'anatinae', 'cinnamon teal', 'american pelican', 'grackle', 'elegant tern', 'common loon', 'great grabe', 'bald eagle', 'surf scoter', 'cormorant', 'gallus gallus', 'fox', 'great black-backed gull', 'razorbill', 'common barn owl', 'lion', 'lynx', 'cattle', 'american black duck', 'gallus gallus domesticus', 'chilean dolphin', 'trumpeter swan', 'horned grebe', 'western sandpiper', 'nevada', 'dolphin', 'black vulture', 'antarctic fur seal', 'domestic goose', 'inca tern', 'european starling', 'partridge', 'bobcat', 'dendrocygna viduata', 'american coot', 'mountain lion', 'black-crowned night-heron', 'snowy plover', 'chicken', 'common eiders', 'glaucous-winged gull', 'american white pelican', 'caspian tern', 'wild duck', 'mink', 'gull', 'skunk', 'raven', 'domestic duck', 'pigeon', 'broad-winged hawk', 'buteogallus urubitinga', 'white-winged dove', 'pelican', 'long-eared owl', 'lesser snow goose', 'muscovy duck', 'nasua nasua', 'hooded merganser duck', 'laughing gull', 'feline', 'goose', 'louisiana', 'northern harrier', 'blue-winged teal', 'waterfowl', 'black skimmer', 'nannopterum brasilianus', 'redhead duck', 'wild turkey', 'bovine', 'teal', 'american woodcock', 'swine', 'white-faced ibis', 'lesser black-backed gull', 'black swift', 'green heron', 'bluejay', 'atlantic white-sided dolphin', 'ostrich', 'house mouse', 'black-billed magpie', 'cygnus melancoryphus', 'hooded merganser', 'california', 'sanderling', 'black swan', 'backyard duck', 'peruvian booby', 'common merganser', 'tundra swan', 'peruvian pelican', 'pheasant', 'pelecanus', 'blue jay', 'great grey owl', 'pinniped', 'northern fulmar', 'red-shouldered hawk', 'franklin gull', 'rough-legged hawk', 'black turnstone', 'colorado', 'gray gull', 'california condor', 'chiloe wigeon', 'great egret', 'pluvialis dominica', 'sea otter', 'california gull', 'southern elephant seal', 'common grackle', 'fregata magnificens', 'iceland gull', 'burrowing owl', 'bufflehead', 'texas', 'parrot', 'green-winged teal', 'red-necked phalarope', 'chimango caracara', 'lesser white-fronted goose', 'graylag goose', 'ruffed grouse', 'quail', 'white-winged scoter', 'wild bird', 'cygnus atratus', 'ruddy turnstone', 'fancy chicken', 'hawk', 'red-tailed hawk', 'pelecanus thagus', 'heron', 'sula leucogaster', 'guinea fowl', 'dromaius novaehollandiae', 'mute swan', 'south american tern', 'brown-hooded gull', 'laridae', 'pintail duck', 'emu', 'goat', 'magpie', 'northwestern crow', 'common rhea', 'domestic chicken', 'falcon', 'black-legged kittiwake', 'alpaca', 'osprey', 'procellaria aequinoctialis', 'ring-billed gull', 'domestic bird', 'finch', 'bos taurus', 'cat', 'great shearwater', 'polar bear', 'dove', 'brown pelican', 'western grebe', 'black-necked stilt', 'chukar', 'african gray parrot', 'whooping crane', 'chukar partridge', 'vulpes vulpes', 'hermit thrush', 'pintail', 'house sparrow', 'sparrow', 'owl', 'great-horned owl', 'harbor seal', 'coopers hawk', 'northern pintail', 'avian', 'virginia opossum', 'pig', 'backyard chicken', 'south polar skua', 'cackling goose', 'chungungo', 'red fox', 'mallard duck', 'flamingo', 'gadwall', 'furnarius rufus', 'american wigeon', 'black scoter', 'backyard turkey', 'peregrine falcon', 'raccoon', 'bluebird', 'dairy cow', 'turkey', 'peafowl', 'south american sea lion', 'ferruginous hawk', 'common goldeneye', 'common murre', 'northern gannet', 'domestic cat', 'eurasian collared dove', 'black-necked swan', 'peruvean booby', 'american green-winged teal', 'panthera leo', 'swan', 'black bear', 'eagle', 'northern shoveler', 'gray seal', 'fisher', 'wild goose', 'crane', 'band-tailed gull', 'guineafowl', 'mallard', 'thalasseus acuflavidus', 'gadwell', 'vulture', 'fish crow', 'south american fur seal', 'rock dove', 'canada goose', 'american kestrel', 'black-crowned night heron', 'snowy owl', 'baikal teal', 'western gull', 'sandhill crane', 'brown skua', 'dog', 'greater white-fronted goose', 'pekin duck', 'kelp gull', 'sterna hirundo', 'gadwall duck', 'crow', 'coscoroba coscoroba', 'herring gull', 'glaucous gull', 'atlantic puffin', 'otaria flavescens', 'numida meleagris', 'gallus', 'ring-necked pheasant']
New animals to add to reference: []
            wild_avian domestic_avian               cattle        feline  \
0     great_horned_owl       pheasant            dairy_cow           cat
1         common_raven         turkey               cattle  domestic_cat
2        cooper's_hawk        chicken  cattle milk product     feral_cat
3         coopers_hawk          goose          bovine_milk        feline
4              peafowl    guinea_fowl              bovine   domestic-cat
...                ...            ...                  ...           ...
1663               NaN            NaN                  NaN           NaN
1664               NaN            NaN                  NaN           NaN
1665               NaN            NaN                  NaN           NaN
1666               NaN            NaN                  NaN           NaN
1667               NaN            NaN                  NaN           NaN

       other_mammal               human         other      pet_food  \
0        deer mouse          washington         mixed      pet food
1       house_mouse              nevada   environment  raw pet food
2             skunk             wyoming  multispecies  raw_pet_food
3     striped_skunk          california       unknown      pet_food
4        norway rat            michigan             '           NaN
...             ...                 ...           ...           ...
1663            NaN            florence           NaN           NaN
1664            NaN                 oms           NaN           NaN
1665            NaN  castilla-la_mancha           NaN           NaN
1666            NaN          guadeloupe           NaN           NaN
1667            NaN               opole           NaN           NaN

     experimental  new
0         macaque  NaN
1           swine  NaN
2             NaN  NaN
3             NaN  NaN
4             NaN  NaN
...           ...  ...
1663          NaN  NaN
1664          NaN  NaN
1665          NaN  NaN
1666          NaN  NaN
1667          NaN  NaN

[1668 rows x 10 columns]

In [ ]:
input("Check animals output. Afterwards, press ENTER to continue.")

''

In [88]:
# Re-label sequences with no assigned genotype as "Unassigned"

metadata_genoflu["Genotype"] = metadata_genoflu["Genotype"].apply(lambda x: "Not" if "Not assigned" in str(x) else x) # Unassigned segments are labeled "Unassigned"

# Cut down dataframe only to genotypes we want

metadata_genoflu = metadata_genoflu[metadata_genoflu['Genotype'].isin(genotypes) | (metadata_genoflu["Genotype"].str.contains("Not"))]

In [89]:
metadata_genoflu

,Accession,Assembly,GenBank_Title,Host,Collection_Date,SRA_Accession,Isolate,Genotype,Geo_Location,full_header,sequence,Serotype,Segment,Partial_Header_Merge,genbank_name
0,PZ803360.1,GCA_059951935.1,Influenza A virus (A/Cackling Goose/North Dako...,Cackling Goose,2026-03-24,NaN,A/Cackling Goose/North Dakota/2740/2026,Not,USA,>PZ803360.1 |Influenza A virus (A/Cackling Goo...,ATGGAAAACATAGTACTTCTTCTTGCAATAATTAGCCTTGTTAAAA...,H5N1,4,A_Cackling_Goose_North_Dakota_2740_2026,A/Cackling Goose/North Dakota/2740/2026
1,PZ803361.1,GCA_059951935.1,Influenza A virus (A/Cackling Goose/North Dako...,Cackling Goose,2026-03-24,NaN,A/Cackling Goose/North Dakota/2740/2026,Not,USA,>PZ803361.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGTAGATATTGAAAGATGAGTCTTCTAACCGAGGTCGAAA...,H5N1,7,A_Cackling_Goose_North_Dakota_2740_2026,A/Cackling Goose/North Dakota/2740/2026
2,PZ803362.1,GCA_059951935.1,Influenza A virus (A/Cackling Goose/North Dako...,Cackling Goose,2026-03-24,NaN,A/Cackling Goose/North Dakota/2740/2026,Not,USA,>PZ803362.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGGTGACAAAAACATAATGGATTCCAACACTGTGTCAAGC...,H5N1,8,A_Cackling_Goose_North_Dakota_2740_2026,A/Cackling Goose/North Dakota/2740/2026
3,PZ803363.1,GCA_059951935.1,Influenza A virus (A/Cackling Goose/North Dako...,Cackling Goose,2026-03-24,NaN,A/Cackling Goose/North Dakota/2740/2026,Not,USA,>PZ803363.1 |Influenza A virus (A/Cackling Goo...,AAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTACTTTT...,H5N1,2,A_Cackling_Goose_North_Dakota_2740_2026,A/Cackling Goose/North Dakota/2740/2026
4,PZ803364.1,GCA_059951935.1,Influenza A virus (A/Cackling Goose/North Dako...,Cackling Goose,2026-03-24,NaN,A/Cackling Goose/North Dakota/2740/2026,Not,USA,>PZ803364.1 |Influenza A virus (A/Cackling Goo...,ATGAATCCAAATCAAAAGATAACAACTATCGGGTCAATCTGCATGG...,H5N1,6,A_Cackling_Goose_North_Dakota_2740_2026,A/Cackling Goose/North Dakota/2740/2026
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150779,OP221403.1,GCA_039270135.1,Influenza A virus (A/bald eagle/Florida/W22-18...,bald eagle,2022-03-03,NaN,A/bald eagle/Florida/W22-189/2022,Not,USA,>OP221403.1 |Influenza A virus (A/bald eagle/F...,AGCAAAAGCAGGTACTGATCCGAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,A_bald_eagle_Florida_W22_189_2022,A/bald eagle/Florida/W22-189/2022
150780,OP221404.1,GCA_039270135.1,Influenza A virus (A/bald eagle/Florida/W22-18...,bald eagle,2022-03-03,NaN,A/bald eagle/Florida/W22-189/2022,Not,USA,>OP221404.1 |Influenza A virus (A/bald eagle/F...,AGCAAAAGCAGGTCAATTATATTCAATATGGAGAGAATAAAAGAGC...,H5N1,1,A_bald_eagle_Florida_W22_189_2022,A/bald eagle/Florida/W22-189/2022
150781,OP222196.1,GCA_039271695.1,Influenza A virus (A/bald eagle/Florida/W22-19...,bald eagle,2022-03-08,NaN,A/bald eagle/Florida/W22-191/2022,Not,USA,>OP222196.1 |Influenza A virus (A/bald eagle/F...,AGCGAAAGCAGGTACTGATCCGAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,A_bald_eagle_Florida_W22_191_2022,A/bald eagle/Florida/W22-191/2022
150782,OP222197.1,GCA_039270135.1,Influenza A virus (A/bald eagle/Florida/W22-18...,bald eagle,2022-03-03,NaN,A/bald eagle/Florida/W22-189/2022,Not,USA,>OP222197.1 |Influenza A virus (A/bald eagle/F...,AGCAAAAGCAGGCAAACCATTTGAATGGATGTCAATCCGACTTTAC...,H5N1,2,A_bald_eagle_Florida_W22_189_2022,A/bald eagle/Florida/W22-189/2022
150783,OP222198.1,GCA_039272365.1,Influenza A virus (A/American pelican/Kansas/W...,American pelican,2022-03-10,NaN,A/American pelican/Kansas/W22-200/2022,Not,USA,>OP222198.1 |Influenza A virus (A/American pel...,AGCAAAAGCAGGTACTGATCCGAAATGGAAGACTTTGTGCGACAAT...,H5N1,3,A_American_pelican_Kansas_W22_200_2022,A/American pelican/Kansas/W22-200/2022

In [90]:
def geo_location_normalize(geolocation: str) -> str:

    geolocation = geolocation.replace(":", ",") # We will need to split on commas later; e.g. USA: MD -> USA, MD

    country = geolocation.split(",")[0] # Get the first part of the geolocation, aka the country 

    state = geolocation.split(",")[-1] # Get the last part of the geolocation, aka the state

    state = state.strip().replace(" ", "_") # Remove leading and trailing whitespace, make sure that all internal spaces are underscored instead

    country = country.strip().replace(" ", "_") # Remove leading and trailing whitespace, make sure that all internal spaces are underscored instead

    country_state = country + "-" + state # Log needed

    return country_state 

# Format: USA-[state abbreviation], e.g. USA-MD
def geo_location_get(metadata: pd.DataFrame, state_ref_file: str = "states_ref.csv") -> pd.DataFrame:

    state_ref = pd.read_csv(state_ref_file)

    # Normalize the locations

    # metadata["name_state_genbank"] = metadata["genbank_name"].apply(lambda x: x.split("/")[2] if x == x else x)

    metadata["Geo_Location_Normalized"] = metadata["Geo_Location"].apply(geo_location_normalize)

    metadata["Geo_Location_Country"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[0])

    # Get country
    metadata["Geo_Location_Country"] = metadata["Geo_Location_Country"].apply(lambda x: state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Country'].iloc[0]
                                                                              if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Country']) > 0
                                                                              else state_ref.loc[state_ref["State"].str.contains(x), 'Country'].iloc[0]
                                                                              if len(state_ref.loc[state_ref["State"].str.contains(x), 'Country']) > 0
                                                                              else x)

    # Get state
    metadata["Geo_Location_State_med"] = metadata["Geo_Location_Normalized"].apply(lambda x: x.split("-")[-1])

      
    metadata["Geo_Location_State_USA"] = metadata["Geo_Location_State_med"].apply(lambda x: 
    # # If "x" is the abbreviated state (e.g. "MD")
    state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" is the state name (e.g. "Maryland")
    else state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" has neither the state abbreviation nor the full state name
    else x)
    

    metadata["Geo_Location_New"] = metadata["Geo_Location_Country"] + "-" + metadata["Geo_Location_State_USA"] 

    # If USA-, delete -
    metadata["Geo_Location_New"] = metadata["Geo_Location_New"].apply(lambda x: x.split("-")[0] 
    if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] 
    else x)

    return metadata

def geo_location_strain_name(metadata, state_ref_file):
    # If there is no state in the metadata, try the strain name
    state_ref = pd.read_csv(state_ref_file)

    metadata["strain_name_state_nonhuman"] = metadata["genbank_name"].apply(lambda x: x.split("/")[2])

    metadata["strain_name_state_human"] = metadata["genbank_name"].apply(lambda x: x.split("/")[1])

    # If nonhuman, do strain name [2]
    metadata["Geo_Location_State_Strain_Name"] = np.where((metadata["Geo_Location_State_USA"] == "USA") & (metadata["Host_Type"] != "human"), metadata["strain_name_state_nonhuman"], metadata["Geo_Location_State_USA"])

    # If human, do strain name [1]
    metadata["Geo_Location_State_Strain_Name"] = np.where((metadata["Geo_Location_State_USA"] == "USA") & (metadata["Host_Type"] == "human"), metadata["strain_name_state_human"], metadata["Geo_Location_State_USA"])

    metadata["Geo_Location_State_Strain_Name"] = metadata["Geo_Location_State_Strain_Name"].apply(geo_location_normalize)

    metadata["Geo_Location_State_Strain_Name_State"] = metadata["Geo_Location_State_Strain_Name"].apply(lambda x: x.split("-")[-1])
    
    metadata["Geo_Location_State_Strain_Name"] = metadata["Geo_Location_State_Strain_Name_State"].apply(lambda x: 
    # # If "x" is the abbreviated state (e.g. "MD")
    state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["Abbreviation"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" is the state name (e.g. "Maryland")
    else state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation'].iloc[0]
    if len(state_ref.loc[state_ref["State"].str.contains(x), 'Abbreviation']) > 0 and len(x) > 0
    # # If "x" has neither the state abbreviation nor the full state name, and is just USA
    else ""
    if x == "USA" or x == "United_States"
    
    else x)

    metadata["Geo_Location_New"] = metadata["Geo_Location_Country"] + "-" + metadata["Geo_Location_State_Strain_Name"] 

    # If USA-, delete -
    metadata["Geo_Location_New"] = metadata["Geo_Location_New"].apply(lambda x: x.split("-")[0] 
    if x.split("-")[-1] == "" or x.split("-")[-1] == x.split("-")[0] 
    else x)

    # Log metadata

    
    return metadata

In [91]:
print(states_ref[states_ref['State'].str.contains("New_York")]["Abbreviation"].values[0])

NY

In [92]:
# Re-Labeling

os.chdir(references)
animals_ref = pd.read_csv("animals_ref.csv")

# Make sure NaN doesn't mess up the whole name
metadata_genoflu = metadata_genoflu.fillna("")
metadata_genoflu["Host"] = metadata_genoflu["Host"].apply(str.lower)

# Fix animals
fix_animals_andersen(metadata_genoflu, animals_ref)

# Get the years
metadata_genoflu["Years"] = metadata_genoflu["Collection_Date"].apply(lambda x: dateutil.parser.parse(x).strftime("%Y"))

In [93]:
os.chdir(references)
metadata_genoflu = geo_location_get(metadata_genoflu, "states_ref.csv")

In [94]:
metadata_genoflu = geo_location_strain_name(metadata_genoflu, "states_ref.csv")

In [95]:
# os.chdir(downloads_saved)
# metadata_genoflu.to_csv("metadata_checkpoint.csv")

In [96]:
# If there is no SRA Accession, replace identifier with Assembly 
metadata_genoflu["Identifier"] = metadata_genoflu["Assembly"].apply(lambda x: x if metadata_genoflu[metadata_genoflu["Assembly"] == x]["SRA_Accession"].values[0] == "" else metadata_genoflu[metadata_genoflu["Assembly"] == x]["SRA_Accession"].values[0]) # np.where(metadata_genoflu['SRA_Accession'] != "", metadata_genoflu['SRA_Accession'], metadata_genoflu['Assembly'].apply(lambda x: x.split(".")[0]))

print((metadata_genoflu[metadata_genoflu["Identifier"].str.contains("SRR")])) # metadata_genoflu[(metadata_genoflu["Identifier"].str.contains("GCA")) |

         Accession         Assembly  \
96      PZ796614.1  GCA_059952205.1
97      PZ796615.1  GCA_059952205.1
98      PZ796616.1  GCA_059952205.1
99      PZ796617.1  GCA_059952205.1
100     PZ796618.1  GCA_059952205.1
...            ...              ...
150083  OQ565628.1  GCA_039342815.1
150084  OQ565629.1  GCA_039342815.1
150085  OQ565630.1  GCA_039342815.1
150086  OQ565631.1  GCA_039342815.1
150087  OQ565632.1  GCA_039342815.1

                                            GenBank_Title       Host  \
96      Influenza A virus (A/chicken/PA/26G09412-001-o...    chicken
97      Influenza A virus (A/chicken/PA/26G09412-001-o...    chicken
98      Influenza A virus (A/chicken/PA/26G09412-001-o...    chicken
99      Influenza A virus (A/chicken/PA/26G09412-001-o...    chicken
100     Influenza A virus (A/chicken/PA/26G09412-001-o...    chicken
...                                                   ...        ...
150083  Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...  pelecanus
150084  Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...  pelecanus
150085  Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...  pelecanus
150086  Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...  pelecanus
150087  Influenza A virus (A/Pelecanus/Peru/VFAR-140/2...  pelecanus

       Collection_Date SRA_Accession                                  Isolate  \
96          2026-06-24   SRR39565249  A/chicken/PA/26G09412-001-original/2026
97          2026-06-24   SRR39565249  A/chicken/PA/26G09412-001-original/2026
98          2026-06-24   SRR39565249  A/chicken/PA/26G09412-001-original/2026
99          2026-06-24   SRR39565249  A/chicken/PA/26G09412-001-original/2026
100         2026-06-24   SRR39565249  A/chicken/PA/26G09412-001-original/2026
...                ...           ...                                      ...
150083         2022-12   SRR23852495           A/Pelecanus/Peru/VFAR-140/2022
150084         2022-12   SRR23852495           A/Pelecanus/Peru/VFAR-140/2022
150085         2022-12   SRR23852495           A/Pelecanus/Peru/VFAR-140/2022
150086         2022-12   SRR23852495           A/Pelecanus/Peru/VFAR-140/2022
150087         2022-12   SRR23852495           A/Pelecanus/Peru/VFAR-140/2022

       Genotype Geo_Location  \
96          Not      USA: PA
97          Not      USA: PA
98          Not      USA: PA
99          Not      USA: PA
100         Not      USA: PA
...         ...          ...
150083     B3.2         Peru
150084     B3.2         Peru
150085     B3.2         Peru
150086     B3.2         Peru
150087     B3.2         Peru

                                              full_header  ...  \
96      >PZ796614.1 |Influenza A virus (A/chicken/PA/2...  ...
97      >PZ796615.1 |Influenza A virus (A/chicken/PA/2...  ...
98      >PZ796616.1 |Influenza A virus (A/chicken/PA/2...  ...
99      >PZ796617.1 |Influenza A virus (A/chicken/PA/2...  ...
100     >PZ796618.1 |Influenza A virus (A/chicken/PA/2...  ...
...                                                   ...  ...
150083  >OQ565628.1 |Influenza A virus (A/Pelecanus/Pe...  ...
150084  >OQ565629.1 |Influenza A virus (A/Pelecanus/Pe...  ...
150085  >OQ565630.1 |Influenza A virus (A/Pelecanus/Pe...  ...
150086  >OQ565631.1 |Influenza A virus (A/Pelecanus/Pe...  ...
150087  >OQ565632.1 |Influenza A virus (A/Pelecanus/Pe...  ...

       Geo_Location_Normalized Geo_Location_Country  Geo_Location_State_med  \
96                      USA-PA                  USA                      PA
97                      USA-PA                  USA                      PA
98                      USA-PA                  USA                      PA
99                      USA-PA                  USA                      PA
100                     USA-PA                  USA                      PA
...                        ...                  ...                     ...
150083               Peru-Peru                 Peru                    Peru
150084               Peru-Peru                 Peru                    Peru
150085               Peru-Peru                 Peru                    Peru
150086               Peru-Peru                 Peru                    Peru
150087               Peru-Peru                 Peru                    Peru

       Geo_Location_State_USA Geo_Location_New strain_name_state_nonhuman  \
96                         PA           USA-PA                         PA
97                         PA           USA-PA                         PA
98                         PA           USA-PA                         PA
99                         PA           USA-PA                         PA
100                        PA           USA-PA                         PA
...                       ...              ...                        ...
150083                   Peru             Peru                       Peru
150084                   Peru             Peru                       Peru
150085                   Peru             Peru                       Peru
150086                   Peru             Peru                       Peru
150087                   Peru             Peru                       Peru

       strain_name_state_human Geo_Location_State_Strain_Name  \
96                     chicken                             PA
97                     chicken                             PA
98                     chicken                             PA
99                     chicken                             PA
100                    chicken                             PA
...                        ...                            ...
150083               Pelecanus                           Peru
150084               Pelecanus                           Peru
150085               Pelecanus                           Peru
150086               Pelecanus                           Peru
150087               Pelecanus                           Peru

       Geo_Location_State_Strain_Name_State   Identifier
96                                       PA  SRR39565249
97                                       PA  SRR39565249
98                                       PA  SRR39565249
99                                       PA  SRR39565249
100                                      PA  SRR39565249
...                                     ...          ...
150083                                 Peru  SRR23852495
150084                                 Peru  SRR23852495
150085                                 Peru  SRR23852495
150086                                 Peru  SRR23852495
150087                                 Peru  SRR23852495

[84904 rows x 27 columns]

In [97]:

# Make new labels
names = ">" + metadata_genoflu["Identifier"].astype(str) + "|" + metadata_genoflu["genbank_name"] + "|" + metadata_genoflu["Serotype"] + "|" + metadata_genoflu["Geo_Location_New"] + "|" + metadata_genoflu["Collection_Date"].astype(str) + "|" + metadata_genoflu["Host_Type"] + "|" + metadata_genoflu["Genotype"]

metadata_genoflu["Name"] = names

In [98]:
os.chdir(complete_files)

# De-duplicate

print(len(metadata_genoflu))
metadata_genoflu = metadata_genoflu.drop_duplicates(subset=["Isolate", "genbank_name", "Segment"], keep="last")
print(len(metadata_genoflu))

# Save metadata
# metadata_genoflu.to_csv("NCBI_Virus_" + date_range + "_metadata.csv") # Make file for metadata

148457
148457

## Rename segments and make complete FASTA files

In [99]:
# Set up segments

segments = {1:"PB2", 2:"PB1", 3:"PA", 4:"HA", 5:"NP", 6:"NA", 7:"MP", 8:"NS"} # Name segments 
metadata_genoflu["Segment_Name"] = metadata_genoflu["Segment"].apply(lambda x: int(x)).map(segments)

# Separate into several dataframes based on genotype + segment
segment_genotype_dfs = []
for segment in segments.values():
    m_g = metadata_genoflu[metadata_genoflu["Segment_Name"] == segment]
    for genotype in list(set(m_g["Genotype"].values)):
        if genotype in genotypes:
            df = m_g[(m_g["Genotype"] == genotype)] 
            # df.drop_duplicates(subset="SRA_Accession", keep="first", inplace=True)
            segment_genotype_dfs.append(df)
            pair = genotype + "_" + segment
            print(pair)
        # if "Not" in genotype:
        #     df = m_g[m_g["Genotype"].str.contains("Not")]
        #     segment_genotype_dfs.append(df)
        #     pair = "Unassigned_" + segment
        #     print(pair)

D1.1_PB2
B3.2_PB2
Minor79_PB2
B4.1_PB2
Minor14_PB2
Minor65_PB2
Minor07_PB2
D1.2_PB2
Minor87_PB2
Minor104_PB2
Minor97_PB2
Minor73_PB2
Minor34_PB2
Minor60_PB2
Minor04_PB2
Minor19_PB2
C2.1_PB2
A2_PB2
C3.1_PB2
B1.3_PB2
B5.1_PB2
B3.7_PB2
Minor99_PB2
Minor91_PB2
Minor12_PB2
Minor51_PB2
B1.2_PB2
Minor94_PB2
B3.4_PB2
Minor09_PB2
A1_PB2
Minor81_PB2
B3.10_PB2
B3.1_PB2
Minor50_PB2
Minor90_PB2
Not_PB2
A6_PB2
Minor11_PB2
B1.1_PB2
B2.2_PB2
A4_PB2
B3.6_PB2
A3_PB2
A5_PB2
B3.13_PB2
Minor08_PB2
B3.12_PB2
Minor45_PB2
Minor01_PB2
D1.3_PB2
B3.3_PB2
Minor105_PB2
Minor77_PB2
Minor13_PB2
B2.1_PB2
B3.5_PB2
Minor100_PB2
D1.1_PB1
B3.2_PB1
Minor79_PB1
B4.1_PB1
Minor14_PB1
Minor65_PB1
Minor07_PB1
D1.2_PB1
Minor87_PB1
Minor104_PB1
Minor97_PB1
Minor73_PB1
Minor34_PB1
Minor60_PB1
Minor04_PB1
Minor19_PB1
C2.1_PB1
A2_PB1
C3.1_PB1
B1.3_PB1
B5.1_PB1
B3.7_PB1
Minor99_PB1
Minor91_PB1
Minor12_PB1
Minor51_PB1
B1.2_PB1
Minor94_PB1
B3.4_PB1
Minor09_PB1
A1_PB1
Minor81_PB1
B3.10_PB1
B3.1_PB1
Minor50_PB1
Minor90_PB1
Not_PB1
A6_PB1
Minor11_PB1
B1.1_PB1
B2.2_PB1
A4_PB1
B3.6_PB1
A3_PB1
A5_PB1
B3.13_PB1
Minor08_PB1
B3.12_PB1
Minor45_PB1
Minor01_PB1
D1.3_PB1
B3.3_PB1
Minor105_PB1
Minor77_PB1
Minor13_PB1
B2.1_PB1
B3.5_PB1
Minor100_PB1
D1.1_PA
B3.2_PA
Minor79_PA
B4.1_PA
Minor14_PA
Minor65_PA
Minor07_PA
D1.2_PA
Minor87_PA
Minor104_PA
Minor97_PA
Minor73_PA
Minor34_PA
Minor60_PA
Minor04_PA
Minor19_PA
C2.1_PA
A2_PA
C3.1_PA
B1.3_PA
B5.1_PA
B3.7_PA
Minor99_PA
Minor91_PA
Minor12_PA
Minor51_PA
B1.2_PA
Minor94_PA
B3.4_PA
Minor09_PA
A1_PA
Minor81_PA
B3.10_PA
B3.1_PA
Minor50_PA
Minor90_PA
Not_PA
A6_PA
Minor11_PA
B1.1_PA
B2.2_PA
A4_PA
B3.6_PA
A3_PA
A5_PA
B3.13_PA
Minor08_PA
B3.12_PA
Minor45_PA
Minor01_PA
D1.3_PA
B3.3_PA
Minor105_PA
Minor77_PA
Minor13_PA
B2.1_PA
B3.5_PA
Minor100_PA
D1.1_HA
B3.2_HA
Minor79_HA
B4.1_HA
Minor14_HA
Minor65_HA
Minor07_HA
D1.2_HA
Minor87_HA
Minor104_HA
Minor97_HA
Minor73_HA
Minor34_HA
Minor60_HA
Minor04_HA
Minor19_HA
C2.1_HA
A2_HA
C3.1_HA
B1.3_HA
B5.1_HA
B3.7_HA
Minor99_HA
Minor91_HA
Minor12_HA
Minor51_HA
B1.2_HA
Minor94_HA
B3.4_HA
Minor09_HA
A1_HA
Minor81_HA
B3.10_HA
B3.1_HA
Minor50_HA
Minor90_HA
Not_HA
A6_HA
Minor11_HA
B1.1_HA
B2.2_HA
A4_HA
B3.6_HA
A3_HA
A5_HA
B3.13_HA
Minor08_HA
B3.12_HA
Minor45_HA
Minor01_HA
D1.3_HA
B3.3_HA
Minor105_HA
Minor77_HA
Minor13_HA
B2.1_HA
B3.5_HA
Minor100_HA
D1.1_NP
B3.2_NP
Minor79_NP
B4.1_NP
Minor14_NP
Minor65_NP
Minor07_NP
D1.2_NP
Minor87_NP
Minor104_NP
Minor97_NP
Minor73_NP
Minor34_NP
Minor60_NP
Minor04_NP
Minor19_NP
C2.1_NP
A2_NP
C3.1_NP
B1.3_NP
B5.1_NP
B3.7_NP
Minor99_NP
Minor91_NP
Minor12_NP
Minor51_NP
B1.2_NP
Minor94_NP
B3.4_NP
Minor09_NP
A1_NP
Minor81_NP
B3.10_NP
B3.1_NP
Minor50_NP
Minor90_NP
Not_NP
A6_NP
Minor11_NP
B1.1_NP
B2.2_NP
A4_NP
B3.6_NP
A3_NP
A5_NP
B3.13_NP
Minor08_NP
B3.12_NP
Minor45_NP
Minor01_NP
D1.3_NP
B3.3_NP
Minor105_NP
Minor77_NP
Minor13_NP
B2.1_NP
B3.5_NP
Minor100_NP
D1.1_NA
B3.2_NA
Minor79_NA
B4.1_NA
Minor14_NA
Minor65_NA
Minor07_NA
D1.2_NA
Minor87_NA
Minor104_NA
Minor97_NA
Minor73_NA
Minor34_NA
Minor60_NA
Minor04_NA
Minor19_NA
C2.1_NA
A2_NA
C3.1_NA
B1.3_NA
B5.1_NA
B3.7_NA
Minor99_NA
Minor91_NA
Minor12_NA
Minor51_NA
B1.2_NA
Minor94_NA
B3.4_NA
Minor09_NA
A1_NA
Minor81_NA
B3.10_NA
B3.1_NA
Minor50_NA
Minor90_NA
Not_NA
A6_NA
Minor11_NA
B1.1_NA
B2.2_NA
A4_NA
B3.6_NA
A3_NA
A5_NA
B3.13_NA
Minor08_NA
B3.12_NA
Minor45_NA
Minor01_NA
D1.3_NA
B3.3_NA
Minor105_NA
Minor77_NA
Minor13_NA
B2.1_NA
B3.5_NA
Minor100_NA
D1.1_MP
B3.2_MP
Minor79_MP
B4.1_MP
Minor14_MP
Minor65_MP
Minor07_MP
D1.2_MP
Minor87_MP
Minor104_MP
Minor97_MP
Minor73_MP
Minor34_MP
Minor60_MP
Minor04_MP
Minor19_MP
C2.1_MP
A2_MP
C3.1_MP
B1.3_MP
B5.1_MP
B3.7_MP
Minor99_MP
Minor91_MP
Minor12_MP
Minor51_MP
B1.2_MP
Minor94_MP
B3.4_MP
Minor09_MP
A1_MP
Minor81_MP
B3.10_MP
B3.1_MP
Minor50_MP
Minor90_MP
Not_MP
A6_MP
Minor11_MP
B1.1_MP
B2.2_MP
A4_MP
B3.6_MP
A3_MP
A5_MP
B3.13_MP
Minor08_MP
B3.12_MP
Minor45_MP
Minor01_MP
D1.3_MP
B3.3_MP
Minor105_MP
Minor77_MP
Minor13_MP
B2.1_MP
B3.5_MP
Minor100_MP
D1.1_NS
B3.2_NS
Minor79_NS
B4.1_NS
Minor14_NS
Minor65_NS
Minor07_NS
D1.2_NS
Minor87_NS
Minor104_NS
Minor97_NS
Minor73_NS
Minor34_NS
Minor60_NS
Minor04_NS
Minor19_NS
C2.1_NS
A2_NS
C3.1_NS
B1.3_NS
B5.1_NS
B3.7_NS
Minor99_NS
Minor91_NS
Minor12_NS
Minor51_NS
B1.2_NS
Minor94_NS
B3.4_NS
Minor09_NS
A1_NS
Minor81_NS
B3.10_NS
B3.1_NS
Minor50_NS
Minor90_NS
Not_NS
A6_NS
Minor11_NS
B1.1_NS
B2.2_NS
A4_NS
B3.6_NS
A3_NS
A5_NS
B3.13_NS
Minor08_NS
B3.12_NS
Minor45_NS
Minor01_NS
D1.3_NS
B3.3_NS
Minor105_NS
Minor77_NS
Minor13_NS
B2.1_NS
B3.5_NS
Minor100_NS

In [100]:
# Create FASTA files

os.chdir(complete_files)

for df in segment_genotype_dfs:
    print(df)
    
    df = df.reset_index()
    if len(df["Genotype"].values[0]) > 0 and "Not" not in df["Genotype"].values[0]: # If we have assigned genotypes, including "Unassigned"
        file_name = df["Genotype"].values[0] + "_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files / (file_name), "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
    elif len(df["Genotype"].values[0]) > 0 and "Not" in df["Genotype"].values[0]:
        file_name = "Unassigned_" + df["Segment_Name"].values[0] + "_" + date_range + ".fasta"
        output_file = open(complete_files / (file_name), "w")

        for index, row in df.iterrows():
            name = df.loc[index, "Name"]
            name = name.replace(" ", "_")
            # names.append(name)
            sequence = df.loc[index, "sequence"]
            # First is header, second is sequence
            output_file.write(name + "\n")
            output_file.write(sequence + "\n")
        
    output_file.close()

         Accession         Assembly  \
168     PZ768697.1  GCA_059776725.1
176     PZ768705.1  GCA_059776745.1
184     PZ768713.1  GCA_059776555.1
192     PZ768721.1  GCA_059776785.1
208     PZ768737.1  GCA_059776925.1
...            ...              ...
124864  PQ664462.1  GCA_046435685.1
124872  PQ664470.1  GCA_046436335.1
125563  PQ615362.1  GCA_046438285.1
125579  PQ585630.1  GCA_046436165.1
125643  PQ573561.1  GCA_046435525.1

                                            GenBank_Title             Host  \
168     Influenza A virus (A/chicken/IN/26G08500-001-o...          chicken
176     Influenza A virus (A/chicken/IN/26G08500-002-o...          chicken
184     Influenza A virus (A/Bald Eagle/CA/26G08579-00...       bald eagle
192     Influenza A virus (A/Red-tailed Hawk/MN/26G087...  red-tailed hawk
208     Influenza A virus (A/Common Tern/NY/26G08915-0...      common tern
...                                                   ...              ...
124864  Influenza A virus (A/chicken/WA/24-031352-002-...          chicken
124872  Influenza A virus (A/chicken/WA/24-031352-003-...          chicken
125563  Influenza A virus (A/Washington/255/2024(H5N1)...       washington
125579  Influenza A virus (A/Washington/UW32495/2024(H...       washington
125643  Influenza A virus (A/Washington/240/2024(H5N1)...       washington

       Collection_Date SRA_Accession  \
168         2026-06-04   SRR39413617
176         2026-06-04   SRR39413616
184         2026-04-30   SRR39413534
192         2026-06-06   SRR39413530
208         2026-06-10   SRR39413532
...                ...           ...
124864      2024-10-21   SRR31167889
124872      2024-10-21   SRR31167888
125563      2024-10-29
125579      2024-10-18
125643      2024-10-18

                                                Isolate Genotype  \
168             A/chicken/IN/26G08500-001-original/2026     D1.1
176             A/chicken/IN/26G08500-002-original/2026     D1.1
184          A/Bald Eagle/CA/26G08579-001-original/2026     D1.1
192     A/Red-tailed Hawk/MN/26G08723-001-original/2026     D1.1
208         A/Common Tern/NY/26G08915-002-original/2026     D1.1
...                                                 ...      ...
124864         A/chicken/WA/24-031352-002-original/2024     D1.1
124872         A/chicken/WA/24-031352-003-original/2024     D1.1
125563                            A/Washington/255/2024     D1.1
125579                        A/Washington/UW32495/2024     D1.1
125643                            A/Washington/240/2024     D1.1

           Geo_Location                                        full_header  \
168             USA: IN  >PZ768697.1 |Influenza A virus (A/chicken/IN/2...
176             USA: IN  >PZ768705.1 |Influenza A virus (A/chicken/IN/2...
184             USA: CA  >PZ768713.1 |Influenza A virus (A/Bald Eagle/C...
192             USA: MN  >PZ768721.1 |Influenza A virus (A/Red-tailed H...
208             USA: NY  >PZ768737.1 |Influenza A virus (A/Common Tern/...
...                 ...                                                ...
124864          USA: WA  >PQ664462.1 |Influenza A virus (A/chicken/WA/2...
124872          USA: WA  >PQ664470.1 |Influenza A virus (A/chicken/WA/2...
125563  USA: Washington  >PQ615362.1 |Influenza A virus (A/Washington/2...
125579  USA: Washington  >PQ585630.1 |Influenza A virus (A/Washington/U...
125643  USA: Washington  >PQ573561.1 |Influenza A virus (A/Washington/2...

        ... Geo_Location_State_med Geo_Location_State_USA  Geo_Location_New  \
168     ...                     IN                     IN            USA-IN
176     ...                     IN                     IN            USA-IN
184     ...                     CA                     CA            USA-CA
192     ...                     MN                     MN            USA-MN
208     ...                     NY                     NY            USA-NY
...     ...                    ...                    ...               ...
124864  ...                     WA                     WA            USA-WA
124872  ...                     WA                     WA            USA-WA
125563  ...             Washington                     WA            USA-WA
125579  ...             Washington                     WA            USA-WA
125643  ...             Washington                     WA            USA-WA

       strain_name_state_nonhuman strain_name_state_human  \
168                            IN                 chicken
176                            IN                 chicken
184                            CA              Bald Eagle
192                            MN         Red-tailed Hawk
208                            NY             Common Tern
...                           ...                     ...
124864                         WA                 chicken
124872                         WA                 chicken
125563                        255              Washington
125579                    UW32495              Washington
125643                        240              Washington

       Geo_Location_State_Strain_Name Geo_Location_State_Strain_Name_State  \
168                                IN                                   IN
176                                IN                                   IN
184                                CA                                   CA
192                                MN                                   MN
208                                NY                                   NY
...                               ...                                  ...
124864                             WA                                   WA
124872                             WA                                   WA
125563                             WA                                   WA
125579                             WA                                   WA
125643                             WA                                   WA

             Identifier                                               Name  \
168         SRR39413617  >SRR39413617|A/chicken/IN/26G08500-001-origina...
176         SRR39413616  >SRR39413616|A/chicken/IN/26G08500-002-origina...
184         SRR39413534  >SRR39413534|A/Bald Eagle/CA/26G08579-001-orig...
192         SRR39413530  >SRR39413530|A/Red-tailed Hawk/MN/26G08723-001...
208         SRR39413532  >SRR39413532|A/Common Tern/NY/26G08915-002-ori...
...                 ...                                                ...
124864      SRR31167889  >SRR31167889|A/chicken/WA/24-031352-002-origin...
124872      SRR31167888  >SRR31167888|A/chicken/WA/24-031352-003-origin...
125563  GCA_046438285.1  >GCA_046438285.1|A/Washington/255/2024|H5N1|US...
125579  GCA_046436165.1  >GCA_046436165.1|A/Washington/UW32495/2024|H5N...
125643  GCA_046435525.1  >GCA_046435525.1|A/Washington/240/2024|H5N1|US...

       Segment_Name
168             PB2
176             PB2
184             PB2
192             PB2
208             PB2
...             ...
124864          PB2
124872          PB2
125563          PB2
125579          PB2
125643          PB2

[4913 rows x 29 columns]
         Accession         Assembly  \
4368    PV810114.1  GCA_058941065.1
9631    PV570957.1  GCA_057181755.1
9639    PV570965.1  GCA_057181925.1
9647    PV570973.1  GCA_057182165.1
9663    PV570989.1  GCA_057181585.1
...            ...              ...
150195  OQ455463.1  GCA_039346635.1
150241  OQ352545.1  GCA_039343775.1
150249  OQ352553.1  GCA_039344385.1
150272  OP691321.1  GCA_039321425.1
150599  OP377589.1  GCA_039285675.1

                                            GenBank_Title                Host  \
4368    Influenza A virus (A/Thalasseus maximus/Isla d...  thalasseus maximus
9631    Influenza A virus (A/Avian/Chile/243717/2023(H...               avian
9639    Influenza A virus (A/Avian/Chile/248916/2023(H...               avian
9647    Influenza A virus (A/Avian/Chile/261059/2023(H...               avian
9663    Influenza A virus (A/Duck/Chile/240466-1/2023(...                duck
...                                                   ...                 ...
150195  Influenza A virus (A/Pelican/CHL/226924-1/2022...             pelican
150241  Influenza A virus (A/black skimmer/Chile/C6196...       black skimmer
150249  Influenza A virus (A/gray gull/Chile/C61947/20...           gray gull
150272  Influenza A virus (A/Falco_rusticolus/EdoMex/C...    falco_rusticolus
150599  Influenza A virus (A/lesser snow goose/North D...   lesser snow goose

       Collection_Date SRA_Accession  \
4368        2023-10-23
9631        2023-03-21
9639        2023-04-11
9647        2023-06-06
9663        2023-03-07
...                ...           ...
150195      2022-12-06
150241      2022-12-02
150249      2022-12-02
150272         2022-10
150599      2022-04-08

                                                Isolate Genotype  \
4368    A/Thalasseus maximus/Isla de Flores/AIV-27/2023     B3.2
9631                          A/Avian/Chile/243717/2023     B3.2
9639                          A/Avian/Chile/248916/2023     B3.2
9647                          A/Avian/Chile/261059/2023     B3.2
9663                         A/Duck/Chile/240466-1/2023     B3.2
...                                                 ...      ...
150195                      A/Pelican/CHL/226924-1/2022     B3.2
150241                A/black skimmer/Chile/C61962/2022     B3.2
150249                    A/gray gull/Chile/C61947/2022     B3.2
150272      A/Falco_rusticolus/EdoMex/CPA-19638-22/2022     B3.2
150599      A/lesser snow goose/North Dakota/ND-10/2022     B3.2

                   Geo_Location  \
4368    Uruguay: Isla de Flores
9631                      Chile
9639                      Chile
9647                      Chile
9663                      Chile
...                         ...
150195                    Chile
150241                    Chile
150249                    Chile
150272           Mexico: EdoMex
150599                      USA

                                              full_header  ...  \
4368    >PV810114.1 |Influenza A virus (A/Thalasseus m...  ...
9631    >PV570957.1 |Influenza A virus (A/Avian/Chile/...  ...
9639    >PV570965.1 |Influenza A virus (A/Avian/Chile/...  ...
9647    >PV570973.1 |Influenza A virus (A/Avian/Chile/...  ...
9663    >PV570989.1 |Influenza A virus (A/Duck/Chile/2...  ...
...                                                   ...  ...
150195  >OQ455463.1 |Influenza A virus (A/Pelican/CHL/...  ...
150241  >OQ352545.1 |Influenza A virus (A/black skimme...  ...
150249  >OQ352553.1 |Influenza A virus (A/gray gull/Ch...  ...
150272  >OP691321.1 |Influenza A virus (A/Falco_rustic...  ...
150599  >OP377589.1 |Influenza A virus (A/lesser snow ...  ...

       Geo_Location_State_med Geo_Location_State_USA        Geo_Location_New  \
4368           Isla_de_Flores         Isla_de_Flores  Uruguay-Isla_de_Flores
9631                    Chile                  Chile                   Chile
9639                    Chile                  Chile                   Chile
9647                    Chile                  Chile                   Chile
9663                    Chile                  Chile                   Chile
...                       ...                    ...                     ...
150195                  Chile                  Chile                   Chile
150241                  Chile                  Chile                   Chile
150249                  Chile                  Chile                   Chile
150272                 EdoMex                 EdoMex           Mexico-EdoMex
150599                    USA                    USA                     USA

       strain_name_state_nonhuman strain_name_state_human  \
4368               Isla de Flores      Thalasseus maximus
9631                        Chile                   Avian
9639                        Chile                   Avian
9647                        Chile                   Avian
9663                        Chile                    Duck
...                           ...                     ...
150195                        CHL                 Pelican
150241                      Chile           black skimmer
150249                      Chile               gray gull
150272                     EdoMex        Falco_rusticolus
150599               North Dakota       lesser snow goose

       Geo_Location_State_Strain_Name Geo_Location_State_Strain_Name_State  \
4368                   Isla_de_Flores                       Isla_de_Flores
9631                            Chile                                Chile
9639                            Chile                                Chile
9647                            Chile                                Chile
9663                            Chile                                Chile
...                               ...                                  ...
150195                          Chile                                Chile
150241                          Chile                                Chile
150249                          Chile                                Chile
150272                         EdoMex                               EdoMex
150599                                                                 USA

             Identifier                                               Name  \
4368    GCA_058941065.1  >GCA_058941065.1|A/Thalasseus maximus/Isla de ...
9631    GCA_057181755.1  >GCA_057181755.1|A/Avian/Chile/243717/2023|H5N...
9639    GCA_057181925.1  >GCA_057181925.1|A/Avian/Chile/248916/2023|H5N...
9647    GCA_057182165.1  >GCA_057182165.1|A/Avian/Chile/261059/2023|H5N...
9663    GCA_057181585.1  >GCA_057181585.1|A/Duck/Chile/240466-1/2023|H5...
...                 ...                                                ...
150195  GCA_039346635.1  >GCA_039346635.1|A/Pelican/CHL/226924-1/2022|H...
150241  GCA_039343775.1  >GCA_039343775.1|A/black skimmer/Chile/C61962/...
150249  GCA_039344385.1  >GCA_039344385.1|A/gray gull/Chile/C61947/2022...
150272  GCA_039321425.1  >GCA_039321425.1|A/Falco_rusticolus/EdoMex/CPA...
150599  GCA_039285675.1  >GCA_039285675.1|A/lesser snow goose/North Dak...

       Segment_Name
4368            PB2
9631            PB2
9639            PB2
9647            PB2
9663            PB2
...             ...
150195          PB2
150241          PB2
150249          PB2
150272          PB2
150599          PB2

[1773 rows x 29 columns]
         Accession         Assembly  \
138503  PP576831.1  GCA_039407075.1

                                            GenBank_Title        Host  \
138503  Influenza A virus (A/snow goose/Kansas/W23-930...  snow goose

       Collection_Date SRA_Accession                            Isolate  \
138503      2023-12-04                A/snow goose/Kansas/W23-930C/2023

       Genotype Geo_Location  \
138503  Minor79          USA

                                              full_header  ...  \
138503  >PP576831.1 |Influenza A virus (A/snow goose/K...  ...

       Geo_Location_State_med Geo_Location_State_USA  Geo_Location_New  \
138503                    USA                    USA               USA

       strain_name_state_nonhuman strain_name_state_human  \
138503                     Kansas              snow goose

       Geo_Location_State_Strain_Name Geo_Location_State_Strain_Name_State  \
138503                                                                 USA

             Identifier                                               Name  \
138503  GCA_039407075.1  >GCA_039407075.1|A/snow goose/Kansas/W23-930C/...

       Segment_Name
138503          PB2

[1 rows x 29 columns]
         Accession         Assembly  \
22775   PX936837.1  GCA_054871905.1
22887   PX936957.1  GCA_054871875.1
22919   PX936989.1  GCA_054871885.1
22935   PX937005.1  GCA_054871865.1
23007   PX937077.1  GCA_054871785.1
...            ...              ...
147976  OQ967689.1  GCA_039296525.1
147984  OQ967697.1  GCA_039297695.1
147992  OQ967705.1  GCA_039296545.1
148304  OQ968017.1  GCA_039297115.1
148352  OQ968065.1  GCA_039284765.1

                                            GenBank_Title     Host  \
22775   Influenza A virus (A/Duck/California/D2213711/...     duck
22887   Influenza A virus (A/Turkey/California/B220003...   turkey
22919   Influenza A virus (A/Turkey/California/D221362...   turkey
22935   Influenza A virus (A/Turkey/California/K220175...   turkey
23007   Influenza A virus (A/chicken/California/D22109...  chicken
...                                                   ...      ...
147976  Influenza A virus (A/chicken/Montana/22-013053...  chicken
147984  Influenza A virus (A/chicken/Montana/22-013053...  chicken
147992  Influenza A virus (A/chicken/Montana/22-013056...  chicken
148304  Influenza A virus (A/goose/Alaska/22-013831-00...    goose
148352  Influenza A virus (A/goose/Wyoming/22-010159-0...    goose

       Collection_Date SRA_Accession                               Isolate  \
22775       2022-09-30                     A/Duck/California/D2213711/2022
22887       2022-08-26                   A/Turkey/California/B2200039/2022
22919       2022-09-29                   A/Turkey/California/D2213625/2022
22935       2022-08-24                   A/Turkey/California/K2201751/2022
23007       2022-08-05                  A/chicken/California/D2210977/2022
...                ...           ...                                   ...
147976      2022-04-28                A/chicken/Montana/22-013053-001/2022
147984      2022-04-28                A/chicken/Montana/22-013053-002/2022
147992      2022-04-28                A/chicken/Montana/22-013056-002/2022
148304      2022-04-27                   A/goose/Alaska/22-013831-002/2022
148352      2022-04-04                  A/goose/Wyoming/22-010159-001/2022

       Genotype     Geo_Location  \
22775      B4.1  USA: California
22887      B4.1  USA: California
22919      B4.1  USA: California
22935      B4.1  USA: California
23007      B4.1  USA: California
...         ...              ...
147976     B4.1     USA: Montana
147984     B4.1     USA: Montana
147992     B4.1     USA: Montana
148304     B4.1      USA: Alaska
148352     B4.1     USA: Wyoming

                                              full_header  ...  \
22775   >PX936837.1 |Influenza A virus (A/Duck/Califor...  ...
22887   >PX936957.1 |Influenza A virus (A/Turkey/Calif...  ...
22919   >PX936989.1 |Influenza A virus (A/Turkey/Calif...  ...
22935   >PX937005.1 |Influenza A virus (A/Turkey/Calif...  ...
23007   >PX937077.1 |Influenza A virus (A/chicken/Cali...  ...
...                                                   ...  ...
147976  >OQ967689.1 |Influenza A virus (A/chicken/Mont...  ...
147984  >OQ967697.1 |Influenza A virus (A/chicken/Mont...  ...
147992  >OQ967705.1 |Influenza A virus (A/chicken/Mont...  ...
148304  >OQ968017.1 |Influenza A virus (A/goose/Alaska...  ...
148352  >OQ968065.1 |Influenza A virus (A/goose/Wyomin...  ...

       Geo_Location_State_med Geo_Location_State_USA  Geo_Location_New  \
22775              California                     CA            USA-CA
22887              California                     CA            USA-CA
22919              California                     CA            USA-CA
22935              California                     CA            USA-CA
23007              California                     CA            USA-CA
...                       ...                    ...               ...
147976                Montana                     MT            USA-MT
147984                Montana                     MT            USA-MT
147992                Montana                     MT            USA-MT
148304                 Alaska                     AK            USA-AK
148352                Wyoming                     WY            USA-WY

       strain_name_state_nonhuman strain_name_state_human  \
22775                  California                    Duck
22887                  California                  Turkey